### ISSUE TITLE
Pressing Unlock Frames multiple times causes "black screen"

### ISSUE THREAD

**Issue by jfastnacht** [shagu/pfUI#1]
"Unlock Frames" in /pfui menu can be pressed multiple times and results in the screen to be blacked out.

![image](https://cloud.githubusercontent.com/assets/6183607/15403304/a2e266c0-1df8-11e6-812e-96ef06dd935d.png)

**Comment by shagu** [comment]
0769ad0b1335ef3897164f56f2ee4846b745b32f
