### ISSUE TITLE
Possible Performance regression

### ISSUE THREAD

**Issue by muellerj** [shagu/pfUI#100]
I went for a 40-man raid yesterday with commit `bf66788` and had severe problems with frame rates, which never seemed to be a problem before. The last "good" commit I can identify is `9a7980f`. 

I have not yet reverted back and tested with that, but will do as soon as I can.

**Comment by dikdigguh** [comment]
I'm also having a huge fps drop. Only occurs in 40-man raids and seems to happen during boss fights when people blow cds. I'll link a video later this afternoon to provide context.

**Comment by ettern** [comment]
Same here... Can't use this ui in raid environment unfortunately.

**Comment by shagu** [comment]
By looking through the code, I've identified some spots which might cause the fps regressions. Could you please try to verify my guess by disabling the pfui raidframes? (you might use sraidframes instead, for the test). Thanks

**Comment by Voidmenull** [comment]
From my exp. making locals (in a onupdate function) to update a 40 man raid had huge impact to the performance. You have just a few of them, but this still could be a problem - idk, just an idea.

**Comment by dikdigguh** [comment]
Also, it started for me during raids on Thursday (North American evening hour) if this helps.

**Comment by shagu** [comment]
Yes, that's exactly one of the spots I'm talking about. I already have a commit ready, but as usual I can't find enough people on my realm to test this. Please be patient.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/95d8d55f14bf362354fd0709bce93964ce4987ab

**Comment by shagu** [comment]
I can't reproduce this one... I'm waiting for your feedback.

**Comment by muellerj** [comment]
I will try with pfUI-RaidFrames disabled tomorrow (first opportunity for me to raid).

Do you also want a comparison with 95d8d55 and the pfUI-RaidFrames enabled?

**Comment by dikdigguh** [comment]
I'll test it out tonight in a 20-man and record if there still any issues.

**Comment by shagu** [comment]
Would be great if you could check with the latest version. If you experience any framedrops, do the following until the frames are good again:
1. ReloadUI (/rl)
2. Disable "raid" in pfUI modules
3. Disable pfUI-Unitframes in pfUI settings
4. Panic.

**Comment by muellerj** [comment]
:)

**Comment by ettern** [comment]
Tested it in raid environment yesterday, with the 9a7980f package. Still having performance issues (lag/freeze). I tried disabling all addons except pfUI; Same result...

**Comment by shagu** [comment]
> Tested it in raid environment yesterday, with the 9a7980f package. Still having performance issues (lag/freeze). I tried disabling all addons except pfUI; Same result...

Of course you do. The version you are using does not contain any of the performance optimization I did the last days...

**Comment by ettern** [comment]
> I went for a 40-man raid yesterday with commit bf66788 and had severe problems with frame rates, which never seemed to be a problem before. The last "good" commit I can identify is 9a7980f.
> 
> I have not yet reverted back and tested with that, but will do as soon as I can.

I did test with the newest release first ofc, but since muellerj said he had it working with this specific package, I had to try that one as well, with no luck..

**Comment by muellerj** [comment]
Sorry if my original comment caused confusion - 9a7980f was the last commit I found in my reflog and had no "holy crap, why is my client so laggy" memories of. As indicated above, I have not verified any of that. It may well have been a week, where I didn't raid in a 40-man encounter.

@ettern: How was the performance with 95d8d55 or later?

**Comment by ettern** [comment]
> How was the performance with 95d8d55 or later?

I have not tested the 95d8d55 package yet as this was not out when I raided 2 days ago. I can see Shagu have commited a new package (yesterday) but I have not been able to test it in raid yet. 

> I'll test it out tonight in a 20-man and record if there still any issues.

Maybe dikdigguh have some good news?

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/140bb0f393f15ece6b86cb329af1fcde6334d0c5
https://github.com/shagu/pfUI/commit/fdf8e8dc404ef88bbcb2377dbb897b1479f71c4a

**Comment by dikdigguh** [comment]
On both Thursday and Monday, I was having issues on my mage. They seemed to only occur in raid and the fps would drop drastically during fights where players popped cd's i.e. bosses. If I reloaded my ui prior to a boss the issues seemed to be  okay for a bit, then they would get worse as the fights went on until I would be getting <1fps. I record all my raids and would be happy to send a private link to the recording if that would help you Shagu. 

Unfortunately, I ended up not being able to raid, however I will be able to test tomorrow!

**Comment by ettern** [comment]
> BTW: Are you experiencing these performance regressions only with a pet-class, like hunter or warlock?
No, Im playing a mage. 
Gonna test these new commits tomorrow.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/25fce07b6c3b6140d33adf5fedf4ba51824ef3f3

**Comment by muellerj** [comment]
I just tested with 022b04a with 20-man raid and had limited success. The frame rates were better than with bf66788, but still not good enough to tank properly. I made some screenshots at the ZG buff spot (100+ players nearby) with different configurations (raid on/off, party on/off, unit frames on/off), but I doubt that's very representative of the use case "boss fight".

Reloading the UI prior to the boss fight seems to help a bit.

![screen shot 2016-11-16 at 18 40 32](https://cloud.githubusercontent.com/assets/53246/20366867/49c2fa1c-ac4d-11e6-828c-46408bf7f2ae.png)
![screen shot 2016-11-16 at 18 43 00](https://cloud.githubusercontent.com/assets/53246/20366864/49bfce1e-ac4d-11e6-9785-7536bcce4b61.png)
![screen shot 2016-11-16 at 18 44 12](https://cloud.githubusercontent.com/assets/53246/20366866/49c208dc-ac4d-11e6-8ec0-94a4b8cfcc59.png)
![screen shot 2016-11-16 at 18 45 07](https://cloud.githubusercontent.com/assets/53246/20366868/49c4e20a-ac4d-11e6-8d2a-7229d19fb6c9.png)
![screen shot 2016-11-16 at 18 46 11](https://cloud.githubusercontent.com/assets/53246/20366865/49c15482-ac4d-11e6-983d-a9ad882dd9e2.png)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/ff934f92261a10e03b09beb2d7d7bb83f8c8c7ff
https://github.com/shagu/pfUI/commit/93e8cba9d618e86d6da28d6978622ad2b92c86c5

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/6eca971ea232aa18ccf8d563bcb0187476d40040

With all the commits I did today, you should notice some real performance improvements.
There where alot of things wich could have caused that fps drop. Now I'm waiting for your feedback.
Thanks for all of your feedback and patience.

Cheers

**Comment by dikdigguh** [comment]
Works great for me in a 20man raid!

**Comment by dikdigguh** [comment]
I'll be testing the following commit in a 40-man raid this evening:
https://github.com/shagu/pfUI/commit/6eca971ea232aa18ccf8d563bcb0187476d40040

:)

**Comment by shagu** [comment]
@dikdigguh Please use the latest commit: https://github.com/shagu/pfUI/commit/1a0d2d6e4e1391ccc8848bacba6a1c97bf84db2d

**Comment by dikdigguh** [comment]
Oops. That's the commit I used last night actually. It worked great :)

**Comment by ettern** [comment]
Just tried now with the latest release. Working ALOT better now in raid environment:) Thanks!
There's still some spikes, but that might be something else. GJ!

**Comment by shagu** [comment]
Yay, Finally! That takes a load off my mind.

**Comment by muellerj** [comment]
Cool! I haven't had a chance to test the latest optimisations, but if someone has, we can close this ticket.

**Comment by dikdigguh** [comment]
Used the build in 40-man last night. Worked flawless! No issues :)

**Comment by muellerj** [comment]
Just for documentation: I used 32f3b15 in a 40-man yesterday and had much better performance. Thanks so much, @shagu 👍
