### ISSUE TITLE
Pushback and chain casting spells

### ISSUE THREAD

**Issue by nonameform** [shagu/pfUI#1000]
I have noticed that while chain casting Lightning Bolt as Shaman, the spell delay time might not reset and add up as long as you maintain the chain. I have seen delay time go as high as 5+ seconds though I was only taking one hit every cast.

**Comment by shagu** [comment]
Thanks for your report and sorry for the delay. This issue is fixed by https://github.com/shagu/pfUI/commit/8c7579ad26517e2c45959f77d22b28c59fab2bfe
