### ISSUE TITLE
lot window - announce loot

### ISSUE THREAD

**Issue by shikulja** [shagu/pfUI#1006]
x-loot was good at this feature, very useful in raids.
since pfui has its own loot window, it would be nice to add it

**Comment by shagu** [comment]
You need to be more specific. pfUI already has "Enable Advanced Master Loot Menu", "Random Roll Announcement Rarity" and "Detailed Random Roll Announcement" that provide loot anouncements.

**Comment by shikulja** [comment]
@shagu 
"Enable Advanced Master Loot Menu" 
maybe this only works for the raid leader, since I don't have any window to declare loot /whisper /group /raid

**Comment by shikulja** [comment]
looks like:
![image](https://user-images.githubusercontent.com/3386359/99720899-77164380-2abf-11eb-8968-0230665e8817.png)

**Comment by shagu** [comment]
I decided to not do it
