### ISSUE TITLE
Second chat window + docking addons

### ISSUE THREAD

**Issue by nonameform** [shagu/pfUI#1007]
If your Recount and Omen 2 (and probably any other addon that supports docking) windows areopen, you can still see chat through them. Though text is invisible, special characters used for marking are not.
![WoWScrnShot_110920_131337](https://user-images.githubusercontent.com/34381716/99957483-d4004b00-2d98-11eb-9f23-fab1e1c40af2.jpg)

**Comment by shagu** [comment]
It's a TBC (2.4.3) issue, where Icons are still visible if the window has full transparency. For some reason, the textures won't inherit the transparency from the parent frame, which makes them visible.
