### ISSUE TITLE
Integrate ShaguChat

### ISSUE THREAD

**Issue by shikulja** [shagu/pfUI#1008]
ChatSuey - Mentions
Highlights mentions of your character's name in chat.

Prat - PopupMessage
Module for Prat that displays chat with your name in a pop up window

almost the same thing, but everyone may like different options. So far the only big drawback is missing.

**Comment by shagu** [comment]
So basically https://shagu.org/ShaguChat/? Yes I can do that.

**Comment by shikulja** [comment]
@shagu 
looked at ShaguChat, good thing. I can't see it in the game yet.
Very similar, but there are many differences.

Prat - uses character name (default) + class color of name in message for pop up window

ChatSuey - the same but only for chat
uses character name (default) + class color + standard sound from the game sounds
(to see you need to watch it yourself, I can't record an example with a video - how the chat sounds and looks when mentioned)

It's hard for me to explain in words
but addons are made to notify first of all the player himself about his mention. ShaguChat mentions any text and no class highlighting. Most likely there will be no sound at the mention
