### ISSUE TITLE
[BAR] new distance bar

### ISSUE THREAD

**Issue by shikulja** [shagu/pfUI#1009]
as a scale of experience or reputation.
there is a similar old addon Distance (mahiro)
But it's easier to implement a stylized built-in distance scale for such a small task. How to use a third-party addon for this

You can also implement the distance to the targets in the tips, which I have not seen in any addon.
This would allow you to track the main target on the distance scale, as well as other targets, if necessary (Tanks in the raid) by mouse hover prompts

**Comment by shagu** [comment]
I have no interest in this. Distance tracking can only be done in huge steps. If there is much estimation to smoothen it out, it becomes quickly very ressource intensive. I have no plans and time to spend that much effort into a feature to just make it equal to already existing addons. Just use one of the already existing.
