### ISSUE TITLE
[question] out of range distance

### ISSUE THREAD

**Issue by shikulja** [shagu/pfUI#1012]
Didn't find how to increase distance, transparency out of range
![image](https://user-images.githubusercontent.com/3386359/101827995-099b8700-3b42-11eb-8d6e-9b3c72f148eb.png)
she's too small for my class. and the norm is 40> yards  (as much as possible for my spells)

**Comment by shagu** [comment]
If you enable the 40y rangecheck (which is bad on performance) you will get 40y range checks. Otherwise 28y is the only sane thing the API allows to do.
