### ISSUE TITLE
TotemTimers skin

### ISSUE THREAD

**Issue by wowvault** [shagu/pfUI#1014]
First of all, thank you for your work. It's clearly a labor of love and it shows. I've recently made the switch from ElvUI, which I've been using exclusively for two years, and I couldn't be happier with my decision. Normally I wouldn't make such a drastic switch but some of the standalone addons I had been using with ElvUI (pfQuest and ShaguWidget) gave me the confidence that pfUI might be the right decision for me.

As for the "issue" itself, while there's uniformity within the aesthetic of pfUI itself, and even with some of the most used addons, there isn't with an addon which I believe most shamans *have to* use. Here's a screenshot to demonstrate the non-uniformity:

![Screenshot 2020-12-19 191315](https://user-images.githubusercontent.com/62483552/102693838-7f80ac00-422e-11eb-9c86-e09eb3b6cc48.png)

If you look at the screenshot, you'll notice the difference between the action bars (pfUI) and the TotemTimers bars. I believe TotemTimers uses the default Blizzard borders and pfUI has borders of its own and that's what makes the difference. I realize the difference is very small but nevertheless, there's a difference. 

It'd be great if we can get a skin for TotemTimers some time in the future. Sorry for keeping this long. I'll provide additional details below. **Thank you in advance**.

---

**Client**: WoW-TBC 2.4.3
**Server**: Karazhan
**pfUI version**: 4.9.21
**TotemTimers version**: 8.1d ([Download](https://www.curseforge.com/wow/addons/totemtimers/files/87106))
**Additional info**: ElvUI has a skin but it doesn't work for most of the totem bars. But maybe it can help kickstart this feature request, so I'm sharing its code [here](https://github.com/ElvUI-TBC/ElvUI_AddOnSkins/blob/master/ElvUI_AddOnSkins/Skins/Addons/totemTimers.lua). (Or maybe it doesn't help at all, I don't know. I don't have any programming knowledge.)

**Comment by shagu** [comment]
Hi,
Thanks for your detailed feature request. A TotemTimers skin is now available via https://github.com/shagu/pfUI/commit/3b6ef1812ff788fdc5e582f1fe4044cc9b2ac04f and https://github.com/shagu/pfUI/commit/6af467aaf14508e3cb1beefe8dfade40f5d4626b
