### ISSUE TITLE
about bag sorting

### ISSUE THREAD

**Issue by deartonym** [shagu/pfUI#1015]
I heard there should be bag sorting function in pfUI for vanilla WoW 1.12.1, however I just cannot find it.

Could you plz confirm about how to use it? if it does not have this function, how to make the pfUI compatible with Baggon? 

Thank you.

**Comment by shagu** [comment]
Hi,
The bag sorting was never part of pfUI. It requires an external addon to show a bag-sort button on the bags.
The following are supported:

**Vanilla:**
- SortBags https://github.com/shirsig/SortBags-vanilla
- MrPlow https://www.wowace.com/projects/mr-plow/files/288059

**TBC:**
- MrPlow https://www.wowace.com/projects/mr-plow/files/136162
- Bag_Sort https://www.curseforge.com/wow/addons/bag-sort/files/84453

If you want to use Bagnon instead, you can simply disable the "bank" and "bag" components of pfUI in the settings.
