### ISSUE TITLE
Totemtimers (tbc) skin

### ISSUE THREAD

**Issue by Retinus** [shagu/pfUI#1017]
Hello shagu,

I' m using version 4.9.25 on a tbc server. When i 'm in combat and hover above totemtimers addon (trying to drop a totem) i m getting "interface action failed because of an addon" error (the list of available totems isn't populated). When i disable the skin all works ok in combat.

**Comment by shagu** [comment]
Hello and Thanks for your report. Fixed by https://github.com/shagu/pfUI/commit/2d1619c3c63c3583533065fd81f26d5fefa8ca6b and https://github.com/shagu/pfUI/commit/40a41ee436a76dc4810915be1bb032c05b001fcb
