### ISSUE TITLE
Focus Target Frame

### ISSUE THREAD

**Issue by kotisorion** [shagu/pfUI#1020]
I would really like a focus target frame added if possible. I'm currently having to use an entire seperate unit frame addon for that one frame.

**Comment by shikulja** [comment]
something similar was in the new add-ons, in pandaria for sure, you could select a target, and with the right mouse button, make it focus.

**Comment by kotisorion** [comment]
I think you are misunderstanding. What I'm looking for is to be able to see the Target of my Focus as a unit frame. There is currently no option for that type of frame in PFui.

**Comment by kotisorion** [comment]
![image](https://user-images.githubusercontent.com/53839088/104852445-b646f200-58c0-11eb-8daf-6deb9e110e89.png)


There are currently:
Target-Target
Target-Target-Target
Pet - Target
Group - Target

What I want added is Focus - Target

**Comment by shikulja** [comment]
@kotisorion no, I was not mistaken, in newer add-ons such functionality was, for blizzard ui. There, the target can be selected as a focus frame.

(no one addon was installed, pandaria)

![image](https://user-images.githubusercontent.com/3386359/104852520-87566d80-590c-11eb-9104-5a36c574ba12.png)


you suggested a good idea, in pfui, it is needed

**Comment by kotisorion** [comment]
I'm not talking about being able to select my target as a focus with a right click menu option. That can be done with a /focus macro. I'm talking about a unit frame that pfui doesn't have the option to display. 

As a healer, I use the focus frame to display the raid boss we are fighting and it is important for me to be able to see what the boss is targeting. But in pfui the target of the focus cant be seen because the frame for it doesnt exist.

**Comment by shikulja** [comment]
I used to do this, ora2 - assign player targets or x-perl - tank module

**Comment by kotisorion** [comment]
As I said in my original post, I already have a work around for the issue. I came here to request the frame be added to pfui. sorry for the trouble.

**Comment by shagu** [comment]
> I would really like a focus target frame added if possible. I'm currently having to use an entire seperate unit frame addon for that one frame.

Thanks for your suggestion :+1: 
I can't estimate the work required for that right now. I will most probably check it the next days. But I can't promise anything yet.

**Comment by shagu** [comment]
Focus-Target frames (disabled by default) are now included by https://github.com/shagu/pfUI/commit/ab3d853f02a76100cbaa47f63e84f01e2a5624ee
