### ISSUE TITLE
Buff Icon Tooltip missing talent bonus

### ISSUE THREAD

**Issue by ntroast** [shagu/pfUI#1024]
Power Word: Fortitude shows +79 stamina in buff tooltip, but +102 in actionbar tooltip

**Comment by shagu** [comment]
Did you tried without pfUI? This is most likely a client issue.

**Comment by ntroast** [comment]
Yeah its a client issue, any way to workaround?

**Comment by shagu** [comment]
Nope, pfUI just calls `GameTooltip:SetSlot(id)` and `GameTooltip:SetPlayerBuff(id)`. The text inside is produced by the client.
