### ISSUE TITLE
ShaguScore error

### ISSUE THREAD

**Issue by shikulja** [shagu/pfUI#1029]
no matter. but there is a mistake. When you hover over enchant with the mouse.
In ATSW addon, maybe it will be in other profession addons too

![WoWScrnShot_021621_193100](https://user-images.githubusercontent.com/3386359/108093137-74ab9180-708e-11eb-9de9-43e83dd116c4.png)

**Comment by shagu** [comment]
This is unrelated to pfUI. Please use the [ShaguScore Bugtracker](https://github.com/shagu/ShaguScore/issues) next time.
Issue should be fixed by this commit: https://github.com/shagu/ShaguScore/commit/25c5967338b999ce86e61763eb4fb0cf3f533733

**Comment by shikulja** [comment]
thanks
