### ISSUE TITLE
Mouse over option for action bars

### ISSUE THREAD

**Issue by kalavera** [shagu/pfUI#103]
I love this funtion for easely making changes to the action bars while keeping the UI clean. The micro menu could use the option as well :D

Many thanks for pfUI it rocks!!!

**Comment by shagu** [comment]
Ehm.. I don't understand, sorry

**Comment by kalavera** [comment]
The action bar is hidden untill you put your mouse over it, then it's hidden again when you remove the mouse from the bar.

Really it's fine without but it could be a nice touch to add down the line :D

Keep up the good work !

**Comment by shagu** [comment]
Ah, okay :)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/65b93c779aeaa6d4a51326dd923f5e58ffe2cf71
