### ISSUE TITLE
Player's healthbar embedded portrait

### ISSUE THREAD

**Issue by Baddha** [shagu/pfUI#1030]
It turns into 
![Sin título](https://user-images.githubusercontent.com/79361424/108593913-f2191f80-7376-11eb-887f-66aa69991949.png)
 randomly. Same with pet's healthbar embedded portrait.
 
Edit: seems to proc after opening game's default map 
![Sin título](https://user-images.githubusercontent.com/79361424/108594029-cba7b400-7377-11eb-8205-40bf5c7044f0.png)
(after selecting this option)

**Comment by shagu** [comment]
Fixed by: https://github.com/shagu/pfUI/commit/af2bb5212c0991df6f8df9c47859745baa328428
