### ISSUE TITLE
[Feature Request] Switch character chat language

### ISSUE THREAD

**Issue by UncleSweaty** [shagu/pfUI#1032]
As far as I'm aware there's no way to switch what chat language you speak in (Common, Orcish, etc), other than to disable the chat component altogether. It would be nice to have a right-click menu to select which language you type in, or have a hotkey to cycle between languages (maybe Alt+Click on chat tab?).

**Comment by shagu** [comment]
You can right-click the chat button to access the dropdown menu:
![image](https://user-images.githubusercontent.com/11586807/110980909-a8fd2f80-8366-11eb-98dc-cb0d0aac64b0.png)

**Comment by UncleSweaty** [comment]
I don't seem to have the icon you're right clicking. I am running the TBC version and updated the mod last week.

**Comment by shagu** [comment]
The icon is part of the "chatcopy" module, make sure to have it enabled
