### ISSUE TITLE
Inbox Elements not clickable

### ISSUE THREAD

**Issue by JensAltst** [shagu/pfUI#1037]
Well since I found the Repository I might as well... 

My Inbox [Mail window] bugs out, and it seems like it renders the background elements in front of the list items.

![grafik](https://user-images.githubusercontent.com/49022685/112349329-ec419180-8cc8-11eb-8d50-af7a0e557c37.png)

I can't click on anything but the checkboxes. This happens very inconsistently, so I have no Idea where to start <.<

**Comment by shagu** [comment]
I don't know what mail addon you're using there. But it looks like the pfUI skin does work with it.
You can disable it in Components -> Skins -> Disable Skin Mailbox

**Comment by JensAltst** [comment]
Okay, I think I tried disabling all addons besides pfui, but I might be wrong. Anyways, thanks!
