### ISSUE TITLE
Add Clique Functionality

### ISSUE THREAD

**Issue by t3hWheez** [shagu/pfUI#104]
Would love if a feature like Clique could be added, working version of Clique is here:  http://armory.digam.dk/?sa=download.file.info&p1=3&p2=13.  It appears you may have something for raid frames but to have it enabled on all frames would be fantastic.

Thanks

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/df4be70f1800b2ece5af44908fa6ad55d834cc83

**Comment by shagu** [comment]
https://github.com/shagu/Clique/commit/a5ee56c3f803afbdda07bae9cd330e0d4a75d75a

**Comment by t3hWheez** [comment]
Is this to be expected on next release?  Is there a specific version of Clique we need to use?

**Comment by crumdidlyumshis** [comment]
@t3hWheez shagu linked his updated version of Clique that he himself fixed in order for it to work properly with pfUI. Click this link: https://github.com/shagu/Clique

Download the addon and once extracted, remove the "-master" on the end and move it to your Interface/AddOns folder.

**Comment by t3hWheez** [comment]
This is literally amazing.  I love you Shagu.
