### ISSUE TITLE
pfui and lazpig breaks world chat

### ISSUE THREAD

**Issue by Brooodley** [shagu/pfUI#1040]
Basically if i have pfui and lazypig active at the same time i can't see world chat anymore.

**Comment by shikulja** [comment]
lazypig has many versions, old versions with cli, others with window, more specific version needs to be specified

**Comment by shagu** [comment]
It's unrelated to pfUI. LazyPig has a Spam filter option that removes those messages.

**Comment by Brooodley** [comment]
version 5.32
and i have the world chat spam filter turned off

**Comment by shagu** [comment]
![image](https://user-images.githubusercontent.com/11586807/128995277-334f98ea-38db-4ebc-a706-4f8663b33713.png)
