### ISSUE TITLE
Option for abbreviated name on unit frames

### ISSUE THREAD

**Issue by Voxnox1** [shagu/pfUI#1044]
Please could an additional option be added to include abbreviated names as longer names can overlap the health text if the unit frame is small. 

![abbrevnames](https://user-images.githubusercontent.com/25552455/131232264-a0e481f6-ac71-4e80-ba8a-adea7e96dd94.png)

Many thanks!

**Comment by journeym** [comment]
Seems this is already working

**Comment by shagu** [comment]
Oh sorry. I completely forgot there was an issue open for that. Thanks
