### ISSUE TITLE
Unable to unlock while unit frames disabled

### ISSUE THREAD

**Issue by mrrosh** [shagu/pfUI#105]
I've disabled the unitframes and when trying to unlock the frames I'm getting this error and the option doesn't work: http://i.imgur.com/zgfAmJR.png

*Edit: Not referring to unitframes not being able to unlock them, I'm talking about the whole option of unlocking all the frames. Doesn't work at all.

**Comment by Cruzix** [comment]
Noticed this a few days ago as well, forgot to report it tho. Well at least i can confirm it now ;)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/92721c57f7565306f1d648561803fb1e894ed729
