### ISSUE TITLE
Experience bar doesn't show rested XP while under tent until /reload (Turtle WoW)

### ISSUE THREAD

**Issue by JustVityok** [shagu/pfUI#1053]
Playing on turtlewow currently. It has feature with rested xp in tents, but i realized one thing - in vanilla UI rested XP slider moves while under tent (updates in real time), but in pfUI it doesn't change until I use /reload

**Comment by shagu** [comment]
It should now by fixed in the latest version via this commit: https://github.com/shagu/pfUI/commit/e95a912b6a81580e3ac2c61ec83870c80b27d031

However, I can't easily test it as I don't have a character there that I could use for it. So please report back if it worked.

**Comment by shagu** [comment]
Thanks to Zojoron who gave my level 1 character a tent, I was able to test it. The above fix solves the issue, closing this issue.
