### ISSUE TITLE
ShaguScore incompatibility

### ISSUE THREAD

**Issue by JustVityok** [shagu/pfUI#1054]
So, i wanted to use ShaguScore, but quantity of items and GS is written in same place (right lower corner) and there is no way to change it. Can we get a possibility to move those numbers to different corners (i.e. to left corner for ShaguScore, right corner for stacks of items?).

**Comment by shagu** [comment]
Fixed by: https://github.com/shagu/pfUI/commit/754b4d53faf8e00da9008cfd054d8dab8db0c6f4
