### ISSUE TITLE
Zone name doesn't tell is it Alliance, Horde or contested turf

### ISSUE THREAD

**Issue by palimoschnitzel** [shagu/pfUI#1055]
You can never know is it Alliance/Horde or contested territory by zone name under minimap. Can we get them colored as in vanilla ui (green for friendly, red for hostile and orange for contested territories)?

**Comment by shagu** [comment]
Not sure when I will find time for it. In the meantime, there's another zone name on the minimap that can tell you:
![image](https://user-images.githubusercontent.com/11586807/141094126-6455d176-3633-4c14-8ac5-71551b2b9c07.png)
