### ISSUE TITLE
Unusable items don't glow red and spells like Mage's "Slow fall" don't show quantity of reagents until /reload

### ISSUE THREAD

**Issue by JustVityok** [shagu/pfUI#1056]
Title. For example, I can't use mail armor as a Mage, so it should glow with red. However, it does like that only after I use /reload. Also, for example Mage spell "Slow fall" won't show number of Light Feathers I have until /reload command

**Comment by shagu** [comment]
Please provide more details:#
- Vanilla or TBC?
- Are you using the latest version of pfUI?
- Did you disabled all other addons to reproduce the issue?
- Did you tried with using the "default" settings of pfUI?

> I can't use mail armor as a Mage, so it should glow with red. 

If you play TBC, then please update to the latest version of pfUI. 
The module for unusable items was not yet whitelisted for TBC: (https://github.com/shagu/pfUI/commit/4ebff6ba092363e00620421fb7225f2c738a7a86)

**Comment by JustVityok** [comment]
ok, i'm sorry
1. Turtle WoW, so Vanilla, i guess
2. Yes
3. Tried, didn't help
4. Tried, didn't help either.
It happens when I log in world and then I have to use /reload and no issues until i exit and enter the game again

**Comment by JustVityok** [comment]
UPD.
Armor durability doesn't change until /reload, too (but strangely, repair cost is shown). For example, i have ~65% durability, but until reload it shows 100%

**Comment by JustVityok** [comment]
UPD.
Figured out it was because I have a .bat file that clears WDB folder every time i start WoW. So the problem is that the cache of game is cleared upon login, I guess..,

**Comment by nonameform** [comment]
I have to second on both of those issues. Sometimes when I loot items they won't have a red glow even though I cannot use them (both armor and weapons). That usually fixes on it's own after some time.

When playing a Hunter I have an ammo counter on my bars and when I top up my bags with projectiles and have a partially used stack, at first it will only show the amount of arrows/bullets in full stacks. For example, I have 6 stacks of arrows. 5 are full stacks, one has 100 arrows. The total on the bar will be 1000 arrows. After some time (maybe after firing an arrow? cannot tell at the moment) the total will reflect the actual count of projectiles.

**Comment by nonameform** [comment]
To illustrate. Looted a mace which I cannot use as Hunter. It is not tinted red.

![WoWScrnShot_052722_141552](https://user-images.githubusercontent.com/34381716/170693078-331ba6b6-dce9-4f2f-94dc-9d250d15d235.jpg)

I do a /reloadui and then I loot another mace. As you can see, both items are tinted red.

![WoWScrnShot_052722_141746](https://user-images.githubusercontent.com/34381716/170693183-6fb16af6-f61e-4a5c-9509-456ec390431b.jpg)

![WoWScrnShot_052722_141835](https://user-images.githubusercontent.com/34381716/170693241-071caa51-029c-4f67-9e6f-441bb11a349b.jpg)

Arrow counter:

![WoWScrnShot_052722_144145](https://user-images.githubusercontent.com/34381716/170693377-20379c72-bf31-4a7f-8c59-db69f0bd60f9.jpg)

I top up:

![WoWScrnShot_052722_144150](https://user-images.githubusercontent.com/34381716/170693419-8504e1af-acc6-4e70-9f44-7e1818498c95.jpg)

Shot an arrow at a critter:

![WoWScrnShot_052722_144815](https://user-images.githubusercontent.com/34381716/170693575-f48b190c-8565-4c43-8014-c08304d8ba5a.jpg)

**Comment by nonameform** [comment]
Basically every time I start the game now, I do a reload, so that unusable items are highlighted when I loot them. For whatever reason the red highlight won't work otherwise. Some items in the bank while I am moving items between bags and bank might change from red to no highlight then to red again. And those aren't even the items I am moving (have plenty of locked lockboxes which I cannot open at the moment).

Also an update on the ammo counter: I filled a 14 slot quiver with full stacks of arrows at the vendor and the total number was 2600, while it should have been 2800. Firing an arrow or reloading the UI fixes the counter. It seems that the counter only updates when you buy the next stack, so if I have some extra arrows outside of my quiver (full 14 stacks + 1 stack with less than 200 projectiles), the total number will be 2800, until I fire a shot or do a reload.

**Comment by journeym** [comment]
> Some items in the bank while I am moving items between bags and bank might change from red to no highlight then to red again. And those aren't even the items I am moving (have plenty of locked lockboxes which I cannot open at the moment).
This is true for me also
