### ISSUE TITLE
"Enable 40y-range Check" doesn't work unless a healing spell is directly on your bars

### ISSUE THREAD

**Issue by BarneyGumball** [shagu/pfUI#1058]
Tested in a raid group as a Shaman with "Enable 40y-range Check" enabled.  Adding and removing a healing spell from my bars (directly, not as a macro) swaps the spell check range between 30 and 40 yards.

This means if all your healing spells on are /pfcast macros, you need to sacrifice an action bar slot to get 40 yard range checks.

**Comment by shagu** [comment]
Exactly. The addon scans for a healing spell with 40y range on your actionbar and uses this to check distances against targets.
So one of those spells has to be on any of your 120 actiobar slots: https://github.com/shagu/pfUI/blob/master/libs/librange.lua#L18-L40
