### ISSUE TITLE
Buff Indicator timers for target/party not displaying

### ISSUE THREAD

**Issue by Rammue** [shagu/pfUI#1059]
When selecting to add timers to buff/hot indicators for targets and/or party it doesn't display the timer.
Tried reloading UI and resizing the indicators incase that was the problem but it still isn't displaying as it seemingly should.
This is for the 1.12.1 client and most recent version of PFui sorry if this is not an issue with the addon and maybe ends up being user error but I couldn't get it to work properly. >.>

**Comment by m88beau** [comment]
I can confirm. I am having the same issue.
WoW 1.12.1, latest build of pfUI. Timers work fine on self-name plate, but target shows no timer on debuffs/buffs/HoTs

**Comment by shagu** [comment]
The addon only has a database builtin for debuff timers and tries to estimate them. 
It doesn't have one for buff timers, you only see what the client is capable of.

I also have no plans to add buff-estimation because its even more ugly to write than the debuff timers.
