### ISSUE TITLE
bags: quest item border colors

### ISSUE THREAD

**Issue by Lemonadez** [shagu/pfUI#1063]
Is there a way to have Color Quality for Quest Item on Bag? Maybe there option on it, if anyone can help me.

**Comment by shagu** [comment]
Feature added by: https://github.com/shagu/pfUI/commit/a886c740ec02010b1d2ce7e25de3382016abfa2a

![Bildschirmfoto vom 2022-12-22 12-40-16](https://user-images.githubusercontent.com/11586807/209127240-9793afa1-cb9e-4981-b278-12916f5eba77.png)
