### ISSUE TITLE
Debuff durations 

### ISSUE THREAD

**Issue by kotopeska** [shagu/pfUI#1064]
installed the pfui addon and the pfui vanilla+ addon and got a problem: I don't see the debuff durations if the default(not changed) target frame is enabled, how to fix it so that the debuffs become visible? pfui target is showing debuff durations.

**Comment by kotopeska** [comment]
![image](https://user-images.githubusercontent.com/56514506/152035219-a011cadb-4670-41dc-a70d-e8acae21a563.png)
![image](https://user-images.githubusercontent.com/56514506/152035435-d57d2b76-0a74-44d8-8c28-4c1249620228.png)

**Comment by shagu** [comment]
This addon is a replacement of the default interface. In other words, it does not modify it, it replaces it.
If you choose to disable a component, you won't have the component's features.

You might want to have a look at [DebuffTimers](https://github.com/Voidmenull/DebuffTimers).

**Comment by kotopeska** [comment]
thanks for clarifying, I spent another 1 hour figuring out the settings and finally I liked how your addon looks. other addons on vanilla+ incorrectly show buff durations. thanks a lot for your addon
