### ISSUE TITLE
Feature Request: Mana bar for shapeshifted druids.

### ISSUE THREAD

**Issue by kotisorion** [shagu/pfUI#1065]
I'd like to be able to see my mana bar while in cat or bear form as well as the energy/rage bar. Ideally place it right below the energy/rage bar itself. If this is something you 100% know you dont want to do, please msg me and i'll look for some other way to add it like with weak auras or something like that.

Thanks for making this addon. It's my fav unit frames for tbc client.

Korion

**Comment by shagu** [comment]
I have no plans to add this feature. 
There are two addons that provide such a feature:

Vanilla: https://github.com/gashole/DruidManaBar
TBC: https://www.curseforge.com/wow/addons/druid-bar/files/86307

For both addons, pfUI provides glue code to apply a matching style to them.

**Comment by kotisorion** [comment]
thanks for the links and for the work you've done.
