### ISSUE TITLE
ChatTabs randomly move

### ISSUE THREAD

**Issue by Rugara312** [shagu/pfUI#1066]
If you create 6 chat windows on the left frame, tabs start randomly moving. 

https://cdn.discordapp.com/attachments/707351435570053171/974120326973779998/unknown.png

**Comment by erikblues** [comment]
I have the same issue. There seems to be a "ghost" element between the chat tabs.

**Comment by sh3ppard** [comment]
Also if you created custom window then after relog you will be stuck on latest window instead of first window and you need to click it manually on window to fix.

**Comment by pn954095** [comment]
Any idea how to fix this? Its happening to me as well.
