### ISSUE TITLE
Add a third party option for addon EquipCompare and Informant

### ISSUE THREAD

**Issue by mrrosh** [shagu/pfUI#107]
This addons are a must-have and would be nice to skin them to fit pfUI theme.
Thank you!

http://i.imgur.com/rydkyfb.png

**Comment by Br4inworm** [comment]
I think it would help a lot to add the most recent version in a download link.

**Comment by mrrosh** [comment]
Download link for both addons: http://www.mediafire.com/file/2mjsbg2d0465nle/EquipCompare+Informant.rar

**Comment by dikdigguh** [comment]
Hey bud, here'ssomething can paste into your EquipCompare folder. Rename it to EquipCompare.xml and it will replace the old file.

[EquipCompare.txt](https://github.com/shagu/pfUI/files/597841/EquipCompare.txt)

**Comment by mrrosh** [comment]
Thanks a bunch @dikdigguh ! Really awesome of you! :+1:

**Comment by shagu** [comment]
Hi, I'd like to build these addons on my own, at least it was planned to do so. 
This will need some time, because there are alot of "more prioritized" bugs/features right now.
You might stick to dikdigguh's contribution until then.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/b210b07a0e8c847f8b423d9a78733d0f48e7e341

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/a3473e46ce41114e52e1683ac3d232c05f50fc79

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/a3473e46ce41114e52e1683ac3d232c05f50fc79

**Comment by shagu** [comment]
Use Shift-Key to enable extended sell/buy values on the tooltip and to show equip compare
