### ISSUE TITLE
Lua errors (nil value) - latest addon version

### ISSUE THREAD

**Issue by ValentinTyanov** [shagu/pfUI#1070]
Greetings, your addon seems great, that's why I stopped on it. I'm a returning player, literally got a fresh TBC install.
I've tested it with no other addons enabled, yet I'm still having issues. I've tried other UI addons and they're working just fine.
I receive the following 3 errors instantly when I login:
interface\addons\pfUI-tbc\api\unitframes.lua:192: attempt to index global 'this' (a nil value)
interface\addons\pfUI-tbc\api\unitframes.lua:157 attempt to index global 'this' (a nil value)
interface\addons\pfUI-tbc\api\ui-widgets.lua:11: attempt to index field 'unitframes' (a nil value)

I couldn't find an older version, as I mentioned in the subject I'm using the latest master version.

**Comment by shagu** [comment]
Hello, is this on retail TBC? 
Because the Addon only works for Vanilla (1.12) and TBC (2.4.3) which were the clients from 2006 and 2007 not the ones used in "Classic".
