### ISSUE TITLE
auto-dismount from turtle-wow turtle mount stopped working

### ISSUE THREAD

**Issue by journeym** [shagu/pfUI#1071]

**Comment by journeym** [comment]
Seems this is after todays patch

**Comment by shagu** [comment]
Fixed by this commit: https://github.com/shagu/pfUI/commit/d315d3f66987404ec2919acb988aebe950a73dd8

**Comment by norstromo** [comment]
Still does not work

**Comment by norstromo** [comment]
> Fixed by this commit: [d315d3f](https://github.com/shagu/pfUI/commit/d315d3f66987404ec2919acb988aebe950a73dd8)
still does not work
