### ISSUE TITLE
Disable "Hide chat frame" button on panels when PF-UI chat module is disabled

### ISSUE THREAD

**Issue by zasnool** [shagu/pfUI#1074]
"hide chat frame" button in question:
![Untitled](https://user-images.githubusercontent.com/100788360/182407869-a9c18b5e-4d7e-48df-bd8c-7cba88704cf5.png)
Right now with PF-UI chat module disabled it only gives this error when clicked:
![Untitled](https://user-images.githubusercontent.com/100788360/182407389-9975eec7-b1cd-4d78-bf7d-0db100533e55.png)

Two options here: either remove the button completely when PF-UI chat module is disabled or make it so that it hides the games default chat window frame.

**Comment by shagu** [comment]
Fixed by: https://github.com/shagu/pfUI/commit/76e8804741983e9826b4df239cfce4a3cec95bb2
