### ISSUE TITLE
Macro Icons Bugged

### ISSUE THREAD

**Issue by Mozlo** [shagu/pfUI#1077]
Everytime I make a macro with a custom icon, it bugs and will change the icon randomly of all my macros to either autoshot or another icon like raptor strike which is quite frustrating when trying to differentiate abilities as they all look the same. Is this something on my end?

**Comment by shagu** [comment]
Is it the latest version and do your macros each have a different name?

**Comment by Zilthoras** [comment]
Hi,
I am having the same issue. I will post som Screenshots of it here. For some reason all my Macros turns into the one recently loaded, or just randomly change icon. But all macros gets the same icon if it is Character Specific Macro.
![image](https://user-images.githubusercontent.com/115936753/205498823-0c9ac70a-4ecf-471a-8049-e13514e36f14.png)

**Comment by shagu** [comment]
Please give your macros a name and fix your addon errors. A tilting addon can cause unforseen problems to the rest of the addons.

**Comment by Zilthoras** [comment]
I will disable Questie which gives errors, as well as giving macros name. Reporting later on my find if it fixes it.

**Comment by Zilthoras** [comment]
Hello! Wanted to confirm that **naming the addons** fixed the issue of icons and spell references.
