### ISSUE TITLE
unitframes: overlay castbar ontop of powerbar

### ISSUE THREAD

**Issue by TheDenast** [shagu/pfUI#1078]
Basically, the option I'm looking for is to be able to embed castbar inside the unitframe over the resource block (mana, energy, etc.). I think elvui and other UF addons have such option.  When you/your target cast a spell, the castbar replaces the resource part of unitframe and when the cast is finished it goes back.

P.S. I am very sorry if this feature is implemented already, but I could not find such option in the config.

**Comment by Pizzahawaiii** [comment]
@TheDenast Note that you can achieve this by manually adjusting your castbar dimensions and moving it over your powerbar. At least that's what I did for [my UI](https://github.com/Pizzahawaiii/pfUI-pizzaUI).

I know, I'm late to the party.

**Comment by TheDenast** [comment]
@Pizzahawaiii I'm not playing vanilla atm, but thanks!

**Comment by shagu** [comment]
I do like that idea, it's also how it was back in ShaguUI. Sadly, I won't have the time to do it in near future tho.
If anyone is eager to implement that, a pull request would be highly appreciated.
