### ISSUE TITLE
Nameplate healthbars not updating

### ISSUE THREAD

**Issue by travisdmcdaniel** [shagu/pfUI#1083]
When entering combat, the nameplate healthbar does not begin updating immediately. Usually, the healthbar will start to update a few seconds after combat has begun, but it is not in sync with the target frame. I'm using the latest version of pfUI on the [Turtle WoW private server](https://turtle-wow.org/#/home).
![2022-08-30 18_14_56-World of Warcraft](https://user-images.githubusercontent.com/29153511/187555693-12685e5b-917e-4eac-9743-51482078bcaf.png)
![2022-08-30 18_28_59-World of Warcraft](https://user-images.githubusercontent.com/29153511/187555697-581785f3-ec7c-4ab3-946c-730adb4aa053.png)

**Comment by shagu** [comment]
Do you use MobHealth or anything else that messes around with health values or any other nameplate addon?
I can't reproduce it when pfUI is the only active addon

**Comment by travisdmcdaniel** [comment]
> Do you use MobHealth or anything else that messes around with health values or any other nameplate addon? I can't reproduce it when pfUI is the only active addon

Ah, it was 100% caused by MobHealth. I don't even remember adding that one. Sorry for the bogus issue!
