### ISSUE TITLE
casts, breath and fatigue bar unlocked after killed a mob

### ISSUE THREAD

**Issue by khoopek** [shagu/pfUI#1089]
![image](https://user-images.githubusercontent.com/110908179/191746241-a8f381e6-d8db-4a50-be51-450da9a9cbf7.png)

player and target castbar, breath bar and fatigue bar became unlocked after killing a mob.
couldn't hide/lock it unless i logout and login again.

Happened after I reinstall wow client and reconfigured pfui config.
reinstalling addon doesn't fix the issue.

**Comment by shagu** [comment]
That's quartz / oCB3, not pfUI.
