### ISSUE TITLE
Macro Extender breaks pfUI

### ISSUE THREAD

**Issue by VioletteClifford** [shagu/pfUI#1090]
![image](https://user-images.githubusercontent.com/114336853/192137947-df442a6a-bb62-49f0-b6c7-130cd61a7af9.png)
MacroExtender breaks pfUI, you can't interact with the Profile Menu anymore, can't unequip items, can't hover over them to see their stats at all.
![image](https://user-images.githubusercontent.com/114336853/192137987-782fa1e3-f61e-486f-9a55-1518925a9f03.png)
http://proxicide.github.io/MacroExtender/
https://github.com/PROXiCiDE/MacroExtender

**Comment by VioletteClifford** [comment]
When you press 'c' the whole window is greyed out and unusable.

**Comment by shagu** [comment]
https://github.com/PROXiCiDE/MacroExtender/blob/master/Lib/Inventory.lua#L300
oof... Not sure if I'm going to workaround that within pfUI.

**Comment by shagu** [comment]
Disabled the breaking MacroExtender functions from within pfUI by this commit:
https://github.com/shagu/pfUI/commit/2c58b41c340eb1630ff069210b288d01e0934f1f
