### ISSUE TITLE
Opening the Ironforge map doesn't work

### ISSUE THREAD

**Issue by VioletteClifford** [shagu/pfUI#1091]
Hello,

Opening the Ironforge map doesn't work at all when you are outside the city on alliance characters and clicking on the Ironforge text.

![image](https://user-images.githubusercontent.com/114336853/192891404-9648ff1d-50b0-4528-a75d-580b66690410.png)

I should be able to click on the mountain or the gate and see the Ironforge map.

Edit: Tested all the other maps and cities, all work except this one.

Thank you,
Vi.

**Comment by shagu** [comment]
Hello,

This is also the case for Undercity, but it is the normal game behaviour and not pfUI related. 
The same thing happens if you disable all addons.
