### ISSUE TITLE
Feature Request: Shaman Totem Timers

### ISSUE THREAD

**Issue by 8EightySixed6** [shagu/pfUI#1093]
Can you incorporate Shaman totem timers? It would be amazing to have it in pfUI!

**Comment by shagu** [comment]
Like this?
![image](https://user-images.githubusercontent.com/11586807/200096725-4daae2fa-cd8a-4c10-9b55-d61fdb81d514.png)
It's already part of pfUI.

**Comment by 8EightySixed6** [comment]
Yes! How do I find that in pfUI?

**Comment by shagu** [comment]
![Bildschirmfoto vom 2022-11-05 16-31-10](https://user-images.githubusercontent.com/11586807/200127571-8d796eb1-f2e8-41f8-b88e-69e7a86a1641.png)

**Comment by 8EightySixed6** [comment]
Success! I had another addon conflicting with it. Thank you so much! <3 I love this addon!
