### ISSUE TITLE
Feature Request: Chat - Ability to mute very talking NPCs

### ISSUE THREAD

**Issue by shikulja** [shagu/pfUI#1094]
https://www.wowhead.com/npc=2532/donna
https://www.wowhead.com/npc=2533/william

https://www.wowhead.com/npc=3518/thomas-miller

https://www.wowhead.com/classic/npc=3504/gil

God, I'm ready to pay the horde for silence

<img width="528" alt="image" src="https://user-images.githubusercontent.com/3386359/202763830-43ba97e6-04c4-4326-84cb-d89d95ad154e.png">

**Comment by shagu** [comment]
Maybe you should search and use a chat filter addon, or simply disable NPC chat in the chat window.
I don't see this added to pfUI. Thanks for the suggestion tho :)
