### ISSUE TITLE
Module\skin error

### ISSUE THREAD

**Issue by shikulja** [shagu/pfUI#1099]
When using the Aero+PfUI addon, an error occurs
<img width="487" alt="image" src="https://user-images.githubusercontent.com/3386359/207149180-82942572-18d2-4144-bf07-c1a3ae863bcb.png">

[https://github.com/gashole/Aero](url)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/4e22cb320117684963700a71eeeaf9803a32209e

**Comment by shikulja** [comment]
@shagu 
ERROR: Interface\AddOns\pfUI\modules\map.lua:129: attempt to perform arithmetic on local `mx' (a nil value)

**Comment by shagu** [comment]
> @shagu ERROR: Interface\AddOns\pfUI\modules\map.lua:129: attempt to perform arithmetic on local `mx' (a nil value)

Fixed via: https://github.com/shagu/pfUI/commit/635456b8ec6ed157408130b4241ebe54ecd1b32f

**Comment by shikulja** [comment]
@shagu With this fix, the map opening animation does not work.

**Comment by shagu** [comment]
> @shagu With this fix, the map opening animation does not work.

It does work for me, and the fix can't have an impact on the animation. There's something else wrong on your side.

**Comment by shikulja** [comment]
@shagu was disabled. sorry
