### ISSUE TITLE
Issue with pet bar scaling.

### ISSUE THREAD

**Issue by AirChandler** [shagu/pfUI#110]
As you can see from this image: http://i.imgur.com/MBWEBv0.jpg the highlights for the active pet abilities don't scale along with the bar size.

**Comment by shagu** [comment]
related to https://github.com/shagu/pfUI/issues/45

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/4afe493b723a7727ef94bf83c54c9481e0cc904b
