### ISSUE TITLE
points of the mobs always remain with 100

### ISSUE THREAD

**Issue by Skrim3** [shagu/pfUI#1100]
why the life points of the mobs always remain with 100 (i.e. the percentage) whereas with Mobinfo2 and without PFUI one has well the number of life points of the mobs.

If you move the mouse over the mob you see the number of hit points but not in the unit frame.

Thx

**Comment by shagu** [comment]
![Bildschirmfoto vom 2022-12-22 10-45-27](https://user-images.githubusercontent.com/11586807/209106393-b4e9c1a6-8b2c-4458-a019-dddaf44e0d63.png)
Works for me running pfUI + MobInfo2
https://github.com/kc8pnd/MobInfo2

**Comment by shagu** [comment]
The problem is, that MobInfo2 overwrites API calls that are used by pfUI to detect mob health which can cause issues. Also on Vanilla there is no real health visible by default and therefore addons try to calculate the health based on the damage that is dealt. Additionally some servers decided to send real values which already breaks some of the health-calculator addons. And the last issue is, that there are hundreds of MobInfo/MobHealth addons around.

Please try with the MobInfo2 version that I've sent you - because that seems to be one of the working ones for me.

**Comment by Skrim3** [comment]
Ok I will test the version, I want to specify that: mobinfo alone (without PFUI) all NPC / Mob and other have their life displayed, Mobinfo disabled with PFui activated some will have their life, others will remain at 100.I will send you some captures tonight of the default. I am on vanilla Nostalgeek (we are several to have the defect)We tested with 3 versions of PFui and yesterday I installed the latest version of mobinfo2Cordialement Mr Régent KévinLe 22 déc. 2022 à 11:46, Eric Mauser ***@***.***> a écrit :﻿
The problem is, that MobInfo2 overwrites API calls that are used by pfUI to detect mob health which can cause issues. Also on Vanilla there is no real health visible by default and therefore addons try to calculate the health based on the damage that is dealt. Additionally some servers decided to send real values which already breaks some of the health-calculator addons. And the last issue is, that there are hundreds of MobInfo/MobHealth addons around.
Please try with the MobInfo2 version that I've sent you - because that seems to be one of the working ones for me.

**Comment by shagu** [comment]
> Mobinfo disabled with PFui activated some will have their life, others will remain at 100

This is normal, as I said. It needs data to estimate health. By default it takes around 5 hits, till pfUI will show the numbers.

**Comment by Skrim3** [comment]
Ok I'll test to type without the weapons 5 shots to see what it isHow can we explain that without PFUI, mobinfo2 estimates the life of NPCs/mob but PFUI can't get the information from mobinfo2ThxCordialement Mr Régent KévinLe 22 déc. 2022 à 12:45, Eric Mauser ***@***.***> a écrit :﻿

Mobinfo disabled with PFui activated some will have their life, others will remain at 100

This is normal, as I said. It needs data to estimate health. By default it takes around 5 hits, till pfUI will show the numbers.
