### ISSUE TITLE
Buff Anchor added

### ISSUE THREAD

**Issue by HS-Disq** [shagu/pfUI#1107]
Hi Shagu,

Ever since I upgraded from pfUI from 5.2.2. to 5.3 (for I am still grateful for continued support btw), my entire profile works fine and got imported fine, except that I have an extra buff now attached to my character frame. I went through the entire options, but I can't find it. I have disabled Buff Indicators at Unit Frames > Player and I have disabled Buff Display in Buffs > Buff/Debuff Icons.

I like the bar and I like to keep it, but not those buffs as I have those covered by VCB (Vanilla Consolidated Buffs).
![image](https://user-images.githubusercontent.com/21331842/209727302-d37bd0db-7ad2-4b45-a96b-84695acf01ca.png)

Attached a screenshot of what it looks like. I may be missing an option, but I can't find it.

Cheers!

~Disq

**Comment by shagu** [comment]
Set Buff Position to "Disabled" in the Unit Frames -> Player options:
![image](https://user-images.githubusercontent.com/11586807/209738690-2d9409a7-db44-4d3b-afb0-bec80b27e9b4.png)

**Comment by HS-Disq** [comment]
Absolute legend you are and apology from me not reading this right!
