### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by herkan** [shagu/pfUI#1108]
1. An optional raid frame that includes all the pets in the raid
2. Ability to show important debuffs and buffs (Polymorph, Reckless Charge, Mortal Strike for example) as icons on the raid frames with countdown timers, maybe a blacklist/whitelist system like the player/target buff bar
4. Blessing of Sacrifice, Freedom and Protection doesn't show as a buff indicator on raid frames, would be nice if they did or if there was an option to show them
5. The resource tick indicator on the player frame is not very reliable, haven't compared it to other addons like EnergyWatch yet - maybe it's universally unreliable

not sure if any of it is doable due to 1.12.1 limitations tho..

cheers

Edit: Just found the "Custom Indicators" option after looking around a bit more, my bad

**Comment by shagu** [comment]
Hello, thanks for your suggestions :)

> 1. An optional raid frame that includes all the pets in the raid

This is already tracked here: https://github.com/shagu/pfUI/issues/1092

> 2. Ability to show important debuffs and buffs (Polymorph, Reckless Charge, Mortal Strike for example) as icons on the raid frames with countdown timers, maybe a blacklist/whitelist system like the player/target buff bar

Regarding the general debuff icons, this is already tracked here: https://github.com/shagu/pfUI/issues/996
However, "Custom Indicators" should be what you're looking for (as you already edited ).

> 3. Blessing of Sacrifice, Freedom and Protection doesn't show as a buff indicator on raid frames, would be nice if they did or if there was an option to show them

I just blindly implemented those by this commit right now: https://github.com/shagu/pfUI/commit/abb55cc39cdeeb7f83509d75e83ac2c05816db1c
But I don't have a paladin, and couldn't test it.

> 4. The resource tick indicator on the player frame is not very reliable, haven't compared it to other addons like EnergyWatch yet - maybe it's universally unreliable

The best I could do. If you can improve it, please send a Pull Request :)

In future, please don't do combined issues. It's easier to work, track and keep an overview on individual issues for each topic. Especially to avoid the duplicates.

Cheers
