### ISSUE TITLE
Macro icons bugged

### ISSUE THREAD

**Issue by lsnadk** [shagu/pfUI#1110]
![image](https://user-images.githubusercontent.com/122232652/211217538-9ae3ef23-e29d-4018-a0ba-61e67d9ef9aa.png)

Three different macros look like heroic strike.. The example is on the image. All other addons are disabled.

**Comment by shagu** [comment]
give your macros unique names and it will be fine :)

*duplicate of: https://github.com/shagu/pfUI/issues/1077*
