### ISSUE TITLE
Clickcasting on original Blizzard UnitFrames

### ISSUE THREAD

**Issue by Eierdotter** [shagu/pfUI#1111]
clickcasting does not work unless i enable the Pfui unit frames.
but i kinda like the original unit frames...

help plz

**Comment by shagu** [comment]
Sorry, but pfUI clickcasting is made for pfUI. Like most of the modules inside pfUI, they depend on each other.
If you want click casting for the regular frames, you should use something like [Clique](https://github.com/shagu/Clique) or you can implement it yourself. I'll gladly accept a pull-request for it into pfUI, if its written well.
