### ISSUE TITLE
ChatBar shows wrong window after login

### ISSUE THREAD

**Issue by sh3ppard** [shagu/pfUI#1114]
When you create a custom window for chat then after login **pfUI** shows wrong window as selected.
**pfUI** version: `5.3.0`

_GENERAL_ window:
![image](https://user-images.githubusercontent.com/121023853/213407022-25392c46-00d0-4676-9207-0fa18e4e6091.png)

Options for _GENERAL_ window:
![image](https://user-images.githubusercontent.com/121023853/213407171-05cda44b-bcf4-4d23-b16b-e36ec232640d.png)

I created _WWWW_ window with that options:
![image](https://user-images.githubusercontent.com/121023853/213407293-e0e1801a-9b85-49ce-b729-f03d0368f73a.png)
_WWWW_ window:
![image](https://user-images.githubusercontent.com/121023853/213409462-8ac2c02b-61ac-453e-9261-e229a16dfa05.png)

After login **pfUI** shows _GENERAL_ tab window as selected but actually shows _WWWW_ window instead:
![image](https://user-images.githubusercontent.com/121023853/213406810-3af7cc57-773f-4bc7-9c45-bae0e54f3c21.png)

For fix that you should click on any tab window manually.

**Comment by shagu** [comment]
It's a pain to work with the FCF-Chat functions from the original UI. I don't really understand why it selects the wrong while the other is shown. From now on, it will always show the first chat frame on login by default (https://github.com/shagu/pfUI/commit/ebaebc6304625a47b825779231df9d4a054fd228)
