### ISSUE TITLE
Nameplates [Request]: Threat/target status in nameplate colors

### ISSUE THREAD

**Issue by fairtale5** [shagu/pfUI#1116]
It would be nice if the nameplates included the option to change color based on threat/target like Plater Nameplates or Threat Plates.

Colors for:
- target on tank
- close to losing threat <- this one is important. many addons dont have that and it is a game-changer.
- target on dps
- target on healer

**Comment by shagu** [comment]
It's not possible. Vanilla has no threat-API and can't read nameplate targets. That's things that were implemented from wotlk 3.3.5 onwards but pfUI is only for 1.12 and 2.4.3.

**Comment by fairtale5** [comment]
oh damn, that's a bit sad to hear, but thanks for answering! !nd keep up the great work on pfUI <3
