### ISSUE TITLE
Pet UnitFrame

### ISSUE THREAD

**Issue by Howdn** [shagu/pfUI#112]
I have a Issue with my Pet UnitFrame. The Mana Bar from my Pet (a Warlock Imp and maybe other Pet's wich I can't test for now) is bugged. If it attacks an enemy there is a difference between the Mana Bar from my Pet UnitFrame and the TargetOfTarget UnitFrame.

I added a Screenshot to show the differences.
Hope you can help!

Btw: Thanks for your awesome work. Really a freaking great Addon!

Kind regards

![wowscrnshot_112116_225504](https://cloud.githubusercontent.com/assets/23643834/20502524/ae0966c4-b03e-11e6-9003-c395f70287ae.jpg)

**Comment by Fundaris** [comment]
https://github.com/shagu/pfUI/blob/0d24db8b3ff790630aac271305a418ef96a9b82d/modules/pet.lua#L106

` elseif hpDisplay > hpReal then`
to
`elseif powerDisplay > powerReal then`

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/9fb160443e5e94fda05c41d1ffb714af0e2e78f6
