### ISSUE TITLE
Hide Party Frames during Raid

### ISSUE THREAD

**Issue by Affenfleisch** [shagu/pfUI#1120]
Hey,

is there any way to hide the party frames when youre in raid?

Best,

**Comment by shagu** [comment]
![Screenshot from 2023-02-07 14-47-23](https://user-images.githubusercontent.com/11586807/217262580-99fc1fe9-d11b-4cb3-b3c9-cb2d30878442.png)

**Comment by shagu** [comment]
The same. The screenshot is from the vanilla 1.12.1 version.
