### ISSUE TITLE
Chat box moves/resets window when looting quest items, hearth, handing in quests

### ISSUE THREAD

**Issue by mortaldemon** [shagu/pfUI#1124]
Chat box moves/resets window when looting quest items, hearth, handing in quests, killing quest mobs. I do have pfquest installed. When I left click the general tab it resets and goes back to normal until one of these tasks are performed. This is pfui 5.3 on 1.12 client.

Never had this issue using pfui prior to this on other 1.12 clients, even reinstalled 2 with 2 different clients.

**Comment by mortaldemon** [comment]
![Screenshot (172)](https://user-images.githubusercontent.com/125772551/219903867-2985a0c9-9af5-402f-8823-ac80bfdacc4b.png)
![Screenshot (173)](https://user-images.githubusercontent.com/125772551/219903869-92e4c8a6-7a79-4b5a-9cd5-f010ec20a6f5.png)

**Comment by shagu** [comment]
Sounds like this from the [FAQ](https://github.com/shagu/pfUI#faq)

> **Why is my chat always resetting to only 3 lines of text?**  
You need to disable the "Simple Chat" in blizzards interface settings (Advanced Options). Then relog and reset/run the firstrun wizard again.

**Comment by mortaldemon** [comment]
Yes that worked thanks so much!!!
