### ISSUE TITLE
Change Height & Width in real time not a thing

### ISSUE THREAD

**Issue by Averdrity** [shagu/pfUI#1125]
Hi,

As this is the only UI that has a very small resemblance to ElvUI, I really need to try for some changes.
Only reason I dont play Turtle WoW is cause ElvUI does not work.

I'm trying to get PfUI to work, but its so badly made it takes days to configure it right.
Ya gotta reload with 99% of the changes you make and you cant even see changes you make before a reload, so if tiny changes being made and ya need to reload and reopen EVERYTHING again ya just quit. The Pre-Built UI profiles are trash, they dont even work. So ya have nothing to start from either. The Text Chat Box is stretched from 1 corner of the screen to the other. You cant even change that? Not in real time atleast and you clicking in numbers and reloading and its a fricking pain.

All this work you've done with all the addons is amazing, but why not just try and port an existing one like ElvUI. Cause pfui does not work as intended.

I really wish to play turtle wow, but I cant get this shit to work.
I even tried few shared profiles from people, but those messing it up even harder.

EDIT: The screenshots is also missleading by FAR. Not even close when trying to default it or use the already built in layouts.
If ya look my screenshots down in the comments ya see what I mean with your screenshots.
Wierd white bars
Wierd black bars
Stuff overlapping (even if i change UI Size)
Text Chat Box is HUGE!
much much more..

Try changing these things in the settings are a pain. Its so wierd and hard for no reason..

**Comment by Averdrity** [comment]
![WoWScrnShot_021923_113403](https://user-images.githubusercontent.com/877028/219942820-3bbd5a37-5597-4b47-b2c3-3a1c8180c9ea.png)
![WoWScrnShot_021923_113226](https://user-images.githubusercontent.com/877028/219942822-5f7d4711-7c5d-4c68-9361-c2f3a4f7e552.png)
![WoWScrnShot_021923_113108](https://user-images.githubusercontent.com/877028/219942824-35f0b72f-51e1-4c25-b9a3-1484722668e6.png)
![WoWScrnShot_021923_113056](https://user-images.githubusercontent.com/877028/219942826-89547269-f860-477f-9aed-db328c82d343.png)
![WoWScrnShot_021923_113040](https://user-images.githubusercontent.com/877028/219942828-099bef1c-c488-41ef-89e6-e7502e3bf460.png)
![WoWScrnShot_021923_113026](https://user-images.githubusercontent.com/877028/219942832-59ddc969-b8d9-43c4-b836-6e7e92b24bcc.png)
![WoWScrnShot_021923_113003](https://user-images.githubusercontent.com/877028/219942836-4874aff2-ef20-4ecd-bf94-93f86133291b.png)

**Comment by shagu** [comment]
This happens if you don't read what addons do and just install them all. Here is the description of pfUI-darkmod which your are obviously using:

> The pfUI-darkmod is an example pfUI module that statically configures pfUI. Its purpose is for developers who want to modify pfUI without changing the addon core itself. This addon and its source-code are intended to give developers an idea of how to use the API, hook functions and change basic alignments of pfUI.

> If you're not a developer on your own but like the darkmod as is, feel free to use it. But be aware that you are out of support and on your own.

So the first step to do would be disable pfUI-darkmod...

> [...] but its so badly made it takes days to configure it right. [...] The Pre-Built UI profiles are trash [...]

If you don't like what I did, and hate it that much just remove it. Seriously.

> [...] but why not just try and port an existing one like ElvUI. Cause pfui does not work as intended. [...]

It works pretty well for many people. And I don'T "port" things, because I prefer to write things from scratch.
To learn stuff and having fun with solving problems with the 1.12.1 API on my own.

The way you wrote doesn't really motivate me to spend even a minute on you. So I'm closing this.

I suggest you to go back to retail, where people make money out of addons, where people like you can be demanding things even without paying any respect to the work that has already been done.

**Comment by Averdrity** [comment]
Shagu a real noob

**Comment by Averdrity** [comment]
" And I don't "port" things, because I prefer to write things from scratch.
To learn stuff and having fun with solving problems with the 1.12.1 API on my own."

Ya better just delete your addons then, cause they trash.

**Comment by shagu** [comment]
I'm sorry that I wasted your time by sharing my work with others. I never meant to share it with you.
There are other people in the internet aswell, you know?
