### ISSUE TITLE
ISsue with getting buttons to bind

### ISSUE THREAD

**Issue by cyemekaray** [shagu/pfUI#1127]
I cannot assign the mouse wheel up, mouse wheel down, mouse button 3 and other mouse buttons, using Hoverbind. Also I cannot press buttons on panels using any mouse buttons other than left and righ.

**Comment by shagu** [comment]
The hoverbind feature does only support keys. 
If you need to bind mouse buttons, you would need to use the regular Keybind menu of the game.
Whenever I decide to work on that, it will be tracked in this issue: https://github.com/shagu/pfUI/issues/1016
