### ISSUE TITLE
Enemy castbar is showing on all mobs nameplates

### ISSUE THREAD

**Issue by mutantsanya** [shagu/pfUI#1129]
When one mob is casting something, I see the castbar on all the mobs nameplates around me. 
![image](https://user-images.githubusercontent.com/50405861/223352297-7228acba-6f7b-41e8-8b0b-ad35757cc5c9.png)

**Comment by shagu** [comment]
It can't be done any better in vanilla. The enemy casts are detected via combat log messages which don't show a unique id per mob, but just the name of it. So everyone with that name will get the cast bar attached to it.
