### ISSUE TITLE
No field to reload after closing the menu

### ISSUE THREAD

**Issue by Voidmenull** [shagu/pfUI#113]
No field to reload after closing the menu. If you enter the pfUI menu a second time and close it will work.
This happens only if you change something in a textfield.

**Comment by shagu** [comment]
Yes, the change is only detected after "Escape" was pressed in a textfield... It's like this since a long time, and I always forget about it. Thanks for creating the Issue xD

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/5cb24765755b6094422ec4a4dbaa788db6c8be85
