### ISSUE TITLE
Click Casting Downrankding

### ISSUE THREAD

**Issue by Affenfleisch** [shagu/pfUI#1130]
Hi folks,

i'd like to know if its possible to choose a specific Rank in click casting. Whatever i type in, it always chooses the highest ranked cast. So far i tried the following combinations:
- Chain Heal
- Chain Heal Rank1
- Chain Heal Rank 1
- Chain Heal (Rank 1)
- Chain Heal (Rank1)

Thanks.

**Comment by shagu** [comment]
Hi, it gets directly passed into the CastSpellByName() API call, which wants it in this format: `Chain Heal(Rank 1)`
