### ISSUE TITLE
 The shortcut keys in the warrior pose bar do not display the set shortcut keys correctly

### ISSUE THREAD

**Issue by tjjxlbj** [shagu/pfUI#1136]
战士姿态栏的快捷键不能正确显示设置的快捷键

**Comment by shagu** [comment]
Please use english language here like everyone else. 

It is hard to keep tickets organized if each of them is written in another language. It makes it hard for people to see if their issue already exists as they can't search like this. It's also annoying to me getting email notifications which I can't read. It always enforces me (and others) to open a browser to translate the contents, before I even get an idea what its all about.

**Comment by tjjxlbj** [comment]
The shortcut keys in the warrior pose bar do not display the set shortcut keys correctly
