### ISSUE TITLE
Doesn't show the spell rank on the castbar

### ISSUE THREAD

**Issue by RRamz** [shagu/pfUI#1137]
![1](https://user-images.githubusercontent.com/128314906/226194696-f60cf27e-039f-4756-b490-c8d371221a0f.jpg)
![2](https://user-images.githubusercontent.com/128314906/226194712-eabe10e0-c85c-4aa9-9b9a-7660d5ff9cb4.jpg)

**Comment by shagu** [comment]
Thank you. 

It was a regression introduced in https://github.com/shagu/pfUI/pull/1101
And is now fixed via https://github.com/shagu/pfUI/commit/3cb0c04a0b66c674423d9e293d4180f764f51587
