### ISSUE TITLE
Minimap Quest Markers not showing.

### ISSUE THREAD

**Issue by selexin** [shagu/pfUI#114]
![quest markers](https://cloud.githubusercontent.com/assets/4695486/20507334/29a22270-b0ae-11e6-8fc5-d23228e602b7.png)

Please see attached screenshot. While quest givers are present around me, they are not shown on the minimap. This functionality is there on blizzard default UI minimap. The simple gold circle marker is shown for quest hand-ins, but nothing for available quests. I can find no way to enable this functionality within pfUI.

Thanks for the great work!
JC

**Comment by shagu** [comment]
>  This functionality is there on blizzard default UI minimap.
That's not the truth. It wasn't there in vanilla.

Please use "Questie" if you want these kind of minimap symbols.
