### ISSUE TITLE
"Interface/Addons/pfUI-tbc/libs/libpredict.lua:323:attempt to index field 'mouseover' (a nil value)"

### ISSUE THREAD

**Issue by romkaromi** [shagu/pfUI#1140]
For some reason i get the following error in the chat while using any (simple) macro: "Interface/Addons/pfUI-tbc/libs/libpredict.lua:323:attempt to index field 'mouseover' (a nil value)". Thanks  in advance for any advice how to get rid of it.

**Comment by romkaromi** [comment]
simple macro example:

#showtooltip
/cast Heroic Strike
/startattack

**Comment by Macumbafeh** [comment]
Heyo @shagu i'm happy to see you still update your addon.
An other member reported the same error than @romkaromi 

![image](https://user-images.githubusercontent.com/47739411/227040587-f7d349b7-571d-4b4d-b6e2-7fd8f6a5089f.png)


Thanks.

**Comment by shagu** [comment]
Oh sorry guys. My bad, i didn't tested that change on TBC.
It's now fixed on the latest pfUI.

(https://github.com/shagu/pfUI/commit/337a1b95194a89de8a7148168dd72b2c90d0c644)
