### ISSUE TITLE
A question about target debuffs

### ISSUE THREAD

**Issue by tiancaisnake** [shagu/pfUI#1142]
I like PFUI very much，But there is a question that has been bothering me for a long time.

How to make target debuff bar only show myself skills，I tried whitelisting，Added my game ID Fromdeath,But it doesn't work，

When I set it up like this，debuff bar is not work，Can you tell me how to fix this，thanks

@shagu

**Comment by tiancaisnake** [comment]
![7ac732c9582394526e261038bc5dc53](https://user-images.githubusercontent.com/43053440/227751188-0cb0bc4f-6e1a-4d57-b01d-5d330c8369dd.png)

**Comment by shagu** [comment]
In the whitelist you enter the Debuffs you'd like to display (e.g. `Serpent Sting`).

The "Time Threshold" is used to only display debuffs with less time than the treshhold.
In your example, it would only show the debuff called "Fromdeath" when it has less than 120 seconds left.

The API to check if a debuff was added by you was introduced in wotlk (3.3.5).
All you can do here, is add all debuffs you do to the list, but it would also show up if other people cast one of those debuffs.
