### ISSUE TITLE
Question about nameplates.

### ISSUE THREAD

**Issue by Valeriy-Semenkov** [shagu/pfUI#1144]
Hey! 
These nameplates are the best I've seen for vanilla. I was looking for the possibility of enabling click through, clicking nameplates between each other, I did not find it, is it possible to add this function?

Thanks for amazing work !

**Comment by shagu** [comment]
![image](https://user-images.githubusercontent.com/11586807/231708481-2a0c2eca-7ada-42b6-a9e9-d2c15aca13ec.png)
