### ISSUE TITLE
Possible to get a bag bar?

### ISSUE THREAD

**Issue by nickgreyden** [shagu/pfUI#1145]
I've looked everywhere for the answer so forgive me if I'm mistaken in finding this.

I've never liked the "one bag" approach as I sort my inventory via bags. The only way to disable it is to disable the entire bag module. No problem. This allows me to view all bags individually as I prefer. However, this also removes the only UI bag bar to individually open bags (via the top bar of the "one bag" inventory window) and thus I have to resort to annoyingly trying to remember the correct Fkey shortcut for each bag or Shift+B to open everything (though clicking on bottom right bar opens all bags as well). Is it possible to get the bag bar similar to the default bar when disabling the bag module? Preferably one that can be moved like every other bar. If it is possible in the current setup, could someone please enlighten me? If not, could this feature be added?

**Comment by shagu** [comment]
Blizzard decided to integrate the bag-bar into the actionbar. So if you want that original bagbar, you would need to disable the pfUI actionbar to show the original one again. I have no plans to add additional code for a bagbar while I already have one built into the bag module. Maybe there are addons out there which do it, I don't know.
