### ISSUE TITLE
PFui.api.lua error 943

### ISSUE THREAD

**Issue by Bonicus** [shagu/pfUI#1148]
When I logged into the game after installing the addon (renaming to "pfui") I was unable to open the configuration menu. My chat box changed as if pfui was working but when I type /pfui the command doesn't work. My quest menu and all is also showing that pfui is working. Any idea how to fix this?

**Comment by shagu** [comment]
I cannot help like that. You need to at least tell me the full error message.
Also try to disable all other addons to see if its a conflict between two addons.

**Comment by Bonicus** [comment]
![image](https://user-images.githubusercontent.com/130321270/231314301-2e366f5e-2564-446e-8240-c5d48d20662f.png)

**Comment by shagu** [comment]
Are you using the latest version and did you checked that it's not a conflict to any other of your addons or client mods?
