### ISSUE TITLE
Focus Frame does not hold focus

### ISSUE THREAD

**Issue by nickgreyden** [shagu/pfUI#1149]
Focus Frame does not hold focus when mobs of the same name are chosen.

**How to recreate the issue:**
_You can join a party or raid for easier verification_

1. Target mob
2. Set focus
3. Target another mob with the same name (Example Defias Looter or Firesworn). Level of mob does not matter, only the name.
4. You can see upon targeting the different mob with the same name the focus frame shifting from the set focus to the mob currently targeted. You can assign party/raid marks to the differing mobs to quickly see the issue is persistent.

As you can see this can cause issue with crowd control in dungeons and becomes a larger issue in raids for things like Garr's Firesworn, Majordomo's Flamewaker Healers, or ZG trash like Gurubashi Axe Throwers.

**Comment by shagu** [comment]
It's a vanilla limitation and nothing I could do about it. The access to UnitUIDs and also a builtin @focus unitstring was both added later.
