### ISSUE TITLE
SuperMacro icon override

### ISSUE THREAD

**Issue by chickiepierce** [shagu/pfUI#1150]
![WoWScrnShot_041223_131040](https://user-images.githubusercontent.com/115864239/231533789-bf5f3e13-ee55-49b0-8aef-a7649cece06e.jpg)

I want to create a macro that uses the icon I choose instead of the name of the first ability- here it is Battle Stance. I have disabled this function in SuperMacro (auto-replace action icons) but it still does it. When I disable pfUI it works like I want. I have no other macro or actionbar addons installed, and have disabling and enabling SuperMacro integration, Module macrotweak, Skin macro. They also do have unique names, I saw that was an issue in some previous posts. Pls help!

**Comment by chickiepierce** [comment]
I resolved this with the line
/run if nil then CastSpellByName("spell") end 
at the beginning of macro. Still not sure if SuperMacro auto-replace can be disabled within pfUI but this fixed enough for me lol

**Comment by shagu** [comment]
It has nothing to do with SuperMacro.

pfUI scans through your macro and updates the actionbar slot to the first spell that is found in the macro or the one that is specified via `#showtooltip` in order to display cooldowns and stuff. I will add an option to disable that.
