### ISSUE TITLE
Alt Key Self Cast conflict

### ISSUE THREAD

**Issue by RRamz** [shagu/pfUI#1151]
![WoWScrnShot_041323_015137](https://user-images.githubusercontent.com/128314906/231584633-83e78de4-bebc-4536-b190-893ac4801486.jpg)

**Comment by shagu** [comment]
Whatever that means, I can't see an issue.

The wow-setting one is for keybinds, the other is for clicking on the action bar.
Anyhow, auto-self cast only makes sense to friendly skills like buffs and heals. 
So if you hold <alt> for your serpent sting, it will try to cast it on yourself, which is obviously an invalid target.

**Comment by RRamz** [comment]
So I can't use Alt+ binds for damaging abilities?
