### ISSUE TITLE
Changing border size to 1 hides the borders for some of the modules

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#116]
When changing the border size to 1 for chat, panel, bags, and action bars it then hides the border rather than giving it a 1px border

**Comment by shagu** [comment]
Where?

**Comment by Cruzix** [comment]
Made the borders white so its easier to see: https://youtu.be/afRogqTaZZk

**Comment by shagu** [comment]
Well, theres a limitation in the WowAPI regarding the edgeFiles (border of the backdrop) around a small frame (e.g an 1px sized manabar). You will then see border artifacts on the edges which do not appear as they should. This is why I'm removing the edgeFile when border is set to less then 2. 
TLDR: Nope, sorry.
