### ISSUE TITLE
Addon doesn't work: Lua error

### ISSUE THREAD

**Issue by SCG-Bones** [shagu/pfUI#1163]
![lua](https://github.com/shagu/pfUI/assets/121634013/4b008c23-9ebc-4d75-995e-0ed93d0c717b)

This error appears right on login and I /pfui command doesn't work, neither do I see any difference in the UI. Doesn't seem to work. Currently at TurtleWoW client. Installed both pfUI and pfUI Turtle, and am at an enUS client too.

**Comment by shagu** [comment]
Please scroll the chat up to the first error. The first one is usually the most interesting that produces follow up issues. Also make sure the addon folder is 'pfUI' and not 'pfUi' and make sure that all files are extracted.

**Comment by SCG-Bones** [comment]
I did scroll to the upmost of the chatbox, those are the first ones. First line lua error "attempt to index global L" appears multiple times, not only on login, couldn't get to know what was making it happen. Addon folder is pfUI.

**Comment by SCG-Bones** [comment]
![addons](https://github.com/shagu/pfUI/assets/121634013/6b875826-0e24-417c-bb45-32a974574c67)
![pfui](https://github.com/shagu/pfUI/assets/121634013/1062774c-b15f-40f7-88b9-ed1bf5196802)

There's my pfUI folder, looks okay. Troubleshooting I disabled almost every addon, same error happens. Will try re downloading pfUI now.

**Comment by SCG-Bones** [comment]
Nevermind, read installation back again and I was overwriting pfUI with pfUI-turtle, while pfUI-turtle is a unique folder. Solved.
