### ISSUE TITLE
aux-addon-vanilla

### ISSUE THREAD

**Issue by aadunin** [shagu/pfUI#1164]
The latest version of the pfUI add-on (5.3.1) affects the operation of [aux-addon-vanilla](https://github.com/shirsig/aux-addon-vanilla), it creates errors.

**Comment by aadunin** [comment]
Hey Eric!
As an exception, I came to the conclusion that disabling the pfUI pixelperfect module solves the problem with the formation of errors in aux-addon-vanilla. If you make the necessary changes, I will be grateful to you.
Have a good day!

**Comment by shagu** [comment]
Hi, I don't know which error. I'm using aux since forever together with pfUI and never seen any pfUI related error.

**Comment by shagu** [comment]
It seems to be an issue with AutoDB2:
https://github.com/refaim/AutoDB2/issues/1

**Comment by shagu** [comment]
Fixed via https://github.com/shagu/pfUI/commit/41acda2c029e4e289ae4464f54cdc67097951f6a
