### ISSUE TITLE
add the display of gold icons

### ISSUE THREAD

**Issue by eskimosssr** [shagu/pfUI#1165]
Displaying gold is not very convenient, it would be great if you could turn on the display of gold on the panel with coin icons

**Comment by MasterBruin** [comment]
Thought the same since I installed the addon. The coin icons were much more pleasing!

**Comment by shagu** [comment]
To me its not worth the effort. Right now each panel section only supports a text string that is handed over to a FontString object (which doesn't support icons in vanilla). 

Pull Requests welcome, but it's nothing I'd be willing to spend several hours on.
