### ISSUE TITLE
support zhTW client fonts

### ISSUE THREAD

**Issue by MonoGlory** [shagu/pfUI#1168]
>   -- load font configuration
>   local default, unit, unit_name, combat
>   if pfUI_config.global.force_region == "1" and GetLocale() == "zhCN" and pfUI.expansion == "vanilla" then
>     -- force locale compatible fonts
>     default = "Fonts\\FZXHLJW.TTF"
>     combat = "Fonts\\FZXHLJW.TTF"
>     unit = "Fonts\\FZXHLJW.TTF"
>     unit_name = "Fonts\\FZXHLJW.TTF"
>   elseif pfUI_config.global.force_region == "1" and GetLocale() == "zhCN" and pfUI.expansion == "tbc" then
>     -- force locale compatible fonts
>     default = "Fonts\\ZYHei.ttf"
>     combat = "Fonts\\ZYKai_C.ttf"
>     unit = "Fonts\\ZYKai_T.ttf"
>     unit_name = "Fonts\\ZYHei.ttf"

```
  elseif pfUI_config.global.force_region == "1" and GetLocale() == "zhTW" and pfUI.expansion == "vanilla" then
    -- force locale compatible fonts
    default = "Fonts\\FZXHLJW.ttf"
    combat = "Fonts\\FZXHLJW.ttf"
    unit = "Fonts\\FZXHLJW.ttf"
    unit_name = "Fonts\\FZXHLJW.ttf"
  elseif pfUI_config.global.force_region == "1" and GetLocale() == "zhTW" and pfUI.expansion == "tbc" then
    -- force locale compatible fonts
    default = "Fonts\\bHEI01B.ttf"
    combat = "Fonts\\bHEI01B.ttf"
    unit = "Fonts\\bHEI01B.ttf"
    unit_name = "Fonts\\bHEI01B.ttf"
```

>   elseif pfUI_config.global.force_region == "1" and GetLocale() == "koKR" then
>     -- force locale compatible fonts
>     default = "Fonts\\2002.TTF"
>     combat = "Fonts\\2002.TTF"
>     unit = "Fonts\\2002.TTF"
>     unit_name = "Fonts\\2002.TTF"
>   else
>     -- use default entries
>     default = pfUI.media[pfUI_config.global.font_default]
>     combat = pfUI.media[pfUI_config.global.font_combat]
>     unit = pfUI.media[pfUI_config.global.font_unit]
>     unit_name = pfUI.media[pfUI_config.global.font_unit_name]
>   end

**Comment by shagu** [comment]
Thank you, merged here: https://github.com/shagu/pfUI/commit/6ddd2d1ee96f6982bb881e82ff873b626bcd5bf9
