### ISSUE TITLE
loot under the cursor

### ISSUE THREAD

**Issue by ramtillda** [shagu/pfUI#1169]
I use a translator. 
Do not judge strictly.

Dear shagu, I really appreciate your contribution to the development of addons. Thank you.
Сan I ask?
I really love the original interface of the game and don't want to change anything in it. But the loot near the edge of the screen just kills me! I can't find anything suitable. 
And your Pfui does what it needs to. But it kills the whole interface.
Please make a separate addon for loot under the cursor. 
Please!!! 
and thanks)

**Comment by shagu** [comment]
[ShaguLootCursor.zip](https://github.com/shagu/pfUI/files/11859396/ShaguLootCursor.zip)
