### ISSUE TITLE
[Feature Request] friendly targets frames

### ISSUE THREAD

**Issue by shikulja** [shagu/pfUI#1171]
In some raids need to heal friendly targets (naxx, aq20) and a quest for Benediction and Anathema
https://youtu.be/GJu7KIh8Wws

it's extremely hard to complete this quest without friendly target frames, just like switching (tabbing) friendly targets doesn't work. This makes the task extremely difficult, I hope there is a way to make life easier for healers

(I also did not find useful addons for these purposes)

![image](https://github.com/shagu/pfUI/assets/3386359/fe464509-b749-49bb-975c-ce43af64c854)

**Comment by shagu** [comment]
Just enable friendly nameplates?

**Comment by shikulja** [comment]
@shagu yes, but that doesn't help much. distance is low. And you still have to choose friendly targets manually. it's very slow
<img width="800" alt="image" src="https://github.com/shagu/pfUI/assets/3386359/6ee61a12-fa8e-4bb7-bbca-f8055e40a025">

**Comment by shagu** [comment]
I don't know then. The video you linked, he just uses the friendly nameplates: https://youtu.be/GJu7KIh8Wws?t=215
I'm not exactly sure what type of addon you imagine and how you think it should look like. But as I never needed such a thing and am not playing anymore, I don't see myself writing it for you.
