### ISSUE TITLE
Chat tab disappearing after AFK screen starts

### ISSUE THREAD

**Issue by Azuredrak0** [shagu/pfUI#1174]
I believe there's an issue with AFK screen.

If a new chat window is created, and then dragged out onto the screen, once the AFK screen is started (due to not touching keys), it wipes out that chat window.
Manually typing /afk doesn't cause this issue.

**Comment by shagu** [comment]
Fixed via https://github.com/shagu/pfUI/commit/580eb9a6ac25867422052b9a3125e8d3b21d0b36
