### ISSUE TITLE
Chat keeps halving

### ISSUE THREAD

**Issue by Acidrop27** [shagu/pfUI#1176]
I have this weird issue where the left chat, and only the left chat, keeps halving from the top down. It happens whenever I go into combat and cast spells, for as far as I can tell anyway.

Right clicking the chat header fixes it for a few minutes until it happens again.

Tried messing with all the settings but haven't found a solution so far.

I'm not at my pc atm but will add a picture tomorrow.

Thank you for the great work!

**Comment by shagu** [comment]
Sounds like you have "Simple Chat" enabled.

> **Why is my chat always resetting to only 3 lines of text?**
You need to disable the "Simple Chat" in blizzards interface settings (Advanced Options). Then relog and reset/run the firstrun wizard again.
*https://github.com/shagu/pfUI#faq*

**Comment by Acidrop27** [comment]
*facepalm* thank you so much, I'm an idiot. I'll send you a cup of coffee for the trouble!

**Comment by shagu** [comment]
Thank you! :)
