### ISSUE TITLE
Cant see the timer of my hots

### ISSUE THREAD

**Issue by GabrielF21** [shagu/pfUI#1178]
There's something i need to do to show my heal over time (druid) on unite frame? I can't see the timer.

**Comment by shagu** [comment]
No, I don't have a database of all hots and their duration builtin. So there's nothing in pfUI that could estimate or guess the buff timers. In TBC you would see your own buff timers, but in vanilla everything would need to be guessed.

**Comment by GabrielF21** [comment]
Ok, ty shagu.
