### ISSUE TITLE
Regarding cast frame bug on mobs nameplates

### ISSUE THREAD

**Issue by raulmoretti** [shagu/pfUI#1179]
When a mob I'm attacking starts casting a spell, for some reason every nameplate of other mobs around the one I'm hitting also show to be casting a spell, even though they aren't. I checked with friends of mine and they also experience this.

I don't know if this has been reported before.

**Comment by shagu** [comment]
Yes, multiple times.

Castbars are guessed based on the combat log. The Combat log only says "XYZ begins to cast ABC."
So every enemy with the name "XYZ" will get a "ABC" castbar displayed. There's no way to get this fixed in vanilla,
except to disable the guessed castbars alltogether.
