### ISSUE TITLE
Add Skinning ability to all frames and addons

### ISSUE THREAD

**Issue by crumdidlyumshis** [shagu/pfUI#118]
Is it in the plans to make this like a full-fledged ElvUI with all default frames skinned and ability to add a second addon like pfUI_AddonSkins so we may use the API to skin other addons? 

I assume this is all in the works. But I honestly haven't seen anything relating to this question yet. My apologies if this has been answered.

**Comment by shagu** [comment]
First of all, this project does not have the goal to be "ElvUI". I like some design decissions of ElvUI and TukUI but I won't start to clone these projects. 
Regarding to your question, this might be done sometime but at the time, there are several other things which will get much more attention.

**Comment by crumdidlyumshis** [comment]
Totally understand! Thank you for the feedback!

**Comment by shagu** [comment]
will be handled here: https://github.com/shagu/pfUI/issues/23
