### ISSUE TITLE
Some action bars are hiding after reload

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#119]
Action bar "BarBottomRight" and "BarRight" are hiding after /rl

https://youtu.be/ibRa2Ru2taw

**Comment by shagu** [comment]
o_O

**Comment by shagu** [comment]
Is this always reproducable? Because I can't. Are you using any other addons? 
I had a similar problem last days with the stance and pet bars... I might fix this one in the same way. 
But it feels bad to "fix" some things, on which I can't confirm that the fix is working.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/732c1b1d749f8d4b5d3dddcb06c6ae9362a3a1f7

Is it fixed?

**Comment by Cruzix** [comment]
Yes, looks like its fixed now 👍
