### ISSUE TITLE
unit frames issue, "enable 40yd-range check" not working

### ISSUE THREAD

**Issue by Rinsedd** [shagu/pfUI#1192]
characters in raid frames are greyed out even though 40yd-range check is enabled

**Comment by shagu** [comment]
Hi, the 40y range check requires you to have a 40y range healing spell (non-macro) on one of your actionbars.

For further details, please have a look here:
<https://github.com/shagu/pfUI/blob/master/libs/librange.lua#L18-L40>

**Comment by shikulja** [comment]
It seems to me that I have a similar problem.
actionbars determines the distance is correct, but raidframes, when checking 40y, do not override the distance to the players, it stays the same.
https://github.com/shagu/pfUI/issues/1162

**Comment by Rinsedd** [comment]
> 

thank you
