### ISSUE TITLE
libpredict.lua:300:attempt to perform arithmetic on local `heal' (a nil value)

### ISSUE THREAD

**Issue by taotaoge** [shagu/pfUI#1194]
I got this error accidently when I healed in raid

I'm using lasted version 5.3.2

![image](https://github.com/shagu/pfUI/assets/21192660/ad684b9b-f8a9-46b4-a0be-1fe2dc63b33d)

**Comment by taotaoge** [comment]
it happens frequently

**Comment by shagu** [comment]
Hello, thanks for your report.
I made a quick change which could fix the issue: https://github.com/shagu/pfUI/commit/225a84bc8dd6715c656be70a7d0452e197bf41dc

Can you please try again with the latest version again?

**Comment by taotaoge** [comment]
seems not happened again,thank you!
