### ISSUE TITLE
thirdparty.lua:264: attempt to index global `ShaguDPS_Config'(a nil value)

### ISSUE THREAD

**Issue by taotaoge** [shagu/pfUI#1196]
with latest pfUI and ShaguDPS installed, I will get this error everytime I create a character and login.

![1690932129937](https://github.com/shagu/pfUI/assets/21192660/79f3834e-d78f-411d-a4fe-31e925015ee9)

**Comment by taotaoge** [comment]
can u have a check plz

**Comment by shagu** [comment]
Hi, thanks for the report. Should be fixed by: https://github.com/shagu/pfUI/commit/155da6504ff851257f836e21c279c7ff3e6d7744
