### ISSUE TITLE
Additional chat windows

### ISSUE THREAD

**Issue by Vagarvis** [shagu/pfUI#1197]
I love how the ui has the left and right chat windows set and how they look but I usually play with a 3rd window above my left panel for just guild chat.  I am not able to figure out how to do this in pf ui.  I can create a separate chat window and move it but it has no background and I am unable to adjust the background shade or color at all.  I would also like it to have a border just like the left and right ones that come standard with pfui.  Is this possible?  I love the ui bundle a lot and Id love to be able to set it up the way that works for me.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/43954c487b7a41cedb41627868aa577858430a32
