### ISSUE TITLE
NPC Name - type, occupation of friendly NPCs on nameplate

### ISSUE THREAD

**Issue by Littletonsofire** [shagu/pfUI#1198]
Hi, shagu,

Is there a way to display the occupation of friendly NPCs on their nameplate?For instance,  XXXX Class trainer, XXX vendor,etc. 
Currently I only see friendly NPCs' name on the nameplate, without their  type or occupation <XXXX tainer,vendor>.

thanks

**Comment by Shazgul** [comment]
Wanna know this too.
