### ISSUE TITLE
Env: french translation for grey items sold

### ISSUE THREAD

**Issue by gsurelle** [shagu/pfUI#1199]
The french translation `Votre objets gris ont été vendue et vous avez gagné` is not really good. `Vos objets gris ont été vendus et vous avez gagné` would be better.

The line of code is https://github.com/shagu/pfUI/blob/ce7222c32a668621fee781ba4a43c7922e27def3/env/translations_frFR.lua#L786C57-L786C108

Thanks for your work.

**Comment by shagu** [comment]
Thank you :)
Fixed via: https://github.com/shagu/pfUI/commit/bea76976b0903d56010a2d8c94364b6589486113
