### ISSUE TITLE
Option to make nameplates click through with right click only

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#120]
Option to make nameplates click through with **right click** only. 

Theres nothing more annoying when you're trying to turn your camera/character direction but nothing is happening because you accidentally right clicked a random nameplate on your screen. 

Nameplates should still be interactable with left click though since thats what most people including myself is using to target with.

**Comment by shagu** [comment]
There is `EnableMouse(true)` which consumes all of your mouse clicks, even if the button is not processed by registering it. If `RegisterForClicks("LeftButtonUp")` is set, it will only react for the left mousebutton.
But the right button is still "enabled", It just does not call any function then.

A sharing of different mouse buttons on overlaying clickable frames, where the first processes left clicks and the second processes right clicks, seems to be impossible (at least in classic).
Looks like you have to decide if you want Mouse or not Mouse.

**Comment by Cruzix** [comment]
Np, if it can't be done.. then it can't be done, sadly. Thanks for the explanation :)

**Comment by shagu** [comment]
Whoop Whoop

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/f72757ed433c0cc35f1a7bd90b31a7bc446a4bef

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/7ec8b11ca96375b161a73c4d0fd2fb6a8625b057
