### ISSUE TITLE
Can't activate German language in TBC version of pfUI.

### ISSUE THREAD

**Issue by JustVityok** [shagu/pfUI#1202]
Hey, I am playing on deDE 2.4.3 client, and as far as I understood, pfUI also has German translation, but, for some reason, it isn't an option in "Language" selector. Am I wrong and there is no actual German translation to pfUI or is it just a bug?

**Comment by shagu** [comment]
Hi, There are no german translations for pfUI. German is the only locale nobody contributed for.

**Comment by JustVityok** [comment]
Oh. That's sad. Thank you for the answer!
