### ISSUE TITLE
A button/feature to prevent unswapping form (while in combat)

### ISSUE THREAD

**Issue by welpenhund** [shagu/pfUI#1205]
Greetings, i got a question related to PFui. 
I love your addon but i have one problem specially on T-WoW. (as a druid player)
Is there any way that you could implement a check that not swaps you out of forms (bear form, cat form etc..) while in combat + clicking an NPC?
We always have people in raids that have their repair bots out and if you mistakenly click one of those repair bots it swaps you out of form. (and you instantly die by bosses like Patchwerk - i know clicks by mistake are my mistake but they happen...)
A button that says "Don't remove form clicking an npc while in combat" 
Casting a spell still should swap you out of form in combat, it is just this clicking on an npc whjle in combat that destroys sometimes being the tanky bear you wish to be when fatfingering over an npc. 😅

**Comment by shagu** [comment]
Is your pfUI up-to-date?
There is already that:
https://github.com/shagu/pfUI/blob/master/modules/autoshift.lua#L95-L98

Introduced 5 months ago via:
https://github.com/shagu/pfUI/commit/cfbea5eea88353e939b7955cd345101c65a0586d

**Comment by welpenhund** [comment]
> Is your pfUI up-to-date? There is already that: https://github.com/shagu/pfUI/blob/master/modules/autoshift.lua#L95-L98
> 
> Introduced 5 months ago via: [cfbea5e](https://github.com/shagu/pfUI/commit/cfbea5eea88353e939b7955cd345101c65a0586d)

Thank you a lot, now that you said it... i still had an old version.  *presses close*
