### ISSUE TITLE
Any way to fix text overflow?

### ISSUE THREAD

**Issue by VinPropane** [shagu/pfUI#1206]
Is there any way to have fonts not overlapping or be cut off? I've tried nearly every font.

![Screenshot_20231010_231044](https://github.com/shagu/pfUI/assets/25494428/8c83668f-5cdd-4c80-bc53-df77fa45a4bb)

**Comment by VinPropane** [comment]
Could you point me to the setting that controls this size? `Standard Text Font Size` doesn't control it and I don't see anything else in the settings.

**Comment by shagu** [comment]
Interesting, you're right. It indeed doesn't control it. I sadly have no clue then.
Do you use any client modifications, or other addon that change text sizes or fonts?
