### ISSUE TITLE
Enable UI-Scale: Off being ignored and resets every log off

### ISSUE THREAD

**Issue by Steco76** [shagu/pfUI#1207]
Hi, 
all of a sudden the setting enable ui-scale changes to a size i choosed before every time i relog. i have to change it to a different size and turn it off again to make it work. Did a fresh install, cleared the cache, reseted everything but it keeps returning. any idea how i can fix it?

![SCR-20231014-hqfn](https://github.com/shagu/pfUI/assets/139595906/0ba7678e-603d-4927-8ffb-13565fe3db89)
![SCR-20231014-hofm](https://github.com/shagu/pfUI/assets/139595906/6530e2a3-ea94-4241-8636-ca34a8a03586)

**Comment by shagu** [comment]
Setting the UI-Scale to "Off" in pfUI just means that pfUI does not touch any UI-Scale related settings.
Other Addons and the normal UI-Scale option in the Video-Settings can still change it.
