### ISSUE TITLE
Chat resets settings

### ISSUE THREAD

**Issue by Apostheum** [shagu/pfUI#1208]
As an example: If you go into the filters of your "General" tab and uncheck "Hardcore" because you don't want to see those messages. After a relog (or even reloadui) it's back.

**Comment by shagu** [comment]
It's an issue of their custom client and how they added HC messages to it. I don't plan to workaround the turtle-wow custom problems. You gotta wait till they fix it. No matter if pfUI or not, all have to struggle with it right now.

Lexie made an addon that seems to workaround it in the meantime:
https://github.com/Lexiebean/TurtleHCFilter
