### ISSUE TITLE
Can't add system messages to the Loot and Spam Window.

### ISSUE THREAD

**Issue by Apostheum** [shagu/pfUI#1209]
As the title implies. There doesn't seem to be a way to see system messages in this tab. I want all my HC related stuff to be relegated to this tab. Including any hcmessages alert. But there doesn't seem to be a way to make them show up here.

**Comment by shagu** [comment]
Sorry, but the vanilla client doesn't natively allow to change anything relating to the system messages.
And pfUI uses the default chat element, not an own implementation of the whole thing. If it's just regarding the HC-Spam, check out Lexies addon that workarounds the current turtle wow client issue with it, to limit it to a single chatframe: https://github.com/Lexiebean/TurtleHCFilter

**Comment by Apostheum** [comment]
np np, saw your other msg as well. Always sucks with client limitations ,Good work on the addon , appreciated
