### ISSUE TITLE
Few things that could help

### ISSUE THREAD

**Issue by eNtreDefias** [shagu/pfUI#121]
List over some things that would be nice:

1. When u enlarge the minimap it does not show all the cords in certen scales.
2. Able to put portrait to the side of the frame option.
3. Changing the hight and length not just the size of Target of target bar option.
4. Changing colour of casting bars option.
5. Moving combo points, and changing size and colour option.
6. Changing colour of healthbars from class colours option.
7. Hide unused actionbars option.
8. Change actionbars to vertical and horizontal option.
9. When targeting a new target making the target bar come up instant insted of a loading effect option.
10. Hide macro and keybinding text option.
11. Change size of font in health bars, and being able to move option.

Sorry if i made this post wrong etc, first time using this site. And also if i made suggestions of things that is possible to do etc. Thank you so much for all ur work with all these addons, ur a fucking god!!!:D

**Comment by eNtreDefias** [comment]
1. Happends with alot of texts not just the cords when u scale up. Not a big issue, but some scales cant be used couse it only shows half the text etc.

**Comment by shagu** [comment]
Well, thanks for your input, but as you already noticed, it's better to put an issue for each request.
I'm closing this one, because many tasks already have an dedicated issue and others are already fixed.
