### ISSUE TITLE
Mob debuffs shows on *all* mob nameplates

### ISSUE THREAD

**Issue by ancan** [shagu/pfUI#1211]
When I place a debuff on a mob, the other mobs on the screen also get the same debuff on their nameplates. Makes it hard to see which one you've got DOT's going on and which not.

**Comment by shagu** [comment]
It only happens if the mobs have the same name and clears itself on mouse over. It guesses debuffs on the mobs you dont have in target, because otherwise you would only see the target debuffs.

You can disable it via:
Nameplates -> Debuffs -> Estimate Debuffs [ ]
