### ISSUE TITLE
Can't inspect talents 

### ISSUE THREAD

**Issue by Kylecat15** [shagu/pfUI#1215]
I am playing Turtle WoW and with pfUI I cannot see anyones talents, the textures are not loading properly 

I get 1 of 2 errors:

interface\AddOns\Blizzard_InspectUI\Blizzard_InspectUI.lua:49: Usage: SetPortraitTexture(texture, "unit")

or

..eXML\Turtle_InspectTalentsUI\InspectTalentsFrame.lua:2505: attempt to index field `?' (a nil value

This is an example of what I see, the images are usually in color though

![image_2023-11-02_010616753](https://github.com/shagu/pfUI/assets/28875069/1452ce78-3842-48a7-a52d-27529907fba9)

**Comment by shagu** [comment]
Nothing to do with pfUI, as it sometimes happens without pfUI too
