### ISSUE TITLE
Addon "Flyout" and "Recents" can not work with PFUI

### ISSUE THREAD

**Issue by wangmeng2410** [shagu/pfUI#1216]
ENV: Turtle wow(EU) with latest PFUI

The following two addons can not work:
https://github.com/luskanek/Flyout
https://github.com/luskanek/Recents

**Comment by shagu** [comment]
According to the Author, `Flyout` should work. You better create an issue over there.
Regarding `Recents`, it's so small that an integration of it would most likely be more code than building such a feature directly it into pfUI. If someone would want such a thing, a PR is welcome, but I'm not going to do it.
