### ISSUE TITLE
Addon "DPSMate" and "SW Stats" cannot work well with PFUI

### ISSUE THREAD

**Issue by wangmeng2410** [shagu/pfUI#1217]
ENV: Turtle wow(EU) with latest PFUI

DPSMate cannot save configuration after relog - fonts reset, DPSmate window hide again
SW Ststs cannot work well too

**Comment by shagu** [comment]
Disable the "Skin" of them in the pfUI thirdparty settings. 
Because that option overwrites their font and colors to match the pfUI configuration.
