### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by Titanicshark80** [shagu/pfUI#1220]
so basically i have issues with my combat text numbers not scrolling combat text i cant change the text no matter how hard i look it seems to be overwritten or something with PF Fonts this is due to the UI setup i have if you know a fix let me know

**Comment by shagu** [comment]
If you change the "Scrolling Combat Text Font" in the pfUI settings, you have to restart the game to have it take effect.
With a simple reload, the game does not re-initialize its combat fonts.
