### ISSUE TITLE
pfUI breaks mouseover casting for other addons.

### ISSUE THREAD

**Issue by Kissanity** [shagu/pfUI#1221]
/pfcast isn't working with NotGrid, and /ngcast (what NotGrid provides) isn't working with NotGrid either while using pfUI, but does work when not using pfUI. It's as though I feel forced to ONLY use the unitframes your mod provides and not my own tastes, or preferences. It's upsetting to say the least.

**Comment by shagu** [comment]
I never used NotGrid, but pfUI allows to disable each component on its own. It is possible to disable the pfUI unitframes and also to disable the mousover module.
