### ISSUE TITLE
No player or NPC names or jobs

### ISSUE THREAD

**Issue by NightMortal** [shagu/pfUI#1222]
Hello. I've disabled the nameplates module, although, for some reason, it still doesn't display player or NPC names or their professions and titles. Instead, it only shows completely blank. This UI would be perfect if it would allow me to use vanilla names and titles, as the current nameplate implementation only shows names and levels, without guilds, and more importantly, the vendor and profession names of the NPCs. I'm unsure if this is an option, but I've dug around and can't find it anywhere, in-game or online.

**Comment by shagu** [comment]
Probably selected an incompatible Font, or used a profile of someone who changed to font to something you haven't installed. Select an existing one in pfUI -> Settings -> General -> 3D World Unit Font (then restart)
