### ISSUE TITLE
pfUI not loading on fresh install

### ISSUE THREAD

**Issue by 8EightySixed6** [shagu/pfUI#1234]
Since patch 1.17 of Turtle WoW, pfUI doesn't load on a fresh install of Turtle. 

1. Addon is enabled (Only addon installed)
2. Fresh copy of Turtle WoW installed
3. No other addons installed

If I exit the game and re-open Turtle WoW, pfUI will load fine from what I can tell. 

This only happens on a fresh install of Turtle. 

With the addon enabled and not loading you can still type the /pfui command in chat. I get the following error

![Screenshot 2023-11-18 092651](https://github.com/shagu/pfUI/assets/115322320/653d12f1-3905-4131-82b0-d1f84b5b5589)

**Comment by shagu** [comment]
You done something wrong at the installation and it is missing some files.
Just do the installation again and make sure to follow the instructions 1:1
