### ISSUE TITLE
Title in the tooltip doesn't trim the character name from titles that are written after that name

### ISSUE THREAD

**Issue by Szalor** [shagu/pfUI#1244]
The tooltip's title management currently only trims the character name from the title if the title is positioned before the character name.
Example:
pvpname: Sergeant Buster
name: Buster
Resulting pvptitle: Sergeant

However, when it comes to other titles (custom non pvp titles in Turtle WoW for instance) that come after the character name, we get the following behaviour:
pvpname: Buster Still Alive
name: Buster
Resulting pvptitle: Buster Still Alive

Here's the fix that seems to be working for me so far: 

in tooltip.lua:
line 208:
local pvptitle = gsub(pvpname or name,name, "", 1)
pvptitle = gsub(pvptitle,"^%s*(.-)%s*$", "%1") --trimming spaces

line 228:
if pvptitle ~= name and pvptitle ~= "" then

**Comment by shagu** [comment]
Thank you, fixed in the latest version. https://github.com/shagu/pfUI/commit/e843ccea2c16f69fab04433dde461bb98496af37
