### ISSUE TITLE
crown icon bugged

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#125]
There are two bugs with the crown icon for group leaders. 1) it is partially covered by the health bar when it should (i assume) be on top. 2) it appears even when not in a group (or rather doesn't disappear)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/68c2b769ba16042008fdc96a0d88cea4886d6954

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/48375a402a8faea72be135353137e7baae8d4786

**Comment by shirsig** [comment]
The first issue was fixed for the player frame but still happens in the group frames.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/3e08060c697f6b923f38c06b99e8708a15a5cc1d
