### ISSUE TITLE
Lacks paladin taunt timers

### ISSUE THREAD

**Issue by lyssebabz** [shagu/pfUI#1252]
warrior taunt shows as 3 seconds
![warar taunt](https://github.com/shagu/pfUI/assets/20995435/9582b082-bb90-4e39-94b3-ec70315ee6d2)
paladin taunt does not
![palattaunt](https://github.com/shagu/pfUI/assets/20995435/e02734ef-ee22-4886-9678-c0dc8298ee31)
Is it possible to add 3 second timer to paladin taunt? This will make boss fights like Sartura easier

**Comment by lyssebabz** [comment]
> What is it called? `Hand of Reckoning`?

Yes :-D

**Comment by shagu** [comment]
Done https://github.com/shagu/pfUI/commit/715776e477d47c1cdb951ee072f0a36c1e38528b
