### ISSUE TITLE
Buffs/Debuffs not showing on raid frames

### ISSUE THREAD

**Issue by AirChandler** [shagu/pfUI#126]
as shown here http://imgur.com/a/3Zmft, a buff is on the player Lymax as seen on the player frame but looking at Lymax on the raid frame no buffs are shown.

**Comment by AirChandler** [comment]
I haven't been able to test with party frames but it may be a similar issue as well as I've yet to see any buffs shown on them.

**Comment by shagu** [comment]
The "Show Buffs" is dedicated for people who need to buff others. Therefore, every class will only see their buffs. It's not a good idea to show 16 buffs (or even up to 32 buffs) inside of a 40px frame.

Regarding the group buffs: Right now there aren't any, but it is already on the roadmap and will follow soon.

Cheers
