### ISSUE TITLE
Is there a way for the unitframes to hide outside of combat? Or to add macro conditions to the displaying action bars?

### ISSUE THREAD

**Issue by alienbogart** [shagu/pfUI#1264]
I'm playing Turtle and also TBC and those are some of the things that I really miss. Any recommended way to achieve that?

Thank you so much for this great addon!

**Comment by shagu** [comment]
One would have to patch the unitframes of pfUI, because as of now there's no option for it yet.
I don't have as much time as before to implement every single feature request on my own, so if anyone is eager to contribute, a pull request would be appreciated. I by myself won't do it in near future.
