### ISSUE TITLE
[Suggestion] Current amount counter

### ISSUE THREAD

**Issue by Muhomono** [shagu/pfUI#1267]
I'd like for there to be a counter in tooltips stating how many of a certain item I have in my inventory at that moment, if possible. Would be very nice quality of life. Example being how many copper ores I have in my inventory.

![inventorycount](https://github.com/shagu/pfUI/assets/161989946/cb9f68de-641f-4408-9f52-621a91ccd7dc)

**Comment by shagu** [comment]
Hi, There are already plenty of addons that do the job. One for example would be [ShaguInventory](https://github.com/shagu/ShaguInventory).
