### ISSUE TITLE
Chat bubbles still show for superignore / ignored players

### ISSUE THREAD

**Issue by Slimthegrim** [shagu/pfUI#1268]
Problem: When you ignore players with superignore, pfui continues to display their chat bubbles. 

Expected / Requested: Chat bubbles in pfui should not display for ignored characters.

**Comment by shagu** [comment]
Thanks for your report, but pfUI doesn't add any logic to the chat bubbles, it just skins them as they appear from the game. So that's more like an issue of the game itself, or the SuperIgnore addon. Either way, I'm not going to fix bugs of other addons from within the pfUI code.
