### ISSUE TITLE
Tooltip and quest indicator

### ISSUE THREAD

**Issue by saysmaker** [shagu/pfUI#127]
The tooltip hides quest progress after viewing NPC for 2nd time (tooltip will not show quests in position chat and bottom; but when on position cursor, it shows)

**Comment by shagu** [comment]
Which quest indicator?

**Comment by saysmaker** [comment]
Say I am on a quest to kill 12 raptors. My tooltip would show 0/12 raptor slain when I move my cursor to the raptor. However, when I move my cursor away and back on the mob. that 0/12 raptor slain text is gone. Let me know if this makes sense

**Comment by shagu** [comment]
There is nothing like a quest progress tracker in tooltips in vanilla wow. If this is an issue in combination with another addon that gives you that tooltip information, please tell me the name of the addon. Otherwise I'll be not able to reproduce your issue.
