### ISSUE TITLE
Functions with items not working when clearing the Itemcache.wdb (in WDB folder)

### ISSUE THREAD

**Issue by unS0uL** [shagu/pfUI#1270]
When starting the game with an empty WDB folder, PfUi does not display the correct number of items on the panel, and also does not highlight items in the bag that cannot be equipped. After use /reloadui, all functions are is on.
In other words, the PfUi reads the game's cache before the game creates the cache, and the item functions do not work.

How to reproduce: 
rmdir wow_folder\wdb
start wow.exe
login to server

Found it bug on Turtle WoW.
I clear WDB all the time when starting the game, like other player, because clearing the cache are recommendation from GM TWOW

**Comment by shagu** [comment]
I would prefer to not query all item informations on boot and delaying the loading screen even more.
I'll check if there's another way to only delay some of the features to a certain point (I don't think there's a WDB-Initialized event tho.)

**Comment by shagu** [comment]
For some reason, a tooltip that gets a :SetOwner() early, won't ever recover itself after the WDB caches are loaded.
Only running :SetOwner() on the same frame again will actually reload it and makes it possible to read tooltips again.

Also fixed the caching logic in both `unusable.lua` and `actionbar.lua` (reagent counter) to no longer accept or trust empty tooltip results.

Fixed via:
- https://github.com/shagu/pfUI/commit/3f217809800d341b2a20cd1d1ae293d8462e0e00
- https://github.com/shagu/pfUI/commit/b3d4eb4288caab8e171b335db3f0f132b834931e
- https://github.com/shagu/pfUI/commit/119d5fe2a67cf93442e912f215b8d9b84a43fdbc
