### ISSUE TITLE
minor improvements: UI

### ISSUE THREAD

**Issue by shikulja** [shagu/pfUI#1272]
1.  Show the number of free slots in bags on the right bottom panel
![image](https://github.com/shagu/pfUI/assets/3386359/e031fc31-7d94-4437-903a-45530c8c2513)

2. Show a tooltip when hovering over the lower left "Armor" panel
Which will show detailed information about equipment breakdowns and the cost of repairs
![image](https://github.com/shagu/pfUI/assets/3386359/236ed2f8-4441-48fc-a110-25413ceeb931)

like - DuraTecFu
![image](https://github.com/shagu/pfUI/assets/3386359/15c5f6c9-fbf9-4e7d-9687-ba4f3be51313)

**Comment by shagu** [comment]
It already does that:

Bag Space:
![image](https://github.com/shagu/pfUI/assets/11586807/d183ce35-8cfc-4c05-8d3d-7cf748ea4a50)

Armor/Repair Cost:
![image](https://github.com/shagu/pfUI/assets/11586807/30c41de9-7760-4ad4-a98e-96cd062dd3f6)

**Comment by shikulja** [comment]
hmm.. I couldn’t find it, maybe it’s not added to the theme I’m using
