### ISSUE TITLE
unusable: performance regression in unusable item detection

### ISSUE THREAD

**Issue by maxcodk** [shagu/pfUI#1273]
hello! I have updated pfui and now i see fps drops during boss fights 
Also first load of character has become longer
Also any macros or addon that searches for items in my bag and equips them(itemrack. roid macro equip macro. my own small addon) freezes the game for 1-3 secs and drops fps to 20 after it
it works so bad only on 1 character with 144 bag slots
what i did for tests:
disabled only pfui and loaded game with all other addons, worked fine
deleted WTF folder, result remained the same

**Comment by maxcodk** [comment]
update - it doesn`t depened on number of your slots in bags

**Comment by shagu** [comment]
Outch.. Could you please disable the reagent counter in the actionbar settings and the 'unusable'-module in the components section, each after the other, to see which of the both is causing it?

**Comment by maxcodk** [comment]
![unusable](https://github.com/shagu/pfUI/assets/111142939/1b6ee110-9d7d-4ed7-811a-c739e85a43d0)

**Comment by maxcodk** [comment]
yes disabling unusable solved the problem

**Comment by shagu** [comment]
Thanks, I will look into when I get home

**Comment by grynold** [comment]
Disabling that module made my game run as before again. Started having problem yesterday, when changing outfit with outfitter my game would freeze for around 5 seconds. Now its back to normal with a sub second freeze.

**Comment by shagu** [comment]
Fixed via: https://github.com/shagu/pfUI/commit/c72cf1fe81403324fcc940aec97a9b071f0a4faa
