### ISSUE TITLE
Editing of Whitelist/Blacklists

### ISSUE THREAD

**Issue by DGreatfox** [shagu/pfUI#1274]
I have looked through all menu options and readme files looking for a place to edit the whitelist and blacklist of the lists I create for target debuffs. Is there a specific way to edit these lists to minimize to my debuffs?

**Comment by shagu** [comment]
There's no option to filter the regular debuffs on the target frame. The only option that exists is to use the debuff indicators (that appear inside the frame) which allow to specify whitelists
