### ISSUE TITLE
Druid Manabar

### ISSUE THREAD

**Issue by welpenhund** [shagu/pfUI#1275]
Is there a way to alwyays show the mana/numbers in forms without having to hover with the mouse over it?

This is without hovering over it
![grafik](https://github.com/shagu/pfUI/assets/30401521/82f070b4-9ac9-4246-961d-2361ef339f37)

This is with hovering the mouse over it.
![grafik](https://github.com/shagu/pfUI/assets/30401521/145db0c1-b597-400b-8679-78277ff32ccc)

I know the addon itself is not from shagu but he offers the support for it and i use pfui. I would appreciate any info that could help me to always see this numbers/mana without having to hover over it with my mouse.
Maybe it is a line in the script that i would only have to change in order to always see it?

**Comment by shagu** [comment]
pfUI does not touch any functionality there, it just moves it and changes borders to match the pfUI style.

But in his code he uses these two lines to set up the text:
https://github.com/gashole/DruidManaBar/blob/master/DruidManaBar.lua#L49-L50

So I assume it's the default game logic that takes care about the showing/hiding of the text in his addon.
Have you tried in the Wow Interface settings to enable the Status Bar Text?
![image](https://github.com/shagu/pfUI/assets/11586807/f04c4d08-bc8f-4e06-900b-cabbeaefe5f8)

If that doesn't help, you have better chances to directly ask the author of the actual addon you're using:
https://github.com/gashole/DruidManaBar
