### ISSUE TITLE
Reagent count not showing on Ritual of Refreshment spell on action bars

### ISSUE THREAD

**Issue by EyeOfTheBeast** [shagu/pfUI#1276]
Shows as 0 despite having 20 arcane powder in my inventory:
![image](https://github.com/shagu/pfUI/assets/142637959/2c02ef04-e0de-4dc8-8bf2-9b0dc4bb645f)

This is on Turtle WoW.

**Comment by shagu** [comment]
Is that the only spell with wrong reagent counts? Does it fix itself after a while?

**Comment by EyeOfTheBeast** [comment]
Ritual of Refreshment is the only spell with the wrong reagents count (my Arcane Brilliance spell displays it the reagents count normally). The Ritual of Refreshment reagents display bug does not fix itself ever.

![image](https://github.com/shagu/pfUI/assets/142637959/789ce477-6f0c-40bb-83d0-d7930282b30c)

The bug may be related to the fact that the Ritual of Refreshment Spell requires 2 Arcane Powder instead of just 1?

**Comment by shagu** [comment]
I sadly don't have a mage to test it - which makes it quite difficult to help here.
It would be helpful to see how such a tooltip of the custom spell looks like. Maybe there's a parsing error?

You could help by changing this line:
https://github.com/shagu/pfUI/blob/master/modules/actionbar.lua#L1595

to 

```lua
_G.reagent_slots = { }
```

Then reload, hover your mouse over both spells and typing for each:
`/run print(reagent_slots[GetMouseFocus():GetID()])`

It should then print the required material.

**Comment by shagu** [comment]
Should be fixed via this commit: https://github.com/shagu/pfUI/commit/2be1cacdfc5451e57ac4746dbf295a0defc32101

**Comment by EyeOfTheBeast** [comment]
> Should be fixed via this commit: [2be1cac](https://github.com/shagu/pfUI/commit/2be1cacdfc5451e57ac4746dbf295a0defc32101)

I updated my pfUI to the latest commit build and it is indeed fixed now. Thanks, this issue can be closed now.

![image](https://github.com/shagu/pfUI/assets/142637959/da642059-4759-4f34-837a-b03b0afa5637)

![image](https://github.com/shagu/pfUI/assets/142637959/247cad1a-f7d1-4ad0-9d50-96e98100a9ba)
