### ISSUE TITLE
Casting bar  have problem

### ISSUE THREAD

**Issue by wyb12080770** [shagu/pfUI#1279]
In Turtle World of Warcraft, only pfUI is loaded
Use WOW. exe into the game, casting bar will not be a problem

If you use SuperWoWlauncher. exe into the game
The casting bar of an NPC is not displayed after being attacked

**Comment by shagu** [comment]
I myself use SuperWow and castbars work perfect.

**Comment by wyb12080770** [comment]
I didn't have any problems with the other models, I only encountered Troll and Murloc

**Comment by shagu** [comment]
I have no idea how and if super wow works on zhCN client. Also I'm the wrong person to ask here.
Don't think it has any relation to the character model you use. Is Defias Mage the only NPC you have troubles with?
