### ISSUE TITLE
Suggestion: Add an option to enable raid/party frames when disabling player/target frame

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#128]
I'm currently using ModUI together with pfUI and I've disabled pfUI's unitframes as I currently find them to be lacking customization to make them look how I want them to be.  
I like the party/raid frames from pfUI but I have no way of enabling them if I prefer using other addons player/target unitframes

**Comment by Oliveryo** [comment]
I would like this

**Comment by shagu** [comment]
I've planned to fix https://github.com/shagu/pfUI/issues/59 during the christmas time. But I'm still not sure if I'll get it done. Nevertheless, I won't do what you described in the ticket, because It's just a work which will be done twice as soon as it gets replaced by the other ticket.
