### ISSUE TITLE
任务导航适配成RXPGuides或Zygor吗？

### ISSUE THREAD

**Issue by cryueh** [shagu/pfUI#1280]
大佬可以针对乌龟服整合下这种商业级的任务插件吗？付费也ok啊，因为实在是太太太太香了，用过就回不去了。
RXPGuides和Zygor都是重量级的任务导航插件，能让新手不走冤枉路，按最优路线升级，期间还包括开鸟点设炉石。还会绕过精英和地下城任务，属于是对新手非常友好的保姆级任务导航插件。
特别是RXPGuides可以支持官服的hc模式，开启后任务路线会根据hc模式进行优化。
网上也有人放出了RXPGuides的汉化版：https://www.bilibili.com/video/BV1Kp4y1A7rG
另外Zygor也是老牌的商业级插件，这是毛子放的破解版：https://rutracker.org/forum/viewtopic.php?t=4858504
期待大佬能把这块重视起来，因为这个插件对新手真的非常友好，而且现在乌龟服的pf生态已经很成熟了，如果能适配下就完美了

**Comment by shagu** [comment]
Nope
