### ISSUE TITLE
Make action bar abilities glow red if out of range

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#129]
Stock UI already do this by default, however it only makes the keybindings glow red rather than the entire ability icon.
Theres a few action bar addons that I know has this feature such as Bongos and CT. 

I also found this http://www.arenajunkies.com/topic/210170-addonscript-to-make-spell-icons-red-when-out-of-range/ (3rd comment), im not sure if that works but I guess it would help you out if it does, and also this https://github.com/ericraio/vanilla-wow-addons/tree/master/r/RangeColor which im not sure works but will test it out later

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/d6746bbdf64534a47f51abfe3c1c990f8445030b
https://github.com/shagu/pfUI/commit/53499a1149b6c95e74d4649888baa780fe0817d7
