### ISSUE TITLE
Error with guild bank

### ISSUE THREAD

**Issue by Flecked42** [shagu/pfUI#1299]
Sometimes you get an error when using guild bank. More so with the log.

![WoWScrnShot_060424_144950](https://github.com/shagu/pfUI/assets/90434262/0b1d9a53-cc89-4c27-bc9a-f53986e9502c)

This mod supposedly fixes it, but doesn't work with pfUI. 

https://github.com/MarcelineVQ/SuperWoWGBankFix

**Comment by shagu** [comment]
This bug is unrelated to pfUI. The same thing happens while pfUI is disabled.
