### ISSUE TITLE
tooltip: configurable offset

### ISSUE THREAD

**Issue by Hallonkaka** [shagu/pfUI#130]
When choosing tooltip position to cursor, have offset and anchor options. Could look at TinyTip addon for more options to add.

**Comment by shirsig** [comment]
Note that the API functions don't support a custom offset for ANCHOR_CURSOR. To implement that one has to use an onupdate handler to constantly reposition the tooltip (e.g., using GetCursorPosition as a reference).

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/65360d1bd69e277eaf24b7df51acbac36dd13ca1
