### ISSUE TITLE
Deleting Characters from Money List

### ISSUE THREAD

**Issue by Shinsiru** [shagu/pfUI#1301]
Hey there, 

I've searched myself through the variables, but I am unable to find the stored data location for money panel overview which char has how much money. 

I want to delete deleted characters, so they don't show up anymore.

With kind regards
Shin

**Comment by shagu** [comment]
Hey,

Such data can be reset by clearing the "Cache":
![image](https://github.com/shagu/pfUI/assets/11586807/c464425f-554b-435e-a01b-87dfd882582d)

If you want to manually delete it, the data you're looking for is within the pfUI_cache variable that is saved per Account. It's saved under `WTF/Account/<ACCOUNTNAME>/SavedVariables/pfUI.lua`.

You could also clear that particular table ingame by typing: `/run pfUI_cache["gold"] = {}` followed by a reload. Or delete individual ones (e.g for character "shagu" on realm "Nordanaar") via: `/run pfUI_cache["gold"]["Nordanaar"]["Shagu"] = nil` followed by a reload (Keep an eye on the case-sensitivity here).

Hope that helps :)
Shagu
