### ISSUE TITLE
Doesn't work in vanilla wow? 

### ISSUE THREAD

**Issue by ChatTemplar** [shagu/pfUI#1307]
Installed it like stated in the small Guide. Already installed it some time ago on turtle WoW, but it's just not functioning in vanilla. No Error nothing. It shows in the addon menu but is not openable using /pfUI. When typing the command it won't enter the command, it will stay in the prompt window for the chat.

**Comment by tslnox** [comment]
Are you sure you installed it correctly? Try deleting the folder WoW\Interface\Addons\pfUI and redownload the addon again, unzip and be sure to rename the folder to pfUI without -master in the name (which you probably did, if it appears in addon menu). If everything fails, I would try to completely redownload the clean client and start over, you might have something broken in the client itself.
