### ISSUE TITLE
Wrong target castbar size

### ISSUE THREAD

**Issue by GrindPlayer** [shagu/pfUI#131]
Hello!
I hope that my English will be understandable
Two little issues (see screenshots) : 

**1/ Size Castbar between Player's Frame and Target's Frame have different height/font.**
I looked into castbar.lua and config.lua and value are the same for the two Frames
![1_castebar_player_target_size_bug](https://cloud.githubusercontent.com/assets/24245537/20705198/531ad4e8-b622-11e6-9a23-d82812a15005.jpg)

**2/ At some long range (Approximately after 30y), the Target's Castbar doesn't appear.**
![2_target_castbar_not_showing_longrange](https://cloud.githubusercontent.com/assets/24245537/20705379/fcd4a586-b622-11e6-9f9a-e870f47fa830.jpg)

Thanks for this nice UI!

**Comment by shagu** [comment]
Did you've used different scalings for "player" and "target" frame?
Please check if the problem has been fixed with this commit: https://github.com/shagu/pfUI/commit/5d8727fd47a8e6aecb4f1b718eaae9cdf77bad05

![castbar](http://i.imgur.com/FmJAXAH.jpg)

**Comment by GrindPlayer** [comment]
The scaling was the same. BTW, your fix works well!
Thanks!
