### ISSUE TITLE
Bug with MasterLooter feature in pfui

### ISSUE THREAD

**Issue by welpenhund** [shagu/pfUI#1313]
We experienced a rare case in our Raid yesterday
That bug might have been caused by either client lag, server lag and/or a failure in the addon. I would like to bring this up cause it might happen again in future and might be fixable?

Master loot set
Epic Item Dropped on Trash, with 2 trash drops ahead of it.

Master Looter tried to raid roll out  FIRST trash item - didnt register

Master Looter tried to raid roll out  FIRST trash item again - didnt register

Master Looter tried to raid roll out  FIRST trash item one more time -   it random rolled out BOTH trash drops and the epic on it now after the third time instead of only rolling out the selected trash items.

![grafik](https://github.com/user-attachments/assets/f85a6cd8-94e4-4872-a66f-e4c630537b33)

**Comment by shagu** [comment]
Interesting. Sounds more like a lag to me. I don't get the "didn't register". You describe he clicked it 3 times, and it rolled 3 items, so it **did** register, no? You have just been lagging.

Anyhow, That feature has been a contribution of someone else and it's there for already so long, I didn't even remember merging it anymore. If you really hit the bug for the first time in the past 7 years, and someone wants to fix it
please send a pull request. As I personally never used it and also don't plan to, I would rather remove it from pfUI than fixing it. Let's leave the ticket open for the next 30 days in case someone wants to work on it.

**Comment by welpenhund** [comment]
> Interesting. Sounds more like a lag to me. I don't get the "didn't register". You describe he clicked it 3 times, and it rolled 3 items, so it **did** register, no? You have just been lagging.
> 
> Anyhow, That feature has been a contribution of someone else and it's there for already so long, I didn't even remember merging it anymore. If you really hit the bug for the first time in the past 7 years, and someone wants to fix it please send a pull request. As I personally never used it and also don't plan to, I would rather remove it from pfUI than fixing it. Let's leave the ticket open for the next 30 days in case someone wants to work on it.

No it seems to be happening if someone is out of range after this is clicked.
The more people are not in range for it the higher the chance seems to be to occur.

**Comment by shagu** [comment]
> i just thought i should report it since it is a neat feature

Ofc, Thanks for reporting :)
I'm just wondering why nobody did in the past 7 years.

Could you please provide a clear step by step instruction how to reproduce it? In case somebody wants to work on it.

**Comment by welpenhund** [comment]
> > i just thought i should report it since it is a neat feature
> 
> Ofc, Thanks for reporting :) I'm just wondering why nobody did in the past 7 years.
> 
> Could you please provide a clear step by step instruction how to reproduce it? In case somebody wants to work on it.

Will ask the person who was doing the loot thing for exact infos and provide them here when i know.

**Comment by welpenhund** [comment]
> > i just thought i should report it since it is a neat feature
> 
> Ofc, Thanks for reporting :) I'm just wondering why nobody did in the past 7 years.
> 
> Could you please provide a clear step by step instruction how to reproduce it? In case somebody wants to work on it.

Quote by the one who did Master Loot:
"""pressed "Give loot to: Random" in PFui menu on gray item, nothing happened. (repeat process x3) 5 seconds later all these rolls catch up and every item on the mob is rolled out."""
