### ISSUE TITLE
Plans for including a Threat Meter

### ISSUE THREAD

**Issue by lburak** [shagu/pfUI#132]
Are there any plans to add support for KLHThreatMeter or any other third party threat meter? Or are you going to create your own threat meter?

**Comment by Z1mmey** [comment]
I'd like to see it implemented in a way like the support for DPSmate. That one DOES have a threat-tab, but it does not seem to work for me.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/issues/23

**Comment by lburak** [comment]
Sorry about that, I searched only for topics :(

Thanks for pointing it out!
