### ISSUE TITLE
Missing stat dropdown

### ISSUE THREAD

**Issue by dgrewe** [shagu/pfUI#1320]
Hello,

I am not sure what it causing the stat dropdown to not appear.

![statdropdown](https://github.com/user-attachments/assets/9ef46cd4-c94d-40c5-b268-ad9ad4348d34)

**Comment by shagu** [comment]
Pretty sure that doesn't exist in vanilla. You'll need an addon like BetterCharacterStats for it.

**Comment by dgrewe** [comment]
ah gotcha. I was going off the pfui-turtle pic from the wiki. Thank you.
