### ISSUE TITLE
Bags search Simplified Chinese 

### ISSUE THREAD

**Issue by kokpk** [shagu/pfUI#1324]
Bags search engine input in Simplified Chinese has no effect

**Comment by shagu** [comment]
Can you please try again with the latest version?
I have made a change here: https://github.com/shagu/pfUI/commit/a9d2494fee1ce94b10099b766117260f5aa5e6d5

**Comment by kokpk** [comment]
latest version is ok  thx

**Comment by shagu** [comment]
That was fast, thanks! :)
