### ISSUE TITLE
Cannot get pfUI Elite Overlay to work

### ISSUE THREAD

**Issue by Antenacht** [shagu/pfUI#1333]
Apologies, I don't want to make a bunch of random post, but I've been struggling with getting the pfUI Elite Overlay to work.

After finally getting pfUI situated and installed, I have ben trying to add the Elite Overlay. I follow the instructions by removing "master" from the name and placing it in my addons section, but nothing pops up under "Addons" in the game, or when playing.

I've searched google, reddit, and this site, but have yet to find a solution.

If someone out there is able to lend me a hand it would be much appreciated.

**Comment by shagu** [comment]
Hello,
Make sure to have 2 folders under `Interface/AddOns`: `pfUI` and `pfUI-eliteoverlay`.
If you play on TBC, the folders should be called `pfUI-tbc` and `pfUI-eliteoverlay-tbc` instead.

Also make sure to not have any of both nested in another folder. 
In both folders, you should see directly the `.lua` and `.toc` files.

**Comment by Antenacht** [comment]
It appears the folder was within another folder with the same name. By removing it, the overlay now works correctly. Thank you so much.
________________________________
