### ISSUE TITLE
Nameplates overlap the minimap

### ISSUE THREAD

**Issue by Sanal** [shagu/pfUI#1334]
Hi there! I'm not sure if this is the core issue since it seems pretty straightforward, but the nameplates appear to be out of place. I couldn't find any settings in the game to configure the layers for the nameplates or the minimap.

I made a temporary adjustment by changing the minimap's `SetFrameStrata` from `BACKGROUND` to `MEDIUM`, but perhaps the author has a better solution.

![WoWScrnShot_102324_0747362](https://github.com/user-attachments/assets/c3697267-36b4-439a-8956-3ea246dce018)

**Comment by shagu** [comment]
Thanks! I don't remember why I forced the minimap strata to such a low value back then.
I removed the custom strata now, and everything seems to be fine: https://github.com/shagu/pfUI/commit/a3f811a0551bb868070ce73be9909bc33da7d240
