### ISSUE TITLE
TurtleWow 1.17.2

### ISSUE THREAD

**Issue by nonameform** [shagu/pfUI#1339]
I have noticed some bugs on TurtleWow 1.17.2 patch.

Since tradeskill windows were changed, they look broken with pfUI skin now.

![WoWScrnShot_110224_141026](https://github.com/user-attachments/assets/a7738825-73c9-4d59-8c4d-6ed2aa3f7ef0)

Also Shadowmeld mechanic was changed. The CD only starts after Shadowmeld is applied for the second time (weird mechanic).

![WoWScrnShot_110224_140741](https://github.com/user-attachments/assets/1fd8c4ef-123c-4557-9f3b-a6ea1c0958d5)

You may see that CD on my bar is already counting down, yet the spell in the book is not counting down.

Now when you move, you lose Shadowmeld, but it's reapplied again immediately for 2 seconds. When that second application happens, the CD actually starts.

![WoWScrnShot_110224_140754](https://github.com/user-attachments/assets/83885238-d4c8-428d-ac44-9b7a7c5322fc)

You may see on the second screenshot that the timers in the spell book and on my bars are not synchronized (56 and 55 seconds).

**Comment by shagu** [comment]
The elements in the proffession window have already been aligned to not be in the way (https://github.com/shagu/pfUI/commit/3958fb42a5a360501920d38173ec28d48fa2e991 https://github.com/shagu/pfUI/commit/69f28b05154554a3a88debcee7d9b4a51fceb8d9). All they miss is "skin", I might look into this later.

Regarding the Shadowmeld, i don't know what I can do about it. pfUI does only displays whatever the client tells about cooldowns. That seems to be something in the game that needs to be adjusted here.

**Comment by nonameform** [comment]
I already reported some inconsistency with how Shadowmeld works at TWow bug tracker (new way/old way). Will see if they change the mechanic.

**Comment by shagu** [comment]
![image](https://github.com/user-attachments/assets/89cb7b3f-223c-4e2c-ad1f-5878d1bf580c)
https://github.com/shagu/pfUI/commit/b54d172175068d630b7fc882fd22a3e96b6f830e
