### ISSUE TITLE
Changing Fonts?

### ISSUE THREAD

**Issue by eNtreDefias** [shagu/pfUI#134]
Was wondering how/if i can add new fonts. Was able to switch the fonts for everything in wow, but when i used the pfUI it owerwrties the fonts i changed and use the the fonts in the pfUI. Is it anyway of adding new fonts to the pfUI addon?

**Comment by shagu** [comment]
You could replace one of the existing fonts or copy your font to pfUI/fonts and add it to https://github.com/shagu/pfUI/blob/master/modules/gui.lua#L603

**Comment by eNtreDefias** [comment]
Thanks :D
