### ISSUE TITLE
Ammo Counter

### ISSUE THREAD

**Issue by nonameform** [shagu/pfUI#1340]
I have noticed long time ago that ammo counter is not correct once you fill all slots in quiver/ammo pouch. I'm not sure if the same is true for thrown.

On the screenshot below I have 807 arrows.

![WoWScrnShot_102324_162128](https://github.com/user-attachments/assets/54aa0f7a-82b2-4a98-ada1-6283f3ad9abb)

I buy another stack and my counter goes to 1,000.

![WoWScrnShot_102324_162133](https://github.com/user-attachments/assets/3384058b-1609-43ac-b205-b81e01ed3398)

If I reload UI or shoot an arrow, the counter updates to the proper quantity of arrows/ammo.

![WoWScrnShot_102324_162153](https://github.com/user-attachments/assets/57acd3e6-5e17-4f9d-9dab-0972c3d36d74)

**Comment by shagu** [comment]
Thanks for your report. There's probably a bag event missing in the refresh logic.
I'm leveling a hunter right now. So I will enable the ammo counter and have a look the next time I play.

**Comment by shagu** [comment]
It's now fixed via https://github.com/shagu/pfUI/commit/073bf5ec42e2efdffb95fbbea45055bed54e52ad
