### ISSUE TITLE
Wrong info in Quest Tracker

### ISSUE THREAD

**Issue by nonameform** [shagu/pfUI#1342]
Might be a Turtle WoW DB issue.

Quest tracker shows that I have killed [Neevan Gubblewire](https://database.turtle-wow.org/?npc=61482) 7 times. Actually I haven't killed him even once at this point. But I have [7 Spare Parts](https://database.turtle-wow.org/?item=61394) in my bags for quest [Malfunction Mayhem](https://database.turtle-wow.org/?quest=40862),

![WoWScrnShot_103024_101104](https://github.com/user-attachments/assets/45641a8c-bdf7-46ea-8506-8ec3947442db)

Then I went outside and killed the NPC in question.

![WoWScrnShot_103024_101607](https://github.com/user-attachments/assets/02216682-5b19-4f43-b24f-9ae55e6d7890)

Now quest tracker shows the right info.

**Comment by shagu** [comment]
Weird.. never seen something like that before. Could indeed be a server hickup.
Also that's not about pfUI at all. Closing it here. 

If the issue persists over a longer period of time or you have any prove showing it's not a server issue,
then please create a new one on the pfQuest bugtracker :)
