### ISSUE TITLE
Error on Turtle Wow LFT skin

### ISSUE THREAD

**Issue by gvdn78** [shagu/pfUI#1347]
Hello i get this error on Turtle wow wince they updated to 1.17.2
Pfui and Pfui Turtle wow skins are only addons loaded

ERROR: Interface\AddOns\pfUI-turtle\skins\turtle\lft.lua:63: attempt to index global `LFTMain' (a nil value)

**Comment by shagu** [comment]
Hello,
`pfUI-turtle` is not my addon, you should ask the author of it here:
https://github.com/doorknob6/pfUI-turtle
