### ISSUE TITLE
Healthbar embedded portraits not showing

### ISSUE THREAD

**Issue by RizeYuzuki** [shagu/pfUI#1348]
As of November 4th 2024, 22h30 EST, after the new changes done to the addon ~12 hours ago, both 2D and 3D portraits are no longer showing when set to "Healthbar embedded", but they will show if the Unit Frame Layout (Unit Frames -> General) is set to "TukUI" instead of "Default".

Every unit frames are affected by this (Player, target, raid, group).
I have also tested this on a fresh install of the game and pfUI without any other addons or modification.

This was working yesterday as intended.
Also tested on a completely different PC with a fresh install of the client and addon.

Server: Turtle WoW
Client version: 1.17.2 (7200)
OS: Windows 10

**Comment by RizeYuzuki** [comment]
After testing it more, I have found that if "Enable Range Fading" is toggled on and that you are far enough from your target to trigger the fading effect, the portrait will show up.

But, if you get close again, it will disappear.

**Comment by shagu** [comment]
Thank you for your detailed report.
I removed the now obsolete Frame Strata changes to the portrait.
Everything seems to work as it should again.

Fixed via: https://github.com/shagu/pfUI/commit/43d76e8d226d588e94554f164f0852046dbe25f6
