### ISSUE TITLE
Turtle-WoW Debuff timers.

### ISSUE THREAD

**Issue by welpenhund** [shagu/pfUI#1350]
Could you add to the turtle-wow module maybe some of the new/longer debuff timers?
Insect swarm and Moonfire are 18 seconds now but the timers of pfui still show the "original" timers from vanilla.
Or can i modify the file somewhere myself to adjust those timers?
Thanks in advance for an answer.

**Comment by shagu** [comment]
Thanks for your report. It's now included via: https://github.com/shagu/pfUI/commit/727bf44acb1d11bd3d9179abe6b0453993df4f92
