### ISSUE TITLE
unitframes: add buff indicator timers for vanilla based clients

### ISSUE THREAD

**Issue by Capracou** [shagu/pfUI#1352]
Hi, I enabled Buff Indicator to track my enrage and Holy Strength, icons show great but timers don't
![image](https://github.com/user-attachments/assets/96d703c1-5482-45ed-a646-9b05d8779044)

**Comment by shagu** [comment]
The `UnitBuff()` function that is used for the Buff indicators doesn't have a time-left in vanilla. Currently those only work on the TBC. Sadly in vanilla `GetPlayerBuffTimeLeft(id)` is the only way to obtain player buffs and they don't match the id's of `UnitBuff(id)`. So there's a bit of work to get it done. I can't tell yet when I will do that.
