### ISSUE TITLE
Trueshot castbar disappear again

### ISSUE THREAD

**Issue by foolishyx** [shagu/pfUI#1355]
> why delete Trueshot castbar, trueshot(now is called steady shot) castbar don't show again
> 
> ![Image](https://github.com/user-attachments/assets/e34bdb6f-8493-4c53-a1e4-82f3039b8331)
> 
> ![Image](https://github.com/user-attachments/assets/5dfa587a-fc5c-4179-ab8e-a3d754b6f763)
> 
> ![Image](https://github.com/user-attachments/assets/6086db26-cac0-4f19-9a32-539591aa56d6)
> 
> 
> 
> 
> 
>  

 _Originally posted by @foolishyx in [8832e42](https://github.com/shagu/pfUI/commit/8832e42fefdc1f50266a0f43753f0863d7db2b59#commitcomment-148854317)_

**Comment by shagu** [comment]
The castbar for Steady Shot has been turned into a regular cast that provides a castbar.
There are now workarounds required anymore. I don't play on the Chinese realm, but on my realm the castbar shows perfectly fine with pfUI enabled and also without any addon. It's just a normal cast now.
