### ISSUE TITLE
Action bar issue

### ISSUE THREAD

**Issue by Flecked42** [shagu/pfUI#1358]
When selecting 9 buttons for an action bar, there's no 1 x 9 option.

![WoWScrnShot_110824_112907](https://github.com/user-attachments/assets/e2af5d38-92a4-4d3d-b8cd-b7e2e7b53198)

**Comment by shagu** [comment]
Thanks for your report. It's now fixed via https://github.com/shagu/pfUI/commit/bd49a202fe2ea44b8d7360da4b655d77683ad3a3
