### ISSUE TITLE
Profession Window leads to crash  - turtle wow

### ISSUE THREAD

**Issue by KlausUllrich** [shagu/pfUI#1367]
When talking to a class trainer and selecting the dialog option to learn new skills the game crashes with the following popup:
"Your game interface files are corrupt. Please remove your Interface\FrameXML folder."

Not sure what do here in Turtle WOW. I removed the pfUI.lua files in the WTF\Account\SavedVariables folder, but no effect. Sorry, I am a beginner. 

In this forum https://www.reddit.com/r/turtlewow/comments/1ghs477/pfui_saved_interface_for_1172/
it appears you have already been notified, but I cannot see a matching entry here.

**Comment by shagu** [comment]
pfUI has nothing to do with those crashes. 
The only thing that was an issue is a weird looking profession UI.
But that one was already fixed a day before the patch came out.
