### ISSUE TITLE
 TurtleWow Sea. The time difference between the server and pfUI

### ISSUE THREAD

**Issue by Eachiin** [shagu/pfUI#1370]
Hello, I am using pfUI 5.4.11 on the TurtleWow Sea. Recently I started fishing and found that the server time displayed by pfUI is wrong. For example, when I use (.server info) to query the time, I find that the server is 21:10 at night, but the panel shows 09:10 in the morning.
![image](https://github.com/user-attachments/assets/733a1c6d-c67a-4d60-865e-57193004fc54)
![image](https://github.com/user-attachments/assets/6547fef2-b65f-46f7-ac0b-1cd1a7849101)

**Comment by shagu** [comment]
That's an intended change that Turtle WoW made. Both continents are set 12 hours apart, so that always one has daylight when the other is at night. That's not a pfUI issue, the addon only tells what the Game API responds. I'm not responsible for custom changes that Turtle WoW decided to do.
