### ISSUE TITLE
Tmog addon icon not going into minimap button frame

### ISSUE THREAD

**Issue by jendryk** [shagu/pfUI#1372]
I have a problem with Tmog addon minimap button, it doesn't get into minimap button frame.
I reached out to the author and he couldn't help me, maybe you will be able to find solution?

**Comment by shagu** [comment]
You can hover your mouse over the icon and type: `/abp add` to add it to the minimap button frame.
Type only `/abp` to see all available options. More commands like that can be found in the [README.md](https://github.com/shagu/pfUI?tab=readme-ov-file#commands)
