### ISSUE TITLE
Last Letters of several UI elements either cutoff or newline

### ISSUE THREAD

**Issue by iReisen** [shagu/pfUI#1376]
![image](https://github.com/user-attachments/assets/8a7c741e-ad95-4a02-88fb-f72aa8678ccc)

especially noticeable in trainer windows (any, not just beast training), but also the logout button has this issue. (spells "Logou")
issue persists with all addons besides pfui disabled.

Issue is only present on Large and Huge layouts, medium and below work just fine. font doesnt seem to matter.

TurtleWoW client, 1080p resolution
Issue was already present before the latest update.

![image](https://github.com/user-attachments/assets/1f4595a0-2d22-449d-becc-3670b28425e3)

**Comment by shagu** [comment]
I can't do anything about it. It's how Windows handles DPI settings and font rendering. There's also VanillaFixes that can do things to how the DPI/Font rendering is done. I'm not a windows user and can't help with those kind of issues. I suggest to disable the pfUI UI-Scale presets if none of them works good for you, and just play with the slider in the Video Settings of the game yourself until you find a value that your DPI/Resolution/GraphicDriver likes.
