### ISSUE TITLE
nameplates: configurable sizes

### ISSUE THREAD

**Issue by HuMa69** [shagu/pfUI#138]
Hey sagu, Gz for your nice UI, i have a suggestion, can you add options for nameplates like healtbar/castbar/debuffs size in nameplates? and its possible to add a timer for the debuffs? thank you

**Comment by shagu** [comment]
Debuff timers won't happen https://github.com/shagu/pfUI/issues/27

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/a7e3ae6e1b91e1e65731d618339830c3cce3809f
