### ISSUE TITLE
Quick tip: You can enrich the issue-labels with unicode signs for better visibility of issues ;)

### ISSUE THREAD

**Issue by dsidirop** [shagu/pfUI#1381]
Since I can't give you a christmas present thought to share this neat silly little trick with you - hope you enjoy it.

![image](https://github.com/user-attachments/assets/40f2e147-19ed-4bf7-a372-cecfa0126c67)

Be safe!

**Comment by shagu** [comment]
Thank you :) But I'll pass and leave it as text only.
