### ISSUE TITLE
How do you switch your language?

### ISSUE THREAD

**Issue by Darter-hub** [shagu/pfUI#1385]
I cannot figure out how to switch my language so I can speak to only members on my faction? There is no chat bubble icon, or any icon in the chat box to change the language. Please help

**Comment by shagu** [comment]
You can right click on the top-right icon of the chat frame to get the dropdown menu.

**Comment by Darter-hub** [comment]
Oh thank you! I would have never tried that. And how do you switch the language back to normal so everyone can understand you?

**Comment by Darter-hub** [comment]
Also I don't know if you realized this, but there are more emotes than what is available in Pfui, like /cackle, /gasp, /plead, /puzzled. Here is a list of them https://web.archive.org/web/20050818080926/http://www.worldofwarcraft.com/info/basics/emotes.html. It would be great if the whole list was accessible.

**Comment by shagu** [comment]
pfUI doesn't do anything special here and doesn't intend to do. The emote list you get with pfUI is the same as you get without it. If you need more emotes in such a list, i think this is more suited for one of the RP-Addons out there.

Closing this one as the question seems to be solved :)
