### ISSUE TITLE
New feature hide action bar bug

### ISSUE THREAD

**Issue by eNtreDefias** [shagu/pfUI#139]
Just tested the new feature for hiding action bars and then being able to show it when u mouse over it. It bugged out after some mins, and now its invisible constantly but im still able to hover over the spells on the bar and use them but they are invisible. Idk if the bug happend couse i was adjusting some other settings. Tryed to reload and take the option off, still the same. 

I rly like the idea of it tho, would be nice if you could do the same with microbars. So u dont need keybindings for spellbook and character etc, but u dont have to show it constanly on the screen.

**Comment by Fundaris** [comment]
Hey I'm trying to reproduce your bug but not seeing anything wrong can u share more details?
For example your config? Located here:
`<WOW Folder>\WTF\Account\<your accountname>\SavedVariables\pfUI.lua`

**Comment by eNtreDefias** [comment]
Deleted and re downloaded pfui so dont think the config will work? It seems to be working now tho, although i havent been testing it much. Idk if there was some other settings that might trigger the bug, or maybe other addons. All i can remmber 100% i did was: "Autohide vertical actionbar" then set the "Secounds to wait until hide bars to 0" so it was instant, insted of delay.

**Comment by eNtreDefias** [comment]
Was able to recreate the bug kinda i made a video to show it: https://www.youtube.com/watch?v=-3jM1IV1Mg4&feature=youtu.be
Although last time it was invisble all the time.

**Comment by shagu** [comment]
Did you changed UIScale, resized the window or moved the frames before recording?
Please try to reproduce with the latest version.

https://github.com/shagu/pfUI/commit/77bbf8cb6b00ff0acb7c3f571910db5ae88aecfd
https://github.com/shagu/pfUI/commit/2cd7f2301e32c874ec062c40fd65db14153a9251

**Comment by eNtreDefias** [comment]
Downloaded the updated version, did not use UIscale or resized and did not use any addons btu pfui, seems to be working now. I tryed to do some stuff to see if i could reproduce the bug, but it seems good now. Only thing wrong now (witch is not that inportent) is: https://www.youtube.com/watch?v=JOJmz2T32-Q&feature=youtu.be sometimes when u use a cd the timer for the cd will show trough when the bar is hidden.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/e55d1ca3b2570a9fcfb78b329e69279d71c6a91e
