### ISSUE TITLE
Changeable rows for Actionbars

### ISSUE THREAD

**Issue by HuMa69** [shagu/pfUI#141]
Hello, is there any way to change the stance bar from the main bar to another bar? i have the main bar hide because i like to put the UI like this https://gyazo.com/d83e4585986aa8b4c1cf985e52a3061a thank you, if is not possible how can i change the main far rows to make it like the the left and right bars?

**Comment by shagu** [comment]
I renamed it to avoid confusion, as the term "stance bar" is used for druid-stances, paladin auras, rogue stealth and so on. What you're talking about seems to be the multiactionbar.

I don't know right now if and when I'm going to make the actionbar rows configurable. I'll tag this with enhancement, but don't expect a fix soon. Sorry :/

**Comment by HuMa69** [comment]
Thank you, then its possible to change the main action bar style to looks like the right and left bars??

**Comment by shagu** [comment]
I want to send a big "THANK YOU" to @Road-block !
