### ISSUE TITLE
Option to change layer of player/target bar

### ISSUE THREAD

**Issue by eNtreDefias** [shagu/pfUI#142]
Would be nice with a option to change the layering of stuff especially player and target bars. Example: Im using Power Auras to show a Icon with a countdown of the cc duration when i use kidneyshot or blind etc, and i rly want to be able to have the icon over the target bar when it happends. The issue is that the icon from Power Auras get hidden behinde pfui targetbar since the layer is higher up on pfui. And i belive this could be usefull not just for Power Auras but stuff in the pfui or other addons aswell.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/b3576ea01daf4a26f5b5b0aedf8dad915ca096c8
