### ISSUE TITLE
Suggestion: Range indicator on actionbar spells when out of range

### ISSUE THREAD

**Issue by Larsy93** [shagu/pfUI#143]
Range indicator on actionbar spells when out of range would be great, perhaps fade out the spell icon to grey and make the binding number a red colour or just simply fade to grey.

Thanks for a great addon btw

**Comment by Fundaris** [comment]
> binding number a red colour
Already happening for me

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/issues/129
