### ISSUE TITLE
Portrait Option

### ISSUE THREAD

**Issue by eNtreDefias** [shagu/pfUI#146]
Any chance to be able to have a option to put the portrait in a square on the left and right side of player and target healthbar frames? (Also would be nice for Target of target) Kinda like the default health and portrait frames. I just feel like it would be more visible to detect the player ur againt etc.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/e3d414093afab59c8865bbd8803af582ec617f80
