### ISSUE TITLE
Addon creates non-clickable "nil" areas

### ISSUE THREAD

**Issue by jfastnacht** [shagu/pfUI#150]
There are some non-clickable spots on the screen, caused by the addon.

Resolution is 1920x1080, happening in an area at around 1150px to 1200px in width. (Screenshot) The red bar marks the area, the red boxes points on my screen which are not clickable (sizes of the boxes are probably not 100% correct).

1. Deactivated any other addon except pfUI and tried it. Areas weren't clickable.
2. Deactivated pfUI (only Blizzard UI and no other addons activated) and it was gone.

GetMouseFocus():GetName() returns a "nil".

![wow 2016-12-08 17-18-16-666-marked](https://cloud.githubusercontent.com/assets/6183607/21018683/ff4cffa0-bd6d-11e6-99e0-aca07a0b63de.jpg)

Video: [https://webmshare.com/play/M0yEd](https://webmshare.com/play/M0yEd)

Can anyone else reproduce this?

**Comment by Cruzix** [comment]
I couldnt reproduce this

**Comment by jfastnacht** [comment]
Whether it's over the action bars seems to depend on UI-Scale. I've tried it with another installation. Same result, but due to different UI-Scale it wasn't overlapping the action bar icons.

**Comment by shagu** [comment]
I can't reproduce this.

**Comment by jfastnacht** [comment]
Position definitely depends on UI scale. I've downloaded a completely new enGB client and installed ONLY pfUI and was able to find these spots on nearly the same area in width, but further upwards.

![image](https://cloud.githubusercontent.com/assets/6183607/21084428/b3a41ab4-c003-11e6-82d9-febfe9d55f72.png)

One point was at 1175x350 from top-left.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/40befe8ab0566836e5b6eabb748cd54065f74b7f
