### ISSUE TITLE
Bug with Range indicator Color Icon

### ISSUE THREAD

**Issue by eNtreDefias** [shagu/pfUI#154]
When u enable "Use colored icon as range indicator" it will disable the grey ish shown on spell icons when u dont have enough mana to cast a spell. https://www.youtube.com/watch?v=EtD5FssxxA4&feature=youtu.be

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/6116b3ae73218d05ed1b01e716b0d07f6a02e216
