### ISSUE TITLE
Enemy nameplate debuffs

### ISSUE THREAD

**Issue by eNtreDefias** [shagu/pfUI#155]
Was wondering if it was possible to add a option to see debuffs on all the nameplates that got hit by a spell, not just the target you have sellected. Would be rly nice for aoe spells to keep track of who has the debuffs on them when fighting multiple targets. https://www.youtube.com/watch?v=r_DLONvHHYM&feature=youtu.be

**Comment by shagu** [comment]
Nope. There is no reliable way in Classic WoW to determine the "real"-mob. 
All I have would be the name of the enemy which means that as soon as enemies have the same name, the debuff display will be terribly wrong.

**Comment by eNtreDefias** [comment]
I see, i know one addon that can do it but it seems kinda buggy and not that reliable for how long the debuff last, the debuffs sometimes gets removed before the duration is out, and debuffs sometimes show up on your targets when other players are using debuffs on other mobs . Its called EnemyFrames if u wanna check it out. Anyways thanks for answering and all ur good work man:)
