### ISSUE TITLE
unitframes: add rare/elite dragon graphics

### ISSUE THREAD

**Issue by eNtreDefias** [shagu/pfUI#157]
Have a suggestion for making elites easyer to spot,  if its possible to add a option like this: http://imgur.com/a/77K3N making the border color gold ish for elites.

**Comment by shagu** [comment]
Thanks for the suggestion. 
But to be honest, I don't like the way it looks.

**Comment by crumdidlyumshis** [comment]
Why not something along the lines of this?

**Comment by eNtreDefias** [comment]
Does not need to be exatly like that, its just nice with something visual for elites rather then text or + imo.

**Comment by crumdidlyumshis** [comment]
@eNtreDefias I totally agree. Anything better than the usual + or "Elite" is more than welcome.

**Comment by shagu** [comment]
Feel free to make more suggestions. :)

In the meantime, you might be interested in: 
https://github.com/Road-block/DragonOverlay/releases/tag/1.93-alpha

**Comment by NibelheimGG** [comment]
would be nice the golde eagle in the frame, or any big icon to identify elites fast

**Comment by crumdidlyumshis** [comment]
@shagu Oh sweet thank you! I had no idea this was out there :)

**Comment by eNtreDefias** [comment]
https://github.com/Road-block/DragonOverlay/releases/tag/1.93-alpha Is pretty nice:), altough im not the bigest fan of the mist of pandaria dragons. Does not fit that well with vanilla imo.

**Comment by eNtreDefias** [comment]
Was thinking of trying to draw a dragon/dragon head or something on my wacom tablet, with the elite gold color and a silver one for the target frame. I have never drawn something for ingame ui before, so im not sure how the resolution would be etc? I was thinking of geting photoshop, as i currently only have a more simple drawing program. It might take some time to finish whatever you want tho, if ur evn intrested that is? Atleast im willing to give it a go:P

**Comment by eNtreDefias** [comment]
Just a visual for most of my suggestions in an epic paint job:P http://imgur.com/a/5hIK6

**Comment by shagu** [comment]
An idea: http://i.imgur.com/F4rem4s.jpg ?
Of course with different colors...

**Comment by eNtreDefias** [comment]
http://i.imgur.com/F4rem4s.jpg pretty nice:O Can draw it in the color style of http://imgur.com/a/TPMer if u want?

**Comment by eNtreDefias** [comment]
I can draw it in 1920x 1080 then scale it down to 512x 128 or whatever works best?

**Comment by eNtreDefias** [comment]
Just wanted to know what file u want it as and size etc? Im drawing in 2560x1280 5x scale of 512x256 since thats the scales etc u need to be able to put in wow as textures for ui right? And as exported as TGA file?
Im not done yet but the scale of it is done i think, so maybe you can test it to see how it fits and maybe give some suggestions for what to improve on (keep in mind its not done:P). Im specaly worried about how the colors will look in game, altough its currently only silver version. Here it is currently: http://imgur.com/jg0qato Il export a file as u want, if u want to try to test it in game.

**Comment by shagu** [comment]
I'd be fine with everything above min. 512x512. You don't have to care about the file format, just use any lossless compression like PNG. I'll scale and convert it on my own. Regarding the color, the best would be to make it colorless, because I'm able to color it ingame via SetVertexColor according to the type of the elite.

**Comment by eNtreDefias** [comment]
Ok thanks for answering:) Sorry again for making a new issue to ask:/ Its just that im not a artist or anything and ive spent most of the day for weeks now trying to make this, as i was alo working on another version that diddent work out, and i just wanted to know if i was doing it right and that u liked it etc. Since i diddent want to waste more time if i did it wrong or anything. And i dont know how this site works and if u got the message in this thread.

**Comment by eNtreDefias** [comment]
Also its in 32 bit not 8 bit, is that a problem?

**Comment by shagu** [comment]
No worries, I will convert everything to make it fit ;)

**Comment by Thorsten42** [comment]
Hi, first thanks for this super ui! Would it also be possible to implement something to see if the target is a rare mob? Killed one yesterday and didn't see anything indicating that its rare, not even in the tooltip.
Thanks!

**Comment by eNtreDefias** [comment]
Just a small update since last, sorry its taking such a long time. I have been takeing some breaks, lost motivasion couse i felt like it was shit, and i diddent know what to do to fix it etc:P. Im learning on the go and now i feel like im starting to get it in the right derection. Here it is so far: http://imgur.com/a/5G434 Let me know if there is anything u feel i can change or anything?

**Comment by eNtreDefias** [comment]
Hey, sorry this has taken such a long time :/ Ive been struggling alot to finish it, and doing stuff over and over again to find that other stuff diddent work etc. So i lost motivation since i could not figure out how to fix the problems that i felt needed fixing. Also i converted it to 8 bit to be able to save it as PNG. For some reason i now have trouble with blending colors, i figured it was this convertion or update to the program that made this happend idk. Anyway i rly cant do much more with this unless i make a new one from scratch and learn from my mistakes etc. I might try in the future, but for now this is what i got: http://imgur.com/a/7Aat0 I hope that u find it ok enough tho since its gonna be scaled down pretty much, and ur gonna fix the colors etc. Its 100% fine if u dont wanna use it tho.

**Comment by eNtreDefias** [comment]
Tryed to make something new, havent worked on it for very long so its not rly that good yet https://imgur.com/a/qX030 The head is copyed much closer to the original on this one. Anyways tell me if u like the concept or not:)

**Comment by shagu** [comment]
@eNtreDefias Could you please upload the image somewhere (preferably as .png) and keep the alpha channels included?

**Comment by shagu** [comment]
https://github.com/shagu/pfUI-eliteoverlay
