### ISSUE TITLE
Move combo points?

### ISSUE THREAD

**Issue by phrazerlol** [shagu/pfUI#158]
I am a total novice when it comes to editing lua but i have managed to move the player power bar to the center of the screen where i want it. 

[http://i.imgur.com/oKVTYXF.gif](url)

I really have tried to move my combo points to form a line across this bar and it just results in me breaking the UI. Can you point me in the direction of the code i need to alter to do this?

lines 355-398 i have tried 20 variations but im just really new at all this.

**Comment by shagu** [comment]
I'm not sure if I got you right, do you want it like this? 
http://i.imgur.com/WPRcsXq.jpg

This is what I changed to achieve it:
`
diff --git a/modules/player.lua b/modules/player.lua
index 3ca2a57..8756122 100644
--- a/modules/player.lua
+++ b/modules/player.lua
@@ -285,7 +285,7 @@ pfUI:RegisterModule("player", function ()
   end
 
   pfUI.uf.player.power = CreateFrame("Frame",nil, pfUI.uf.player)
-  pfUI.uf.player.power:SetPoint("BOTTOM", 0, 0)
+  pfUI.uf.player.power:SetPoint("CENTER", UIParent, "CENTER", 0, 0)
   pfUI.uf.player.power:SetWidth(pfUI_config.unitframes.player.width)
   pfUI.uf.player.power:SetHeight(pfUI_config.unitframes.player.pheight)
   pfUI.utils:CreateBackdrop(pfUI.uf.player.power, default_border)
diff --git a/modules/target.lua b/modules/target.lua
index e0daec1..04a476f 100644
--- a/modules/target.lua
+++ b/modules/target.lua
@@ -366,7 +366,7 @@ pfUI:RegisterModule("target", function ()
           pfUI.uf.target["combopoint" .. point]:SetWidth(5)
           pfUI.uf.target["combopoint" .. point]:SetHeight(5)
           pfUI.utils:CreateBackdrop(pfUI.uf.target["combopoint" .. point])
-          pfUI.uf.target["combopoint" .. point]:SetPoint("TOPLEFT", pfUI.uf.target, "TOPRIGHT", pfUI_config.appearance.border.default*3, -(point - 1) * (5 + pfUI_config.appearance.border.default*3))
+          pfUI.uf.target["combopoint" .. point]:SetPoint("TOPLEFT", pfUI.uf.player.power.bar, "TOPLEFT", (point - 1) * (5 + pfUI_config.appearance.border.default*3), pfUI_config.appearance.border.default*3)
           if point < 3 then
             local tex = pfUI.uf.target["combopoint" .. point]:CreateTexture("OVERLAY")
             tex:SetAllPoints(pfUI.uf.target["combopoint" .. point])
`
