### ISSUE TITLE
Overlapping of actionbars and chat frames

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#159]
![](http://i.imgur.com/jIqpvr0.png)

**Comment by crumdidlyumshis** [comment]
What is your screen resolution?

**Comment by shirsig** [comment]
1920x1080.

**Comment by shagu** [comment]
The default Wow setting doesn't show the left and the right actionbar. 
If you change this setting you should also make sure by yourself that these are placed in a proper way. There are already alot of methods implemented to do this:
- Change UI scale (most common)
- Use pfUI's pixel-perfect mode
- Change Button size
- Change Actionbar scale
- Change Chat size 
- Move Actionbars
- Move Chat

**Comment by shagu** [comment]
I'm working on a more dynamic approach for the initial frame placement.

**Comment by shagu** [comment]
The layout has been reverted to use smaller frames again.
