### ISSUE TITLE
Chat panels return to position on logout after removal

### ISSUE THREAD

**Issue by dikdigguh** [shagu/pfUI#16]
One issue I face is that I like to remove the Loot & Spam chat box. If I remove or move the chat box upon client reload the chat frame will return to it's original dock location. I know this is a feature (and a great one at that, but I would love to have an option to turn it off.

My workaround was to comment lines 188-191 out in the chat.lua module:

    -- set position of Loot & Spam
  -- if not ChatFrame3.isDocked == 1 or not ChatFrame3:IsShown() then
  --   FCF_OpenNewWindow("Loot & Spam")
  --   end

Love the UI btw and have been using it avidly for months!

**Comment by dikdigguh** [comment]
I saw you are integrating DPSMate in the right-panel... That's exactly what I was hoping for.

I could kiss you Shagu!

**Comment by shagu** [comment]
I believe this issue is resolved by my latest commits.
Chat will only be initialized once per character. 
To reinitialize the chat, a "reset chat" button has been added to /pfui menu.
