### ISSUE TITLE
"proc" abilities are flickering and shown as usable

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#160]
Abilities such as Mongoose Bite, and Overpower are flickering and are shown as usable while they arent because they havnt procced yet

https://youtu.be/3WCZF5Psqs0

**Comment by Cruzix** [comment]
Addon wasnt updated. The fix to it seems weird though as you have to set the transparency yourself now which is extremely hard to get right

**Comment by shagu** [comment]
What?

**Comment by Cruzix** [comment]
When I updated from the old version to the new version it looked like this http://imgur.com/a/6cP7Z by default, so now I have to manually set the transparency to the red color which is pretty much impossible to make it look right

**Comment by shagu** [comment]
If it helps, the default transparency is 65%
https://github.com/shagu/pfUI/blob/master/modules/config.lua#L83

**Comment by Cruzix** [comment]
I just tried installing my old version of pfUI again to get a comparison of the two. Theres a huge difference http://imgur.com/a/ZHLgV 

The new version looks washed out and weird and its not possible to replicate the old look

**Comment by shagu** [comment]
I know, but changing the vertexcolor broke the out-of-mana color.

**Comment by Cruzix** [comment]
I have no idea about coding etc but cant you just do the same for the gray (unusable ability) and blue (out of mana) colors?

Bongos has this feature working perfectly, I dont know how to read its code but maybe you could see how it works there

**Comment by Cruzix** [comment]
Not sure if this is any help, but found this in Bongos_ActionBar>actionBar>button.lua: http://imgur.com/a/tqPaH

**Comment by Cruzix** [comment]
Made a new issue thread instead as this has gone too off topic: https://github.com/shagu/pfUI/issues/161
