### ISSUE TITLE
Make the range color feature similar to bongos's

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#161]
The last update to the range color feature made it look completely different to how it was before, however it did fix the previous issue ( https://github.com/shagu/pfUI/issues/154 ) but maybe you could take a look at how the author of Bongos fixed that issue as it keeps the more clean look the previous version had

Heres an image of before and after the #154 fix: http://imgur.com/a/ZHLgV

This is how it looks for Bongos: https://youtu.be/qtfpinmBifU?t=4m22s (Keep in mind you can change the color so its pretty much similar to previous pfUI version but without the gray/out of mana color issue)

This is Bongos' code: http://imgur.com/a/tqPaH

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/db2a6296e74da98fd62b927977a44c91706363a4
