### ISSUE TITLE
Add "None" display option for panels

### ISSUE THREAD

**Issue by serveral1** [shagu/pfUI#162]
Pretty straight forward.

Add a "None" option for those people that use other addons like FuBar or TitanPanel and don't like redundant info being displayed everywhere.

As of right now, all we can do is disable the panel module altogether, but that takes away the dpsmate and hide/show chat buttons the panel module provides.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/f23f8539df6075f9bfa9ae9ca706ab9a8aaa9787
