### ISSUE TITLE
request: stand up when using ability

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#165]
I used to use the auto dismount addon for this. Since you added the dismount part it would be nice if you could add this too. Basically it would make you stand up automatically if you attempted to use an ability while sitting.

**Comment by Ekimin** [comment]
do u mean EzDismount?
I suppose it could make u auto standup when u attempt to cast or mount while  eating.

**Comment by shirsig** [comment]
Yeah, that's the one.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/ebc9f3cafa37314e871e41275482f61631e2e4d5
