### ISSUE TITLE
bug: two instances of the loot module being displayed in the settings

### ISSUE THREAD

**Issue by serveral1** [shagu/pfUI#166]
which apparently disables it altogether regardless of it's enabled status (enabling/disabling one also applies the same for both)

pics showing the issue

![](http://puu.sh/sTBVi.jpg)

![](http://puu.sh/sTCuH.jpg)

i know i'm using xloot but i did so after pfui's loot box didn't show up and instead the vanilla loot box was shown instead. i also had xloot and pfui's loot box both enabled at some point when i first installed it and pfui's loot box still showed up, so it's not a conflicting addons issue.

**Comment by shagu** [comment]
Already fixed:
https://github.com/shagu/pfUI/commit/03ad55c869df4186cf64db697de6a32cd4aba434
