### ISSUE TITLE
Add locale compatible font (zhCN)

### ISSUE THREAD

**Issue by Ekimin** [shagu/pfUI#168]
Hi there,
Thx for ur useful addon it helps me a lot.
There's 2 improvements which I found could be done:
1.The default setting of chatbox width and height are 0,which causes the problem that input characters couldn't be seen while typing.(30 height and 200 width is ok)
2.the fonts in the addon do not support Chinese characters in English Client. I use English Client with Chinese fonts, and I found i cant see any Chinese characters using pfui. I changed the fonts(arial) in your addon with Chinese fonts and it works well with both English and Chinese characters.

**Comment by shagu** [comment]
Hi,

1. the width and height are set to 0 but this actually means that pfUI is using its builtin settings, which are 22 height and actionbar width (https://github.com/shagu/pfUI/blob/master/modules/chat.lua#L469-L474)

2. Is there a arial alike font which also provides chinese characters somewhere? If yes, could you please link it?

**Comment by Ekimin** [comment]
Hi,
1. I found that my addon do not show what i type if i do not set width and height manually.Maybe it is a individual case for me.
2. I'v post a pull request in which i added a arial alike font. It's unicode fonts so it  provides both Chinese characters and English ones too.

**Comment by Ekimin** [comment]
Here is the font link(arial unicode ms.ttf):  https://github.com/Ekimin/pfUI/tree/master/fonts

**Comment by shagu** [comment]
Wow! It's 23 MB. I won't add that. Sorry.

**Comment by shagu** [comment]
Does the Wow default font (without pfUI) support chinese characters?

**Comment by shirsig** [comment]
The fonts shipped with the english client don't, but I assume the default font (as assigned to STANDARD_TEXT_FONT) varies by client and if you use that it would work for every client.

**Comment by shagu** [comment]
As a first step, this adds support for zhCN gameclients: https://github.com/shagu/pfUI/commit/77f02d96743bc2ede861c697ca8c4e62578e8448

chinese characters are still not visible on non chinese gameclients. 
(because the font is not available for non chinese clients)

**Comment by jokers-x** [comment]
thinks for you very nice addon , but the pfUI addons nameplates or ShaguPlates can't work on cwow

**Comment by Ekimin** [comment]
> chinese characters are still not visible on non chinese gameclients.
(because the font is not available for non chinese clients)
----
The default fonts of original English Client does not support Chinese characters. This makes that many English Client users see that Chinese players typing blank messages. Chinese-based Client supports Chinese characters but some addons could not be used because many addons are designed just as English edition. My solution is using English Client and add Chinese fonts manually, so I can use those helpful addons and view Chinese characters at the same time.
----

**Comment by jokers-x** [comment]
@Ekimin how to add Chinese fonts in English Client ?

**Comment by Ekimin** [comment]
@jokers-x It's easy.
1. First locate the path: {gamedir}/fonts. You will found several font files here. 
2. Download  https://github.com/Ekimin/pfUI/tree/master/fonts(arial unicode ms.ttf), or other fonts supports Chinese charcters.
3. Replace every .ttf file at  {gamedir}/fonts/ with the same name. This means u need to make some replicates ,rename them and replace original English fonts with them.

**Comment by jokers-x** [comment]
@Ekimin wow/data/fonts.mpq?

**Comment by Ekimin** [comment]
@jokers-x Just at wow/fonts/

**Comment by shagu** [comment]
> but the pfUI addons nameplates or ShaguPlates can't work on cwow.

For me, the nameplates work flawless on the cwow client.
http://imgur.com/a/IJ0ix

**Comment by jokers-x** [comment]
I'm so sorry, maybe I wasn't being clear.

I can't see the enemycastbar.

![2](https://cloud.githubusercontent.com/assets/24637857/21346384/2e56df1c-c6df-11e6-881f-c86f99f4ef8b.jpg)

![3](https://cloud.githubusercontent.com/assets/24637857/21346385/2e5e761e-c6df-11e6-87f5-335ef85337e8.jpg)

![4](https://cloud.githubusercontent.com/assets/24637857/21346386/2e5fccda-c6df-11e6-8eb7-94b04b754266.jpg)

**Comment by shagu** [comment]
@jokers-x this is because of missing translations, have a look here:
https://github.com/shagu/pfUI/issues/178

**Comment by jokers-x** [comment]
thank you so much.

![1](https://cloud.githubusercontent.com/assets/24637857/21373468/27ebcff4-c75a-11e6-9063-28890231eaf8.jpg)

**Comment by shagu** [comment]
@jokers-x Could you please share your working translations here: https://github.com/shagu/pfUI/issues/178 ?

Thanks in advance.

**Comment by shagu** [comment]
I analyzed the client files and found out that there is no zhCN compatible font in all clients.
Unfortunately, clients with all language specific fonts were added with later expansions.
I'm not going to add a font which is more than 10 times bigger than the actual version of pfUI.
I ask for your understanding. Closing this one as "wontfix" :(
