### ISSUE TITLE
Minimap shows 0,0 coordinates in dungeon

### ISSUE THREAD

**Issue by nhll** [shagu/pfUI#170]
When you're in a dungeon, the minimap shows the coordinates 0,0 on mouseover. Might aswell just hide them completely in instances.

![Minimap Coordinates](http://fs5.directupload.net/images/161219/qc745sr4.png)

**Comment by shagu** [comment]
Not responding to mouse-over if coords are empty feels wrong, like the UI would hang.
I changed it to not available ("N/A") now.
https://github.com/shagu/pfUI/commit/6d9d7946c33737e2f716844480156f4cefa8be0c
