### ISSUE TITLE
mobhealth support not working

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#172]
always shows 100/100

**Comment by shagu** [comment]
Works for me:
http://i.imgur.com/NULujan.jpg

http://addons.us.to/addon/mobhealth

**Comment by shirsig** [comment]
hm, is the blizzard frames thing also needed?

**Comment by shagu** [comment]
No, but you should notice that mobhealth calculates the enemy hp by analyzing your damage you did to the target. So without a fight, it will always show 100/100.

**Comment by shirsig** [comment]
Oh, wait. Is that screenshot from nost? Most vanilla servers are showing the hp despite it not being blizzlike so you don't even need mobhealth.

**Comment by shagu** [comment]
It's not nost, but the server isn't showing HP without mobhealth ;)

**Comment by shirsig** [comment]
Hm, nost is always showing 100/100 for me. Done a few bgs since the restart and never seen it change. Other people say it's working so I thought it would be pfUI.

**Comment by shagu** [comment]
Nost PvP
![nost pvp](http://i.imgur.com/undefined.jpg)

**Comment by shagu** [comment]
Maybe related: https://forum.elysium-project.org/index.php?showtopic=25989

Closing this, as it doesn't seem to be an issue with pfUI. 
Feel free to reopen when it turns out I'm wrong with my assumption.
