### ISSUE TITLE
menu panel position

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#174]
Would it be possible to change the default position to below (or above) the minimap zone label, scaled to fit the size of the label? Seen this in some screenshot thread and it seems to fit so naturally there.

**Comment by shagu** [comment]
Good point, but to convince me, you'll have to show one of the screenshots where it ifts so naturally :D

**Comment by shirsig** [comment]
Couldn't find it anymore but tried to recreate it:
![](http://i.imgur.com/DbPeaB1.png)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/d858d308bb33d264c996b534629e304a058ba4b1
