### ISSUE TITLE
Auto-selfcast not working with mouseover /pfcast macro.

### ISSUE THREAD

**Issue by Rewinding** [shagu/pfUI#176]
On luna (which i'm guessing this is based on) you can do /lunamo macro for mouseover healing and still have it function normally with autoselfcast or targets as long as you don't mouseover anything.

With /pfcast greater heal(rank 1) it only functions when i mouseover frames.

**Comment by shagu** [comment]
> On luna (which i'm guessing this is based on)
It's not. I'm going to add selfcast.

**Comment by shagu** [comment]
If automatic selfcast is enabled in Wow settings, pfUI will make use of :)
https://github.com/shagu/pfUI/commit/b40ba837175d7673d6d1982875ab146210c3f971

**Comment by Rewinding** [comment]
works beautifully, thanks!
