### ISSUE TITLE
Translations for frFR

### ISSUE THREAD

**Issue by shagu** [shagu/pfUI#179]
https://github.com/shagu/pfUI/blob/master/env/locales_frFR.lua#L19-L44

**pfLocaleShift** 
Must be the exact term you see on your localized client when switching stances

**pfLocaleSpellEvents**
Must be the exact term you see on your localized client in combat logs.
(Mobname and values are extracted by regex, I can do that for you, if you mark these parts)

**pfLocaleSpellInterrupts**
Must be the exact Spellname translation of your client.

**Comment by SarekCDL** [comment]
Hello, I'm French and can do it.

I will install this a home this evening. ;)

**Comment by shagu** [comment]
Yes, the "-- TODO" Sections. That would be great. If you experience any other mistakes I made with the other ones, feel free to correct them :)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/d2f339963a34d6c2b248388af594166578ccdb35

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/97b140ea27e322bc89a81495e7bb2eaf544fa8fc
