### ISSUE TITLE
Bag/Bank item sorting

### ISSUE THREAD

**Issue by jfastnacht** [shagu/pfUI#18]
## Feature Request:

Add bag/bank item sorting functionality.

Already started in https://github.com/jfastnacht/pfUI/tree/feature/sort-bags with an item list (WIP). Might take a while if I continue working on that.
### Item order

~~Weapons & Armor (Artifact - Uncommon) > Consumables > Trade Goods > Quest > Hearthstone > Weapons & Armor (Common - Junk) > Junk~~

~~Junk will be on the top, while Weapons & Armor from artifact to uncommon quality will be on the bottom.~~

#id class
0 Consumable
1 Container
2 Weapon
4 Armor
5 Reagent
6 Projectile
7 Trade Goods
9 Recipe
11 Quiver
12 Quest
13 Key
15 Miscellaneous

There are also further subclasses. _(Source: https://media.readthedocs.org/pdf/mangoszero-docs/latest/mangoszero-docs.pdf, 184ff.)_
### Quality order

Artifact (6) > Legendary (5) > Epic (4) > Rare (3) > Uncommon (2) > Common (1) > Poor (0)
## Unresolved issues
- ~~What to do with Misc items?~~
- ~~Something missing?~~
- Sort order?

**Comment by shagu** [comment]
See this one for further details:
https://github.com/shagu/pfUI/pull/69
