### ISSUE TITLE
Cannot see my buffs/hots/debuffs on party frames

### ISSUE THREAD

**Issue by max-cp** [shagu/pfUI#181]
I do not have these options disabled, pretty sure I have them all enabled but in a party I cannot see my buffs on my party members, like I can't see if they have fortitude. I have to manually click them and see if they have the buff on their target frame.

Same goes for my hot (renew) and any debuffs they incur (I assumed this might be because I can't dispel it yet or maybe just no debuffs to speak of as of lvl 12.

The biggest concern is not being able to see my buffs/renew. I can't tell when to re-cast fortitude or if renew is ticking on someone at a glance.

I appreciate any help.

**Comment by shagu** [comment]
UnitFrames -> Group -> Enable Raidframe's Buff behaviour for Group
UnitFrames -> Raid -> Show my Buffs
UnitFrames -> Raid -> Show Hots

Is this set?

**Comment by Narec** [comment]
I have set those options. No change.

**Comment by shagu** [comment]
@Narec which class? which server? which pfUI version (date)?

I can't help without any information.
