### ISSUE TITLE
Chat problems.

### ISSUE THREAD

**Issue by hernberg** [shagu/pfUI#182]
Downloaded pfUI today.

My problem is that i can't write in general or trade etc.

When i write "/1" nothing happens :P nor /2,/3... think you got the point.

Dunno if the "addon" remove some settings or something? And i am no pro at all at setting thingy :)

**Comment by Rewinding** [comment]
Your message is written in the middle below character unit frame. When you write "/1 Hi everyone!" you will have said "Hi everyone!" in general chat.

**Comment by hernberg** [comment]
I know. It should be like that. But it aint :P i gonna try remove Wtf folder when i get home. :)

**Comment by hernberg** [comment]
No sucess when removed wtf folder either :P

**Comment by slajkon** [comment]
Pfui divides the chat into two parts, one on the left side and one on the right side, if you have DPSMate enabled this maybe cause the right chat to be removed. In this case you have to enable trade/general and similar channels in the left panel again, that's what I've done atleast.

**Comment by hernberg** [comment]
Well, i have no idea what solved it.. but i left the game to play some csgo... And when i log back in it works... Must have been my computer spoofing? It feels like the addon couldnt have done the problem.

**Comment by shagu** [comment]
I observed the same issue on nostalrius, but only on nostalrius so far. I was even able to reproduce this without any addons loaded. I might find out why this happens and introduce a hackfix to workaround the problem. But it's still pretty unclear.

**Comment by shagu** [comment]
/leave world
/join world
seems to help, but I still have no idea why this happens.

**Comment by hernberg** [comment]
Thanks for Your Effort man. Great that you found a fix for it! :) tho the problem havnt come back for me (yet) :P

**Comment by Narec** [comment]
Problem is I have to do /leave /join EVERYTIME I log in. :/

**Comment by Rewinding** [comment]
This issue was on old server aswell, nothing to do with the UI.

**Comment by shagu** [comment]
I tried to workaround this by code, but wasn't able to fix it. Sorry.
