### ISSUE TITLE
Mouseover healing, selfcast /pfui and target healing - Enhancement

### ISSUE THREAD

**Issue by Rewinding** [shagu/pfUI#184]
I could not come up with a proper title for this one..

Sorry for starting to many of these, great quick change with selfheal for /pfui mouseover heal macros. 
I was wondering if it would further be possible to have it **NOT** selfcast if you had a selected target and were not hovering your mouse above your frame.

Example behavior for a macro with /pfui Greater Heal(Rank 1) 

Hovering your mouse over a frame - Heals that target on keybind press (Just as it does now)
Not hovering your mouse over a frame and with no target - Heals yourself with auto-selfcast enabled on keybind press (Just as it does now)
Not hovering your mouse over a frame but with a target selected - Heals your selected target  on keybind press even with auto-selfcast enabled (At the moment it will heal yourself instead)

Tag: Enhancement

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/4f6f2fce88de09e09b3db26c511ed13f119eb0f9

**Comment by Rewinding** [comment]
10/10
