### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Oliveryo** [shagu/pfUI#185]
Is there any way to make one bar larger than the rest?

**Comment by slajkon** [comment]
There's the option to scroll on each element to rescale it in the "unlock" mode. Not sure if it fulfills what you want to do. But maybe that's what you need (:

**Comment by Oliveryo** [comment]
Thank you, this is what I was looking for!!

**Comment by Oliveryo** [comment]
Do you know how to show targets targets target?

**Comment by slajkon** [comment]
I am glad (:

I am not sure this is implemented yet. If it is I don't know how to do it.

**Comment by slajkon** [comment]
If this is not implemented you can add this as a new suggestion probably (:
