### ISSUE TITLE
Resize/stack nameplates

### ISSUE THREAD

**Issue by slajkon** [shagu/pfUI#186]
I've heard it's really hard to make nameplates stack or overlap in a good way in Vanilla. So if this is not possible then maybe it atleast is possible to add a width/height option for the nameplates to make them align more compact?

Also if it's possible to make them stack closer above each other or similar that would be great.
(Making the gaps between the nameplates smaller)

Keep up the great work! I love your addon alot!

**Comment by shagu** [comment]
This won't happen, as it would take too much cpu load on classic. Regarding the height and width, this will be taken care in https://github.com/shagu/pfUI/issues/138. Closing this one :)

Cheers
