### ISSUE TITLE
How to move all the raidFrame

### ISSUE THREAD

**Issue by jokers-x** [shagu/pfUI#187]
How to move all the raidFrame?

Not move this one by one.

thx!

**Comment by slajkon** [comment]
Shift-click-drag on one of the raidframes in "unlock" mode (:

**Comment by jokers-x** [comment]
@slajkon  Why I can't do it  ?

**Comment by slajkon** [comment]
@jokers-x It should be possible, it just doesn't update correctly until after you've dragged the element, I was a bit confused about it too the first time. But it should work.

Hold shift, left click on a raidframe, drag the frame where you want it, then all the other frames should move responsibly afterwards.
