### ISSUE TITLE
Suggestion/Question

### ISSUE THREAD

**Issue by Oliveryo** [shagu/pfUI#189]
Is it possible to decide how many buffs/debuffs that will show up on player/target frame?
Or making the buff list go upwards in rows and place the debuff list under frame going downwards?
Is it possible to ignore some buffs like ice armor and other longer ones?
Is it possible to remove the fill in bar function when i target someone, their hp fill in from left to right?

**Comment by shagu** [comment]
>Is it possible to decide how many buffs/debuffs that will show up on player/target frame?

No, not planned in future.

> Or making the buff list go upwards in rows and place the debuff list under frame going downwards?

No, not planned in future.

> Is it possible to ignore some buffs like ice armor and other longer ones?

No, not planned in future.

> Is it possible to remove the fill in bar function when i target someone, their hp fill in from left to right?

Not yet, I will introduce that.

**Comment by Oliveryo** [comment]
Okay, thanks! :)
