### ISSUE TITLE
Timestamp issue

### ISSUE THREAD

**Issue by jclock** [shagu/pfUI#191]
Hi Shagu,

Grabbed the latest download, enabling timestamps in the UI prevents any new messages/chat from showing.
Additionally, adding an option to change the brackets around channel and name would be nice.

**Comment by shagu** [comment]
> please reset your config or select a valid color within /pfui settings.

https://github.com/shagu/pfUI/issues/152

**Comment by shagu** [comment]
this commit should rescue broken configs: https://github.com/shagu/pfUI/commit/96dc8f93a560aa0570ab0efce925d7628c770425
