### ISSUE TITLE
Wrong Buff/Debuff Timers on Playerframe

### ISSUE THREAD

**Issue by Oliveryo** [shagu/pfUI#193]
I'm using Voidmenull/DebuffTimers and timers don't show up on my own debuffs.
Do you know how to fix this?

**Comment by shagu** [comment]
You might want to ask @Voidmenull about that.

**Comment by Voidmenull** [comment]
noope shago, hes asking about the debuffs on the playerframe :)

its buggy on pfUI :) its showing wrong timers or no timers at all (in my version that is few days old)

**Comment by shagu** [comment]
o_O

**Comment by shagu** [comment]
Alright, was able to reproduce this:
![1](http://i.imgur.com/Hz8sAuP.jpg)

This is not related to Voidmenull/DebuffTimers.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/1d1b099d34416214479b3a23ddb8963da59cbe5a
