### ISSUE TITLE
Cooldown text color

### ISSUE THREAD

**Issue by Oliveryo** [shagu/pfUI#195]
The cooldown text color is black on minute, hour and day for me and I can't change it.

**Comment by shagu** [comment]
Please reset your settings or set a valid value via /pfui settings (don't forget to adjust the alpha value).
There has been a change on which I had to change the format in which the colors are saved to the profile.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/96dc8f93a560aa0570ab0efce925d7628c770425
