### ISSUE TITLE
/pfcast cooldown and tooltip

### ISSUE THREAD

**Issue by Eidolon91** [shagu/pfUI#196]
Creating a macro with /pfcast doesnt allow the tracking of cooldown in the skillbar nor does it show the tooltip of the spell. Would be nice if this could be implemented like /cast funktion does

**Comment by shagu** [comment]
Uh, is that even possible in 1.12? I'll have a look later.

**Comment by Road-block** [comment]
Cooldown on actionbutton the player themselves can do with a simple trick.  
Tooltip is trickier.  
It's possible but it would need a fair amount of work from shagu.
For showing the cooldown on button put this at the top of your macro.
`/run if nil CastSpellByName("spellname")`  
Where "spellname" the name of the spell you want cooldown shown for.

**Comment by l453rl453r** [comment]
![2017-01-04_014712](https://cloud.githubusercontent.com/assets/24902382/21628434/c996da86-d21f-11e6-9b33-d2a11f306b47.png)

its working and showing the cd, but i get this errormessage every time ...

**Comment by l453rl453r** [comment]
ok so i got my answer from somewhere else, this macro also works for me and doesnt print error messages:

/run if 1==0 then CastSpellByName("spellname");end
