### ISSUE TITLE
cd bug

### ISSUE THREAD

**Issue by KasVital** [shagu/pfUI#197]
![cooldown bug](https://cloud.githubusercontent.com/assets/15636669/21437227/af1aef8e-c893-11e6-8d8b-4ed920289c6c.jpg)
cooldown bug an item at inventory

**Comment by shagu** [comment]
I'd need a list with all your installed addons, because I'm not able to reproduce this with "only pfUI"

**Comment by SarekCDL** [comment]
![cooldown](https://cloud.githubusercontent.com/assets/9592144/21443267/f438dfc6-c8a3-11e6-93b2-3ead5cc40ec9.jpg)

Didn't know if it's linked but I have a similar bug when doing nothing (but my priest buff was fading to 0 at the time of the screen).

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/01d541ba0553e9572ca172ddf20403a3443c2e00

**Comment by KasVital** [comment]
i have EngBag
