### ISSUE TITLE
NOT WORK DPSMate in RUru locale

### ISSUE THREAD

**Issue by gamer4eg** [shagu/pfUI#198]
My level of English is very plohouy text generated by Google translator * = (
DPSMate RUru does not support the client, could you add Integration addon KLHThreatMeter or any other DPS meters from localized into Russian.
Link to an archive with localized mods elysium site
forum topic
https://forum.elysium-project.org/index.php?showtopic=18686
direct links
https://yadi.sk/d/wwdbb_AMiqA6n
https://drive.google.com/file/d/0Bz4qLUQsxHCQSTNxWUlDMGdfMGc/view?usp=sharing

**Comment by shagu** [comment]
Hi,
For other addon integration to match the pfUI-theme (e.g KTM) will be handled here: https://github.com/shagu/pfUI/issues/23
I've planned to create a framework on which the user can easilly theme 3rd party addons on their own. But it's still a lot to do there.

@Geigerkind: Is there a ruRU translation for DPSMate planned or ongoing in the near future?

**Comment by Geigerkind** [comment]
Yes it is planned. But as long as I don't find anyone who might help me for everything except german and english, I can't do anything :<

I will ask in the thread again for translators.

**Comment by gamer4eg** [comment]
Link to a group of Ruthenian localizers wow 1.12.1 (they translate addons for the client RUru)
https://vk.com/wowruru
