### ISSUE TITLE
Minimap symbols overlay each other

### ISSUE THREAD

**Issue by Plaetomat** [shagu/pfUI#20]
Hey,,

I'm using ShaguUI and first of all have to say it's amazing! Just THE thing I was looking for a long time to improve my interface.

One thing I've noticed is that the inbox symbol covers my herbalism tracking symbol at the minimap. Is there a way to fix those symbols?

Thank you in advance!

**Comment by jfastnacht** [comment]
Sounds like another addon. Can you provide a screenshot?

**Comment by Plaetomat** [comment]
I'm refering to:  http://shaguaddons.ericmauser.de/shaguui/

![wowscrnshot_081516_193619](https://cloud.githubusercontent.com/assets/21041771/17673085/db9b1c52-631f-11e6-939c-a3327241f9c2.jpg)

**Comment by jfastnacht** [comment]
This is the pfUI repository. Unfortunately I can't help you. :( I don't know whether there'a repository dedicated to ShaguUI.

**Comment by shagu** [comment]
You can change this in ShaguUI\libs\simpleMinimap\simpleMinimap.lua on line 23:
Just replace "mail=30" with "mail=20" and the symbol. Play with the values until you found a suitable position but 20 seems to be okay.

As @jfstnacht already mentioned, this is the wrong place to report Issues for ShaguUI. Closing this ticket.
