### ISSUE TITLE
Disable pfUI from addonlist frame

### ISSUE THREAD

**Issue by SarekCDL** [shagu/pfUI#204]
Is it intended to be able to uncheck pfUI in the addonlist frame available in the bottom right pane (when clicking on fps/ping) ? 
That disable everything without being able to restore it whitout disconnecting.

**Comment by shagu** [comment]
Of course. Why should I limit your autonomy of decision?

**Comment by SarekCDL** [comment]
It's true, now that we talk about it I didn't remember if I didn't see this also when clicking to Reset All. 
I will do more test this evening.

I like this project and will try to help as much as possible. ;)
