### ISSUE TITLE
unitframes: option to show yourself in group

### ISSUE THREAD

**Issue by SarekCDL** [shagu/pfUI#205]
Group unit frame show the 4 others players but it's disturbing that we can't see oneself especially when u are healer and the group are far from the player unit frame.

And it would be helpful to be able to move all the group unit frame in one time.

**Comment by SarekCDL** [comment]
Will try to implement this in my fork and suggest it when ready.

Feel free to ask for help. :)

**Comment by lovestrange** [comment]
Yes, this would be really helpful as a healer. I was hoping more features like this along with more click casting options would be added soon, since there's a lack of healer friendly UI out there.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/e93b52c2baa52ceeb482f2c92af3ff41e38a4836
