### ISSUE TITLE
minimap: show zone text on mouseover.

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#209]
Make the zone text show on top of the minimap upon mouseover so we can use the minimap panel for other modules instead (ElvUI has friends/guild module there as an example)

edit: Similar to how the coords are shown

**Comment by greenya** [comment]
This feature is already implemented -- http://i.imgur.com/Jz4BlCv.png

**Comment by Cruzix** [comment]
yup, its an old report prior to implementation. Closing it now :)
