### ISSUE TITLE
Enhancement: Right clicking individual action bar in "unlock mode" for edit menu

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#213]
Make an option to edit individual action bar by right clicking them in "unlock mode" similar to how Bongos does it. 
When you right click them in unlock mode a small window with edit options should appear with stuff like scaling, rows. columns, opacity, hide, show on mouseover, spacing, hide backdrop etc that would only change it for that single action bar.

http://addons.us.to/addon/bongos

**Comment by SarekCDL** [comment]
I find the ElvUI way more convenient with a big settings frame well categorized but I agree with that.

**Comment by shagu** [comment]
There's already an issue about actionbar customization. Please comment your suggestion there.
https://github.com/shagu/pfUI/issues/141
