### ISSUE TITLE
thirdparty: option to embed 2 addons into the right chat

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#214]
Add an option to embed 2 addons into the right chat such as KTM and DPSMate so it looks like this without having to manually move them
![Image of KTM and DPSMate](http://i.imgur.com/AlkQyxX.png)

**Comment by Rachdingue** [comment]
How do you do that?

**Comment by Cruzix** [comment]
@Rachdingue 

> so it looks like this without having to manually move them

Move them manually.

**Comment by godtanker** [comment]
oh nice~ how do that? source code plz..~

**Comment by shagu** [comment]
![1](https://cdn.discordapp.com/attachments/329951327859900417/333594248605859841/image.png)
https://github.com/shagu/pfUI/commit/02a81bd646e007bd7a86ba49c6b7b4fcb2b29d50
