### ISSUE TITLE
Enhancement: Option to make the right chat frame only function as a addon embed window

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#215]
Option to make the right chat frame only function as a addon embed window, in case people never intend to use it for chatting. 

Currently it resets to the chat window upon /rl or login so you have to manually change it to the addon embed window by clicking the arrow in the corner every time.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/010f83e90724665712a7cd1c23e614fd654eb5b5
