### ISSUE TITLE
Enhancement: Option to show pfUI castbars with unitframes disabled

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#216]
Make an option to show pfUI castbars with unitframes disabled

**Comment by shagu** [comment]
Sorry man, I won't split every single frame.

**Comment by Cruzix** [comment]
All good, its just sad that theres no standalone addons that has both player and enemy castbar so if you choose to disable pfUI unitframes you'll end up having 2 different looking castbars as they are the only alternatives unless the unitframes you're using has some integrated.
