### ISSUE TITLE
Disable pfUI chat channel modifications upon first install

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#217]
Currently pfUI changes the chat settings upon first installation and also recolors some channels such as "incoming whispers" a lot more bright than stock settings. 

Personally I really like how the chat channels are colored and set up by stock and I feel like pfUI shouldnt be forcing people to have the chat settings changed so you afterwards have to change it back.

I know you have plans of a installation window where you can choose things like this to happen or not, but thats not the case at the moment.

Also to fix this problem for myself, how do I reset the chat settings completely?

**Comment by shagu** [comment]
Yes. pfUI will have a First-Start wizzard before 1.0-Release gets out. I thought I already got an issue about that... leaving this one open until I find it.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/issues/239
