### ISSUE TITLE
Hey have some questions!

### ISSUE THREAD

**Issue by tnylifestory** [shagu/pfUI#22]
Sup my mate i really like you new UI but i have some problems.
Where is ts XP bar how it open this ?
And i have chat typing window problem is in a center,its possible to move?
And you have really beautiful quest data base but show in my screen,all quest in location i see in the map!
In you quest helper it possible ? Tnx for answers and PfUi!
![wowscrnshot_082016_150842](https://cloud.githubusercontent.com/assets/21141535/17831113/0195b800-66e9-11e6-9b14-62b6e2ff9d88.jpg)
![wowscrnshot_082016_150829](https://cloud.githubusercontent.com/assets/21141535/17831114/05f3c6b2-66e9-11e6-947a-a1e29307878d.jpg)

**Comment by shagu** [comment]
Hi,
On this video you can see how to use the XP-Bar: 
https://www.youtube.com/watch?v=7FlIxlyaVvM

The Chat-Input field can't be moved right now. Will be possible some time but right now there is some more important stuff to do.

I don't understand your question about ShaguDB, as all I can see on your Screenshot is Questie. Please note that this is the Bugtracker for only pfUI not for all ShaguAddons. Closing as invalid.

Cheers
Shagu

**Comment by tnylifestory** [comment]
hey tnx for answers)
