### ISSUE TITLE
eqcompare: support for atlas / atlasloot

### ISSUE THREAD

**Issue by Cephel** [shagu/pfUI#222]
It seems Atlas uses its own tooltip system and as such pfUI does not pick up on the comparison when needed.

![](http://i.imgur.com/kvMNn12.png)

**Comment by shagu** [comment]
Yes, it only works for bank/bag items right now.

**Comment by Cruzix** [comment]
![image](https://cloud.githubusercontent.com/assets/6162744/21462149/dbfeaa34-c958-11e6-94a9-62327abd754d.png)
And buffs apperently, it'll show your previous hovered item :D

**Comment by shagu** [comment]
@Cruzix Cannot reproduce this with default buffs

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/36fe8aafd10ee77ab3a7c5768244e4f962855fe9
