### ISSUE TITLE
Add a way to restore correct chat settings on various triggers

### ISSUE THREAD

**Issue by Cephel** [shagu/pfUI#223]
It seems an issue with populated servers is that chat settings, in particular the order, visibility status and joined channel ist get out of alignment based on unknown factors.

Suppose this is your chat setup:
1. General
2. Trade
3. LocalDefense
4. LookingForGroup
5. World
6. SomeAddonChannel

One or more of the following things can happen, either when logging in, changing zones, reloading the UI, and so on:
- One or more channels are no longer subscribed to
- One or more channels are subscribed to, but any attempt to write in them will fail (using /4 for example will not turn into the proper chat prompt)
- One or more channels are unchecked in the chat window option and are thus not visible
- The channel order is messed up (ie. General is now /3)
- A channel subscription to Trade exists outside of a major city

The way to fix this quick and dirty is to use a macro to leave every relevant channel and rejoin them in order. A macro in the form
```
/leave General
/leave Trade
/leave LocalDefense
/leave LookingForGroup
/leave World
/leave SomeAddonChannel
```
and a second macro in the form
```
/join General
/join Trade
/join LocalDefense
/join LookingForGroup
/join World
/join SomeAddonChannel
```
do suffice for this purpose.

This however auto checks them all for visibility, even though in the case of the addon channel, you may want it to stay hidden. It also auto puts them into the chat window frame 1, where you may want to have one or more channels in other frames.

If you do not follow this procedure, the inccorect chat settings are saved to the corresponding config file on logout, further making the settings go out of alignment.

It would be nice if pfUI was capable of setting these chat settings somewhere and either periodicially or based on proper detection restores the correct chat settings so that invisible to the user, they never go out of alignment.

**Comment by shagu** [comment]
Please have a look here: https://github.com/shagu/pfUI/issues/182
