### ISSUE TITLE
Equipment comparison window not cleaned up properly

### ISSUE THREAD

**Issue by torusnc** [shagu/pfUI#226]
The recently implemented equipment comparison window becomes stuck on screen, moving with the tooltip (currently, tooltip is set to 'cursor' in my options). Each item that regenerates a tooltip moves the item window to that location, as if the comparison is continuing. Please see screenshots below at the following link:

https://imgur.com/a/6jW33

Thank you!

**Comment by Barry031** [comment]
This bug is caused by the addon Questie, revert back to 3.2 or wait for the questie dev to update it.
Working fine for me with quetie disabled.

**Comment by Barry031** [comment]
This is a questie addon bug, disable it or revert back to an older version. Working fine for me with latest pfUI build and questie disabled.

**Comment by torusnc** [comment]
Great, thanks for the note! I'll raise the issue on Questie's github.

**Comment by torusnc** [comment]
Questie has been updated to address this issue, tests fine on my end.
