### ISSUE TITLE
Friendly nameplates bug

### ISSUE THREAD

**Issue by Rewinding** [shagu/pfUI#229]
Can't say if this applicable in other scenarios so il just describe what happened in mine.

Casting renew on a friendly nearby target with nameplates enabled makes it look as if the target you casted on AND every friendly target around it is casting renew. 

I believe it's the same with all friendly spells.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/b1ba3c1f967db1f1f0f25b4b94e08c69ceb586fc
