### ISSUE TITLE
Ability to skin 3rd party frames

### ISSUE THREAD

**Issue by dikdigguh** [shagu/pfUI#23]
Right now, I modify pfUI to make extra panels where I place versions of KTM & Eavesdrop that I modified to have transparent backgrounds. That way there is a consistent look across my UI.

I see you are integrating a third party addon like DPSmate (which is amazing)! Do you have plans to integrate required addons like KTM as well? If so disregard the top request :)

Best UI ever!

**Comment by shagu** [comment]
KTM is on my roadmap, but right now there are still alot of other things to do.

**Comment by Voidmenull** [comment]
i made a KTM version in pfUI style, you can use this till shagu implent KTM it into the UI:

https://www.dropbox.com/s/1q6idlbeqevpt3h/KLHThreatMeter.zip?dl=0

http://i.imgur.com/4PcMvM3.jpg

**Comment by Voidmenull** [comment]
And another one for sw_stats:

https://www.dropbox.com/s/rg5mhsbnntjembo/SW_Stats.zip?dl=0

http://i.imgur.com/oxrdrfu.jpg

**Comment by dikdigguh** [comment]
Nice guys - I also swapped out textures on KTM, EavesDrop, IgniteStatus, and XRS. I'll upload mine to share once I'm home from work xD
