### ISSUE TITLE
Player/Target Castbar Placement

### ISSUE THREAD

**Issue by scionix** [shagu/pfUI#232]
Having the option to align the player/target castbars to the top of the unit frame as well as the bottom would be a nice quality of life option.  Kind of like the top/bottom/hidden options in regards to player/target buffs and debuffs.

**Comment by Cruzix** [comment]
On top of this, it would be nice if you could make it drag-able too so you could place it where ever you want it

**Comment by jclock** [comment]
And even more on top of this, ability to change the dimensions.

**Comment by l453rl453r** [comment]
not really an issue on your end but i know you already made it work on shaguui. i use pfui with luna uf and i want the castbar to be the same as it was on shagu ui, so that its over the manabar. can u tell me how i can do that?

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/144fb4266b1472d296dbcd751efe48b560346b37
