### ISSUE TITLE
Nameplates. Friendly players nameplates colour

### ISSUE THREAD

**Issue by paulpss** [shagu/pfUI#233]
Hello,

I figured out how to change the width in lua config file, but I can not find an entry to change the behaviour of friendly players' nameplates colours. Is there any possibility to keep them one-coloured (blue or any other one) while having enemy players nameplates colours according to the class? Like it was in the Custom Nameplates addon.

Thank you

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/454fdd2ab9ab3dbda77f4aa878a3739f38d88893
