### ISSUE TITLE
option to change color of incoming whispers

### ISSUE THREAD

**Issue by torusnc** [shagu/pfUI#234]
Incoming whispers stay the same color regardless of chat setting. See image link below:

http://imgur.com/1F7b4GQ

**Comment by Cruzix** [comment]
I believe that the "First-Start wizzard" that he talks about here https://github.com/shagu/pfUI/issues/217 will take care of this. Atleast this was one of the things that I mentioned in the post as well.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/bfb9590e69e1866c7a5c453ab22e304f8c242fb5
