### ISSUE TITLE
Nameplates. Issue making them show

### ISSUE THREAD

**Issue by henriquefsp** [shagu/pfUI#235]
Hey shagu,

I was having trouble finding a way to message you about this issue. As I'm not sure if I'm doing something wrong or getting a bug I wasn't sure if this would be the proper place to ask but anyway it was the only way I found to message you.
I can't make the nameplates show, I checked the module and it isn't disabled, I think I have every setting on correctly to show them but they're not showing at all for me. I don't know if it could be a bad interaction with the system or the interface menu but that's my issue. I'll post a screenshot of the nameplate menu.
Do you know what could possibly be causing this?

http://imgur.com/a/sZtGR

Cheers,

henrique

**Comment by Road-block** [comment]
This is a long shot, but are you sure you haven't accidentally turned them off?  
Check your keybinds for nameplate commands and use it to toggle them back on if that's the case.

**Comment by henriquefsp** [comment]
oh man and this is why I'm the guy who can't fix things

thank you man, I was using the wrong keybind to turn them on -.-
