### ISSUE TITLE
Rogue Stealth button

### ISSUE THREAD

**Issue by Fundaris** [shagu/pfUI#24]
Bei dem stealthbutton fehlt eine 1 Sekunde cooldown :/ 

Das führt dazu das wenn man raufklickt "Fähigkeit ist noch nicht bereit"

**Comment by Fundaris** [comment]
Fix: 
cooldown.lua#L41
` if (remaining >= 0.0 and this.duration > 1.5) then`

**Comment by shagu** [comment]
thanks, fixed in https://github.com/shagu/pfUI/commit/09d86acb1da76af8a305ac8675c02eadd7613c5a
