### ISSUE TITLE
pet happiness

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#240]
could you add a pet happiness indicator (or is there one already somewhere?)
Also in combat/pvp indicators would be nice too.

**Comment by shagu** [comment]
The pet happines indicator is the color of your pet's healthbar. 
(if using custom colors, then it's the textcolor of your pet)

green = happy
yellow = neutral
red = sad

combat indicator is the red glow around your player frame, or if set the red glow around your screen edges.

pvp indicators can be set in the /pfUI settings -> Unitframes -> Player -> Show PvP Icon.

**Comment by shirsig** [comment]
thanks

**Comment by thompdre84** [comment]
I tested this in Lightbringer (Light's Hope) server. It is my experience that pet health bar does not change colors with pet happiness change, not does text color. Lost a pet due to this issue. Turned off custom frames and waited until I saw new pet go from happy to content, content to unhappy. Turned on custom frames and reloaded UI each time: --> No change to health bar, no chance to text color. Sorry, no screenshots to provide.

**Comment by shagu** [comment]
Tested on Light's hope on my hunter. I've added the following to verify the event is triggered:
```
diff --git a/api/unitframes.lua b/api/unitframes.lua
index f86cbf4..52dd277 100644
--- a/api/unitframes.lua
+++ b/api/unitframes.lua
@@ -239,6 +238,9 @@ function pfUI.uf:CreateUnitFrame(unit, id, config, tick)
 
       -- UNIT_XXX Events
       elseif arg1 and arg1 == this.label .. this.id then
+        if event == "UNIT_HAPPINESS" then
+          message("TRIGGER")
+        end
         if event == "UNIT_PORTRAIT_UPDATE" or event == "UNIT_MODEL_CHANGED" then
           pfUI.uf:RefreshUnit(this, "portrait")
         elseif event == "UNIT_AURA" then
```
Result:
![image](https://user-images.githubusercontent.com/11586807/32963542-9cac8fce-cbd0-11e7-8662-79168d66753f.png)

**Comment by thompdre84** [comment]
So just to confirm, did you make a code change or are you verifying that it is working as intended?

Thanks!

**Comment by shagu** [comment]
Happy / Content / Unhappy
![image](https://user-images.githubusercontent.com/11586807/32971549-01d0b6f6-cbee-11e7-88e6-3d5bb7a6277c.png)

**Comment by thompdre84** [comment]
Huh. Yeah mine doesn't do that. I did have a lot of addons installed before this one, perhaps I need to wipe the addons folder and reinstall just the stuff I need.

Thanks for taking the time to post the screenshot for me. If it still doesn't work after a wipe I'll post screenshots and any other debug info I can find.

**Comment by thompdre84** [comment]
I was able to fix this issue by deleting my major WoW folders and reinstalling pfUI. Pet health bar now correctly changes colors based on mood.

Thanks for the help.
