### ISSUE TITLE
Nameplate&Castbar

### ISSUE THREAD

**Issue by jokers-x** [shagu/pfUI#243]
When i press down right mouse and move to the mob's nameplates, one white line  appear under the  nameplates ， one second later, the line  disappear.
![2](https://cloud.githubusercontent.com/assets/24637857/21515608/3933f9e6-cd0c-11e6-8074-058751837084.jpg)

Another BUG： when the mobs cast skills, nameplate  appear  the castbar,but one bug appear  that tha same name mob (dont in combat) appear the castbar too.
![1](https://cloud.githubusercontent.com/assets/24637857/21515590/2145bf36-cd0c-11e6-96e4-d7693e4eed78.jpg)

**Comment by shagu** [comment]
> When i press down right mouse and move to the mob's nameplates

I can't move the nameplate via right click, and it is not supposed to be able to. Did you changed anything in the code?


> Another BUG： when the mobs cast skills, nameplate appear the castbar,but one bug appear that tha same name mob (dont in combat) appear the castbar too.

This can't be fixed. In classic there is no way to check which mob is casting. All I have is a mobname, if two mobs share the same name, both will be "casting".

**Comment by jokers-x** [comment]
Thx,the first question I didn't meet，my friend asked me to ask you.
The second question so unfortunately :D
