### ISSUE TITLE
unitframes: display group as raid

### ISSUE THREAD

**Issue by gamer4eg** [shagu/pfUI#245]
Can u add an option through the mapping of the raid interface (UI group and hide even in the party)?

**Comment by gamer4eg** [comment]
I am sorry that the hurry, but it is a very useful option for healers ...)

**Comment by nesherman** [comment]
Also second this.

**Comment by joao-fidalgo** [comment]
+1

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/509d60ef6e0dfbb9269b8999893a2fac314dd1a1
