### ISSUE TITLE
chat: support web links

### ISSUE THREAD

**Issue by Cephel** [shagu/pfUI#248]
Title

**Comment by Cruzix** [comment]
Here's an addon that makes it possible to copy links from ingame chat, I believe that is what @Cephel is refering to. 

http://addons.us.to/addon/urlcopy-0
You can use it to figure out how to make this @shagu

**Comment by Cephel** [comment]
Yes, sorry I'm a little short on description sometimes, that's what I mean

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/fa17a9b4253c89a2d9b635b6ffef3712ab2d3a76
