### ISSUE TITLE
PVP indicator not refreshing properly

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#249]
Doesn't show with /pvp, only after /run ReloadUI() (also, i think it's missing from the target frame. actually, the icon should probably be the flag like in the default frames, not the crossed swords, because for the target it would otherwise be ambiguous)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/2cf0033d9420dde4f8fd90069af880fa33198e53
