### ISSUE TITLE
Cooldowntimer stuck when in inactive bar

### ISSUE THREAD

**Issue by Fundaris** [shagu/pfUI#25]
Hey Shagu,

wenn ich mit dem Rogue im Stealth "Ablenken" mache und dann ausm Stealth gehe und der komplette CD durch ist. Hängt sich der CD auf, ab dem Zeitpunkt, wo die bar nicht mehr aktiv ist.

**Comment by shagu** [comment]
Hi,
I don't have a rogue and cannot reproduce. But I did some bugfixing on the cooldowns, maybe it is fixed with this commit?
https://github.com/shagu/pfUI/commit/6e7b191d3d711a384dbe15423a6d3b2f64fcfc7d ?

**Comment by Fundaris** [comment]
Works thanks mate!
