### ISSUE TITLE
unitframes: add 40 yard range check

### ISSUE THREAD

**Issue by Pride014** [shagu/pfUI#252]
Hi
It seems there's no 40 yard range check available. 
It makes it useless as an healer.

**Comment by Rewinding** [comment]
It's a little annoying, but could also leave you confused as to why your friendly spells without increased range isn't hitting. Optimal would be if you could choose which rangecheck to use in the settings.

**Comment by shagu** [comment]
Yes. 
I won't force it to players ;) If I do 40y range checks then it will be an option only. 
Because 40y checks are always unreliable and always consume more load than the actual one.

**Comment by Rewinding** [comment]
Shameless bump!

**Comment by muter941** [comment]
I need that too.

**Comment by shagu** [comment]
New Unitframes now Available on `master`
