### ISSUE TITLE
target: strange health bar movements (mobhealth3)

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#256]
Sometimes the (target frame, maybe others too) health bar jumps back up and down for no reason. Seems to happen most often after a big crit on a full hp enemy but that may just be a coincidence. Might have something to do with the effect when the frame is shown, maybe the frame is hidden/reshown for some reason. Could also be a conflict with other addons automatically changing the target for scanning or something (enemyframes?) but I'm pretty sure I've had it happen with no such addons.

**Comment by shagu** [comment]
- It jumps from zero to the actual health for no reason?
- Related to MobHealth?

**Comment by shirsig** [comment]
It jumps to full and then back to the actual health I think. Gonna try and pay closer attention. I think it happened on kronos too so probably not mobhealth.

**Comment by shagu** [comment]
I'll have an eye on it

**Comment by Rewinding** [comment]
Are you sure this is not due to feign death? :)
Fools me sometimes!

**Comment by shirsig** [comment]
Definitely. no feign death for 19 twinks.

**Comment by shirsig** [comment]
Hm, can't reproduce it anymore. Will try again on kronos sometime, or maybe it really was a target scanning addon. Actually, it would be nice to have an option to disable the animation for target scanning addons like enemyframes.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/79ab3ee0b30799af981e8b6744d4d891b91ad4f6

**Comment by shirsig** [comment]
Great, thanks.

**Comment by shirsig** [comment]
I noticed the targettarget frame still has the animation. Think it would make sense if they shared that setting.

**Comment by shagu** [comment]
:D

**Comment by shirsig** [comment]
Was able to reproduce it after all:
https://www.youtube.com/watch?v=nlKBOFiuDtg
https://www.youtube.com/watch?v=5z14l8YuYPU

**Comment by shirsig** [comment]
This is caused by mobhealth btw, sorry, must've missed your message about this.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/4162312ba9646326a9dbe2cd1cafb34fc9e94f0e
