### ISSUE TITLE
chat: add mouseover tooltips for item links

### ISSUE THREAD

**Issue by jclock** [shagu/pfUI#258]
I'm not sure if it was a feature possible in 1.12.

**Comment by shagu** [comment]
I'm not sure if this is possible. I'll have a look and add the appropriate tag as soon as I know more :)

**Comment by RajuJanne** [comment]
It is possible. 
For jclock: as a work around you can use ChatSuey, only enabling "ChatSuey" and "Chat Suey - Item Link Hover" will leave the chat otherwise altered.

**Comment by jclock** [comment]
I'll take a look at it, thanks. I want to try and limit the possible addon conflicts.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/f1f411302bbd6fc9b81616299e59765667669638
