### ISSUE TITLE
Some party members visible in raid with party frames in raid disabled

### ISSUE THREAD

**Issue by RajuJanne** [shagu/pfUI#259]
As the topic says. So far this has happened when reconnecting after a server crash or joining a battleground with a raid group. Not sure if pre-existing raid group is relevant on the BG case tho. Reloading UI has always fixed the problem. I've attached a list of loaded addons and a screenshot of the behaviour.

http://i.imgur.com/IsvTyjH.png
[AddOns.txt](https://github.com/shagu/pfUI/files/679887/AddOns.txt)

-- Rubberfist

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/ee99a9d36732178121283126409bcf3c41897fe1
