### ISSUE TITLE
bag quality border only working for gear (not sure if intended)

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#260]

**Comment by shagu** [comment]
Yes, I'm using the quality color of:
```
local texture, count, locked, quality = GetContainerItemInfo(bag, slot)
```
Is there any better function that also gives quality for non-gear?

**Comment by shirsig** [comment]
GetItemInfo. But to use that you have to extract the id from the link but then you might just as well extract the color from the link (GetContainerItemLink)

**Comment by shagu** [comment]
I always assumed that GetContainerItemInfo will just return the same as GetItemInfo but with the ease of use for containers.. Thanks for the clarification :)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/15f27138d98fd2bf8ca780e3247a77744a575f60
