### ISSUE TITLE
actionbar bug

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#261]
In the newest version strange things happen with the action bar. When in melee range one bar disappears:
https://www.youtube.com/watch?v=3f82Y7AkTtM

**Comment by Cruzix** [comment]
I'm pretty sure this is an intended feature that you can disable and enable in the settings.

**Comment by shirsig** [comment]
Ah ok, thanks.

**Comment by shagu** [comment]
!(range based auto paging)[http://i.imgur.com/05IYOd7.jpg]

First commit: https://github.com/shagu/pfUI/commit/dc3c89b3adac44f56aef420e137dbce6a52c00ad
Issue: https://github.com/shagu/pfUI/issues/34
