### ISSUE TITLE
got error when any items on cd and open bag

### ISSUE THREAD

**Issue by KasVital** [shagu/pfUI#264]
![image](https://cloud.githubusercontent.com/assets/15636669/21581360/a9e6e658-d040-11e6-8bfb-15a57b7c3607.png)

addon EngBags

**Comment by KasVital** [comment]
![image](https://cloud.githubusercontent.com/assets/15636669/21581371/3f8e6cee-d041-11e6-8208-148c218bcbd4.png)
fixed with
12, 13, 14 lines cooldown.lua
`if not this:GetParent() then
if not getglobal(this:GetParent():GetName() .. "Cooldown"):IsShown() then this:Hide() end
end`

**Comment by shagu** [comment]
I've seen your "fix" but to be honest, this will lead to other errors:
If not this:GetParent() then please give me this:GetParent():GetName() as a global to check.. this doesn't make any sense, or am I missing something here?

**Comment by KasVital** [comment]
![image](https://cloud.githubusercontent.com/assets/15636669/21581504/dbc67194-d044-11e6-9fb2-fd326c90c686.png)
this?

**Comment by KasVital** [comment]
maybe: 13-15 line:
`	  if getglobal(this:GetParent():GetName() .. "Cooldown") then
		if not getglobal(this:GetParent():GetName() .. "Cooldown"):IsShown() then this:Hide() end
	  end`

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/22312b602b26b171030f6bab1748b629d27cb29a

**Comment by KasVital** [comment]
thanks
