### ISSUE TITLE
Bug: Right chat tab disappears after hiding UI

### ISSUE THREAD

**Issue by serveral1** [shagu/pfUI#265]
Technically it disappears after I enable it back again but yeah. 

Only solution right now is to reset the chat from the options menu to get it back up.

**Comment by shagu** [comment]
what the heck?! thanks for reporting

**Comment by shagu** [comment]
I was only able to reproduce it once. Did you found a way to 100% reproduce it?
Because after deleting WTF, I'm not able to get this bug again :(

**Comment by shagu** [comment]
Nvm. After waiting with hidden UI for about 30 seconds, I'm able to reproduce again. Maybe related to the chat fading?

**Comment by shagu** [comment]
I don't think, this is really a pfUI bug. With all addons disabled, I did the following:
- Create a new Chat Tab
- Move the Chat Tab to a seperate window
- Hide the Interface
- Wait 30 seconds
-> The Chat is gone

**Comment by shagu** [comment]
Let's hackfix this one...
https://github.com/tekkub/wow-ui-source/blob/1.12.1/FrameXML/FloatingChatFrame.lua#L63

**Comment by serveral1** [comment]
Yeah, it seems to be an issue with windows not in the "default position" themselves.

I never really played around with separate chat windows prior installing this addon so my first guess was that it had something to do primarily with the addon itself and not the client.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/631915fd6bc4405a04c614b4259adcf092582acf
