### ISSUE TITLE
minimap: pvp queue icon

### ISSUE THREAD

**Issue by Cephel** [shagu/pfUI#266]
Ie. some first party symbol that looks better than the circle that it is currently: ![](http://i.imgur.com/O7pkOF1.png)

**Comment by shagu** [comment]
Yes Sir!

**Comment by Cephel** [comment]
Dank

**Comment by jclock** [comment]
This would also fix the thing where the icon lays on top of the minimap coordinates.

**Comment by Cephel** [comment]
Can this be extended to provide some kind of grid system where you can plug non-first party addon minimap symbols into? It could be as simple as
- Hiding the symbol inside the 3rd party addon
- Adding a new link to pfUI minimap
- Bind it to the chat command of the 3rd party addon (eg. /myaddon minimap show)

**Comment by shagu** [comment]
Vanilla doesn't provide an API for Minimap symbols, so every addon author is using its own method. Grabbing all kind of addons, on which everyone uses other mechanisms, will be hell of work.

**Comment by Cephel** [comment]
Well if you follow the method I posted then it would work without editing the target addons themselves, provided you can hide the minimap symbol yourself (user work) and then provide a "new" symbol that just links to what is basically a glorified chat command. This requires the addon to have a menu accessible via a chat command, so that your symbol can link to that.

For example, let's take SWStats because I know the chat command here by chance:
- The user would hide the SWStats minimap symbol
- The user would go to the pfUI configuration menu and add a new minimap icon. This icon is styled correctly in line with pfUI and provides a selection of icons that the user can select from
- The user inputs the chat command or (lua) scripting command that is executed when the minimap button is pressed (ie. "/swstats gs")
- Pressing the minimap button now executes "/swstats gs" on the chat window, effectively toggling the swstats settings window

The system can be expanded to provide hover-over and right-click functionality to include several of such chat or scripting commands.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/1323a75a0637919c2519506c95b22d94e1a0edb6
