### ISSUE TITLE
icon does not disappear

### ISSUE THREAD

**Issue by KasVital** [shagu/pfUI#267]
icon after death doesn't  disappear 
![pfbug](https://cloud.githubusercontent.com/assets/15636669/21587877/19b8e60a-d0f2-11e6-9892-b0b88069f5dd.jpg)

**Comment by Cruzix** [comment]
I have absolutely no idea what you mean and what we're supposed to be looking at 😕 ❓

**Comment by KasVital** [comment]
check debuff

**Comment by KasVital** [comment]
i have at blizzardframe 1 debuff
but pfui show other

**Comment by shagu** [comment]
Do you run the lastest version? Is it still happening for you?
