### ISSUE TITLE
unitframes: buff/debuff timer

### ISSUE THREAD

**Issue by Minatbar** [shagu/pfUI#27]
The Enemy Unit frame is not displaying timers on the buffs/debuffs at all, only icons.

**Comment by jfastnacht** [comment]
Is that even possible in Vanilla?

**Comment by Minatbar** [comment]
yea I've seen it work in vanilla, on many UIs, for example =
https://www.youtube.com/watch?v=40xcyujsfzM 
start at 6:50 there is numeric timer on every debuff the rogue uses+ if you look closely above enemy nameframes there is cooldown tracker of enemy used cooldowns, super cool element, can't seem to find the addon for it and is not included in modui which the player uses in the video, would be a really good add to your addon if you have the knowledge, i really like this pfUI really ElvUI like :)
regarding the enemybufftimersvanilla, can't change the position or size of the "timer"to match the enemy Unitframe debuff icon, screenshot attached. Not a supercoder so have no idea how to do it and the addon doesnt have config option except directly in .lua file.. /ebtv /enemybufftimers /enemybufftimervanilla dont work in game.
![wowscrnshot_091616_174354](https://cloud.githubusercontent.com/assets/22225981/18589951/921bd524-7c35-11e6-874c-3827ed4135db.jpg)

**Comment by shagu** [comment]
I tagged this as enhancement rather than a bug, because something like this isn't available in vanilla. It would require a spell database containing all durations and a monitoring of the combat log to detect  the spells. This is alot of work, and won't be implemented soon (at least I have no motivation for doing this, right now)

**Comment by Minatbar** [comment]
thank you for fast reply!

**Comment by Voidmenull** [comment]
you can use my EBTV fork for several unitframes till shagu implent this:
https://github.com/Voidmenull/EnemyBuffTimersVanilla

**Comment by Oliveryo** [comment]
Please create this, would be awesome for pvp.

**Comment by nesherman** [comment]
Would love to see this implemented!

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/2666799ad8683dd12cb27c77c5081a7c166435a8
