### ISSUE TITLE
Request: Add server time to "Time" panel mouseover if different.

### ISSUE THREAD

**Issue by jclock** [shagu/pfUI#270]
Additionally, option to change between 12/24 hour clock.

**Comment by Rosexephon** [comment]
Any update on being able to see an AM/PM setting like 3:28pm instead of 15:28?

**Comment by shagu** [comment]
Oh, totally forgot about that. thanks for the reminder :)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/c8e547a46a79df0c850fe8b3d9f20a1462a887b9
