### ISSUE TITLE
Issue: Items in inventory occasionally gray out after clicking CleanUp

### ISSUE THREAD

**Issue by jclock** [shagu/pfUI#272]
Unable to interact with the item until I /rl or zone.

**Comment by shagu** [comment]
@shirsig ?

**Comment by shirsig** [comment]
https://github.com/shirsig/Clean_Up_GUI/issues/1
Seems to be a server bug on nost.

**Comment by shagu** [comment]
Alright, thanks

**Comment by jclock** [comment]
Thanks for the quick response.

**Comment by shirsig** [comment]
Well, the way the sorting works/what makes it so fast is that it takes advantage of the fact that you can do multiple moves in one step as long as they don't involve the same items. Between those steps it is already throttled.  Thottling it during a step would require a rather big change as this is done simply with a loop.

Either way, it has nothing to do with delay, it must be an issue in nost's inventory scripting. And it's most likely not blizzlike as the old retail addon bag sort also used multiple moves per step.

By the way, do you know how to report something on the elysium bugtracker?

**Comment by shagu** [comment]
Thanks for the explanation, that sounds really awesome, good job! :)

> By the way, do you know how to report something on the elysium bugtracker?

No, never did that.

**Comment by jclock** [comment]
@shirsig are you talking about this link:
https://elysium-project.org/bugtracker/issue/add

**Comment by shirsig** [comment]
Thanks, couldn't find a link to that on the tracker.
Anyway, reported it: https://elysium-project.org/bugtracker/issue/966
Please upvote :)

**Comment by jclock** [comment]
No problem upvoted, thanks for all of your help. Also, I especially like:

 CORRECT BEHAVIOR
**They don't.**

 SOURCES
**Doh.**
