### ISSUE TITLE
Right chat frame disappears

### ISSUE THREAD

**Issue by TrueRmia** [shagu/pfUI#273]
Hide the right chat frame. Logout
Login. The right chat frame is gone only the backdrop is visible.

**Comment by shagu** [comment]
A side effect I didn't thought of.

**Comment by muellerj** [comment]
I can also reproduce this (sometimes with just reloading the UI after entering/leaving an instance) and have gotten quite good at creating a new chat window with "Loot & Spam" in the meanwhile :)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/f650f20d5fb9e3c394121665de097ddba24ebf2c
