### ISSUE TITLE
I am a Chinese wow players！

### ISSUE THREAD

**Issue by 123yinlunwei** [shagu/pfUI#275]
I am using the translation software to communicate with you！Dear author! Hello there!I really like the plugins you do!Will not be able to add a DEBUFF surveillance category in the inside? If you can add this feature, I think there will be a lot of people like your creation!I hope you get better! Come on! Come on! Come on!

**Comment by shagu** [comment]
Hi, adding debuff timers is alot of effort in vanilla world of warcraft. Instead, please have a look at https://github.com/Voidmenull/DebuffTimers . It is compatible with pfUI and should do what you requested.

Duplicate: https://github.com/shagu/pfUI/issues/27
