### ISSUE TITLE
Add option to hide chat tap frames

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#276]
Would appreciate if you could add an option to hide chat tap frames, or maybe be able to set color/transparency on them. 

I want this because I like having my entire chat being transparent however its currently not possible to change the chat tap frames transparency which ruins it a bit for me.

![asfsafasfasf](https://cloud.githubusercontent.com/assets/6162744/21612228/a1be1e56-d1d0-11e6-9070-5cf26db0a41c.PNG)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/b100109814596d5386dc56e53cfb7ff432b404d3
