### ISSUE TITLE
Tooltip doesn't fade out/hides

### ISSUE THREAD

**Issue by Fundaris** [shagu/pfUI#28]
Wenn ich mit der Maus über einen Spieler gehe im Raid/Gruppenframe verschwindet der Tooltip nicht nacht X Sekunden sondern bleibt da. 

Schritte:
 - Gruppe aufhaben
 - Mit der Maus über das Gruppenmitglied gehen
 - Die Maus auf eine freie Stelle ziehen **ohne** einen anderen Tooltip zu triggern.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/7722c1b3993960008a20bf71aada55c565852833
