### ISSUE TITLE
Drawing concept for showing elites on health border (Not complete)

### ISSUE THREAD

**Issue by eNtreDefias** [shagu/pfUI#280]
Been learning how to use Krita. Worked for a while with a pretty advanced drawing, fcuked up some angles so after a long battle decided to give it up:P Made a pretty fast sketch after http://i.imgur.com/F4rem4s.jpg 
u suggested.

Here it is: http://imgur.com/a/tKOG8 this is not evn close to complete, its just to show roughly how it will look. I will repaint over with more details highlights etc. I will complete it if u like the concept.

**Comment by shagu** [comment]
Looks good :) But it would be nice if you could use the other issue for that.
https://github.com/shagu/pfUI/issues/157

**Comment by eNtreDefias** [comment]
Sure man, just diddent know if u would see it then:P
