### ISSUE TITLE
Request: Swap action bars

### ISSUE THREAD

**Issue by Evillek** [shagu/pfUI#284]
How could I swap positions of main action bar with bottomleft action bar like:
Main bar - top row
Bottomleft bar - bottom row
Both bars 12x1

**Comment by Cruzix** [comment]
Unlock your frames and change the bars to 12x1 in the settings? 😕 ❓

**Comment by Evillek** [comment]
In default are bars like:
Bottomleft bar - Y Y Y Y Y Y Y Y Y Y Y Y Y
Main bar          - X X X X X X X X X X X X 

but I would like have bars like:
Main bar          - X X X X X X X X X X X X 
Bottomleft bar - Y Y Y Y Y Y Y Y Y Y Y Y Y

Simply, move main action bar from bottom to top row.

**Comment by Cruzix** [comment]
I'm so confused... aren't you answering your own question now? 🤔 

pfUI settings > Unlock > do exactly what both you and me already stated (swap the bars)

**Comment by Evillek** [comment]
Yes, That is Exactly what I needed. Looks like I had older version of your UI and there was not this option, but now it is working. Many thanks ;-)
