### ISSUE TITLE
Battle Shout not shown as buff

### ISSUE THREAD

**Issue by muellerj** [shagu/pfUI#285]
As a responsible warrior, I would like to see if all party members have been Battle-Shouted. I have the respective options enabled in the config:

![config](https://cloud.githubusercontent.com/assets/53246/21640201/853eae7c-d274-11e6-95dd-9cf9ef003088.png)

With no buffs, everything looks fine:

![before_buff](https://cloud.githubusercontent.com/assets/53246/21640251/ed613902-d274-11e6-9b07-8c949773570c.png)

However, after using Battle Shout, the buff should appear in the party and raid interface?

![after_buff](https://cloud.githubusercontent.com/assets/53246/21640270/01b157ac-d275-11e6-8ba7-1c9c24ad7b3b.png)

Thanks for the awesome work so far!

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/76924c367a4a6e1ea4fd0dff3ebceb4ec5f9b59e

**Comment by muellerj** [comment]
Tested and deemed awesome. Thanks very much.
