### ISSUE TITLE
Hunterbar not swapping

### ISSUE THREAD

**Issue by Satoq** [shagu/pfUI#287]
As the title says.
No other addons loaded. Cleaned up my WTF folder.
Shagui's hunterbar works (it automaticaly switches based on range), pfui's doesn't.

I love pfui but I need hunterbar to work ;)

**Comment by Cruzix** [comment]
It works fine for me with the latest version. Make sure you havn't disabled it in both of these places:
Modules > Hunterbars
ActionBar > Range based auto paging (Hunter)

**Comment by Satoq** [comment]
No still not working. Thx for looking into this tho. Keep up the good work!

**Comment by Cruzix** [comment]
Have you tried disabling all addons but pfUI and see if the issue still occur?, I really cannot reproduce this - been trying for a while now. It just works perfectly for me.

Also make sure u have the latest version.

**Comment by shagu** [comment]
Please make sure you have the skills "Wing Clip" and "Arcane Shot" on any actionbar.

**Comment by Rageguy1** [comment]
Do you mean i need to have BOTH on the action bar? i have a lvl 6 hunter on 1 server and a lvl 19 hunter on another. and the lvl 19 hunter has no issiues with swapping bars but the newly created hunter will not swap bars correctly

**Comment by shagu** [comment]
Yes you'll need to have both skills on any of your actionbars. Doesn't matter which one.
