### ISSUE TITLE
Add option for sticky chat

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#289]
Add option for "sticky chat"

This is a feature that most chat addons has (e.g. Prat and ChatMod etc), what this feature does is to remember which channel you wrote in last time you wrote.
So if I type something in /p (party) - next time I press Enter to type something it will already be typing in /p without me having to make the command for it.

It should remember all channels even whispers.

**Comment by shagu** [comment]
```lua
-- Remember last channel
ChatTypeInfo.WHISPER.sticky = 1
ChatTypeInfo.OFFICER.sticky = 1
ChatTypeInfo.RAID_WARNING.sticky = 1
ChatTypeInfo.CHANNEL.sticky = 1
...
```

**Comment by Cruzix** [comment]
My bad

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/1e4ff722e53777b80995191cacf05e3342cc19a3
