### ISSUE TITLE
Gatherer Minimap (Tooltips) broken

### ISSUE THREAD

**Issue by Fundaris** [shagu/pfUI#29]
Gatherer zeigt auf der Minimap normalerweise Infos über den Spot an und allgemein sind die Gatherer spots um x-1, y+1 verschoben.

![screen4](https://cloud.githubusercontent.com/assets/3646843/18635789/86c49cc6-7e86-11e6-970f-09b8792d7bd2.jpg)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/0ae104c3d9d84e936c19f94a3dc6a450f6109e89
