### ISSUE TITLE
Make whispers say "W to" instead of just "W" when you're typing to somebody

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#290]
Make whispers say "W to" instead of just "W" when you're typing to somebody as it easily can get confusing as to what message you've sent and which one you've gotten.

Here's a screenshot of me typing to myself ( 😭 ) to show my point. 
![whispers](https://cloud.githubusercontent.com/assets/6162744/21683813/4885e8dc-d35b-11e6-8018-ad2911d3735b.PNG)
You could also go even further and make incoming whispers say "W from"

**Comment by shagu** [comment]
This is why there was a different color by default.. grml.. https://github.com/shagu/pfUI/issues/234

**Comment by Cruzix** [comment]
But... but... Its confusing to have different colors for the same channel 🤕

Thanks for looking into it though :)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/562bf1b8098f7295fef9d6c6a1bd48ac64d529d0
