### ISSUE TITLE
chat: new message flash in the chat tap is slightly off

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#291]
New message flash in the chat tap is slightly off
![off set](https://cloud.githubusercontent.com/assets/6162744/21683957/edb44010-d35b-11e6-8eaa-2b916f1b02fd.PNG)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/e3b19818d498ea121a210fe13aa2f8245e60f057

**Comment by shagu** [comment]
![1](https://media.discordapp.net/attachments/246573943056629760/354370543983525889/image.png)
