### ISSUE TITLE
Missing vertical actionbar [TwoRight]

### ISSUE THREAD

**Issue by MMARK88** [shagu/pfUI#292]
Hi,

First off I want to say, what an amazing ui you have made here, I really love it!

I was messing a bit around with it to tweak it to my likes, and suddenly the TwoRight actionbar went missing, I might have shift or alt/ctrl clicked it and then it dissapeared when I stopped dragging it.

My question is, can I reset only this one actionbar or do I have to reset every position/rescale I've done?, I have been looking around the options and this site, with no luck, I dont hope this will be a double post.

![wowscrnshot_010517_225959](https://cloud.githubusercontent.com/assets/24945817/21699380/b8e28064-d39b-11e6-9516-dc3ce55723cb.jpg)
![wowscrnshot_010517_230028](https://cloud.githubusercontent.com/assets/24945817/21699381/baa12a18-d39b-11e6-8c17-2ccfdf6d991a.jpg)

**Comment by Road-block** [comment]
You can try running this script in-game.
```lua
/run pfUI_config["position"]["pfBarTwoRight"]["ypos"]=-250
/run pfUI_config["position"]["pfBarTwoRight"]["xpos"]=250
/run pfUI_config["position"]["pfBarTwoRight"]["scale"]=1
/rl
```
This should put it somewhere in your screen so you can move it where you want it with next Unlock.

**Comment by MMARK88** [comment]
@Road-block 
It worked, thanks alot :>
And yes 2nd bar right was set to on in blizz interface.
