### ISSUE TITLE
player: show druid mana in forms

### ISSUE THREAD

**Issue by DKXAM** [shagu/pfUI#294]
Would be great to have an option to see druid mana while in form, it does not need to be a 100% accurate. 

http://www.vanilla-addons.com/dls/druidbar/ as an example of how this is done

**Comment by Cruzix** [comment]
I'm fairly sure Luna UnitFrames also has this feature in case you're looking for further inspiration of how to do this. I can imagine this being a very valuable feature for Druids! 👍

**Comment by Reubentrapdoor** [comment]
LunaUnitFrames has a library for this feature here: https://github.com/Aviana/LunaUnitFrames/tree/master/libs/DruidManaLib-1.0

Someone else has already used it in a standalone addon with success here:
https://github.com/gashole/DruidManaBar

**Comment by Kalty** [comment]
Shagu, is there any hope it could be in some future version?

**Comment by Razorwynd** [comment]
I can not wait for the day when I can use pfUI frames with druid mana. I am getting tired of the slightly less aesthetic luna frames. The Druidbar, DruidManaBar, and StatusBar addons just do not look great with pfUI frames

**Comment by jaystabins** [comment]
Would also like to see this implemented!
