### ISSUE TITLE
Disenchanting (and probably other auto-loot)

### ISSUE THREAD

**Issue by Road-block** [shagu/pfUI#299]
Breaks the lootframe.  
If you disenchant something, the dust gets auto-looted but the lootframe stays up indefinitely.  
It also breaks the bags.  
The disenchanted item is still shown and attempting to interact with it posts an "item is already looted" message in errorframe and bugs the lootframe again.  
It is not resolved until logging out of the character and logging back in (reloadui doesn't solve it).  
I'm thinking that this might actually be a server issue (with Elysium where I observed this behavior)

**Comment by Road-block** [comment]
Temporary workaround.  
**Escaping** the open lootframe at the end of disenchanting instead of clicking the dust, actually loots the dust and closes the lootframe, as well leaves the bags in working order.

**Comment by shagu** [comment]
I can't reproduce this on my local CMaNGOS server. 
As I don't have an enchanter on Elysium, I'm not able to fix this.

**Comment by shagu** [comment]
Another video from elysium:
https://youtu.be/Qwe0yHaA6m4

All changes made to loot.lua were `message(GetNumLootItems())` on line 25, for debugging reasons.

**Comment by Road-block** [comment]
This was after all an unfortunate coincidence.  
It happens with other container-like items (like clams) but it's not a problem with pfUI.  
Something happens occasionally with Clean_Up the companion addon that leaves bag slots in a **locked** state after a sort.  
When that happens all sorts of strange things happen with loot until you logout and back in to clear the locked status of those items.

**Comment by shirsig** [comment]
https://elysium-project.org/bugtracker/issue/966
