### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by Fluffykable** [shagu/pfUI#302]
Hello,i have issues to change my Fonts in game.
I cant change dmg Fonts.(dont like it)
I was tried copy past to my folder Fonts what i`m want.But its still show PfUI fonts,cant even add new font at Pfui folder.They not even show up for me in game pfui menu(only standart Pfui fonts.)
sorry about my English

**Comment by shagu** [comment]
Change the font requires a game restart. A simple Reload is not enough.
If you want to add your own fonts, you'll have to replace the existing ones with yours or add the new ones to the fontlist in gui.lua.

**Comment by Fluffykable** [comment]
Ty!
