### ISSUE TITLE
After reloadui pet action frame disappears

### ISSUE THREAD

**Issue by BoneLord** [shagu/pfUI#303]
I play warlock and have active pet. After I changing something and reloadui pet action frame bar disappears.
If I summon pet manually pet action bar appears.
Shagu thanks for hard work on this amazing ui.

**Comment by shagu** [comment]
This is not pfUI related and I can't to anything against it.
https://www.youtube.com/watch?v=cMWrctFCnUQ

**Comment by BoneLord** [comment]
Okey, thanks for fast answer.

**Comment by crumdidlyumshis** [comment]
@BoneLord sadly it's a server side issue

**Comment by crumdidlyumshis** [comment]
Just wanted to leave this here in regards to the pet action bar: https://forum.elysium-project.org/topic/34789-development-update-25012017/

_"Pet's action bar will return after reloading user interface."_
