### ISSUE TITLE
Show max HP in addition to current HP of a target

### ISSUE THREAD

**Issue by everytimer** [shagu/pfUI#305]
This is useful in many situations where you don't want to know just the current HP of your target but also the maximum health. Several temporal buffs / debuffs (warrior last stand / life giving gem among many others) affect maximum HP instead of actual HP.

Example of format: hp/maxHp - hp%

http://prntscr.com/dswdx9

**Comment by Rachdingue** [comment]
How do you see enemies HP in numbers? I can mange only to check for %

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/issues/40
