### ISSUE TITLE
Default font for unaltered frames

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#306]
Would it be possible to retain the default font for the unaltered blizzard frames? (mailbox, questlog, AH ...)
The pfUI font doesn't look very nice there I think.

**Comment by shagu** [comment]
No, because many fonts that are exchanged must be already altered before SAVED_VARIABLES are loaded. So it is impossible for me to add an option for that. You'll have to do it on your own, have a look at env/fonts.lua it should be quite self explaining.
