### ISSUE TITLE
[Question] Buffs Bars

### ISSUE THREAD

**Issue by Rachdingue** [shagu/pfUI#307]
Hello everyone. I'm playing paladin and every buff I do to myself or allies it shows it the timer in bars over my unitframe. The problem is that I cannot find the options for it to move those bars as it goes bottom to my nameplate and it's ugly as fuck.

Also I don't want pfui to show me a 5 min bar for my blessing of might. I feel stupid for not finding this lol
![sin titulo](https://cloud.githubusercontent.com/assets/24988815/21750183/7b4d4cf2-d5ad-11e6-9325-c3343131c6d8.png)

**Comment by shagu** [comment]
pfUI does not create these bars.
