### ISSUE TITLE
Hovering over your actual bags won't make their tooltip appear

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#309]
Hovering over your **actual bags** won't make their tooltip appear, so you're not able to see what kind of bag slots/quiver you're using.

**Comment by saysmaker** [comment]
I also experience this. This would be useful when you want to quickly know how many slots the bag contains without counting, or the % boost from quivers/ammo pouches.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/cec258ed1609f6b9a8c13cc84316c1ee43068bf6
