### ISSUE TITLE
tooltip: place above bag when opened

### ISSUE THREAD

**Issue by Crumdidlyumshis** [shagu/pfUI#311]
Would it be possible to add an option to the tooltip menu so that when your tooltip is either above chat frame or on the bottom of chat frame, when bag is shown, place tooltip above bag frame, else, back to location set. Same thing elvui does on retail. Thanks!

**Comment by athei** [comment]
Yes this would be super cool. I place it above the chat frame but when the bag is open the tooltip will collude the bag.

**Comment by shagu** [comment]
Oh, that's already done. Just forgot to close this.
