### ISSUE TITLE
Pet bar disappearing on /reloadui

### ISSUE THREAD

**Issue by nemods** [shagu/pfUI#313]
Hey
The warlock pet bar disappears on /reloadui.
Only way to get it back appears to be re-logging or re-summon pet.

**Comment by shagu** [comment]
This is not pfUI related and I can't to anything against it.
https://www.youtube.com/watch?v=cMWrctFCnUQ

> https://github.com/shagu/pfUI/issues/303

**Comment by nemods** [comment]
Thanks for the quick response, and to bad.
Great work on pfUI and the databased, really appreciate the effort you have and are putting into it.
