### ISSUE TITLE
timer on buffs?

### ISSUE THREAD

**Issue by l453rl453r** [shagu/pfUI#315]
are there timers for the buff icons? i cant seem to find them.

**Comment by Fluffykable** [comment]
Yes,on enemy plates and target-enemy frames.No cooldowns debuff\buff.
Was trying put cooldowns addon or enemybufftimer.This is not show up at Pfui.But work at standarte ui or Mod ui(addon pack)

**Comment by l453rl453r** [comment]
Nah i was looking for cooldowns on my buffs in the top right corner next to the minimap, not on the nameplates.

**Comment by shagu** [comment]
![1](http://i.imgur.com/Vp44C69.jpg)
