### ISSUE TITLE
player: add resting icon

### ISSUE THREAD

**Issue by eNtreDefias** [shagu/pfUI#317]
Pretty much title:P maybe in a corner or something.

**Comment by Cruzix** [comment]
Is this really needed though?, I personally wouldn't wanna enable such feature. 

You already know when you're in a resting area without this, any big cities or at a Inn Master.

**Comment by Fluffykable** [comment]
well its small thing.But its mast be!

**Comment by eNtreDefias** [comment]
Well its not urgent, but its nice to be sure when ur in a rested area.

**Comment by Road-block** [comment]
I had asked shagu about this some time ago. He has put that information on the experience bar tooltip.  
There will be a `status: resting` line on it if you are in such an area.
