### ISSUE TITLE
Bug with healthbar!

### ISSUE THREAD

**Issue by eNtreDefias** [shagu/pfUI#318]
https://www.youtube.com/watch?v=sf4rTule4fs&feature=youtu.be
Pretty sure it has something to do with changing the health color? It does not show the health going down either. I do not have the error message since i just used a alrdy complete profile. It does not work when relogging or re downloading.

**Comment by shagu** [comment]
wtf

**Comment by eNtreDefias** [comment]
Il see if i can reproduce it with a fresh wow client:p

**Comment by eNtreDefias** [comment]
Found it i think: https://www.youtube.com/watch?v=4oodF0unRFc It blinks much more on the video then in game for some reason. But it do blink sometimes ingame aswell, the main issue is the health going darker and not moving when loosing hp.

**Comment by eNtreDefias** [comment]
Also got this error when changing player health width: http://imgur.com/a/C2Qhe

**Comment by shagu** [comment]
Looks like you're having wrong values in "Animation Speed".

**Comment by eNtreDefias** [comment]
Ah, tryed to set it to 0.1 before to see if that was the problem. Seems like it works fine if i dont use any 0.X, and just set it to 1. Sorry for the trouble should have figured that out, altough there are some other options where u use 0.X and not whole numbers.
