### ISSUE TITLE
The first Pet-Button only works once

### ISSUE THREAD

**Issue by TrueRmia** [shagu/pfUI#32]
Class: Hunter
Attack an enemy by **clicking** the first PetButton(Attack) - it works
Try again - it didn't work.
Dismiss Pet & Call Pet,
Try again - it works again one time

Attacking by hotkey always works.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/b826b63ca728aa15df6e0423c9fe55cc860f229f
