### ISSUE TITLE
castbar: add aimed shot

### ISSUE THREAD

**Issue by Eighti** [shagu/pfUI#320]
Hi!
ShaguUI had a castbar showing the Aimed Shot.
I liked it a lot, would be nice to have it here too.

**Comment by TrueRmia** [comment]
#244

**Comment by Cruzix** [comment]
Not sure why this got marked as duplicate tbh - https://github.com/shagu/pfUI/issues/244 is a request for auto attack bar, this request is to implement aimed shot support.

Anyways, I crave this feature. Currently if you use aimed shot it'll show the default cast bar but it will never finish so once you used aimed shot you'll be watching the standard cast bar until you reload or relog which is extremely tedious xD

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/51974f23c0401a8123486c7b95498c181313fec2

**Comment by TrueRmia** [comment]
Shame on me :(

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/51974f23c0401a8123486c7b95498c181313fec2
