### ISSUE TITLE
Quest tracking/notification on middle of the screen

### ISSUE THREAD

**Issue by metspo** [shagu/pfUI#321]
Pfui disables blizzards normal quest notification from the middle of the screen.
Example if you kill a kobold 1/10 or a loot a sausage 4/10

**Comment by metspo** [comment]
Seems like that "Disable UI errors" removes this functionality also.

**Comment by Cruzix** [comment]
It's not "also" the  Disable UI errors feature that does it, it's only that feature.

But yeah, it would be nice if you could find a solution for this @shagu

**Comment by shagu** [comment]
I'm not going to start parsing all messages and add a checkbox for every kind of message that could ever appear on the UIErrorsFrame.
