### ISSUE TITLE
Unequipable items aren't shown in red text.

### ISSUE THREAD

**Issue by leifolini** [shagu/pfUI#322]
As a mage if I have an item that is leather/mail/etc. that I can't use, the text is not red to indicate that it's not for me.

**Comment by Cruzix** [comment]
I've noticed the same, the item tooltip dosn't say if the item can be equipped on your character or not.

**Comment by shagu** [comment]
Does it on default UI?

**Comment by Cruzix** [comment]
Yes

**Comment by Cruzix** [comment]
![image](https://cloud.githubusercontent.com/assets/6162744/21778051/fff6c06a-d6a1-11e6-8f97-1d513545a178.png)
That's how it's supposed to look. The dagger is red text because it can't be equipped.

**Comment by shagu** [comment]
![1](http://i.imgur.com/IReB4Xd.jpg)
![2](http://i.imgur.com/MQDdkpL.jpg)

**Comment by Cruzix** [comment]
Hmm, might be a setting that is causing the issue then. I'm not online atm and won't be until they fix their retarded queues so I can't provide an ingame screenshot. Maybe @leifolini can, or somebody else who has the same issue?

**Comment by leifolini** [comment]
Playing as a mage, I can't equip mail or leather for example. Here are two screenshots that show leather and mail as white. But the level requirement is still red when it is above my level, as shown in screenshot 3. I just downloaded the latest version as well. Playing on the Elysium project / Nostalrius server.

![111](https://cloud.githubusercontent.com/assets/25014157/21779209/d2f25cfa-d6a6-11e6-817a-b9954352a7b9.png)
![222](https://cloud.githubusercontent.com/assets/25014157/21779208/d2f1586e-d6a6-11e6-84f8-1cf377cefebf.png)
![333](https://cloud.githubusercontent.com/assets/25014157/21779210/d2f320ea-d6a6-11e6-80d3-d020bd2efaf9.png)

**Comment by leifolini** [comment]
I am sorry. This seems to be a problem with Elysium perhaps. I disabled the pfUI and it still shows as white with the default as shown here.
![555](https://cloud.githubusercontent.com/assets/25014157/21779377/b1572160-d6a7-11e6-99dd-1b5350ac55e5.png)
