### ISSUE TITLE
portrait model bug

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#324]
sometimes the model isn't ready or something when the unit frames are loaded so the model/portrait ends up all white/textureless and weird.

**Comment by everytimer** [comment]
Yes, I have experienced the same, I think after some time or zoning / targeting / untargeting it's solved. I remember similar stuff occurring in retail so don't sure if there can be a real solution to this.

**Comment by shirsig** [comment]
Maybe it can be reloaded after every animation cycle. Guess loading with delay wouldn't be a reliable solution.

**Comment by shagu** [comment]
I will find a way.

**Comment by shagu** [comment]
I cannot reproduce it. Are you sure this haven't been already fixed by https://github.com/shagu/pfUI/commit/ac3d8b94a5321547a760dcfaa8d2098b17491dab ?
