### ISSUE TITLE
class color chat account wide for all realms

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#325]
the class color cache should discriminate between realm (also noticed sometimes the class color doesn't work for a single message)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/4a89c69b951d490b46a86090e26fb551af8bbc6e

**Comment by shirsig** [comment]
The second thing still happens (sometimes no class color for an individual message), even though the same name is colored in another message. The color cache could be improved by making it account wide again and explicitly associating it with realm names so that it can be shared between characters.

**Comment by shagu** [comment]
I wasn't able to reproduce it. Could you please give me more insight in how to reproduce it?
Regarding the player cache, there are several other things which are more important to improve right now.

**Comment by shirsig** [comment]
![](http://i.imgur.com/kletRI2.png)
