### ISSUE TITLE
Cant see the total HP of other players 

### ISSUE THREAD

**Issue by JamesCutter** [shagu/pfUI#326]
all I see is  > Lvl - Name - 100 
cant find an option to change that maybe latest version?

**Comment by Road-block** [comment]
Do you have an addon like MobHealth?  
Enemy health is not reported in vanilla (except Kronos realms as I understand but that's not blizz-like, it's something custom for that realm)

**Comment by SarekCDL** [comment]
You cannot see exact health of a player if he is not in your group.

It's blizzlike as long as I remember
