### ISSUE TITLE
Interrupts don't show up as successful on enemy castbars

### ISSUE THREAD

**Issue by t3hWheez** [shagu/pfUI#327]
If you interrupt a mob the cast bar will continue till the end like you didn't actually interrupt it.

No idea if its possible to show the cast being interrupted but figured we could try.

**Comment by Road-block** [comment]
This needs combat log parsing and quite a bit of guesswork.  
DPS meters and full blown castbar addons make the effort so it somewhat works for a few of them but it's a lot of code.  
There is no actual offensive interrupt event / combatlog line in vanilla so that complicates things.

**Comment by Xyr2** [comment]
+1

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/d43fdc7a3dacb2ac7d7a506f793859af65fe09b2

**Comment by moootv** [comment]
Casts are still not stopping if they get interupted.
Any idea?
