### ISSUE TITLE
Combat Log can not be hidden

### ISSUE THREAD

**Issue by TrueRmia** [shagu/pfUI#33]
Switch to combat log.
Try to hide.
Just the "backdrop"? will be hidden.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/4e7ea17666513359b02aa4c256ff4274b15f3ccf

**Comment by TrueRmia** [comment]
Now the "Loot & Spam" window can not be hidden, only the backdrop will be hidden.

**Comment by shagu** [comment]
outch, sorry. will fix this soon

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/55db423606c5886db281c7818d2378f77cbd0a3e
