### ISSUE TITLE
Logic error in skin.lua

### ISSUE THREAD

**Issue by Road-block** [shagu/pfUI#331]
While investigating some 3rd party issues (EQCompare and similar addons tooltips) I came upon these 2 lines in skin.lua
[skin.lua:70](https://github.com/shagu/pfUI/blob/10fdf161984b4b4ec99f4c6265b8663a7a0a9521/modules/skin.lua#L70) and [skin.lua:77](https://github.com/shagu/pfUI/blob/10fdf161984b4b4ec99f4c6265b8663a7a0a9521/modules/skin.lua#L77)
Both suffer the same problem.  
```lua
if not d or d == 0 then d = (border*2)+d+1 end
```
will give an "attempt to perform arithmetic with nil" if the `if not d` part is ever true.
Easy fix is to make it
```lua
if not d or d == 0 then d = (border*2)+1 end
```

PS. _It didn't solve the custom shopping tooltip problems I had, that requires further modifications to pfUI (or EQCompare... but that's a dead addon) but that line would error regardless third-party addons if **d** was ever nil._

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/c10dec2077325dbe91a67955f40bc8685b983cc0
