### ISSUE TITLE
compare tooltip stuck on screen

### ISSUE THREAD

**Issue by Wassaaa** [shagu/pfUI#333]
so yea, seems like the compare tooltip is getting stuck on screen after shift comparing any item in bag. I only seem to be able to fix it with a reload.

![stuck](https://cloud.githubusercontent.com/assets/7949652/21879263/1e6eca88-d8a0-11e6-8727-fd0910f38e26.png)

**Comment by Junglaa** [comment]
I've also had this bug for the last 3 builds, And the same thing happens for me, Shift anything and you will have that item you compared stuck on your screen (and it moves too) all the time until you reload,

**Comment by Cruzix** [comment]
I don't have this issue anymore, and as far as I can remember it was an issue with Questie. So update your Questie and report back if the problem still occurs.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/issues/226

**Comment by Wassaaa** [comment]
yes, thank you, updating questie fixed the problem
