### ISSUE TITLE
Hiding buffs / debuffs?

### ISSUE THREAD

**Issue by gamer4eg** [shagu/pfUI#334]
Is it possible to add a setting to hide certain buffs / debuffs (on the list) and display only the setting of your debuffs?

For example, I want to see only their debuffs (enlarged icons) + some other players debuffs.
Or just your own.
Or, but his first on the list and with increased icon.

**Comment by shagu** [comment]
I don't really get your point. What buffs exactly are you talking about?
Player? Target? Default BuffFrame?

**Comment by gamer4eg** [comment]
I am sorry - very bad know English (and Google translator seems to be even worse than I xD)
player, target
The Legion of credit default interface is a function to hide all debuffs on target but yours (but it lacks a possibly setting)

**Comment by shagu** [comment]
You only want to show debuffs on your target that has been applied by you?

**Comment by gamer4eg** [comment]
Yes. But it would be nice to add a possibility to hide a specific buff / debuff.

**Comment by gamer4eg** [comment]
И еще раз прошу прощения за гугл переводчик - стыдно)

**Comment by shagu** [comment]
Only displaying debuffs that have been applied by you, would be alot of effort and I'm not going to do this. Sorry.

**Comment by gamer4eg** [comment]
It's okay, you're already done so wonderful UI =)
