### ISSUE TITLE
Problems with pfUI

### ISSUE THREAD

**Issue by Syturio** [shagu/pfUI#335]
Are you aware this addon reduces players FPS by a lot?

I made a test:
- With pfUI = 270'ish FPS.
- No pfUI = 190'ish FPS.

------

Also, World Map frame size is way to small, it doesnt scale properly.
I cant move buffs / castbar.
I cant use [Whisper] instead of [W] on Chat,
It still lacks many features and customizations.

**Comment by shagu** [comment]
Yes.
