### ISSUE TITLE
About the elite dragon on healthframe

### ISSUE THREAD

**Issue by eNtreDefias** [shagu/pfUI#336]
Hey, asked u some questions on the #157 but im not sure that u saw it since its been 2 days. Sorry to bother u fi u saw it.

**Comment by Cruzix** [comment]
You don't need to make another issue report just to say this. That's just an annoyance, bump it in the comments on your original issue report if you really feel like its needed.

**Comment by shagu** [comment]
Stop that! I did read your message, but I am not able to instantly answer everyone.

**Comment by eNtreDefias** [comment]
Fuck me sorry man, i diddent know...
