### ISSUE TITLE
target hide -> unit popup close

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#338]
Like with the default unit frames the unit popup should be closed when the target frame is hidden:
https://github.com/AtheneGenesis/Vanilla_enUS_FrameXML/blob/master/TargetFrame.lua#L114-L117

**Comment by shagu** [comment]
thanks, will do

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/8f6a8c9ba6b0573e32f8732f79e1d59a68dbd1fe
