### ISSUE TITLE
disabling loot&spam is broken

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#339]
when disabled it's shown on top of the other chat frame

**Comment by Sascal** [comment]
I didn't want to create a duplicate so i will write it here: disabling the loot and spam option will make the right panel autmatically hide everytime you reload the game/ui. I guess it wasnt intended to be like that.

**Comment by shagu** [comment]
It is intended like this, because otherwise people would create issues like "chat background is visible, even without a chat". I'm going to save the toggle state and restore it on reload.

**Comment by shagu** [comment]
> when disabled it's shown on top of the other chat frame

Could you please provide the steps to reproduce it? I tried in several ways but wasn't able to.
