### ISSUE TITLE
Auto-switch between actionbar's depending on the target's range

### ISSUE THREAD

**Issue by TrueRmia** [shagu/pfUI#34]
Would be a nice feature :)
Should behave like the Bartender2-Hunterbars module.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/dc3c89b3adac44f56aef420e137dbce6a52c00ad

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/a7a7ac48f467f61ba9f4146b0c4b7aa0219b40c9

**Comment by TrueRmia** [comment]
Using Raptor Strike does not work as intended, because the spell has no range limitation. Using Wing Clip instead works.
I also added UnitExists("target") to line 37 so it look's like : 
` if IsActionInRange(pfUI.hunterbar.melee) == 1 and IsActionInRange(pfUI.hunterbar.ranged) == 0 and UnitExists("target") == 1 then`
Because the bar does not swap bag to ranged then the target gets killed in melee range.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/a78e5082626db52bf2bcb60aa68da1e69582f137
