### ISSUE TITLE
Wrong portraits in party frames after group member changes

### ISSUE THREAD

**Issue by Cephel** [shagu/pfUI#341]
I can not replicate this, but here is a screenshot of this happening:

![](http://i.imgur.com/2Lqzdgv.png)

Note the target I have selected

**Comment by Cephel** [comment]
Through further experimentation it seems to happen when someone leaves the party and the portrait seems to "stick" in the position it was in, whereas the name list is collapsed.

Example:
- Party member 1 | Orc portrait
- Party member 2 | Tauren portrait
- Party member 3 | Troll portrait

If member 1 leaves, this then seems to become:
- Party member 2 | Orc portrait
- Party member 3 | Tauren portrait

**Comment by shagu** [comment]
It's not the wrong gender, it's a wrong portrait. Have a look at the shoulders ;)

**Comment by Cephel** [comment]
> It's not the wrong gender, it's a wrong portrait. Have a look at the shoulders ;)

Did you just assume my gender? 😂 👌 

Also, yea as I said it seems to be that it just assumes the portrait of the guy who was in that party "slot" (member 1-4) before.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/5c896ff567efdba7d6f53adbedecaa2de6e4ed5a
