### ISSUE TITLE
Item Comparisons keep poping up everywhere

### ISSUE THREAD

**Issue by Xenimus** [shagu/pfUI#343]
After clicking shift on an item in my character screen to compare it that item will just show up next to buffs, items in my bag, nameplates and other things its not supposed to. I have attached a picture as an example, of whats happening.
![wowscrnshot_011317_160428](https://cloud.githubusercontent.com/assets/8617201/21945741/07fa31f0-d9ab-11e6-83cf-cca857327ae4.png)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/issues/226

**Comment by DustinHendrickson** [comment]
This bug is persisting after downloading the latest 1.5 version.
