### ISSUE TITLE
Suggestion for group loot option

### ISSUE THREAD

**Issue by Nordrassil** [shagu/pfUI#346]
Hiya!

Personally, I do not like the group loot frames that comes with this package, so I've disabled it and am using SmartLoot instead :  http://www.wow-one.com/forum/topic/64565-new-addon-smartloot-unobtrusive-group-loot-frames/

Only thing is that addon's proven difficult to skin/change the appearance of, and it doesnt match the look of your UI very well.

Might I suggest integrating Smartloot into your default UI instead of the group loot you use now?

**Comment by shagu** [comment]
README.md:
>  It is completely written from scratch without any inclusion of 3rd party addons or libraries. This is not an addon-pack like ShaguUI which means that no external Addons will be included.
