### ISSUE TITLE
[Help] Embbed KTM and DPSMate

### ISSUE THREAD

**Issue by Rachdingue** [shagu/pfUI#347]
My DPSMate addon is already embed correctly but I want to do also on KTM and have the 2 addons in the right. I've seen pics around but I don't find how to do so

**Comment by TrueRmia** [comment]
#277

**Comment by Rachdingue** [comment]
I feel stupid cause those links (already seen before) doesn't tell me how. DPSMate is embed automatically but not ktm

**Comment by Cruzix** [comment]
pfUI can't embed KTM currently. Its a work in progress though. 

Move it manually if you want it in there together with DPSMate.
