### ISSUE TITLE
There's just one action bar appearing 

### ISSUE THREAD

**Issue by Synx3d** [shagu/pfUI#348]
I'd like to know how to add the other actions bars on my game, I can't find the left/right bottom bar and the vertical one, even when I unlock, just the main appear.

Edit: Its just like the screenshot from the page: http://shagu.org/pfUI/mmobase/screen.jpg
but everywhere I see the pfUI, everybody is with all the others bars.
I'm a new player at wow, and my english is not that good, so sorry anything.

**Comment by Cruzix** [comment]
Press Escape > Interface > Advanced Settings > then tick all the boxes for the action bars you want to have shown

**Comment by Synx3d** [comment]
Well, I had done this, and it wasn't work, but I was trying to fix and I figured that was something at the WTF paste was causing the problem, so, its fixed, sorry for my neewbies...
