### ISSUE TITLE
May you please share a screenshot of your addons folder>?

### ISSUE THREAD

**Issue by Maggew** [shagu/pfUI#349]
Here is a picture of mine:

![image](https://cloud.githubusercontent.com/assets/1291364/21958359/aa071074-da7a-11e6-8b2f-6f1e908b9953.png)

Just let me know if you want me to share any of the addons.

**Comment by shagu** [comment]
what?

**Comment by Cruzix** [comment]
what the... ❓ ❓ ❓

**Comment by Maggew** [comment]
I was unable to find a contact form on the site, and was just curious if you would be so kind to share a screenshot of your addons folder shagu.

Hope all is well,

**Comment by crumdidlyumshis** [comment]
@Maggew What about the screenshot of his addons do you need information for? I am not sure how this relates to anything other than curiosity?

**Comment by shagu** [comment]
```
AtlasLoot
Cartographer
DebuffTimers
DPSMate
KLHThreatMeter
MobHealth
pfUI
'!Questie'
Scratch
ShaguDB
ShaguQuest
ShaguScore
WIM
```

**Comment by Maggew** [comment]
I don't **need** anything brothaman. It just related to me wanting to be like shagu.

Shagu, delivers quality and just seems _to do things right_. My request to learn from him... is just that. I want to be like shagu when I game, as I'm sure many others do. 

The mighty shagu, lol, leads by example and delivers the kind of quality I don't often see across the web...

**Comment by crumdidlyumshis** [comment]
dafuq

![629](https://cloud.githubusercontent.com/assets/7307335/21965389/71cc99a4-db24-11e6-934e-87ef0b1a7feb.gif)

**Comment by Maggew** [comment]
I know right? Ask for a screenshot of someones addon folder, and get trolled by some plebs. 

Wishing you good health, wealth and wisdom in 2017 - happy new year from me to you! GLHF

p.s. - that GIF is crazy, creepy and scary.

**Comment by shagu** [comment]
I'm really glad you like my work. But to be honest, I have to admit that I'm not a pro-gamer. 
All my passion is programming, not for raiding and such. 

Back to topic: As I know have a screenshot of your addon folders, please let me give some feedback:
- `ShaguPlates` is not required if you're using `pfUI`. Using both will dramatically decrease your performance, also the pfUI nameplates are more up to date

- `WHDB` is incompatible with `ShaguQuest`, you should choose one. `ShaguDB` can be used without `ShaguQuest` if you want to stick to `WHDB`.

- If you're using the pfUI UnitFrames, the `MobHealth3_Blizzardframes` can be disabled, 

Cheers,
Shagu
