### ISSUE TITLE
Chat links are broken - Picture inside

### ISSUE THREAD

**Issue by SneakySphynx** [shagu/pfUI#350]
Heya, love the addon/rework job!

Have been sitting and adjusting everything to my taste.
Have to manually change the chat font sizes everytime i log in still, but that's prat's fault i think. :)

But i have a massive problem check picture here: [http://image.prntscr.com/image/9e6f16dc760b485683b09b0be5c49850.png](url)

Everyone who link something in chat, except if they link more than one item. Displays the users name instead of an item.

Example nr 2, if they link more than 1 item it works:
[http://image.prntscr.com/image/08f59ac45ad84dae96760c7cd7e007c0.png](url)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/issues/68

**Comment by bilboswagens** [comment]
Confused - I'm having this same issue and used the search function and found no answers to this.
