### ISSUE TITLE
Bag slots size not set correctly if chat module is disabled

### ISSUE THREAD

**Issue by MarkKoz** [shagu/pfUI#352]
Note: No other AddOns enabled, just pfUI.

This causes slots to spill out of the main bag frame, both for the bank and backpack. For me, an entire column is outside of the frame, but this probably will vary depending on resolution and/or UI scale.

The bag slots seem to be directly based on the value of `pfUI.bag.button_size`. When I query these values in game with the chat module enabled and disabled, different results are returned. `pfUI.bag.button_size` is based on the width on the bag frame, it's effective scale, and the border size. `pfUI.bag.right:GetWidth()` returns different values in-game depending on if the chat module in enabled or disabled (the scale and border size don't change.) 

When the chat module is disabled, the width is ≈380, as it's supposed to be per the defaults. When enabled, it's ≈342 but running `pfUI.chat.right:GetWidth()` still returns 380. Strangely though, measuring the pixels on my screen, the bag frame's width is no different. 

<del>Maybe somewhere `SetWidth()` is being called on the bag frames but there's too much code to look through; a search on the entire AddOn for `pfUI.bag.right:SetWidth` only returns one result, so if anything it'd probably be getting the frame through a function parameter or something.</del> Actually, this wouldn't make sense since from my measurements the visible width was actually still the same.

For myself, I did a temporary fix:
 ```
-- pfUI.bag.button_size = (frame:GetWidth() / frame:GetEffectiveScale() - 2*default_border - 9*default_border*3)/ 10
pfUI.bag.button_size = (342 / frame:GetEffectiveScale() - 2*default_border - 9*default_border*3)/ 10
```
The value probably wont be 342 for everyone so there needs to be some calculations done. What those are, I don't know.

That's where my research into this stops. I do want to also point out that if the default is 380, then by default the bag slots would spill out of the frame and only because the bag frame for some reason is 342 do they perfectly align (but only when the chat module is enabled).

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/8a91be54b2a69d5995bdcc2d0d03dd7be59885c3
