### ISSUE TITLE
skin: move broken armor icon

### ISSUE THREAD

**Issue by ghost** [shagu/pfUI#353]
Image:

http://prntscr.com/dvtlha

Possible solutions:

enable option for moving the broken armor icon in the Undocked mode of pfUI
enable option for offsetting (x, y) the position of the icon
enable option for hiding the broken armor icon

Probably should be another Issue but: are you considering to override the style of this icon to match better pfUI stylish style? I can open a new issue if you wish.

As always, thanks, and keep the awesome work going!

**Comment by MarkKoz** [comment]
You can use an addon like MoveAnything to move the armour. Simply type `/move DurabilityFrame` once the addon is installed and it will let you drag it around.

Alternatively, you can offset the armour icon with this simple line of code:
```
DurabilityFrame:SetPoint(TOPLEFT, pfUI.panel.microbutton, BOTTOMLEFT, 0, 0)
```
This anchors the top left of the armour frame to the bottom left of pfUi's panel frame. The last the arguments are for x and y offsets.

If you wish to hide it, pretty sure you can just do
```
DurabilityFrame:Hide()
```

You can run this LUA code via `/script` in chat or a macro (I believe it will need to be done every time you log on a character) or you can create your own addon that will just consist of one of these single lines and a .toc with meta info about the mod.

**Comment by everytimer** [comment]
Thanks Mark, this is just some input to polish this nice UI.

Ofcourse you can do a mini addon that its only function is to do that small thing, but would it be the right path to follow?

**Comment by MarkKoz** [comment]
It's just an immediate fix if that is what you were looking for, but I can see that was not your (only) goal.

**Comment by everytimer** [comment]
Same issue with Quest Timers

**Comment by Altoholic** [comment]
I'm able to move all these frames with pfUI only, so i suppose this issue can be closed.

**Comment by dein0s** [comment]
well, quest timers still can't be moved as they're not implemented/reskined in pfui :\
