### ISSUE TITLE
targettarget: portrait not refreshed

### ISSUE THREAD

**Issue by everytimer** [shagu/pfUI#355]
To reproduce:
1. Select some unit
2. Select yourself

http://prntscr.com/dw2n02

http://prntscr.com/dw2n6q

Happens with players too
http://prntscr.com/dw2nej

**Comment by shagu** [comment]
Yeah.. targettarget is a mess. I'll see what I can do

**Comment by shagu** [comment]
New Unitframes now Available on `master`
