### ISSUE TITLE
HealComm bar not properly aligned with portait

### ISSUE THREAD

**Issue by Z1mmey** [shagu/pfUI#356]
The healComm Healing preview bar does not seem to be aligned correctly when the "portait left/right" option is enabled.

![2017-01-15](https://cloud.githubusercontent.com/assets/17708471/21966828/5a70f4ce-db7b-11e6-8519-e06bbb1eba77.png)

It seems as if the preview bar calculates its length and starting coordinates from the total length of the unit frame including the portrait instead of just the HP bar.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/002b72479226b34507d0fbc6bc898a5c15038983
