### ISSUE TITLE
Make the name on healthbar not overlap the health numbers

### ISSUE THREAD

**Issue by eNtreDefias** [shagu/pfUI#357]
The names of players and npcs will overlap the health numbers when the name is to long. Only way to fix it is to make the over all font size smaller. This makes alot of numbers and text to small, as u cant change individual font size? Is it possible to add a feature to make the visible name text shorter in the health frame or soemthing?

http://imgur.com/a/5cMFS

**Comment by crumdidlyumshis** [comment]
In ElvUI and TukUI they have it set to show a specific amount of characters and add an ellipsis after so many characters.

**Comment by shagu** [comment]
This has been already done, but the portrait messed it up. I'll provide a fix soon.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/8a49ad5034bc8f126065fc8d83fed6bda14416a2
