### ISSUE TITLE
How to show the quest progress text on screen?

### ISSUE THREAD

**Issue by SneakySphynx** [shagu/pfUI#359]
Heya, 

Wondering how i can see the quest progress text on screen.
Like " Collected blabla 1/12 " 

It got hidden with this beautiful addon/suit/ui :)

**Comment by Cruzix** [comment]
pfUI settings > Global Settings > untick "Disable UIErrors"

**Comment by SneakySphynx** [comment]
Aha, it goes under UiErrors, damn. Sucks to not be able to disable the errors but still keep the text.

Have to prioritze i guess :P

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/issues/321
