### ISSUE TITLE
Keyring display buggy

### ISSUE THREAD

**Issue by muellerj** [shagu/pfUI#36]
Displaying the keyring currently shows a large icon in the inventory and requires a `/rl` to recover:

![screen shot 2016-10-09 at 12 07 47](https://cloud.githubusercontent.com/assets/53246/19219651/54e49aa6-8e19-11e6-9851-e1b516364efd.png)

Maybe the keyring display could be incorporated in the bags view as a "retractable container"?

Keep up the good work! 👍

**Comment by shagu** [comment]
I did a complete rewrite of the bag and bankframes. (https://github.com/shagu/pfUI/commit/fb323e22a2a48ceeb31f112af47d61591e55e69f)

Support for an integrated keyring will follow soon.
