### ISSUE TITLE
Hunterbar not swapping 

### ISSUE THREAD

**Issue by Rageguy1** [shagu/pfUI#361]
Just started lvling a new hunter on the fresh elysium server. I allready have a lvl 20 hunter where everything functions perfectly. it changes from melee to ranged when it should. 
but my new hunter will not change change action bar. it has been this way since i created it. tried toggeling the range and hunter bar modules off and on but to no success. 
anyone know how to solve this?

**Comment by Cruzix** [comment]
I mean... you already commented on https://github.com/shagu/pfUI/issues/287 with the exact same title as this one and you even responded to @shagu explaining the issue..... why make a new report... sigh

**Comment by Rageguy1** [comment]
1. ive tried everything in that post and the problem still presists.
2. that thread is closed. i did not know if it was going to get replied to again. 
simply delete this if it's double. no reason to be an ass about it.

**Comment by Cruzix** [comment]
Gonna quote what @shagu told you... which you also responded to and to what fixes your issue.
> Please make sure you have the skills "Wing Clip" and "Arcane Shot" on any actionbar.

If that dosn't work, then update your addon and/or disable all addons except pfUI and see if the issue still occurs.
