### ISSUE TITLE
Pet Frame

### ISSUE THREAD

**Issue by Tocsin614** [shagu/pfUI#362]
Any way to get pet happiness to show on the frame?
Maybe green yellow or red frame of some sort depending on state of pet?

**Comment by SneakySphynx** [comment]
It already does, when the pet hp bar turns yellow, or red.

**Comment by Cruzix** [comment]
This is already implemented.
![petttest](https://cloud.githubusercontent.com/assets/6162744/22020414/70b523e8-dcb8-11e6-9c30-b01fb00c37ea.gif)

**Comment by Tocsin614** [comment]
lol Crap, figures it's in there and I just never noticed rofl..thanks
