### ISSUE TITLE
Issue: Compatibility with Clique

### ISSUE THREAD

**Issue by GoochGuardian** [shagu/pfUI#363]
I can't figure out if it's a problem with registering clicks on the target frame or not. I've searched through your target and unit frame scripts and can't find anything that would be interfering. Is it Clique that I should be looking through?

**Comment by gamer4eg** [comment]
The same thing is in the last regard.
https://github.com/shagu/pfUI/issues/358

**Comment by shagu** [comment]
I never used Clique and never made any compatibility for that. No Idea how this works

**Comment by gamer4eg** [comment]
link for test : http://www.vanilla-addons.com/dls/clique/
its clickast - macros addon.
not work with pfUI frames

**Comment by shagu** [comment]
https://github.com/shagu/Clique/commit/a5ee56c3f803afbdda07bae9cd330e0d4a75d75a
