### ISSUE TITLE
Enhancement: Minimap Width (scaled) Slider (or text box)

### ISSUE THREAD

**Issue by crumdidlyumshis** [shagu/pfUI#367]
Possible to add an option to adjust the minimap size? 😄

**Comment by shagu** [comment]
every frame can be scaled by scrolling while in unlock-mode.

**Comment by crumdidlyumshis** [comment]
oh crap I had no idea xD Sorry. Thanks for letting me know!

**Comment by crumdidlyumshis** [comment]
So I got home and resized the minimap, however, it literally scales everything larger? I was thinking it would scale the minimap larger without effecting the size of location text, coord text, and points of interest icons. Is there a way to scale it without effecting the other stuff within the minimap?
