### ISSUE TITLE
Swapping bags currently not possible?

### ISSUE THREAD

**Issue by muellerj** [shagu/pfUI#37]
I don't know if this is me being thick, but I can't seem to swap a bag for another currently without disabling `pfUI`? Is there a button I'm missing?

**Comment by TrueRmia** [comment]
#19

**Comment by muellerj** [comment]
Sorry about that. Mind if I augment the README with a note about it, so less ppl fall into that trap?

**Comment by shagu** [comment]
I did a complete rewrite of the bag and bankframes. (fb323e2)
Now there's a button for that :)
