### ISSUE TITLE
Level coloring

### ISSUE THREAD

**Issue by everytimer** [shagu/pfUI#371]
I don't know what are the correct values for this but there must be a little bug at coloring the level of your target. 

i.e. My character, which is level 17, sees as green as low as level 9, those should be colored as gray instead.

In addition it would be more consistent to color as yellow levels around the same as the character (instead of current green).

In addition (x2) I think it would be nicer to mark with a little skull or some icon targets that are ten levels above yours.

In addition (x3), this is a personal choice but I would color the level of allies in yellow independently. This would be consistent with default UI and wouldn't scare when you target some high level ally :)

**Comment by Road-block** [comment]
For a level 17 player the ranges for enemies are (should be) grey up to 11, 12-14 green, 15-19 yellow, 20-21 orange, 22-26 red, 27+ skull.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/2d9493a34eb091d9538adfdcf83d894fba547a1c
