### ISSUE TITLE
Bags not working well...

### ISSUE THREAD

**Issue by NibelheimGG** [shagu/pfUI#373]
the bags is not working well, some items dissapear only can see them with blizzard ui, what is wrong? i have 10 slots bag but in the pfui shows like 8 slots so the other 2 slots dissapear, i think the bug is related about your last bag improvement, is it possible? thanks

**Comment by gamer4eg** [comment]
+

**Comment by NibelheimGG** [comment]
im using an older bags.lua and its works good but with the latest version im missing slots, 12 slot bag show only 8 slots

**Comment by gamer4eg** [comment]
thx

**Comment by Cruzix** [comment]
I never had this issue myself, could you provide a screenshot of it?

**Comment by NibelheimGG** [comment]
yes, this is my bags with older bags.lua working good -> https://gyazo.com/a5d24401252d1f864aac7feb338804e1

And this are my bags with the latest pfui version -> https://gyazo.com/09e4bf0905eb8b0b309fbdfdf4f844a2  has you can see the addons is missing bag slots so you cant see or use these items

**Comment by Cruzix** [comment]
You didn't include your bags in the images... I was kinda looking if it was a dummy mistake, but meh probably not.  Have you tried disabling all addons but pfUI and seen if the bug still occurs?

**Comment by NibelheimGG** [comment]
i have 1 bag of 12 slots and 3 of 10 slots, i didnt clean my pfui variables of WTF folder because i wont to lose my configuration, can this cause this problem? i never had problems installing a new version

**Comment by Cruzix** [comment]
> Have you tried disabling all addons but pfUI and seen if the bug still occurs?

**Comment by NibelheimGG** [comment]
yes, i dont have any other bag related addons, i have this bug since the last bag.lua edit for Shagu, i thought everyone had this bug, meanwhile i have an older bag.lua so i dont worry so much

**Comment by Ksnz** [comment]
Have this bug too

**Comment by Fluffykable** [comment]
same

**Comment by Cruzix** [comment]
I still cannot reproduce this bug O.o 

I'm trying to reproduce it on RetroWoW and I'm assuming all of you play on Elysium? Maybe its a server thing?

**Comment by Ksnz** [comment]
![Image](http://i.imgur.com/I2rLzvn.png)

**Comment by Cruzix** [comment]
Yep, I can reproduce now as well. It seems to be happening if your right chat frame is too wide or not wide enough. I've always had mine set to 350 and I never had this issue with that width, but when I changed it to 450 or 250 the issue appeared.

**Comment by Ksnz** [comment]
https://github.com/shagu/pfUI/blob/master/modules/bags.lua#L223
Replacing '9' to '8' seem like a solution
![Image](http://i.imgur.com/EWwVahO.png)

**Comment by Ksnz** [comment]
![Image1](http://i.imgur.com/X5xAr2s.png)
![Image1](http://i.imgur.com/WGORagD.png)
I found out that scaling cause bug :triumph:

**Comment by NibelheimGG** [comment]
i get this bug even editting that value to 9 and changing width or scale of the rightchat, lets wait to shagu fix it

**Comment by Cruzix** [comment]
@NibelheimGG Try to set ur right chat to 350 width and see if it still occurs 

> Yep, I can reproduce it now as well.
It seems to be happening if your right chat frame is too wide.

I've always had my right chat set to 350 width so I never had this issue, but when I changed it to 450 the issue appeared.

**Comment by shagu** [comment]
I'm not able to reproduce this at all. I tried it by scaling the chatframe, scaling the whole UI and setting a different chat-width. No matter which settings I have tried, I never ran into this issue.

Please provide all steps on how to reproduce it from a full reset onwards.
Also make sure you have version 1.5 running.

1. Reset All
2. ???
3. ???

Thanks in advance

**Comment by Cruzix** [comment]
Just tried to reproduce it once again and cannot seem to get it to happen at all. 
My previous theory was just me being stupid and didn't spent enough time looking into it.

At this point I'm pretty sure it's just people having some kind of addon conflicting with pfUI and/or an old version of pfUI because I've literally tried everything to reproduce it now.

**Comment by NibelheimGG** [comment]
maybe a full reset fix it, but im to lazy now to re configure the whole UI because im pretty maniac with the frames position, someone with this bug can try it?

**Comment by crumdidlyumshis** [comment]
@NibelheimGG Just copy/pasta your WTF/Interface folder and make a backup of it. Then delete both and install a fresh pfUI and start from there. If the problem is still there then we know. Else, you can safely put your WTF/Interface folders back. 👍

**Comment by NibelheimGG** [comment]
ok, i found the bug, is cause when you down the size of the chat by the Shift+scroll on the move UI mode, if you touch this the bag go out the chat screen

**Comment by Ksnz** [comment]
@NibelheimGG try 
`    pfUI.bag.button_size = (frame:GetWidth() * pfUI.chat.right:GetScale() - 2*default_border - 9*default_border*3)/ 10 `
https://github.com/shagu/pfUI/blob/master/modules/bags.lua#L201 here

**Comment by Cruzix** [comment]
@NibelheimGG Just change its height/width in the settings rather than scaling it. Much more controllable as well

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/51b3e525e54b97b23363fac6d361b0ed7d9c085e

**Comment by Vilefelhinie** [comment]
Happens to me too

Server: Elysium fresh start
Bag: 4x6slots
Resolution: 1280x1024
Addon version: Lastest 1.5
Scale of chatframe: <1.0

Seems like i lost bag slot when i play with <1.0 scaling (im forced to with such bad res), when i grow to 1+ bag slot come back, else they are like out of screen and out of the UI frame.

**Comment by Cruzix** [comment]
@Vilefelhinie The fix haven't been added to a release version yet. Update here if you wan't the fix https://github.com/shagu/pfUI

**Comment by Vilefelhinie** [comment]
Amazing, thanks mate!
