### ISSUE TITLE
Class color on nameplates randomly disappearing

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#377]
https://youtu.be/4zGi8AufU9s

**Comment by Cruzix** [comment]
Just came to think of it could possibly be related to https://github.com/shagu/pfUI/issues/325 ?

**Comment by shagu** [comment]
I don't like the "randomly" here. Did you found any way to easilly reproduce it?

**Comment by Cruzix** [comment]
I have no idea why it's happening, sorry :/ 
You can easily reproduce it by running around in the starting zone on RetroWoW, always lots of players there. 
It's only some targets where their class color disappears but for those it'll happen very frequently

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/3a51b93d04e91ddb11ce8062fc00488786145113
