### ISSUE TITLE
wishlist

### ISSUE THREAD

**Issue by TinyLittleBits** [shagu/pfUI#378]
- chat windows: button to clear chat without reloading
- action bars: hide keybinds option
- action bars + unit frames: option to hide while out of combat and with full life and mana. + sub options: show if targeting enemy; show if targeting (even friendly).
- buffs: whitelist, blacklist
- map coordinates for these that won't use Cartographer.

o/

**Comment by crumdidlyumshis** [comment]
![5539df1feb1e1d8bbd31f173a682b923_-me-to-detail-my-wish-list-christmas-wish-list-clipart_653-519](https://cloud.githubusercontent.com/assets/7307335/22265656/909eef60-e242-11e6-8abd-d6429128bb2d.gif)
