### ISSUE TITLE
group: add pet frames

### ISSUE THREAD

**Issue by Maievh** [shagu/pfUI#379]
Either im blind or there aint a way to show group pets in the ui settings?

**Comment by elenmerbau** [comment]
I was looking for that options in pfui settings for 10 minutes

**Comment by khalismur** [comment]
Yep, this would be great for healers when teaming up with hunters / locks :-)

**Comment by Rewinding** [comment]
Bump, would like to see pet raid frames.

**Comment by MrMeerkat37** [comment]
Is this in the works? Its the only problem i find with Pfui :)

**Comment by shagu** [comment]
>> Is this in the works? Its the only problem i find with Pfui :)

Yes, will be part of the new unitframes: https://github.com/shagu/pfUI/tree/new-unitframes

**Comment by shagu** [comment]
New Unitframes now Available on `master`
