### ISSUE TITLE
My pet bar disappeared? halp (It's not the reload UI bug)

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#381]
https://youtu.be/DwyH3m08SNA

Anyone know how I can make it show again?, I don't recall what exactly made it disappear - possibly scaling too low and it just went away?

**Comment by shagu** [comment]
`/run pfUI_config.position.pfBarPet = nil`
Logout, Login.

**Comment by Cruzix** [comment]
Thanks!

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/405a4943c3408d24dc1d61519807b591a9147fd2
