### ISSUE TITLE
buff: drop blizzard buffframes and create new ones

### ISSUE THREAD

**Issue by Crumdidlyumshis** [shagu/pfUI#382]
title

![world of warcraft 1_23_2017 9_51_46 am](https://cloud.githubusercontent.com/assets/7307335/22211676/750d86de-e153-11e6-9fa0-a692d1e4968e.png)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/8fb5f3a10d43d7483473af8a82f0e56814f09162
