### ISSUE TITLE
Warlock pet bar disappears when pfui settings are changed.

### ISSUE THREAD

**Issue by SHJ234** [shagu/pfUI#383]
Hi,

Problem 1:
Whenever i do a change in pfui regardless of what change. The pet control bar disappears. The only way to get it to appear again is if i re-logg.

I have tried every restart method and also reload the whole ui without any success.

Problem 2:
If i shift click gear. The gear will be stuck wherever my mouse hoover over. So it appears next to persons or items alike.
This is however fixed with doing a restart of pfui. But Then problem number 1 happens again.

Please see attached pictures

![gear following hoovering items nps players](https://cloud.githubusercontent.com/assets/16563253/22217969/42c826aa-e1a5-11e6-9bc8-0d20a1365ea3.png)

![petbar missing](https://cloud.githubusercontent.com/assets/16563253/22217974/489027d6-e1a5-11e6-80e1-5b88473e1682.png)

**Comment by Cruzix** [comment]
That has nothing to do with pfUI. Its a bug with in the vanilla client, it happens every time you reload your UI whenever your pet is summoned.

You have to either relog or resummon your pet to fix it.

**Comment by SHJ234** [comment]
Sorry and thx for fast help. Much appreciated.

**Comment by crumdidlyumshis** [comment]
To be more specific it's a server side issue. Not client. It happened on warmanes servers for a long time and they fixed it a while back.

**Comment by crumdidlyumshis** [comment]
Just wanted to leave this here in regards to the pet action bar: https://forum.elysium-project.org/topic/34789-development-update-25012017/

_"Pet's action bar will return after reloading user interface."_
