### ISSUE TITLE
Quest tracking progress

### ISSUE THREAD

**Issue by Rosexephon** [shagu/pfUI#387]
When you're on a kill quest, say kill 15 raptors, after you kill a raptor it doesn't pop up in the top middle saying 1/15 raptors slain. It gives no indication and you have to refer to your questlog. I've disabled all addons and found that PfUI is causing this.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/issues/321

**Comment by crumdidlyumshis** [comment]
This is a server-side issue.
