### ISSUE TITLE
Using spell ranks with (UnitFrames - Raid - Click-cast)

### ISSUE THREAD

**Issue by H0rac3** [shagu/pfUI#390]
I am able to enter a spell just fine and click-casting works with the highest rank I know. But I'm not able to enter a lower spell rank to use. This is what I've tried:

WORKS:
Chain Heal

DOESN'T:
Chain Heal (Rank 2)
Chain Heal(Rank 2)

I've tried a few other variants with no luck. Is there a specific format to do this or is it not implemented yet? Thanks and love the UI!

**Comment by shagu** [comment]
The last one, without the space between spell and rank always worked for me. I'll check as soon as I'm home.

Did you already tried without any other addons?

**Comment by Cruzix** [comment]
I use a macro similar to this and it works just fine - atleast a couple of versions back

`/run if 1==0 then CastSpellByName("Wing Clip");end
/cast Counterattack(Rank 1)
/cast Wing Clip
/cast Wing Clip(Rank 2)
/cast Wing Clip(Rank 1)`

**Comment by shagu** [comment]
For me, It works as expected. 

Please make sure to remove all leading and trailing spaces in the textfield if existing, also make sure that you don't run any conflicting addons.
