### ISSUE TITLE
Ability to hide the background of unused Action Bar Buttons

### ISSUE THREAD

**Issue by BewareOfPiranha** [shagu/pfUI#392]
Currently (to my knowledge) there is no ability to hide the background of unused action bar buttons. This means there is a black square background where there is no active button. Being able to hide those would be great. Amazing addon by the way!

**Comment by Rewinding** [comment]
Disable actionbars in wow interface. (Does not hide individual buttons)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/a2d69f777da89e76ebeb77af1099b18c41aa4eca

Use Blizzards Interface settings to configure.

**Comment by BewareOfPiranha** [comment]
I was rreferring to individual button backgrounds that are unused, not the entire actionbar.

**Comment by BewareOfPiranha** [comment]
Thank you for your incredible support.
I am however using that option:
![alwaysshow](https://cloud.githubusercontent.com/assets/25347990/22326447/0f710b68-e3b3-11e6-8496-9cfe778b1ea9.PNG)

This is what mine looks like:
![actionbar](https://cloud.githubusercontent.com/assets/25347990/22326467/1d2ee59a-e3b3-11e6-8ad2-b333e55d3b54.PNG)

Using Release v1.5.

**Comment by Cruzix** [comment]
https://github.com/shagu/pfUI/commit/a2d69f777da89e76ebeb77af1099b18c41aa4eca hasnt been pushed to a release version yet. Update here if its something you need right now https://github.com/shagu/pfUI

**Comment by BewareOfPiranha** [comment]
Thank you so much. Updating there solved it!
