### ISSUE TITLE
[Bug Castbars] Cast while Channeling: compare with nil

### ISSUE THREAD

**Issue by Shimatsuke** [shagu/pfUI#393]
When you use a skill with casting time while channeling another spell, the castbars-module will throw an "attempt to compare with nil" exception.
Tested while Castbars were hidden, with Warlock's drain life & shadow bolt

**Comment by shagu** [comment]
Please attach a complete error message. I'm especially interested in the line number.

**Comment by Shimatsuke** [comment]
I'm so sorry, I should've thought of that. The full error message is: 
ERROR: Interface/Addons/pfUI/modules/castbar.lua: 128: attempt to compare number with nil

**Comment by EffToyz** [comment]
![pfui_error](https://cloud.githubusercontent.com/assets/24850811/22333977/c104fe82-e3a6-11e6-91ba-c37cd0a37299.PNG)

It happens when you casting something and start to cast something else, I was bandaging my pet and then started to craft new bandages before cast ended.

(is there the way to copy messages from chat with pfUI yet?)

**Comment by EffToyz** [comment]
also I'm using **enemyFrames** addon, which doesn't work anyway.

**Comment by Cruzix** [comment]
enemyFrames works just fine?, I use it myself.

**Comment by shagu** [comment]
On which server is this castbar issue happening?

**Comment by Shimatsuke** [comment]
That's Darrowshire for me. 
The only other addon I use that relates to unitframes/castbars is LunaUnitFrames, which I use to replac the original Unitframes with. (That's why the pfui-castbar was hidden when I noticed the bug occuring).

**Comment by EffToyz** [comment]
Zeth'Kur for me.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/7912090ac3a01d443c67364ff161984fc2778108
