### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by EffToyz** [shagu/pfUI#394]
Feature Request:
1. Shift-click (or anything really) on time to pause/unpause timer.
2. Persistent timer (for often disconnects) or quick relog
3. Ctrl-click for additional timers (when you farm some specific mobs/item respawn) (with map mark where did you start this timer (but I guess this is idea for whole another addon))

**Comment by Cruzix** [comment]
This seems like something that is only useful to the very very very minority besides there is already an addon capable of this called "Timers" - pfUI has a basic "StopWatch" feature already when you click on the clock panel module (and recently added a module specificly for this iirc)

**Comment by EffToyz** [comment]
My language. By 1. I meant stopwatch, I knew about one already in pfUI, but it is unstoppable, you can only reset it.
Point 3. is yeah, another addon matter, but 2. I guess is pretty doable?

**Comment by shagu** [comment]
I won't add other timer/countdown/stopwatch related stuff. At some point, people should use a specific addon if they need something more sophisticated.
