### ISSUE TITLE
Loot/Spam not showing any chat channels

### ISSUE THREAD

**Issue by ghg0004** [shagu/pfUI#396]
Loot/spam bar won't show world/general/trade chat. I have right clicked it and set it to join those channels, and I can talk in them and what I say will show up on the right chatbox, but I cannot see what other people are saying. I have tried fiddling with the chat settings in pfUI and relogging and redownloading pfUI but the issue persists.

**Comment by ghg0004** [comment]
forgot to mention this is on Elysium servers.

**Comment by TrueRmia** [comment]
Do you use Lazypig? Disable it and try again

**Comment by ghg0004** [comment]
IT WORKED!!!! @TrueRmia Thanks so much. Is there any way to still use lazypig or do I have to live without for this to work? Thanks again.

**Comment by TrueRmia** [comment]
Yes. I disabled all Chat relatet options in Lazypig.
Can Tell you more when i am at Home.
