### ISSUE TITLE
target: movable combo points

### ISSUE THREAD

**Issue by nacedos** [shagu/pfUI#398]
Would you be able to make combo points more customizable / visible where they are at the moment?
I would like to move them as a group, size and colum so I can put them in horizontal in middle of the screen. 
Atm   ##I have a hard time tracking them

**Comment by Cruzix** [comment]
You can use this for now: https://wow.curseforge.com/projects/project-2643

**Comment by nesherman** [comment]
Would really love to see this implemented as well as some other options to change up combo point display (i.e. make them circular, change colors, adjust width and direction they expand). It's is honestly the only reason I haven't fully committed to the pack yet.

Great work!

**Comment by nesherman** [comment]
I've been playing with the LUA and have found a way to edit the combo points to my liking, but I cannot make them expand horizontally rather than vertically. Would you be able to tell me what line of code to insert where?

I can typically get by with messing around, but I'm lost on this one.

**Comment by shagu** [comment]
you can move them individually, if you check-out the `new-unitframes`-branch.

**Comment by nesherman** [comment]
Version 2.2? I'm not seeing anything, but perhaps I'm lost? Any other descriptors?

**Comment by nesherman** [comment]
found it! amazing work man. this is perfect.

**Comment by shagu** [comment]
This is how to get it:
[1](http://i.imgur.com/dULJF58.png)
[2](http://i.imgur.com/STox0iG.png)

I'll launch a beta-release soon.

**Comment by moootv** [comment]
@shagu when do you release the combopoint branch?

**Comment by shagu** [comment]
New Unitframes now Available on `master`
