### ISSUE TITLE
unitframes: status text customization

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#40]
Having the option to enable/disable which status text you want shown (hp, pp, percenthp, percentpp, name, etc) and to anchor their position on the unit frame (Left, right, center, topright etc) would be a great feature to add.
Heres some inspiration as to which status text you could add http://i.imgur.com/tfyfVpa.png

Also being able to offset each status text in x/y direction would be very handy as well - heres my retail UI which reminds fairly much of pfui where I use this feature to offset my targets name outside the frame to keep both my own and target frame clean and similar http://i.imgur.com/GbNrFl8.png

Really appreciate your work so far and i'm looking forward to see your progress on this project in the future!

**Comment by shagu** [comment]
New Unitframes now Available on `master`
