### ISSUE TITLE
thirdparty: custom skin for vQueue

### ISSUE THREAD

**Issue by Rosexephon** [shagu/pfUI#401]
Just curious if you take the request to reskin other add-ons for pfUI? I'd like to request vQueue an increasingly popular add-on for forming, advertising and finding groups

https://github.com/Devlix/vQueue

**Comment by byaka** [comment]
For me, reskinning not so important like adjusting zindex:
![image](https://user-images.githubusercontent.com/1580811/28458426-5b9dea1c-6e12-11e7-9bfe-e774876efa9a.png)
![image](https://user-images.githubusercontent.com/1580811/28458436-60462bb0-6e12-11e7-85bb-5c1caaf87968.png)

Also one big problem of vQueue - if u enabled notify for groups, window pops also if u in combat.  and no option to disable popping window. In my opinion for notify would be better just fleshing minimap icon, like this addon do if u have new group requests (when u search not group, just members for group).

But i think Shagu have enouth work with pfUI.

**Comment by shagu** [comment]
Won't happen. Sorry
