### ISSUE TITLE
api: possible performance regression

### ISSUE THREAD

**Issue by muellerj** [shagu/pfUI#402]
At some point between `1.5` and the current master, my performance has dropped significantly. It shows most prominent in occasional spikes, where the framerate drops below 5 fps and then recovers.

These are the commits since `1.5`:

``` git
* 7912090 (HEAD -> master, origin/master, origin/HEAD) castbar: stop channeling on cast (3 hours ago) [shagu]
* c8e547a panel: add option for 12 hour clock (20 hours ago) [shagu]
* cec258e bags: show tooltips on bagslot buttons (21 hours ago) [shagu]
* 6420c23 fonts: use combat font for scrolling combat text (21 hours ago) [shagu]
* 5791f95 firstrun: fix title of cvar dialog (21 hours ago) [shagu]
* a2d69f7 actionbars: add option to hide grid (21 hours ago) [shagu]
* 8b43b58 firstrun: add dialog to setup default interface settings (21 hours ago) [shagu]
* 27a6fa1 unitframes: show magic debuffs for warlocks (2 days ago) [shagu]
* 096ee9d api: add option to move frames offscreen (2 days ago) [shagu]
* 389a7b6 tooltip: add option for custom transparency (3 days ago) [shagu]
* d8c8ee4 api: allow custom transparency (3 days ago) [shagu]
* 3a51b93 nameplates: always update player colors (3 days ago) [shagu]
* 2d9493a target: use wow api to calculate levelcolor (3 days ago) [shagu]
* b878edf buff: adjust position of item enchant duration (3 days ago) [shagu]
* 405a494 api: prevent frames from being placed offscreen (3 days ago) [shagu]
* 51b3e52 bags: fix appearance on scaled chat frames (3 days ago) [shagu]
* 091ac41 toc: remove old font module (3 days ago) [shagu]
* 3cad6d4 (tag: 1.5) tag: release version 1.5 (10 days ago) [shagu]
```

**Comment by muellerj** [comment]
P.S.: Reverting back to `1.5` seems to fix the issue.

**Comment by shagu** [comment]
Please provide as much information as possible:
- Which other addons are used?
- Where did measure the performance?
- What do you do during the measurement?
- Which Server are you playing on
- Does this also occur after a complete UI reset? ("Reset All" in pfUI settings)

**Comment by muellerj** [comment]
# Other Addons:

```sh
AfterCast                   Blizzard_CombatText         Blizzard_TalentUI           Fury                        LVBM_GUI                    Outfitter                   dpsmate
Atlas                       Blizzard_CraftUI            Blizzard_TradeSkillUI       KLHThreatMeter              LVBM_MC                     Prot                        pfUI
AtlasLoot                   Blizzard_GMSurveyUI         Blizzard_TrainerUI          LVBM_API                    LVBM_NAXX                   TankPoints
Blizzard_AuctionUI          Blizzard_InspectUI          CT_RaidAssist               LVBM_AQ20                   LVBM_Other                  WIM
Blizzard_BattlefieldMinimap Blizzard_MacroUI            Charrge                     LVBM_AQ40                   LVBM_RaidTools              WarriorHUD
Blizzard_BindingUI          Blizzard_RaidUI             EQL3                        LVBM_BWL                    LVBM_ZG                     XRS
```

# Location of spikes
I'm not sure exactly what triggered the spikes, but it only happens in "crowded" places (i.e. more than 10 other players around, doing something. They don't have to be in the same group/raid. I can't point to something specific, but moving the camera seems to cause it sometimes?

# Server
Nefarian, same as you ;)

# Reset
I have reset everything (although it's a bit of a pain to position and scale all the frames again) and reverted back to `origin/master`. I'll be in touch if I can either reproduce it or the problem goes away. I was hoping you'd  have a first suspicion just by looking at the commit range.

Thanks for the awesome work.

**Comment by shagu** [comment]
> I was hoping you'd have a first suspicion just by looking at the commit range.

This is the only one I'd have in mind that could lead to the regression:
```* 3a51b93 nameplates: always update player colors (3 days ago) [shagu]```
It didn't had any impact on my game performance. But you might want to revert it and test again.

**Comment by muellerj** [comment]
I tested today with `3a51b93` in a 40-man environment and couldn't notice any difference. Maybe the first problem was on my local client only. I'm closing the ticket.

**Comment by elraro** [comment]
Hello.

This is the first time i tried this UI. Thanks! Its very impressive :)

I have problems with fps. Tried with master branch and last release. Sometimes fps drop to 30 (check for example opening bags).

**Comment by shagu** [comment]
Thanks for your feedback. Even without having pfUI enabled, the framerate drops when all bags are opened. I assume there are some issues within the Wow code regarding the Bag Buttons. 

I still have some code optimizations in mind, but I don't think I'm able to fix Wow's Bag Buttons completely.
