### ISSUE TITLE
Bag Sorting

### ISSUE THREAD

**Issue by EffToyz** [shagu/pfUI#404]
2 feature request.

1. Add ctrl-click shortcut on sort icon for reverse sorting
2. Make negative weight for grey garbage items, so bags will sort as [garbage slots] [empty slots] [useful items]
3. Optional for 2. alt-click (for example) on item in bag to assign negative weight as well (for example some white drop which is useless vendor loot).

**Comment by Road-block** [comment]
Just a note that sorting is provided by a 3rd party addon. shirsig's [Clean_Up](https://github.com/shirsig/Clean_Up) . Might be best to post the suggestion over there.

**Comment by EffToyz** [comment]
I was hoping @shagu will hack this addon, I asked for this feature shirsig, but his position "this is final" is strong.

**Comment by shagu** [comment]
Nope, sorry. I have enough on the todo with my own addons.
