### ISSUE TITLE
Target castbar not visible

### ISSUE THREAD

**Issue by Secus** [shagu/pfUI#405]
I'm having a problem with the target castbar not being visible. 

Player castbar works correctly. 

Target castbar is not disabled in pfUI settings.

**Comment by Cruzix** [comment]
I had the same issue but with the pet bar a few days ago, maybe you can tinker a bit with shagu fix in the comment and see if you can make it target the target castbar https://github.com/shagu/pfUI/issues/381

**Comment by Secus** [comment]
Didn't seem to work, I can see castbar when viewing the location through the unlock option. But the bar does not show when the target is casting.

**Comment by Cruzix** [comment]
weird, try disabling all other addons and see if it still occurs

**Comment by Baltimus** [comment]
Same problem (with French client).
No casting bar for my target... but all castbar settings enabled.

http://imgur.com/a/oOKRQ

Trying :
- new setup
- to disabling all other addons
- /run pfUI_config.position.pfTargetCastbar = nil

No results.

**Comment by shagu** [comment]
Seems to be an issue with the translations. Please check your combat log and compare it to https://github.com/shagu/pfUI/blob/master/env/locales_frFR.lua#L39-L46

Would be also helpful if you could provide the following informations:
- Does it affect all spells?
- Do you use any other addons?
- Does this also happen after a "Reset All" in the settings?

**Comment by Baltimus** [comment]
The translations strings not match to combat log, how I can help you ?

> Does it affect all spells?

**Yes all casting spells**

> Do you use any other addons?

**Any other addons**

> Does this also happen after a "Reset All" in the settings?

**Yes also happen after Reset all**

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/4b5926d9b8fe70746276aa6454c9df382b298c8c
