### ISSUE TITLE
Immolate spell pushback

### ISSUE THREAD

**Issue by Capracou** [shagu/pfUI#406]
Hi Shagu this bug has been up for quite a while now, the improved immolate (1.3sec) cast time is bugged when pushed back by a monster, seems fine with the 2sec immolate tho.

**Comment by shagu** [comment]
Are you talking about the player or target castbar?

**Comment by Capracou** [comment]
Player's obviously since there is no displaying the target's pushback, here is a screenshot : 
![immolate](https://cloud.githubusercontent.com/assets/25414875/22589829/9dcddaa8-ea0c-11e6-9a6e-ab3f80dd2467.jpg)
http://imgur.com/UngzE3M

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/1bfc5dd27c756417596203d3d6d7dcd941984822
