### ISSUE TITLE
Show info from other addons when hovering items in the lootframe

### ISSUE THREAD

**Issue by nummersyv** [shagu/pfUI#407]
When hovering an item in the lootframe, information from other addons like aux or comparestats are not shown like they are when hovering items in the bag or bank.

**Comment by gamer4eg** [comment]
+

**Comment by shagu** [comment]
Does it show on lootframe without pfUI?

**Comment by nummersyv** [comment]
They are not, no.
My intention with this issue is not a bug report but rather a feature request.

**Comment by shagu** [comment]
Then I can't do anything about it. Its something that must be implemented in the aux code first.

**Comment by nummersyv** [comment]
It isn't possible to add triggers to the hover event so aux treats it as a hover like any other item in the bag?

**Comment by nummersyv** [comment]
Or rather, to make pfUI treat it as any regular hover?

**Comment by shagu** [comment]
No, because different functions are used to retrieve item data from loots, bags, inventory and others:

http://wowprogramming.com/docs/api/GetContainerItemInfo
http://wowprogramming.com/docs/api/GetLootSlotInfo
http://wowprogramming.com/docs/api/GetInventorySlotInfo
...

**Comment by nummersyv** [comment]
Thank you for your responses - and for your work on all your awesome addons!
I apologize for my ignorance regarding the wow api.

**Comment by shagu** [comment]
You're welcome. It's always good to ask ;)
