### ISSUE TITLE
actionbar: mindcontrol breaks actionbar paging

### ISSUE THREAD

**Issue by dabadoo** [shagu/pfUI#408]
When the Nefarian warrior class call ends the main action bar becomes bugged. By bugged i mean that the main action bar changes to a wrong action bar. (Maybe it is the empty action bar that appears when the player is dead?)

The only way i have tested to fix this is to manually click one of the 3 warrior stances.

This issue does not occur with pfui action bars turned off.

**Comment by shagu** [comment]
Interesting.. Is there another way to reproduce this without participating in raids?

**Comment by dabadoo** [comment]
I have only experienced this at nefarian. I will try to take screenshots today of the problem if i remember to do it. But i might get distracted and forget mid fight :)

**Comment by Cruzix** [comment]
@dabadoo record it instead, then u wont forget :p
