### ISSUE TITLE
Items linked in chat displaying clickable name. 

### ISSUE THREAD

**Issue by JeremyPerpignani** [shagu/pfUI#409]
Hey there, thank you so much for this addon. The only problem I am having is chat item links do not work. Whenever a item is linked in any chat, all i get is their name again as the color of the item they linked. Then if a second item is linked it will show that item normally. Sometimes when I click the linked name bug, the actual item will show. Here are some screen shots? Any suggestions? I have troubleshooted my addons and the bug goes away only when I disable pfui. I thought it was atlas but the bug still persists when disabled. 

Here is an image to better understand. 
[http://i.imgur.com/uLJW10h.jpg](http://i.imgur.com/uLJW10h.jpg)
Thank you so much once again!! Have a great day!

**Comment by Cruzix** [comment]
https://github.com/shagu/pfUI/issues/68 duplicate.

**Comment by JeremyPerpignani** [comment]
Thanks, sorry I didn't think to search here.
