### ISSUE TITLE
Target Buffs and Castbar not showing

### ISSUE THREAD

**Issue by Wonderboy88** [shagu/pfUI#410]
1. Enemy target doesn't show their own buffs above their target unitframe, only debuffs. Cannot find a setting for it so this is either a bug or a feature request.

2. It also doesn't show the target castbar when they spellcast below it. I can see the castbar when I unlock the frames but doesn't show when the target casts something. I can also see the code for it in the Castbars.lua file, so assume this is a bug.

Using latest release.

**Comment by shagu** [comment]
1. Is vanilla. Same with the default UI.
2. Sounds like the same as https://github.com/shagu/pfUI/issues/405 Please provide informations on which spells and which game client localization this occurs on the linked issue.
