### ISSUE TITLE
Created group layout, how to get in contact?

### ISSUE THREAD

**Issue by DaK1Ga** [shagu/pfUI#413]
Hi,

I've added an option to change group width via GUI and a dropdown to choose between raid and group look of groups. Just take a look at my attached picture and I guess it will speak for itself.

![wowscrnshot_020217_195704](https://cloud.githubusercontent.com/assets/25509324/22563659/da9d404e-e981-11e6-80c6-4e86d8ef2d06.jpg)

That's an early stage but I would love realise some more ideas in the future, how to do so?

Best regards,

Daniel

**Comment by shagu** [comment]
Hi, this looks good. Whenever you feel ready, just send a pull request :)
