### ISSUE TITLE
Auto dismount does not work on Qiraji battle tanks

### ISSUE THREAD

**Issue by vashin1** [shagu/pfUI#415]
Auto dismount works perfectly for all other mounts but does not work for the blue, green, yellow or black bug mount from AQ40

**Comment by shagu** [comment]
It does work for me

**Comment by shagu** [comment]
I believe this happened because you had more than 16 buffs. With this commit, it will now search in up to 32 buffs: https://github.com/shagu/pfUI/commit/879cba9034b2eba0b902b993fedf887faf4c0cd6
