### ISSUE TITLE
Extendable OnClick support for Unit/Raid frames

### ISSUE THREAD

**Issue by kxseven** [shagu/pfUI#418]
Would you consider replacing the OnClick function created separately in each unit frame (player/target/party/raid) with a generic one that accepted `button` and `unitid`?

```lua
function pfUI_OnClick_Handler(button, unitid)

    -- use the custom OnClick function if one is hooked
    if (type(pfUI_Custom_ClickFunction) == "function") then
        if (pfUI_Custom_ClickFunction(button, unitid)) then
            -- pfUI_Custom_ClickFunction should return true if handled, then we do nothing more.
            -- no return and we'll continue with default pfUI behaviour
            return true
        end
    end

    -- existing pfUI OnClick code/behaviour
    ...

end
```

 - This would allow other AddOns (healing orientated ones primarily) to hook their custom function. 
 - This is how it was coded in PerlClassic and X-Perl which then allowed support for AddOns such as Clique and HealBot
 - I've prepared a version of [Clique](https://github.com/kxseven/Clique/commit/acc9c51a75a496901b3d1f550b4879c7441fd54c) with support for pfUI if this change is made.

**Related Issues:**
https://github.com/shagu/pfUI/issues/363
https://github.com/shagu/pfUI/issues/104

**Comment by kxseven** [comment]
Updating;
 - I've started work on a fork of pfUI with support added for player, target and targettarget frames.
 - I'll submit a PR once I've got party and raid frames working also.

**Comment by kxseven** [comment]
PR submitted https://github.com/shagu/pfUI/pull/419

**Comment by shagu** [comment]
Thanks.

**Comment by kxseven** [comment]
Updated PR https://github.com/shagu/pfUI/pull/436 based on current implementation of OnClick function

**Comment by shagu** [comment]
https://github.com/shagu/Clique/commit/a5ee56c3f803afbdda07bae9cd330e0d4a75d75a
