### ISSUE TITLE
Hunterbar paging.

### ISSUE THREAD

**Issue by Lebaowski** [shagu/pfUI#420]
The hunterbar options doesn't seem to do anything for me, the action bars does not change based on range. I tried running the game with no other addons but pfUI present, and the WTF folder cleared but the bars still won't change based on range. I also tried running ShaguUI to check if it still works there, and it does, without problems.

Is this a normal issue, or is it on my end? Not sure what else I can do after running the game with no other addons or settings present.

**Comment by shagu** [comment]
Do you have `Wing Clip` and `Arcane Shot` on any actionbar?
