### ISSUE TITLE
Player online panel?

### ISSUE THREAD

**Issue by NibelheimGG** [shagu/pfUI#421]
is it possible to add an option to see playes online in the left and right channels? i mean where you can set durability,fps,hour,fiends online etc

**Comment by vashin1** [comment]
Sounds like a total resource waste to me mate.

**Comment by Cruzix** [comment]
I'm pretty sure this will also affect when you shift click on names to see their class/guild/level etc. since /who is used for both of these things. Could be wrong though

But I agree with vashin1 nonetheless

**Comment by shagu** [comment]
There is no API call for that, and it would be much to heavy on your ressources to do it on a regular basis via the /who method.

**Comment by crumdidlyumshis** [comment]
Also in addition to this not being feasible without increasing resources, this is not exactly doable for all servers. When you /who some servers only show the blizzlike number of 50. Whereas other server show the actual population of the whole server, or actual population of the faction side. This would not be a reliable feature as it is only logical for some servers. Good idea nonetheless! Keep up the ideas!
