### ISSUE TITLE
Chat fix?

### ISSUE THREAD

**Issue by gamer4eg** [shagu/pfUI#423]
On elysium work correctly only client enUS chats. Need a fix chat to other languages when entering the location to connect to these chat chanels. I can provide lists of names of locations on ruRU (and enUS for comparison).

**Comment by shagu** [comment]
what?

**Comment by gamer4eg** [comment]
Chat channels on elysium work properly on all customers other than English.
Need a fix chat to any client to connect to the English Channel.
Example:
Общий:Оргриммар
General:Orgrimmar
This is different channels.

**Comment by shagu** [comment]
Does it work without pfUI?

**Comment by gamer4eg** [comment]
It is generally anywhere and in any way does not work. = (
I can provide a list of channel names and locations (in Ru and in Eng for comparison)

**Comment by gamer4eg** [comment]
But on pfUI not work standard fix through addon vQueue

**Comment by shagu** [comment]
> It is generally anywhere and in any way does not work. = (

If it is not related to pfUI, then you should ask in your server forums for a general solution.

**Comment by gamer4eg** [comment]
For 3 months I write, and not just me ...
Admins are too busy ...

**Comment by Cruzix** [comment]
@shagu has nothing to do with the server, why even think about making a request for something you already knew was server related. geez.
