### ISSUE TITLE
spam error with last commit

### ISSUE THREAD

**Issue by KasVital** [shagu/pfUI#424]
![image](https://cloud.githubusercontent.com/assets/15636669/22619916/29eeed2a-eb10-11e6-8838-183e37b4db3e.png)
ruRU locale
mb
['OTHER_SPELL_HIT'] = "\"(.+)\" (.+) наносит %a+ %d+\ ед. урона.",
this fix it correct?!

**Comment by shagu** [comment]
Please check https://github.com/shagu/pfUI/commit/4b5926d9b8fe70746276aa6454c9df382b298c8c
