### ISSUE TITLE
Future enhancement suggestions

### ISSUE THREAD

**Issue by Voxnox1** [shagu/pfUI#425]
Thanks for this amazing addon! - it would be really nice to have the following options:

1) Option for a movable/resizable horizontal exp/rep bar
2) Option for an additional movable panel and option to disable/enable existing panels
3) Option to hide the chat tab names and chat button/chat forwarding button (only show on mouseover)
4) An indicator to show you are scrolled up in the chat
5) An option for a movable bag/inventory (with a panel to show gold amount)
6) Item slot quality colouring in the character/inspect panels
7) Auto sell junk / repair feature at merchants
8) pfUI theme skinning of UI panels (character,talents,spellbook etc)

Thanks again!

**Comment by Cruzix** [comment]
I like pretty much all of these requests, but you should make a issue request for each one of them instead. It'll make it easier for Shagu.

**Comment by shagu** [comment]
Hi, just what Cruzix said. The 8th point is btw. a duplicate and don't need to be created.
Thanks in advance.

**Comment by Voxnox1** [comment]
Will submit as individual requests. Thanks again Shagu!
