### ISSUE TITLE
chat: add scrollbar or indicator if scrolled up

### ISSUE THREAD

**Issue by Voxnox1** [shagu/pfUI#429]
Option to add an indicator to show you are scrolled up in the chat

**Comment by shirsig** [comment]
Just wanna highlight how useful this would be. Since after the history is maxed out the chat starts scrolling and old mesages apear as if they had been just posted this can lead to some embarrasment when replying to them.

**Comment by greenya** [comment]
I was investigating this issue, tried to do something.
Got this -- http://i.imgur.com/xQLOZwa.jpg

The good parts:
- pretty few changes in the chat module, and it handles all chat tabs;
- being a standard button, it does all correctly (e.g. when player press PgDn or mouse scroll hovering chat area, it handles all cases correctly and blinks);

The bad parts:
- the button not skinned for pfUI look (it has couple of layers as i understood, pressed, unpressed, hovered button states and a glow, when it blinks);
- doesn't disappear when nothing to scroll;
Please share if anyone knows the way to solve any of "bad" parts, or have other suggestions.
