### ISSUE TITLE
Add buffs, hots, debuffs to group/raid view depending on my class

### ISSUE THREAD

**Issue by knikat** [shagu/pfUI#43]
As a healer I want to be able to see my buffs, my hots and debuffs I can remove on group and raid frames so that I do not need to click on each player frame seperately to check if I need to (de)buff something.

**Comment by shagu** [comment]
Thanks, will be done soon :)

**Comment by Br4inworm** [comment]
Is it coming soon? That's something as a buffing class I miss the most compared to other raid frames. I will have to manually check every single player if my buff is still there. Thanks!

**Comment by shagu** [comment]
I don't know much about healing, so I'd need a list of hots and buffs that should be possible to display on the raidframe. So far, I only added some druid and priest spells. Buffs are only visible for the current class.

I made the following config options:
- Show Buffs
- Show Hots
- Only display Hots of my class

https://github.com/shagu/pfUI/commit/17b1386504e4570bb9b94e417eedba99a8c74d3b

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/0d24db8b3ff790630aac271305a418ef96a9b82d

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/b96c9ff4055e9349ee1ef14d6352ee42261b6624

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/d8efc2270c1e399e7d26e086492186d32e483d62

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/9f2920a4a4d1f14f73d0823b744687c0a091d1f4
