### ISSUE TITLE
skin: item slot quality colors

### ISSUE THREAD

**Issue by Voxnox1** [shagu/pfUI#431]
Item slot quality colouring in the character/inspect panels

**Comment by shagu** [comment]
will be related to https://github.com/shagu/pfUI/issues/224

**Comment by potty** [comment]
Is it also possible to show ilevel of each item in character panel? ElvUI enhanced for Wotlk has this option, but dunno if this info is available in vanilla API.

**Comment by Road-block** [comment]
> don't know if this info is available in vanilla API.

It is not 😄
