### ISSUE TITLE
vendor: auto sell / repair option

### ISSUE THREAD

**Issue by Voxnox1** [shagu/pfUI#432]
Auto sell junk / repair feature at merchants

**Comment by shagu** [comment]
note to myself, this will be a new module.

**Comment by Cruzix** [comment]
I'd prefer if you added an option to choose if it should sell upon pressing a button (just like SellValue does it) or auto sell when the vendor window opens. 
I'd much rather have to manually click a button for it to sell the grays :)

**Comment by shagu** [comment]
Good Point

**Comment by vashin1** [comment]
Can't wait for this Shagu,  RisenUI is no more! It's all about this now.

I really wish you took donations sometimes :(

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/546ce6287c72edf5e2f55b31eae7ad2ebce7c1ac
