### ISSUE TITLE
Bag Marker - hover over bag to highlight items inside that specific bag

### ISSUE THREAD

**Issue by Fapguy** [shagu/pfUI#433]
EngInventory does this, and is desperately needed for changing bags.
As it is now I have to disable both pfUI AND EngInventory because EngInventory is kinda stupid. (or maybe I am)

Maybe, you, the great and mighty all powerful magic coding king, could backport ArkInventory? I imagine that's a HUGE project.. (or somehow integrate current EngInventory and fix it's issues? *wishful thinking*)

Well, main issue is that pfUI doesn't have highlighting. I'll still be using EngInventory though, can't live without that auto sorting.

Thanks for an amazingly nice UI!

**Comment by shagu** [comment]
This has already been done months ago. https://github.com/shagu/pfUI/commit/d4f19f8007b56966abc961ba6abaaedae878fa09

**Comment by Fapguy** [comment]
oh.. weird.

I have the absolutely newest version but doesn't do that.

OH, doh, of course. I put the border size to 1, and that causes the borders to not show apparently.

Putting it to 2 puts it back :D

(I hate borders, want as small as possible..)
