### ISSUE TITLE
raid: add option to use horizontal layout

### ISSUE THREAD

**Issue by kxseven** [shagu/pfUI#437]
In the current code the raid frames are created as vertical stacks.

Suggested Change:
 - Order the raid frames so that they build in layers as the group grows
 - For 10-man raids there would be one layer
 - For 20-man raids there would be two layers
 - For 40-man raids there would be four layers

Example:
[http://imgur.com/a/WaWcY](http://imgur.com/a/WaWcY)

![image](https://cloud.githubusercontent.com/assets/11297100/22696867/87614b72-ed47-11e6-9eaf-0209b567f5fc.png)

**Comment by Cruzix** [comment]
Urgh this would be extremely confusing to me, and for healers. It's much better to have them ordered by group tbh. 
But I guess it wouldn't hurt to implement an option for it at some point.... but there's tons of other requests right now that I would say are far more important imho :p

**Comment by vashin1** [comment]
100% agree with Cruzix on this one.

**Comment by shagu** [comment]
I believe I won't spend any effort for this. People can use the unlock mode to achieve that
