### ISSUE TITLE
Slight grammar mistake in one of the first options people see when doing /pfUI

### ISSUE THREAD

**Issue by vashin1** [shagu/pfUI#438]
e9a19ae2e92fb3652b736466b06e5af27255ca2b

**Comment by shagu** [comment]
Do you have more of that? I would then change them all in one shot.
Thanks in advance

**Comment by vashin1** [comment]
I will go through all of them tonight when I get some time mate and provide you with the new file so you can diff and merge the changes.

I'm learning alot from pfUI Shagu, Thank you so much

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/c7d565b3af5b9101a738e2119391e97e546230fc
https://github.com/shagu/pfUI/commit/f0df9853135ee4c3a60f1955a4476127093fff8d
