### ISSUE TITLE
env/Fonts.lua:  Some lines need updating with recent changes

### ISSUE THREAD

**Issue by vashin1** [shagu/pfUI#439]
https://github.com/shagu/pfUI/blob/master/env/fonts.lua

looks to me there is some code here in need of an update Shagu.

`STANDARD_TEXT_FONT = "Interface\\AddOns\\pfUI\\fonts\\arial.ttf"`

to

`STANDARD_TEXT_FONT = "Interface\\AddOns\\pfUI\\fonts\\Myriad-Pro.ttf"`

and

```
 pfUI.font_default = "Interface\\AddOns\\pfUI\\fonts\\arial.ttf"
 pfUI.font_square = "Interface\\AddOns\\pfUI\\fonts\\homespun.ttf"
 pfUI.font_combat = "Interface\\AddOns\\pfUI\\fonts\\diediedie.ttf"
```

to

```
 pfUI.font_default = "Interface\\AddOns\\pfUI\\fonts\\Myriad-Pro.ttf"
 pfUI.font_square = "Interface\\AddOns\\pfUI\\fonts\\Homespun.ttf"
 pfUI.font_combat = "Interface\\AddOns\\pfUI\\fonts\\DieDieDie.ttf"
```

**Comment by shagu** [comment]
Oh Sorry. I totally forgot about those

https://github.com/shagu/pfUI/commit/58aae8dfd7de5da9cfab8c8a5c4303f807c7cc88
