### ISSUE TITLE
Cooldowns won't disappear after switching actionbars

### ISSUE THREAD

**Issue by Reiner88** [shagu/pfUI#44]
Wenn man mit Shift+Number die Actionbar durchschaltet, sieht man z.B. den CD von Seite 1 auf Seite 2, sofern sich auf Seite 2 an der Stelle wo der CD auf Seite 1 kein Skill mit CD befindet.

// edit: When changing actionbars, cooldowns won't be hidden if theres no spell on the new actionbar position.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/8703c2255939ebfa864497d7d5728f75f6653b18
