### ISSUE TITLE
Latest server maintenance broke the "Loot & Spam" channels

### ISSUE THREAD

**Issue by BewareOfPiranha** [shagu/pfUI#440]
The maintenance today broke the channels in the Loot & Spam window for me. No text is showing up despite all channels being activated. Tried resetting cache and toggle the chat pane on and off etc. Also tried leaving channels and joining again.
Thank you for an amazing addon.

**Comment by shagu** [comment]
vQueue?

**Comment by BewareOfPiranha** [comment]
No never used vQueue.

**Comment by shagu** [comment]
Could you please disable all addon beside pfUI and check if the problem still persists? Thanks in advance.

**Comment by BewareOfPiranha** [comment]
Your suggestion worked perfectly. The addon causing it was LazyPig.
As always, thank you so much Shagu!

**Comment by shagu** [comment]
You're welcome :)
