### ISSUE TITLE
New Chat Window Issue

### ISSUE THREAD

**Issue by Toups5** [shagu/pfUI#443]
When I try to add a new chat window "Guild/Whisper" I'm able to make it, however the messages goes into that window for my selection are not working properly.  Also when logging in, it defaults my chat window to that new one instead of General like normal. (I select Channels -> Guild, Whisper so they're active):
![setting](https://cloud.githubusercontent.com/assets/25284342/22795825/0fcec7ee-eec6-11e6-9b52-208fba55363e.jpg)
  

No guild messages (other than GMOTD) appear, and only outgoing whispers appear:
I'm tried enabling & disabling "change layout of incoming whispers" with no change.

Guild chat (shows nothing but motd):
![no-guild](https://cloud.githubusercontent.com/assets/25284342/22795781/e7e9d048-eec5-11e6-9a50-0635d076cb1d.jpg)

Whisper (only shows outgoing):
![only-out-whisper](https://cloud.githubusercontent.com/assets/25284342/22795799/f62398a6-eec5-11e6-8ea3-60abd1a0ad34.jpg)

**Comment by vashin1** [comment]
Hmm works fine for me,  you using prat or Chatsuey?

**Comment by Toups5** [comment]
Using chatsuey but issue persists even when its disabled.

**Comment by vashin1** [comment]
Try deleting chat-cache.txt from WoW/WTF/Account/*youraccount/*yourrealm/*yourchar/ and restarting the client and testing.

**Comment by Toups5** [comment]
Weirdly that made it worse - loot & spam turned into "chat3" and now contains nothing. Made a new window for guild/whisper and it doesn't contain GMOTD nor outgoing whispers now.

**Comment by shagu** [comment]
Hi, 
Please try to "Reset Firstrun" in your pfUI-settings, answer every question with "Yes" and then try again to apply your custom changes. 

Is there any other addon loaded that could interfere like Prat, ChatSuye, SpamFilters, LazyPig or vQueue?

**Comment by Toups5** [comment]
Got it.  Was an addon called "Chat Filter" that was embedded in another addon as a module.  Appreciate the help!
