### ISSUE TITLE
api: allow custom frame strata on movable frames

### ISSUE THREAD

**Issue by Toups5** [shagu/pfUI#444]
This is more of a enhancement request/idea.  I did it for myself by modifying some of the code.  

The idea is for the loot & spam window to have it's frame strata higher so it  covers anything in the bottom right (such as dpsmate & ktm like I'm using) so then "hide" triangle/arrow minimizes the loot & spam window to show what's behind it so they don't need to take up more room on the screen.  The bags had to have its frame-strata higher too so that opens up above the loot & spam. 

![image](https://cloud.githubusercontent.com/assets/25284342/22796004/c3fb8824-eec6-11e6-9de6-02ef2baf7a98.png)

![image](https://cloud.githubusercontent.com/assets/25284342/22796021/d28e5baa-eec6-11e6-909c-65cf05284c4e.png)

I modified modules/chat.lua line ~182 to:
```
  pfUI.chat.right:SetFrameStrata("MEDIUM")
  pfUI.chat.right:SetFrameLevel("100")
```

modules/bags.lua line ~198 to:
` frame:SetFrameStrata("HIGH")`

I also modified the positioning a little of the bag so it wouldn't cover the right panel info such as gold amount:
![image](https://cloud.githubusercontent.com/assets/25284342/22796128/3a4c6d18-eec7-11e6-856f-00c6160c58aa.png)

modules/bags.lua line ~184-189 now are:

```
  pfUI.bag.right:SetPoint("BOTTOMLEFT", pfUI.chat.right, "BOTTOMLEFT", 0, 19)
        pfUI.bag.right:SetPoint("BOTTOMRIGHT", pfUI.chat.right, "BOTTOMRIGHT", 0, 19)
        pfUI.bag.right:SetWidth(pfUI_config.chat.right.width)
      else
        pfUI.bag.right:SetPoint("BOTTOMRIGHT", UIParent, "BOTTOMRIGHT", -5, 18)
        pfUI.bag.right:SetWidth(pfUI_config.chat.right.width)

```

**Comment by shagu** [comment]
I'm working on an advanced unlock mode which allows you to set the FrameStrata of every frame directly. I believe it will make this change obsolete :) There's still alot to do, so I can't tell you when I'll be done with it.
