### ISSUE TITLE
nameplates: debuffs always visible

### ISSUE THREAD

**Issue by KasVital** [shagu/pfUI#445]
always shows debuffs at nameplates, fix:
nameplates.lua
line 323: `if pfUI_config.nameplates["showdebuffs"] == "1" then frame.debuffs[1]:SetPoint("TOPLEFT", healthbar.castbar, "BOTTOMLEFT", 0, -3) end`
line 331: `if pfUI_config.nameplates["showdebuffs"] == "1" then frame.debuffs[1]:SetPoint("TOPLEFT", healthbar, "BOTTOMLEFT", 0, -3) end`

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/6bbfee842079f994853cee28f947b738def496da
