### ISSUE TITLE
localization: translations for koKR

### ISSUE THREAD

**Issue by muter941** [shagu/pfUI#447]
Please support language Korean.
The many korean users want to use pfUI.
thanks. bye

**Comment by muter941** [comment]
hi shagu.
is it in progress?
what can i do help? i'm korean.

**Comment by gamer4eg** [comment]
need koKR Spell.dbc and GlobalStrings.lua for add spell name, and line for parser chat.
sry my english)

**Comment by muter941** [comment]
We are localizing in our guild.
Sorry to bother you. have a good day :)

**Comment by shagu** [comment]
I'd like to leave this open, as long as pfUI doesn't have koKR locales. If you made some, it would be great if you could share them.

**Comment by godtanker** [comment]
https://docs.google.com/spreadsheets/d/1II24oJbu9j38cDLnx78H0lGLBkEkaXJA3-PJ_LbiWvQ/edit#gid=1046393174

**Comment by godtanker** [comment]
this pics this koKR pfUI : http://cafefiles.naver.net/MjAxNzA0MTlfNTcg/MDAxNDkyNTMxMzcxNTkw.pOLk0-uzc904X9EAWwIztCwbJs1Pui5jvinwxnOLdMwg.sZuqPQIcu6lyh5vD5qAlQDXtKtafjik8rqBjNKvUe1og.JPEG.ll2j/2313.jpg

**Comment by shagu** [comment]
That's awesome, I'll try to add your changes soon :)

**Comment by godtanker** [comment]
There was no bug, and I used pfUI from the past. Korean Spell DB is still less complete.

**Comment by godtanker** [comment]
http://cafefiles.naver.net/MjAxNzA0MjFfMzMg/MDAxNDkyNzcwNDc2MjAx.5nRL9m7oLYmdBcM8wUlOp7_37nG7PdH-v9nT2zzi0p8g.2RuAerZ4E-vau-GCYcKMRUcfgWXSDKymoM3ed-MimLYg.JPEG.ll2j/poll.jpg
this pics check~plz

**Comment by godtanker** [comment]
group frame not hide :
http://cafefiles.naver.net/MjAxNzA0MjFfMjkx/MDAxNDkyNzcyMjYxMzI2.WCM7DNd7xxIUcP9wEvgIZmuP7KQWRFUTxtHIuTz8Yp4g.vDyL-YSiS6T9dCK9kSuflwsf6uWOjU-KlDgpWwHwp28g.JPEG.ll2j/23213.jpg

**Comment by shagu** [comment]
thanks, please check the update ;)

**Comment by godtanker** [comment]
thanks..shagu ..
youer korea name 상구 ^^*

**Comment by shagu** [comment]
I added the translations but wasn't able to test them because I can't find a download link to get a koKR-gameclient.

https://github.com/shagu/pfUI/commit/d80bb527bc161d78ef4d8f4a78ded355125cbdc1
https://github.com/shagu/pfUI/commit/bca1ae7616b911a22c3a18ca16ec94836e2ef1b4

'new-unitframes' branch is updated aswell :)

**Comment by godtanker** [comment]
vanilla wow client kr :
https://drive.google.com/file/d/0B6lZ3S7Jte22em5idjU0Sktidm8/view
Thank you for adding Korean version

**Comment by godtanker** [comment]
https://docs.google.com/spreadsheets/d/1II24oJbu9j38cDLnx78H0lGLBkEkaXJA3-PJ_LbiWvQ/edit#gid=815920986

**Comment by godtanker** [comment]
Korean wow users are grateful to pfUI. Thank you very much.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/6e7f34cff6f6c13676fd8ae4175e1399a046548d

**Comment by godtanker** [comment]
['wantBattleBerserkStance'] = "전투 태세 필요, 공폭 태세 필요", -->>['wantBattleBerserkStance'] = "전투 태세 필요, 광폭 태세 필요",

**Comment by shagu** [comment]
Now that I have a koKR-Gameclient, I was able to extract all spells from the client files. 
I'll update them in pfUI tomorrow :)

**Comment by godtanker** [comment]
ok thank

**Comment by shagu** [comment]
Here we go: https://github.com/shagu/pfUI/commit/afac8a0cb253cc05ed5da6f0e379d79877464b4f
Could you please have a look at the changes?

**Comment by godtanker** [comment]
OK

**Comment by shagu** [comment]
Just scroll through the changes and check if it makes sense, because I can't read any single word of this :-D

**Comment by muter941** [comment]
Shagu. thanks you so much :)
I want to know how to donate.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/d63162666208944c7f5e510934a2604d171c8c8c

> I want to know how to donate.
I really appreciate it, but I don't accept donations, just have fun :)

**Comment by godtanker** [comment]
@shagu (상구)After testing the new version, I will check for bugs and reply.
