### ISSUE TITLE
thirdparty: latest dpsmate version breaks the integration code

### ISSUE THREAD

**Issue by nummersyv** [shagu/pfUI#448]
[DPSMate](https://github.com/Geigerkind/DPSMate) has restructured their code into multiple folders instead of just a single one. After this code update pfUI doesn't seem to detect DPSMate anymore and won't reskin or integrate it.

**Comment by khalismur** [comment]
Ah so that's why I don't see DPSMate window.

**Comment by dakotarisen** [comment]
Shagu,fix this pls)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/30693b66ca9c1edecc3054635e235dbd9afb9a42

**Comment by Rewinding** [comment]
ETA on donate button? Desperately needed feature

**Comment by nummersyv** [comment]
> **How can I donate?**
> You can't. I'm doing that for fun. Enjoy!

**Comment by Rewinding** [comment]
I'm well aware, it was supposed to be a joke.
