### ISSUE TITLE
Improve Cooldown appearance and add option for enabling Global Cooldowns

### ISSUE THREAD

**Issue by Reiner88** [shagu/pfUI#45]
Es wäre gut wenn man eine Animation bei Skills wie z.B. Schlachtruf hätte wenn der CD refreshed ist, da der ja "Sofort" verfügbar ist, eine art aufleuchten oder einen kurzen glow effect um den Skill herum hat.

// edit: Would be nice to have an animation whenever a cooldown refreshes.
Additionally an option to reactivate the display of global cooldowns should
be implemented.

**Comment by Reiner88** [comment]
Sollte konkret den "Global CD" betreffen.

**Comment by Larsy93** [comment]
Something like the grey fade that goes in the circle behind the seconds counter

right now its like this
https://i.gyazo.com/84209c0acc3ea4fc1d2005997b35565d.png

Something like this would be neat
https://i.gyazo.com/c5a0d7935929eb8b8091812070237ea1.png

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/94001b41dab2eac688184cfb292d1a64ccf2999d
