### ISSUE TITLE
Chat: Add option to toggle "To" on outgoing whispers

### ISSUE THREAD

**Issue by hepkat** [shagu/pfUI#451]
I know there is an option to change the colors. Having an option to enable "To" on outgoing whispers again would be nice. It's less confusing when sharing screenshots with friends of whisper conversations.

**Comment by Cruzix** [comment]
There's already an option to change this, take a closer look at the settings.

**Comment by hepkat** [comment]
Must be in an update I haven't installed yet.

**Comment by Cruzix** [comment]
it's over a month ago he added the option as you can see in the link I provided

**Comment by hepkat** [comment]
Don't see a link, but yeah I'll update my pfUI immediately. :) Thanks

**Comment by Cruzix** [comment]
![image](https://cloud.githubusercontent.com/assets/6162744/23138988/951443c4-f7aa-11e6-8d3e-db0e51a862fc.png)

**Comment by hepkat** [comment]
![image](https://cloud.githubusercontent.com/assets/25138984/23139019/b2e35590-f767-11e6-9949-ebebab428c12.png)

**Comment by hepkat** [comment]
but #290 , got it.

**Comment by hepkat** [comment]
You updated your post. ;)

**Comment by Cruzix** [comment]
Yeah prior to me mentioning it
