### ISSUE TITLE
Hide Party Frames

### ISSUE THREAD

**Issue by chrheg** [shagu/pfUI#454]
There is a option under module to "Disable group" but then default Blizzard Group interface shows up.
You can disable Blizzards Raid interface but not group interface by any options.

This can be done by running /script HidePartyFrame() but would be nice to have the an option on the interface to disable it.

Might not be an issue for most but maybe nice to have.

**Comment by shagu** [comment]
This works as designed, because as long as the whole group module is disabled, there should not any code that impacts the group behaviour in any way.

If another addon than pfUI is used to display group-frames it's in this addons responsibility to take care of hiding blizzards groups or whatever.
