### ISSUE TITLE
cooldown.lua error, seems to be when I swap gear

### ISSUE THREAD

**Issue by vashin1** [shagu/pfUI#457]
Error: Interface/FrameXML/Cooldown.lua:10: attempt to index local "this" (A nil value)

seems to only be happening when I swap gear from the bank, swapping gear in bags seems fine.

**Comment by shagu** [comment]
I wasn't able to 100% reproduce this. But after alot of tries, I believe it's fixed with this commit https://github.com/shagu/pfUI/commit/aae7e034f3bb39cc24e6f3fe5b2fa33a042c06e6
