### ISSUE TITLE
Battlefield  ERRO!

### ISSUE THREAD

**Issue by aixiu** [shagu/pfUI#458]
ERRO:interface\AddOns\pfUI\api\api.lua:251:attempt to call method set backdrop (a nil value)

**Comment by shagu** [comment]
I wasn't able to reproduce this. But a fix that might be related is: https://github.com/shagu/pfUI/commit/ff1b7a56b44461eab435258116af0c71b281b6c3

Could you please check if the error still occurs on the 'master' branch?
