### ISSUE TITLE
Option to change buff positions on Playerframe

### ISSUE THREAD

**Issue by Reiner88** [shagu/pfUI#46]
Bei dem Playerframe wäre es gut wenn oberhalb die Buffs/Debuffs auch unter das Frame setzbar wären.

// edit: Would be nice to add an option to change the position of buffs/debuffs to the bottom
of the playerframes.

**Comment by Reiner88** [comment]
Und es wäre gut wenn die Buffs neben der Minimap verschwinden, sofern! die Buffs am Playerframe aktiviert sind.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/3bab0d0caad19f82937601e57bb62734c9a7d97f

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/1e749832d202ac94597244f89d207b380a5f506f
