### ISSUE TITLE
mouseover: command missing

### ISSUE THREAD

**Issue by Z1mmey** [shagu/pfUI#460]
Hey Shagu,

my /pfcast mouseover macros don't seem to work with the latest release.
They worked fine in cf915a20aeaf521c1dcc1528296357a1a1ffe0eb.

**Comment by Road-block** [comment]
Are you using CastModifier alongside pfUI by any chance?

**Comment by Z1mmey** [comment]
No, just the plain /pfcast macro.

**Comment by shagu** [comment]
Any error message?

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/65b18a51253219d274a5961cc44bb6bf45347d96
