### ISSUE TITLE
Can't loot disenchanted things

### ISSUE THREAD

**Issue by elenmerbau** [shagu/pfUI#461]
In 1.6 I cant loot nothing from loot window after disenchanting, it just popups and stays, escape helps to close it, after what disenchanted things appear in the bag. But I can loot if I disenchant anything equipped on me. After farming a lot of greens accure in the bag and disenchanting becomes very annoying because of pressing esc after each thing. I tried to reser pfui, to turn off all other addons, to reinstall, nothing helped.

**Comment by Road-block** [comment]
I had a similar problem (must be a closed ticket) but I don't remember if it was something I did (or a conflicting addon).
I'll search my tickets.

**Comment by Road-block** [comment]
Found it: https://github.com/shagu/pfUI/issues/299
Do you use Clean_Up? Did you notice if you had locked bagslots?

**Comment by elenmerbau** [comment]
Yes, I do, gonna turn it off, thank you. Hope fix will come soon.

**Comment by shagu** [comment]
This is not directly related to Clean_Up, instead it also occurs without any addon loaded:

[![video](https://img.youtube.com/vi/zECZNqtFFqk/0.jpg)](https://www.youtube.com/watch?v=zECZNqtFFqk)

As I'm **only** doing addons, I won't fix your servers code.
