### ISSUE TITLE
loot: sometimes the window does not update after looting

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#464]
sometimes an item stays in the loot frame even after it's looted

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/issues/461
https://github.com/shagu/pfUI/issues/299

**Comment by shirsig** [comment]
They seem more related to the other issue I just made. This has nothing to do with autoloot or disenchanting. I've had it happen when manually clicking (i think always the bottom most) items to loot.

**Comment by shagu** [comment]
which server? tried without addons? tried without any other addons than pfUI? does it always happen?

**Comment by shirsig** [comment]
think I last saw it on zeth'kur. Haven't tried without other addons but don't think any of the ones i have should interfere with it. I noticed it while doing deadmines for twink gear so I was looting a shitload of stuff and it happened only rarely.

**Comment by crumdidlyumshis** [comment]
I bet I know what this is. I could possibly be related to server lag. Sometimes when you get a super bad lag spike, your character will loot a corpse and then looting another corpse doesn't update the loot table. Could be entirely wrong. Just thinking aloud.

**Comment by shagu** [comment]
Server related.
