### ISSUE TITLE
chat: add more font-sizes to dropdown menu

### ISSUE THREAD

**Issue by Nordrassil** [shagu/pfUI#469]
An option to separately change font size for the chat windows would be great.

The default chat windows only allow the size down to 12, whereas I'd really like to set it lower, like at 8 or 10.

Tried editing this in the chat lua, but it doesnt seem to work.

**Comment by shagu** [comment]
If all of your font's are too big, you might want to change the UI-Scale instead.
As I use Wow's default ChatFrames, it would be confusing having pfUI overwrite the settings in the dropdown. I'll need to evaluate if I'm able to add another fontsize to the original dropdown menu.

**Comment by Jabark** [comment]
I'd like to increase the size of the chat window(s) font, but I can't see where to do it?

**Comment by Cruzix** [comment]
@Jabark You change it the same way as if you were using stock UI.

**Comment by Jabark** [comment]
@Cruzix when you say 

> stock UI

, I'm guessing you mean the default Blizzard UI? If so, please forgive the noob question but how do I do that? 😆

**Comment by Cruzix** [comment]
@Jabark right click the chat taps O.o

**Comment by Jabark** [comment]
@Cruzix Hmm, I did try that and nothing happened. I'll have another go later I guess 😕.

**Comment by Jabark** [comment]
Alas, I was right clicking on the window itself, you're supposed to right click on the tab header itself 😕 .

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/ae291b316566d508fa2a983ce633278ca4871845
