### ISSUE TITLE
Addon Support (Thirdparty)

### ISSUE THREAD

**Issue by Reiner88** [shagu/pfUI#47]
MobInfo2/MobHealth
KTM (Threatmeter) (Aggrometer)
Atlas (+Loot)
Auctioneer
Cartograper (ShaguQuest)
Equip Compare
Enhanced Tooltip
Gatherer
Quest Announcer

**Comment by shagu** [comment]
MobHealth is already supported. For each of the other ones, please make an proposal how you want it to be "integrated".

**Comment by Reiner88** [comment]
Vom Frame her, in diesem Schwarzen Simple Stil
und EQ Compare vielleicht als Standard Funktion in einem UI, genau wie Quest Announcer.

Aber bei MobInfo werden im Tooltip keine Details angezeigt (Loot, Mana, usw.)
