### ISSUE TITLE
Menus look different - Screenshots included

### ISSUE THREAD

**Issue by Formyndare** [shagu/pfUI#470]
Hi I updated my PFUI along with a couple of addons and my menus changed from this 

![](http://puu.sh/utsgX/d14e514618.jpg)

to this

![](http://puu.sh/utsgE/73ce509131.jpg)

How can I resolve this?

EDIT: My current addons are as follows 

![](http://puu.sh/utqQM/2bd6895f24.png)

**Comment by shagu** [comment]
> How can I resolve this?

You'll have to find out which of your new addons causes this, and create an Issue on their bugtracker.

**Comment by Formyndare** [comment]
I was hoping for some help identifying what I am looking for/what could affect this part of the UI or SOME direction. The SUB menus are fine but not the first one:

![](http://puu.sh/utFZ1/8b7ca59798.jpg)

**Comment by Formyndare** [comment]
Found it - It was Aux (the AH addon) for future reference and to help anyone else in future with this issue! You can close/mark resolved sorry for the trouble.

**Comment by Formyndare** [comment]
@shagu with shaguQuest and the autotracker function I am experiencing lag/stutter as described in this thread https://community.mmobase.de/addon-lounge-entwicklung-support/8269-%5Baddon%5D-shaguquest-ein-datenbank-quest-addon-f%FCr-1-12-a-6.html

I am thinking it is simply because the autotracker updates after EVERY mob kill, and changes shaguDB map colours etc. Would it be possible to ONLY autotrack when quest is picked and completed?

This would improve performance a LOT.

**Comment by Formyndare** [comment]
@shagu no reply on this?

**Comment by shagu** [comment]
I'm sorry, I dont't have the time to further improve ShaguQuest, as long as there aren't any gamebreaking bugs and errors. With the performance improvements I made between 7.0 and 7.2 I wasnt able to see any behaviour like this, because quest updates got a flood protection and only show a limited result. Where does this happen? Which quests are in the Log? Which Version is installed?

**Comment by Formyndare** [comment]
Shagu 7.2 (downloaded less than a week ago) quests in darkshire was when me
and my friend noticed - After every mob kill relevant to a quest the game
stutters for half a second, when you turn autotrack off it no longer
happens.

It is definitely related to ShaguQuest and Autotrack. I just think it would
be greatly improved by an option to ONLY update the shaguDB display on the
map when quests are accepted and completed rather than after each single
mob kill, is this possible for you to do?
