### ISSUE TITLE
tukui preset player/target castbars 

### ISSUE THREAD

**Issue by prov1dence** [shagu/pfUI#473]
If tukui preset for unit frames is selected, player/target castbars  always returns to default position after trying to move them. Default positions of castbar blocks hp flat/percentage value of the target, target name.

_btw tukui health/name string also overlaps buff, if they set to show on bottom on player/target frames.
It's like that name-hp bar hight is not counted for anything_ 
**default**
http://i.imgur.com/S7fC1Gm.jpg

**trying to move them**
http://i.imgur.com/G0sTBGy.jpg
http://i.imgur.com/0r9eLyw.jpg

**and they back**
http://i.imgur.com/MUzBcsO.jpg

**default pos overlapping name/hp**
https://i.imgur.com/JIN8UJe.jpg

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/75dbf3d096e0a0361b0c15b81433d1a58c19ee1c
https://github.com/shagu/pfUI/commit/93d073d53ff5c2f006427c584307652dda2448b1
