### ISSUE TITLE
loot: rename option to auto-loot BoP items

### ISSUE THREAD

**Issue by vashin1** [shagu/pfUI#478]
For whatever reason, this doesn't seem to work for me.  I'm not in a party at all and right clicking a loot frame doesn't loot it, still have to hold shift and loot.

**Comment by shagu** [comment]
Guess I'll have to rename it. It is used to disable the "do you really want to loot the BoP item?"-dialog. Suggestions welcome.

**Comment by vashin1** [comment]
Disable loot confirmation dialog when solo ?

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/8b460e3d67f505741edfd3570a54d76a68549bc1
