### ISSUE TITLE
transparency of unit frame indicators

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#479]
When a party member is out of range it has reduced transparency. I think this should not apply to the indicators (like party leader, loot master)

Also, indicators appear on multiple frames sometimes, but this may be a server issue?

**Comment by Road-block** [comment]
I've noticed that with the leader indicator at least.  
On Elysium realms at least leader is jumping around when crossing an instance portal which is probably a bug, but whatever the reason leader indicator shows on both the new and old party member.

**Comment by shirsig** [comment]
The leader jumping thing is definitely a server issue though

**Comment by shirsig** [comment]
And it's the actual leader that changes

**Comment by Road-block** [comment]
> And it's the actual leader that changes

Yes but I meant that the problem with duplicate indicators is very obvious that way.

**Comment by chrheg** [comment]
Elysium Latest Updates | April 04, 2017 - Group leadership should no longer change players when zoning

**Comment by shagu** [comment]
The transparency works as intended,
