### ISSUE TITLE
unitframes: add a focus frame

### ISSUE THREAD

**Issue by Kalty** [shagu/pfUI#480]
I start using FocusFrame addon. It is really superb addon for focus function, but im curious if is any chance to reskin this frame.

addon github: https://github.com/wardz/FocusFrame

Thanks

**Comment by shagu** [comment]
With the latest changes I made for the new unitframes, it was quite simple to add a focus frame. But I'm not yet sure where to place it, every suggestion welcome :)

**Comment by Kalty** [comment]
Superb. I think left-up from player frame maybe.

**Comment by Road-block** [comment]
Since focus is kinda like a "stored target" I think some spatial relation to the target frame makes more sense.

**Comment by shagu** [comment]
That's the default position right now:
[1](http://i.imgur.com/tNtK2Sr.jpg)

**Comment by shagu** [comment]
New Unitframes now Available on `master`
