### ISSUE TITLE
skin: special mini-frames

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#482]
There are some rare small frames like the timer for a quest, the breath indicator breath, the exhaustion when far out in the sea and also the battleground map (which behaves wonky in all kinds of ways too). These all lack the pfUI theme and look rather out of place. A possible improvement for the map: 
![1](http://i.imgur.com/dP43TQS.jpg)

I wouldn't except you to change larger frames as they're often the target of specific other addons which could cause chaos, but these are passive and rather not very featureful so likely few addons for them.

**Comment by Cruzix** [comment]
Any chance you could take a screenshot of that forum post? I don't have a Kronos account so I can't view and prefer not to create one

**Comment by shagu** [comment]
> Any chance you could take a screenshot of that forum post? I don't have a Kronos account so I can't view and prefer not to create one on their forums
fixed.
