### ISSUE TITLE
gui: full localization

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#483]
Dear Shagu
Add please feature localization for settings

**Comment by shagu** [comment]
Puh.. We'll see

**Comment by shagu** [comment]
Api provided, now it's your turn ;)

https://github.com/shagu/pfUI/commit/5832215f9550caea42f612daeaee3518681123b6

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/d16441a29e631eb2d36c840590d712f3cead5d8a
