### ISSUE TITLE
unitframes: option to replace current health with health deficit

### ISSUE THREAD

**Issue by Niapants** [shagu/pfUI#486]
As a healer, I'm more interested with how much health a player is missing than how much they currently have.  It helps me to select the best type and rank of heal.

An option to replace current health with health deficit whilst in a party would be very helpful.

**Comment by Rewinding** [comment]
Go to Pfui settings, Unit Frames - Raid - Tick "Show Missing Health" box

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/issues/40

**Comment by shagu** [comment]
New Unitframes now Available on `master`
