### ISSUE TITLE
addon conflict: eqcompare

### ISSUE THREAD

**Issue by Larsy93** [shagu/pfUI#487]
https://i.gyazo.com/57ddcbe72504b9ab8b05007e6907188a.png

**Comment by shagu** [comment]
reproducable with http://addons.us.to/addon/eqcompare

**Comment by shagu** [comment]
Tagging this as "enhancement" rather than as "bug" because pfUI already includes a built-in equip compare and also the thirdparty addon "EquipComare" works without any issues.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/d158955eb306e3f00890a3d4d278df1ab5d33e1a
