### ISSUE TITLE
chat: Identifiable Class Color is inconsistent in Chat

### ISSUE THREAD

**Issue by jpcenac** [shagu/pfUI#490]
I can update with a picture when i'm home but i'm at work right now so hopefully I can explain it through text.

In the chatbox when a character has typed something in trade chat for example, more often than not their character Class Color is not shown, unless I /who or shift click on their name, only then will it become observable on their next entry.

**Comment by shagu** [comment]
The addon needs to cache the characters class first. There's nothing I can do.
