### ISSUE TITLE
group: add option to show all buffs / debuffs

### ISSUE THREAD

**Issue by Druas** [shagu/pfUI#491]
I would like them to show up. Curses, disease, magic, etc. Am I the only who cannot see group members debuffs in the group window? Maybe I don't know how to enable them?

**Comment by shagu** [comment]
Right now, there's only an option to tint the group members color based on the debuff they have 
(e.g green if poisoned)

**Comment by Druas** [comment]
OK how do you do that? I mean it doesn't solve the problem, but at least it's better than nothing.

**Comment by shagu** [comment]
UnitFrames -> Raid -> Show Debuff Indicators
UnitFrames -> Group -> Enable RaidFrames Debuff Behaviour For Group Frames

**Comment by Druas** [comment]
I don't know if I'd say that this is solved.

**Comment by shagu** [comment]
New Unitframes now Available on `master`
