### ISSUE TITLE
META: New UnitFrames Issues

### ISSUE THREAD

**Issue by shagu** [shagu/pfUI#494]
If you experience any new issues that have been introduced with the 'new-unitframe' ([branch](https://github.com/shagu/pfUI/tree/new-unitframes)) changes, Please report them within this ticket.

This is how to get it:
![1](http://i.imgur.com/dULJF58.png)
![2](http://i.imgur.com/STox0iG.png)

A beta release will be made soon.

Thanks in advance.

**Comment by godtanker** [comment]
New UnitFrames  i can not see group pet
http://cafefiles.naver.net/MjAxNzA0MjJfMjg1/MDAxNDkyODQ2ODYzMzEw.lYlwsGEpkEng1de2MKKUQd5vC6SCQh77Lxyp7MOuG8gg.ft6j4XwDcT9wD0XneQJiBP1_KJoOnkVdqLsx-5UPmbMg.JPEG.ll2j/aa.jpg

**Comment by shagu** [comment]
Affected Issues: https://github.com/shagu/pfUI/milestone/4

**Comment by Rewinding** [comment]
Increasing healthbar with on raidframes disrupts the alignment and makes the unitframes overlap which makes the "padding" between raidframes pointless.

**Comment by Rewinding** [comment]
Increased load times during /reload, one of these reloads caused my game to crash and for some reason reset my pfui settings completly.

**Comment by shagu** [comment]
> Increasing healthbar width on raidframes disrupts the alignment and makes the unitframes overlap which makes the "padding" between raidframes pointless.

Thanks, I'll fix that

> Increased load times during /reload, one of these reloads caused my game to crash and for some reason reset my pfui settings completly.

I'll have a look

**Comment by Rewinding** [comment]
Sorry, going to test more stuff soon! Just haven't had much time to set things up properly and changing things mid-raid with the potential crash on /reload made me revert to the regular one.

**Comment by shagu** [comment]
> Increased load times during /reload, one of these reloads caused my game to crash and for some reason reset my pfui settings completly

I had a look at this and it really increased from 0.20 seconds to 0.40 seconds, the module that increased the most is "gui" which makes sense, because it now contains more than twice configuration options. I wasn't able to achieve a crash there at all - so this won't be a blocker to roll the new features out to the master branch.

**Comment by Road-block** [comment]
Just a note that the first place to look for hard-crashes of the client, is :SetPoint() or similar (OnDragStart/Stop handlers are typical cases) with bad or absent parent/child frame relations.   
It's actually pretty easy to intentionally crash the client that way.

**Comment by crumdidlyumshis** [comment]
@Road-block Thank you so much for pointing this out! I have been working on the [ElvUI-TBC](https://github.com/ElvUI-TBC) backport version for 2.4.3 client and have had some super bad crashes lately reloading the UI. I know it has to do with the code cause the client works fine when the addon is not loaded. I had no idea until I read your comment. :) Great work @shagu on this addon and all the updates you have put out! Keep it up!

**Comment by shagu** [comment]
> Just a note that the first place to look for hard-crashes of the client, is :SetPoint() or similar (OnDragStart/Stop handlers are typical cases) with bad or absent parent/child frame relations.
It's actually pretty easy to intentionally crash the client that way.

Thanks, I'll check that. :)

**Comment by sulowitch** [comment]
there are some problems with setting portrait with custom color+background in player,target and pet frames.

![11](https://cloud.githubusercontent.com/assets/28542140/25819145/4c77bb5e-342d-11e7-96d6-152f3f46833e.jpg)

**Comment by shagu** [comment]
> there are some problems with setting portrait with custom color+background in player,target and pet frames.

Could you please tell me exactly what you did there?

**Comment by sulowitch** [comment]
my bad, sorry. i have copied new frames now and after login cant see target and my frame.
![33](https://cloud.githubusercontent.com/assets/28542140/25820617/3b0fe904-3432-11e7-8e31-43b700ce2a7d.jpg)
default settings.first login. need to delete some folders for fresh "instal"?

**Comment by shagu** [comment]
> need to delete some folders for fresh "instal"?

No, but you'll have to restart the game, a relog won't be enough.

**Comment by sulowitch** [comment]
not working after restart.
![33](https://cloud.githubusercontent.com/assets/28542140/25820920/4cb1357c-3433-11e7-9589-264ab2c48b38.JPG)

**Comment by shagu** [comment]
> not working after restart.

Gimme 10 minutes

**Comment by sulowitch** [comment]
![33](https://cloud.githubusercontent.com/assets/28542140/25821346/0890eaf2-3435-11e7-9a63-c4dcb75450ac.JPG)
same problem, diffent number.

**Comment by shagu** [comment]
> same problem, diffent number.

Did you checked to not have whitespaces in your settings? It looks like you have some bad characters within the buffsize field.

**Comment by sulowitch** [comment]
everything working after "reset config". Gonna delete my profile because as you said, i have for sure some messed up settings there.

**Comment by shagu** [comment]
> everything working after "reset config". Gonna delete my profile because as you said, i have for sure some messed up settings there.

At least pfUI has now more checks to be more robust, thanks for your help.

**Comment by sulowitch** [comment]
again same problem :) 
![33](https://cloud.githubusercontent.com/assets/28542140/25822801/2bf901d2-343a-11e7-9fa7-8b6347cca021.JPG)
player buff position "hide" is doing that.

**Comment by shagu** [comment]
> player buff position "hide" is doing that.

Thanks alot! It's fixed now, but you'll have to manually change it from "hide" to "off" in the settings now.

**Comment by Rewinding** [comment]
> Thanks for your input here, I really apreciate it. I had a look at this and it really increased from 0.20 seconds to 0.40 seconds. The module that increased the most is "gui" which makes sense, because it now contains more than twice configuration options. Optimizing the gui module is on the roadmap but will be another topic.. I wasn't able to create a crash there at all - so this won't be a blocker to roll the new features out to the master branch.

Yes that unfortunately comes down to bad testing from me since i should really do it with only pfui and nothing else enabled.. but my testing is done live mostly so there are some addons i don't want to disable.

**Comment by Rewinding** [comment]
Minor strange bug..

As a priest i have buff indicators on raidframes showing 3 things, priest buffs, priest hots and druid hots.
Sometimes priest skill renew or druid skill rejuvenation jumps inbetween the Fortitude and Spirit buff.. estimate it to be about 10-20% of the times (sample pool around 100). 

Absolutely no clue what causes it.. just a minor annoyance.

**Comment by Rewinding** [comment]
Another point.. might be me being blind but i'm sure i saw pet raidframes a few weeks ago and now i can't find it anywhere? looked through settings very closely several times. I still have group pets but not raid pets.

**Comment by shagu** [comment]
> Just a note that the first place to look for hard-crashes of the client, is :SetPoint() or similar (OnDragStart/Stop handlers are typical cases) with bad or absent parent/child frame relations.
It's actually pretty easy to intentionally crash the client that way.

There were issues with the party-pet frames, that have been solved now :)

> Another point.. might be me being blind but i'm sure i saw pet raidframes a few weeks ago and now i can't find it anywhere? looked through settings very closely several times. I still have group pets but not raid pets.

I never did raid-pet frames yet.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/733be72b21caf6a44a9da87b715b4e6b1af685e2
