### ISSUE TITLE
can enable LazySpell

### ISSUE THREAD

**Issue by korolevlong** [shagu/pfUI#496]
there is a mouseover cast addons,
[https://github.com/satan666/LazySpell](url)
can support this?
thank u.

**Comment by shagu** [comment]
Shouldn't this already work with a Clique version that supports pfUI?
https://github.com/shagu/Clique

**Comment by gamer4eg** [comment]
Could you modify Clique to make it work with the shortcut keys like Q+LKM,E+PKM and so on?

**Comment by shagu** [comment]
No, I'm not interested in any Clique development.

**Comment by gamer4eg** [comment]
Well, here's another option:
I just implement it via LazyScript =).
https://github.com/shagu/pfUI/issues/504
