### ISSUE TITLE
Pressing 'R' to reply to a whisper causes an 'r' to appear in the WIM input field

### ISSUE THREAD

**Issue by caspervk** [shagu/pfUI#497]
Pressing the 'R' key to reply to a whisper causes an 'r' to appear in the WIM input field, which have to be deleted before you can begin typing your intended message.

I only have two enabled addons: pfUI and WIM. The issue is gone when disabling third-party support for WIM under pfUI settings.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/ec4c3419519455b81ad3b264c6b5bed80a5eeed5

**Comment by caspervk** [comment]
You have no idea how long this has been bugging me for. Thank you very much for this, and for your many other great AddOns!
