### ISSUE TITLE
help : ShaguQuest and ShaguDB -translations for koKR

### ISSUE THREAD

**Issue by godtanker** [shagu/pfUI#498]
so~~~~~~~~~~~many DB file ㅜㅜ;;
i'm work ShaguQuest and ShaguDB -translations for koKR need, vendorDB,questDB,itemDB,spawnDB all kokr db lua file or MangosZero Localised Korean_Quest file

ty ..

**Comment by shagu** [comment]
https://github.com/shagu/ShaguQuest/releases/tag/8.0loc

Please use the ShaguQuest Issue tracker in future. :)

**Comment by godtanker** [comment]
ty
