### ISSUE TITLE
About ShaguQuest

### ISSUE THREAD

**Issue by jokers-x** [shagu/pfUI#500]
How long does it take you to export itemDB from mangos?

Only spawnDB need to use aowow.sql?

I have successfully exported Chinese vendorDB.lua and questDB.lua with questDB.php vendorDB.php.

This Addon very nice,I want to use CWOW.

Thanks.

**Comment by shagu** [comment]
https://github.com/shagu/ShaguQuest/releases/tag/8.0loc

Please use the ShaguQuest Issue tracker in future. :)
