### ISSUE TITLE
chat: error when someone on friendlist goes online/offline

### ISSUE THREAD

**Issue by Voidmenull** [shagu/pfUI#501]
Interface/AddOns/pfUI/modules/chat.lua:408:table index is nil

**Comment by nguyetr3** [comment]
reopen!
![image](https://cloud.githubusercontent.com/assets/3873023/25727737/393d7222-312b-11e7-859e-83d8dcee5999.png)

**Comment by shagu** [comment]
Does it happen on all of your characters? did you tried that with a default config? did you ran the firstrun dialog? which other addons are loaded?

**Comment by nguyetr3** [comment]
yea is happen with all my char, i tried reset all config.
i will post list of addon when i come home

**Comment by nguyetr3** [comment]
Questie
ShaguUI
KTM
Informant
HealComm
EquipCompare
Decursive
CCWatch
BigWings
Cartographer
Cartographer_Mining
Cartographer_Herb
AtlasQuest
AtlasLootEnch
Atlas
TheoryCraft
SuperInspect
SpecialTalent
SimpleFeignHealth
Sellvalue
Pingy
MasterControlProgram
LazyPig
FlightMap
ExtendedQuestlog
CT_MailMod
CorpseInfo
CopyCat
CasterStats
BonusScanner

**Comment by shagu** [comment]
Did you already tried to disable all addons beside pfUI? which Version of pfUI do you have?

**Comment by nguyetr3** [comment]
*ShaguUI_WIM

i just tried Disable all exept
pfUI and ShaguUI_WIM

now when someone go online/offline
![image](https://cloud.githubusercontent.com/assets/3873023/25770962/a30b2b18-3243-11e7-80f2-d4a05d0d4c56.png)

**Comment by Cruzix** [comment]
> verNo ... well i downloaded from Git as last ver 2 months ago?

Wouldn't it be logical to update your addon to check if the issue is still present at current version before reporting it then? >.<

**Comment by nguyetr3** [comment]
same with v2.2

**Comment by shagu** [comment]
Well, I now wasted two hours trying to reproduce this issue without any success. It's kinda frustrating that people want me to fix issues but don't provide usefull information on their own. Please, answer the following questions and enable me to fix the issue.

1. When did this happen the first time (Version)
2. What's the exact error message in the latest version (No matter if `2.2` or `master`, just tell me)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/592f4946d74bf2c66d04bfa78faed99439b8907f
