### ISSUE TITLE
Raidframes: add aggro notifier on raidframes units 

### ISSUE THREAD

**Issue by Sascal** [shagu/pfUI#502]
Like grid and lunaUF do, when players have aggro their respective raidframe units have a red notifier on them such as a red dot(on lunauf) or surrrounded by a red outline (Grid). This would really help healers to prevent sudden deaths in raid :P.

**Comment by chrheg** [comment]
This would be really nice to have 👍

**Comment by shagu** [comment]
Now Included and working :)
