### ISSUE TITLE
Modification of BigWigs

### ISSUE THREAD

**Issue by chaph** [shagu/pfUI#503]
There's no current use for the BigWigs you included in the addon on the elysium project (Which is, by far, the biggest vanilla server currently)

Can you replace it with Hosq BigWigs that has updated WORKING timers for the server. I believe this will yield an overall higher satisfactory rate of your UI.

This is the link to his addon: https://github.com/Hosq/BigWigs

**Comment by shagu** [comment]
I don't include any addons.
