### ISSUE TITLE
LazyScript support

### ISSUE THREAD

**Issue by gamer4eg** [shagu/pfUI#504]
add to raidframes support lazyscript mousover comand 

> spellTargetUnit=mouseover
targetUnit=mouseover

for healers can use lazy for healing with pfUI raidframes
Link to addon https://github.com/laytya/LazyScript

**Comment by Murkchan** [comment]
mouseover is a UnitID, so you can type a comand 
>spellname(rankN)@mouseover-

**Comment by shagu** [comment]
I don't understand the purpose of this issue.

**Comment by gamer4eg** [comment]
LazyScript's mousover mode does not work with pfUI frames (The same problem that was with Clique)

**Comment by shagu** [comment]
Sorry, I'm not going to fork LazyScript.
