### ISSUE TITLE
fonts: add option to choose default game game fonts

### ISSUE THREAD

**Issue by cocochepeau** [shagu/pfUI#505]
Hello,

Could it be possible to let us choose between pfUI fonts and **actual game fonts**?

Thanks for the awesome UI!

**Comment by smurfu** [comment]
Or better yet, load any font we want into the fonts folder?

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/e8e5b72d9694d6e393ea2def6db61fdb8e18cdb0
