### ISSUE TITLE
Group/raid frames: Fake Death

### ISSUE THREAD

**Issue by Murkchan** [shagu/pfUI#508]
Sometimes useful to know if hunt is realy dead or fakes death.
I suggest it should be a huge icon of FD buff on a frame.

**Comment by shagu** [comment]
same as https://github.com/shagu/pfUI/issues/210 ?

**Comment by t3hWheez** [comment]
This could be considered the same issue.  As a healer, its hard to know if a Hunter is FD or dead without looking at chat.  I'd love for the healthbar to change color or something and continue to show their current HP.
