### ISSUE TITLE
Make Mail Notification more visible

### ISSUE THREAD

**Issue by Reiner88** [shagu/pfUI#51]
Die Post Anzeige auf de MiniMap besser ersichtlich machen, z.B. einen leuchtenden Rand um den Briefumschlag oder überlappend auf der Minimap anzeigen, oder sogar direkt extern.

// edit: The mail notification should be more "visible", by adding a glow or something like that to the mail logo.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/4f6917ecd9e4a862b93956054b5a5edf44148159
