### ISSUE TITLE
Ability to change transparence of all ui by hotkey

### ISSUE THREAD

**Issue by byaka** [shagu/pfUI#514]
For me it can be useful while in town...

**Comment by shagu** [comment]
Create a macro like this, if you want to change the transparency of all UI:
```/run a = (not a and true) or nil; if a then UIParent:SetAlpha(.3) else UIParent:SetAlpha(1); end```

Replace `.3` with whatever transparency you like.

**Comment by byaka** [comment]
@shagu, thx for solution!
