### ISSUE TITLE
raid: make it easier to sort raid frames

### ISSUE THREAD

**Issue by Xpenzz** [shagu/pfUI#516]

**Comment by shagu** [comment]
suggestions?

**Comment by Xpenzz** [comment]
Well right now you have to sort one raid frame bar to another.. Maybe if you could make the groups move together

**Comment by nesherman** [comment]
Would personally love if:

1) The groups moved together
2) Option to invert the current group growth (right now 1st player is at the bottom and 5th player is at the top)

Sort by class would also be helpful I imagine for some people.

**Comment by Xpenzz** [comment]
Yeah that would really make it alot easier.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/ee37452615898cd3029bb6b797ad093c1dbc5fa9

Subgroups can now be moved together using the "Ctrl" key.
