### ISSUE TITLE
Portraits for Groupframes not working when in range

### ISSUE THREAD

**Issue by moootv** [shagu/pfUI#517]
When in range to groupmembers, portraits are not working. When out of range (like >30 yards), they are working.

Server: Kronos
Tested it on several clients/characters, without other addons. Fresh install of WoW.
https://gyazo.com/5b5579f11c084c3f6691ec90a5af85ee

**Comment by moootv** [comment]
The branch new user-unitframes fixed it.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/a7f6e0abe15a0bc131d841955bd0a848e092523f
