### ISSUE TITLE
gatherer: nodes don't show up when tooltip is set to cursor

### ISSUE THREAD

**Issue by smurfu** [shagu/pfUI#518]
Normally, Gatherer for vanilla will mark the location of a node when a harvest attempt is made. Gatherer will even mark the node's position if the character does not have the skill required to harvest. 

However, when using pfUI, and when the tooltip is set to "cursor", the node's location is not marked if the character's skill is not high enough to harvest. The location is still marked when a harvest is possible.

However, I like to mark nodes that I can't harvest for future reference.

My current workaround for this is to put the tooltip into a mode other than "cursor".

**Comment by shagu** [comment]
That's strange.. Will have to look into the gatherer source code... :'(
