### ISSUE TITLE
chat: add possibility to copy everything

### ISSUE THREAD

**Issue by Xpenzz** [shagu/pfUI#519]

**Comment by byaka** [comment]
Hey, check ShaguCopy  in  https://github.com/shagu/ShaguCollection, it solves this problem for me.

**Comment by Xpenzz** [comment]
Thanks

**Comment by gamer4eg** [comment]
This function may drop FPS to 2-5 (if faster combat log)
Need option for NOT copy combat log

**Comment by Cruzix** [comment]
@gamer4eg or just an option to disable this feature entirely. I won't be using this feature at all so having FPS drops from it would suck :p
