### ISSUE TITLE
Add Stopwatch and Countdown to Panel

### ISSUE THREAD

**Issue by Reiner88** [shagu/pfUI#52]
Unten rechts bei der Uhrzeit evtl. wieder wie bei ShaguUI eine "Stoppuhr" einfügen oder sogar einen Countdown. Oder sogar einen Reminder?

// edit: Add a stopwatch and countdown to the panel.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/a9466660d46c97cf1acef338ff4c01940bcfd395

**Comment by shagu** [comment]
I won't make a countdown. Stopwatch should be enough.
