### ISSUE TITLE
[Suggestion] Swing Timer

### ISSUE THREAD

**Issue by nesherman** [shagu/pfUI#521]
Attack Bar Timer or Abar have not been updated in a very long time and nobody has taken on a reliable **dual weild** swing timer in recent history. It would be invaluable to have this, though I'm sure the work involved would not be easy.

A humble suggestion. Love the UI.

**Comment by byaka** [comment]
It would be cool. For now i'm use https://github.com/EinBaum/SP_SwingTimer
For me it worked for Rogue, but ofcourse with mistakes.

**Comment by nesherman** [comment]
Unfortunately this only works for your main hand.

**Comment by byaka** [comment]
Yes, it really pain in my ass...

**Comment by nesherman** [comment]
The fact that nobody has revamped a swing timer addon is an anomaly to me. It's so critical.

**Comment by byaka** [comment]
Maybe nobody use it, only we? xD

**Comment by nesherman** [comment]
All of our top DPS uses it. Surely someone in the world wants a completely functional swing timer with a command system that isn't completely archaic? Idk maybe you're right. It might just be us. Still, it's so critical for top level play.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/issues/244
