### ISSUE TITLE
[UI Error] Caption & Cast Bar for Target Frame on Tukui is larger than Player Frame

### ISSUE THREAD

**Issue by nesherman** [shagu/pfUI#523]
The caption space for the Target Frame is a couple pixels taller than the Unit Frame.

This is also the same for the Target Cast Bar.

Using the "new-unitframes" branch

**Comment by nesherman** [comment]
Going into the LUA I noticed this:

pfUI.uf.target.caption:SetHeight(C.global.font_size + 3*default_border)

pfUI.uf.player.caption:SetHeight(C.global.font_size + 2*default_border)

**Comment by nesherman** [comment]
However when I fix these, it does not fix the mismatched height of the castbars.

**Comment by shagu** [comment]
Could you please provide screenshot? With default settings, the tukui mod looks just fine for me.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/ec6bcf4eb7f3aa6b6bc516205f9c587b25582478

Could you please describe what you mean with "mismatched height of castbars" ?
Both castbars are using SetAllPoints to the caption, so they shouldn't be larger than their parent.

**Comment by nesherman** [comment]
What I mean is that the cast bar for target frame is taller than the cast bar for player. However, when I correct the values above I don't get the error.
