### ISSUE TITLE
cooldown: add option to change fontsize

### ISSUE THREAD

**Issue by moootv** [shagu/pfUI#525]
Please let us configure the size and font of cooldown numbers (for actionbars, buffs and debuffs)

**Comment by nesherman** [comment]
Please!

**Comment by shagu** [comment]
sure

**Comment by moootv** [comment]
I also suggest to have the option to only change the chat-fontsize. Atm i only can change it down to 12 pixels. But i would like to have the chatfontsize at 10 pixels.

**Comment by shagu** [comment]
@moootv, this is already tracked here: https://github.com/shagu/pfUI/issues/469

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/9a2993450e45915fa3a84a0c0752bb665426997b
