### ISSUE TITLE
Branch [new-unitframes] missed some 3rd-party integration?

### ISSUE THREAD

**Issue by byaka** [shagu/pfUI#526]
Tested this branch - it's amazing!
But i missed integration with debufftimers (your fork) and MobHealth3. No errors.
With master it's works!

**Comment by nesherman** [comment]
Also missing the debufftimers here

**Comment by shagu** [comment]
Thanks.

https://github.com/shagu/pfUI/commit/8a5be9b23b3feffb2e2d348540ac2f1e09ec9b03
https://github.com/shagu/pfUI/commit/e22048fc84f0f5b6d59352c5da65b275cda9d7d8
