### ISSUE TITLE
[new-unitframes] Combo-point Sizing

### ISSUE THREAD

**Issue by nesherman** [shagu/pfUI#527]
Combo points set to odd integers (size 3, 5, 7, 9, 11...etc) add a 1 pixel black buffer to the right-side of the combo point frame. Nothing game-breaking, just a little unsure whether this is intended.

<img width="45" alt="screen shot 2017-05-21 at 2 08 45 am" src="https://cloud.githubusercontent.com/assets/28659816/26281613/706ede2e-3dca-11e7-8172-407312ce0d36.png">

**Comment by nesherman** [comment]
Actually, I might redact this and say that there is some odd rendering involved with the borders. I've tried using some even integers and there are still some irregularities with the borders & dimensions.

**Comment by nesherman** [comment]
<img width="39" alt="screen shot 2017-05-21 at 2 14 23 am" src="https://cloud.githubusercontent.com/assets/28659816/26281630/3ba87564-3dcb-11e7-9725-28cd3a3c4700.png">
Set at size "10"

**Comment by byaka** [comment]
@nesherman, like it! where i can change this value?
Also i'm changing [this](https://github.com/shagu/pfUI/blob/master/modules/target.lua#L351 ) (or [this](https://github.com/shagu/pfUI/blob/new-unitframes/modules/combopoints.lua#L39) for branch "new-frames") to '5' so only fifth combo-point will be green. In my opinion it more senseble.

**Comment by shagu** [comment]
This is related on how the gameclient scales its interface. Theres nothing I can do here. If you're playing at 1080p you could try the "pixel perfect" mode which should fix this by mapping the internal resolution to the current screen resolution (only for fullscreen).

related issue: https://github.com/shagu/pfUI/issues/106
