### ISSUE TITLE
[new-unitframes] Tukui Unit Frame Buffs & Debuffs Set To "Bottom" Overlap w/ The Text Plate

### ISSUE THREAD

**Issue by nesherman** [shagu/pfUI#528]
<img width="197" alt="screen shot 2017-05-21 at 2 24 43 am" src="https://cloud.githubusercontent.com/assets/28659816/26281677/ab91c82a-3dcc-11e7-8716-e459a91c51fc.png">

**Comment by shagu** [comment]
Thanks

https://github.com/shagu/pfUI/commit/f93019e723a2a32b75c6d60cf773fceeaf6e1385
https://github.com/shagu/pfUI/commit/d2f12f041977c47df35f21c4a8f30b61831bdf1d
