### ISSUE TITLE
Forward whisper

### ISSUE THREAD

**Issue by Reiner88** [shagu/pfUI#53]
Wozu ist eigentlich diese Funktion im linken Chatfenster oben rechts? Ne Sprechblase mit 2 Pfeilen drin wenn ich das richtig sehe. "Forward whisper to" "flüstern weiterleiten zu ... wie funktioniert das und welchen nutzen hat das?

// What is the whisper forward?

**Comment by shagu** [comment]
It's not an Issue. Please write an eMail, ingame message or send me a PM on any of the private server boards, if you have questions.
Nevertheless, this is used by people that use 2 accounts at the same time.
Let me show you an example:
Your main is logged in, just idle in ironforge. 
Your twink is beeing activly played by you. 

The Problem: Your Main will receive all the messages as nobody knows your twink.
The solution: Forward whispers from your main directly to your twink.
