### ISSUE TITLE
Branch [new-frames].  What this overlay-colors mean and how to disable it?

### ISSUE THREAD

**Issue by byaka** [shagu/pfUI#530]
![scr0](https://cloud.githubusercontent.com/assets/1580811/26287793/eeb497ea-3e8a-11e7-8513-dfebdabb5ca7.png)

i'm talk about this yellow overlay above my frame and frame of my group mamber. Somitems i see it in another color, also in my target.

**Comment by shagu** [comment]
It's the debuff indicator, that can be disabled in the settings. 

Blue for magic, Green for Poison, Purple for curse, Orange for disease and Red for every thing else.

**Comment by byaka** [comment]
Thx!
It's interesting realisation... What happened, if char poisoned and cursed at same time?

**Comment by shagu** [comment]
![1](http://i.imgur.com/W7vncaP.png)

**Comment by byaka** [comment]
Cool!

**Comment by shagu** [comment]
related: https://github.com/shagu/pfUI/issues/201
