### ISSUE TITLE
Nameplates causing extreme lags when checking for certain debuffs.

### ISSUE THREAD

**Issue by Rewinding** [shagu/pfUI#532]
I found two cases where nameplates can cause high fps lag (freezelag or down to 1 frame every third second or so).

First case was during AQ40's gauntlet part where you AoE the scarabs. The AoE itself has little to 0 impact on my fps but when the scarabs start to die my game freezes up completly or drops to extremly low fps. (This was completly nullified when disabling nameplates) Same thing happens when you AoE the whelps in bwls suppression room but it seems to not be as bad there as in aq40.

Second case is also in AQ40 at the Anubisath Defenders after Huhuran, immense FPS lag (same as when the scarabs die) occur ONLY when the Defenders use the plague spell, causing me to believe it has to do with it checking for cooldown of plague spell or something like that. Disabling nameplates removes the lag ALMOST completly, i still however experience some lag when they use plague, but it is nowhere near what i experience with nameplates enabled. 

The lag ONLY occurs when they use plague spell, making me think it has to do with it specifically. 
Another note is that i never "show" nameplates in PvE, but since it's enabled in the backround i still experience the lag. I have to disable it completly for the changes to happen.

Sorry for long text, i am really bad at explaining things and wish to make sure i'm not misunderstood.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/848c20e26cf1a4fc9bf7d6db56c54c0f233544df

**Comment by shagu** [comment]
Did you already tried with the latest `master`-branch? 
There was some nameplate optimization 19 days ago.

**Comment by Rewinding** [comment]
Tried it but no help i'm afraid, seems there is another culprit besides nameplates possibly. Tricky to figure out exactly what since i only do these packs once a week :)

**Comment by Rewinding** [comment]
The parts on C'thun where he does green eye beam also causes lag. Similarly to the defenders using plague and i believe they may be related. The lag goes away completly when he does the red eye beam that circles the room or any "phase" when the green eye beam isn't used. Maybe has to do with reading mob targeting? Don't really know.

I've been trying to narrow it down what's causing it but doing trial and error testing during boss fights isn't very satisfying. Wish there was a test enviroment for this.

**Comment by shagu** [comment]
Are you sure this is related to pfUI and has nothing to do with the lags that appear on some servers if the view distance is set to max. in certain areas?

**Comment by Rewinding** [comment]
I cannot be 100% sure, but in a large stake bet i would without a doubt put my monet on pfui being the culprit. 

Last C'thun fight it got to a point where i felt so useless i wiped my wtf and interface and added Cthunwarner, Luna(very old version), Bigwigs, Mobhealth, Supermacro, Detox, C'thunwatcher, Lazypig and MSBT i then copied over WTF settings for everything but Luna and experienced the fight with 0 lag. It was horrible still horrible to play with an UI like that, but atleast i could actually do something and not lag whenever there was a phase with green beams.

If you want il try my normal UI with view distance lowered but i'm on skype during these fights with a friend who also had viewdistance max who experienced 0 lag. I should perhaps include that i currently don't use 40yard rangecheck or anything so that's unrelated to the lag.

**Comment by shagu** [comment]
Thanks for your detailled report, highly appreciated. Could you pleaae try to disable the nameplate module next time during this certain zone?  And could you pleaae try to disable the castbar module for the raid after?

This is to check if this is either related to the nameplate scanning or the combatlog parsing. 

Thanks in advance

**Comment by Rewinding** [comment]
Will do!

**Comment by shagu** [comment]
Any updates on this one?

**Comment by Rewinding** [comment]
Sorry no updates, more or less quit vanilla temporarily. My guild fell apart and i had no interest in adjusting to a new one.
