### ISSUE TITLE
[new-unitframes] Cursor Tooltip - Enemy Tooltip Is Showing Even When Cursor Is Right-Clicked

### ISSUE THREAD

**Issue by nesherman** [shagu/pfUI#536]
A bit invasive while raiding. I'll right click on the middle of my screen for the whole raid and enemy tooltips will show up wherever the depressed cursor is. Does not seem to happen for friendly players or NPCs.

**Comment by shagu** [comment]
Sorry, I don't understand

**Comment by shagu** [comment]
As discussed on discord chat, I'll close this issue. 
Please reopen, if it should happen again and you were able to record the strange behaviour.
