### ISSUE TITLE
Castbar in Cartographer visible

### ISSUE THREAD

**Issue by TilmanK** [shagu/pfUI#537]
![wowscrnshot_052517_205722](https://cloud.githubusercontent.com/assets/8856390/26521227/9e46ec4c-42e3-11e7-9c73-553d475e6b51.jpg)

See Screenshot. On all my chars the castbar text in cartographer is visible.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/97a07b7ac0348fbc42fb5cebd1a9e310dde12b6d
