### ISSUE TITLE
When you planning to merge branch[new-unitframes] to master?

### ISSUE THREAD

**Issue by byaka** [shagu/pfUI#539]
I use only this branch since last week (so 12 days) and it's really amazing! Don't want to return to "old" master, but master have new releases with new fixes and feautures... So whan u plan to merge them, or what you need to complete before it happened?

**Comment by shagu** [comment]
I don't know yet, it's more like an extended test phase before merging such a huge change. I want to make sure that everything and every setting works as expected.

Nevertheless, the `new-unitframes` branch is always rebased ontop of the latest `master` branch. If you're doing a git-pull or just download it again, you should have all changes that have been made on `master`.

**Comment by byaka** [comment]
thx @shagu, this solution that what i wanted.
And really big thanks for your work, this addon is best UI for me!
