### ISSUE TITLE
Keep Chat Channel after writing

### ISSUE THREAD

**Issue by Reiner88** [shagu/pfUI#54]
Wenn man z.B. "/5" (World) eingibt und dort schreibt und abschickt, darauf aber wieder dort schreiben will, öffnet sich nur "/s", besser wäres es aber den zuletzt benutzen Channel wieder aufzugreifen.

// edit: After typing in /5 the next chat input should be opened in /5 instead of /s

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/issues/289
