### ISSUE TITLE
Disabling Module:FirstRun in chat.lua

### ISSUE THREAD

**Issue by samishii23** [shagu/pfUI#541]
Disabling first run in the module list seems to cause a fairly major crash in the UI.
Disabling most of the UI modifications.
[Screenshot](https://drive.google.com/file/d/0B19GXkSGJLPjWFFWSHlhTW5qcUU)

> ERROR: Interface\Addons\pfUI\modules\chat.lua:2: attempt to index field `firstrun' (a nil value)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/c7adb0244f19d330c79340ab5266aa07d43003b9
