### ISSUE TITLE
Castbar: Text and time overlap

### ISSUE THREAD

**Issue by TilmanK** [shagu/pfUI#542]
I have all fonts to "Expressway" in General settings. Font size is 12. This causes the text to overlap with the remaining cast time on the cast bar.

![wowscrnshot_060117_093633](https://cloud.githubusercontent.com/assets/8856390/26669421/10691e62-46ae-11e7-938a-2f266d61d257.png)

**Comment by vashin1** [comment]
https://github.com/shagu/pfUI/commit/c02f39e2154f15a2fcfc6496767def776f2855e3

set the font to 10 or 11 as a temporary fix until Shagu implements some sort of total font control within the GUI, there are currently alot of static fonts in pfUI and this is the method I used to get the castbar the way i wanted in my personal UI
