### ISSUE TITLE
fonts: add option to only change pfUI fonts

### ISSUE THREAD

**Issue by TilmanK** [shagu/pfUI#543]
I have all fonts to "Expressway" in General settings. Font size is 12. In the character menu the tabs at the bottom are too wide when having a pet (this occurs for my Warlock and my Hunter).

![wowscrnshot_060117_093633](https://cloud.githubusercontent.com/assets/8856390/26669489/5d8103ae-46ae-11e7-9bf7-170a04d31fef.png)

**Comment by shagu** [comment]
What do you expect?

**Comment by TilmanK** [comment]
My expectation would be to limit the font size so that the tabs aren't oversized. Actually even nicer could be a rework of that window (idk if possible).

Well, I guess there is no really graceful approach to this.

If you are able to set the font size for those texts explicitly, one way would be to set a maximum value that cannot be overridden by the user for the affected fonts. Without trying, I assume that there are also other texts that would overlap (i.e. in the shown character tab) when increasing the font size.

This might on the other hand be a bad solution if there are users, that want to choose bigger fonts over tidyness. You could therefore introduce an option that explicitly disables those max values.

In fact this needs probably a lot of testing, since there will be different max sizes for each font.

**Comment by shagu** [comment]
If the UI-Scale is set correctly, there won't be any unreadable text on the screen.
I won't and can't treat people like a child and check **every possible setting-combination** beforehand. 
People will always have the freedom to change whatever they want. Even if it breaks something.
It's not in my responsibility to forbid users to do whatever they feel like and if someone wants to use a 100-pixel border around everything, then I'm totally fine with that.

But there's a valid point, I could add an option to not use the selected font-size for non-pfUI elements.

**Comment by shagu** [comment]
I don't think I'll ever do this
