### ISSUE TITLE
Branch New Unitframes still 2.4

### ISSUE THREAD

**Issue by moootv** [shagu/pfUI#544]
The newest release is 2.5, but the Branch New Unitframes is still 2.4, can you update it as well?
I still have to use the branch because of the combopoint feature.

**Comment by byaka** [comment]
> because of the combopoint feature
can u pls axplain what feature u mean?

**Comment by moootv** [comment]
movable/resizable combopoint frame.

**Comment by byaka** [comment]
ah, thx

**Comment by shagu** [comment]
done
