### ISSUE TITLE
HealComm Issue

### ISSUE THREAD

**Issue by t3hWheez** [shagu/pfUI#548]
When using your Clique and casting on raid frames, the incoming healing always shows as casting on myself instead of the target.

**Comment by shagu** [comment]
This is a bug in the stand-alone HealComm Library. And can't be fixed within pfUI. You'll have to wait for Aviana to update his library or use this fork in the meantime: https://github.com/shagu/HealComm

The fork includes the latest Version of HealComm which is currently only available in LunaUnitFrames.

**Comment by t3hWheez** [comment]
I will switch this when I get home.  Thanks
