### ISSUE TITLE
Unitframes: Add range fading range

### ISSUE THREAD

**Issue by MiniLel** [shagu/pfUI#550]
Can you add Rangefading on unitframes in raids, Coustomisable range fading

**Comment by MiniLel** [comment]
I mean so it would be possible to chose when  when raid/party frames fade like if you would like them to fade when they are 30 yard 40 yards etc :)

**Comment by shagu** [comment]
The 40y Rangecheck can be activated here: ![1](http://i.imgur.com/CS8TiH5.jpg)

And if a Unit should fade or not, can be set for each type here: ![2](http://i.imgur.com/t6ZHZOu.jpg)

What is missing?

**Comment by MiniLel** [comment]
Hmm i dont think we understand eatchother now. i will clarify me self
I mean it would nice to have like cousumisable range fading like if i want party frames to fade at for say 20 yards or 30 yards or 40 yards or for the sacke 100 yards is it possible to do that? so it would be totally custamizable if you want it to fade 39 yards etc.

**Comment by shagu** [comment]
Well, You can't do that. All I have is this function: http://wowprogramming.com/docs/api/CheckInteractDistance

It returns me if the player is in:
1 = Inspect, 28 yards
2 = Trade, 11.11 yards
3 = Duel, 9.9 yards
4 = Follow, 28 yards

The 40y check is done by targeting everything around you and checking if the target is in range of a specific spell. (https://github.com/shagu/pfUI/blob/master/env/locales_enUS.lua#L30-L35)
