### ISSUE TITLE
No sound effect when selecting/switching target

### ISSUE THREAD

**Issue by FamitNostralia** [shagu/pfUI#551]
The target unit frame of Blizzard's default UI has a sound effect when player select/switch to a new target.

However in pfUI the sound is absent. This problem is widely spread in many unit frame mods.

Perhaps provide an option to turn the sound effect on?

**Comment by Cruzix** [comment]
Thats intentionally made that way, and imo a great enhancement.

I believe it has something to do with if you want nameplates with class color in vanilla then you will have to either mouseover or target them to be able to pick up the data. So what pfUI and other vanilla nameplate addons does it very quickly target players around you to get the data and then switch back to your previous target, and if the targeting sound was enabled that would get quite annoying really fast :p

I'm not 100% sure this is how it works, but its something along these lines as far as I could understand from someone with vanilla lua experience a few month back (possibly shagu?, cant remember who exactly)

**Comment by shagu** [comment]
As Cruzix said.
