### ISSUE TITLE
Nameplates Not showing enemy healing spells

### ISSUE THREAD

**Issue by KingLoki123** [shagu/pfUI#552]
Just noticed as i was tanking with this amazing mod that a lot of the heals that enemys cast do not show up on the nameplates like the other spells do ... was just wondering if there is a quick fix for this

**Comment by shagu** [comment]
I'd need to know which spells. People told me that on elysium sometimes the combat logs for enemy casts (especially on trash mobs) are missing. And as long as I can only rely on combatlogs to detect spells, there's nothing I can do for you.

If this happens for you over and over again with some specific spells, feel free to reopen with the following information:

- Missing spellname
- Your servername
- The language of your gameclient.
