### ISSUE TITLE
Vendor Trashing causes D/Cs

### ISSUE THREAD

**Issue by samishii23** [shagu/pfUI#554]
On the server I play on (Elysium), when you vendor over 9 grey items with your UI it causes disconnects. Perhaps limit the selling to 8 or 9 items, then just need the user to click a 2nd  time. Or add some kind of wait or timeout function to be able to sell all items with out disconnects.

**Comment by Road-block** [comment]
This was a bug from Nostalrius days.  
I had added a small throttle to [AutoProfit](https://github.com/Road-block/AutoProfit) for that same reason.  
It's the rate of vendor not the number of items sold.  
`TOOLTIP_UPDATE_TIME` (0.2 sec) has never disconnected me sofar. I think I tested with 0.1sec as well and it also worked but I went for extra safety, it's still fast enough (5items/sec)

**Comment by shagu** [comment]
_Note: Does not happen on `Nefarian`-Realm_

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/ff7fafda473de71ac93adfc71670a3f728d95da0

**Comment by shagu** [comment]
Tested on `Anathema` with 14 Items.
