### ISSUE TITLE
All unitframes have dissappeared after dowloading latest version

### ISSUE THREAD

**Issue by tmacg86** [shagu/pfUI#555]
Installed latest version, and I no longer have any unitframes, no player, no target, nothing

**Comment by samishii23** [comment]
try going into your wtf folder and looking for the pfUI files and deleting them to start from scratch.

**Comment by tmacg86** [comment]
I did that, and Once I change the width of the unitframes, they all dissapear

**Comment by shagu** [comment]
Make sure to only have numbers in the width (check to not have any whitespaces).
And Please scroll up the chatframe and tell us the error you see.

**Comment by tmacg86** [comment]
Ok this has fixed itself somehow, but now my castbar is behind my player and target unitframes, is there a way to make them come front?

**Comment by shagu** [comment]
No, you'll have to move it to somewhere else
