### ISSUE TITLE
unitframes: Debuffs not showing up on group

### ISSUE THREAD

**Issue by futjikato** [shagu/pfUI#557]
I dont see any debuffs as a paladin in the group window.
Looked into it and came across the fact that UnitClass doesn´t return the class name in upper case.

Is there something wrong on my end? 

![2017-06-10 14_52_12-world of warcraft](https://user-images.githubusercontent.com/1497821/27002934-6272d5a4-4ded-11e7-93ab-b13f1c7cd528.png)

**Comment by shagu** [comment]
UnitClass returns two values. Please try:
`/run a,b = UnitClass("player"); message(a .. " / " .. b)`

If you're on a german client, logged in as a hunter, the Function will return "Jäger" (a) and "HUNTER" (b).

Regarding the title: Which Debuffs are you talking about? The debuff Indicators (poisoned, cursed, ..) or the default debuffs?

**Comment by futjikato** [comment]
Ah sorry missed that second return value in the code. ty. not an issue
