### ISSUE TITLE
Some De-,Buffs are missing

### ISSUE THREAD

**Issue by Reiner88** [shagu/pfUI#56]
Manchmal werden Buffs & Debuffs nicht am Playerframe angezeigt, obwohl in der Config eingestellt.

// edit: Sometimes the Buffs & Debuffs won't be shown on the playerframe.

**Comment by shagu** [comment]
I'd need more information about that.

**Comment by Reiner88** [comment]
Ich kann leider keine Screenshots einsenden, trotz des korrekten Formats.
Aber um mal ein Beispiel zu nennen, z.B. "Verbände" haben ein CD und dieser CD bzw. Debuff, immer neben der Minimap angezeigt wird, aber nicht immer (irgendwann eben) über dem Playerframe.

**Comment by Reiner88** [comment]
Thema kann geschlossen werden, Fehler meinerseits erkannt. Alles korrekt dargestellt. Jedoch müssen die Buffs und Debuffs neben der Minimap ausschaltbar gemacht werden,  doppelt gemoppelt ist Sinnlos.

**Comment by shagu** [comment]
k
