### ISSUE TITLE
thirdparty: DPSMate Integration Appearance

### ISSUE THREAD

**Issue by t3hWheez** [shagu/pfUI#560]
I love that DPSMate is working with pfUI and its appearance seems to be functioning properly but was wondering if this look is intended or is a bug.  It shows a single column with bars only showing on 40% or so of the window.  Is the intention to create additional windows and have them next to the first?

![capture](https://user-images.githubusercontent.com/23520811/27101738-c3bf1a2e-5037-11e7-836b-47cbc45d5874.PNG)

Thanks

**Comment by byaka** [comment]
same for me...

**Comment by shagu** [comment]
It's pretty hard to maintain due to many different DPSMate versions out there, please tell me the version you're running.

**Comment by t3hWheez** [comment]
I had 122, checked the new version which is 123 and the same issue is happening.

**Comment by moootv** [comment]
I fixed it by deleting the pfui cache (via pfui interface).

**Comment by t3hWheez** [comment]
I tried that and it doesn't work but I've upgraded to v3.0.

**Comment by shagu** [comment]
Fixed in 3.1
