### ISSUE TITLE
META: Upcoming 3.0 Release

### ISSUE THREAD

**Issue by shagu** [shagu/pfUI#561]
Hi folks,
the current `master`-branch will be released as 3.0 soon.
Please give me some feedback (especially for the new Configuration-GUI).

Is there anything that **must** be fixed before releasing it?

If you don't have any unknown bugs and everything works fine for you, please put a "Thumbs Up" on this Issue. It would help me to get a rough overview.

Thanks in advance.

**Comment by shagu** [comment]
Will be fixed before: https://github.com/shagu/pfUI/issues/562

**Comment by t3hWheez** [comment]
Please update this issue when v3.0 has been released.

Thanks!

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/releases/tag/3.0

**Comment by Kalty** [comment]
Hi. I know its OT here but I cant find place for such question.
What is best procedure to upgrading pfui to new version? I have another addons with settings and dont want to setup all from beginning.

Is there any way to simplify this? thx

**Comment by byaka** [comment]
@Kalty, you simple remove old folder and replace it with new. nothing more!

**Comment by Kalty** [comment]
@byaka thx a lot!
