### ISSUE TITLE
Chat: Item name showing as player's name

### ISSUE THREAD

**Issue by jchiera** [shagu/pfUI#564]
When someone links an item in chat it shows as the player's name instead of the item name.

**Comment by jchiera** [comment]
Here's a screenshot. IT happens all the time no matter the item. 
![capture](https://user-images.githubusercontent.com/9950776/27258297-6277b19a-53c5-11e7-9073-a05b17b502cc.PNG)

**Comment by shagu** [comment]
It's prat, run `/prat playernames toggle`

https://github.com/shagu/pfUI/issues/68

**Comment by jchiera** [comment]
That was it, thank you! Sorry to waste your time.
