### ISSUE TITLE
autoshift: false removal of strike of the scorpok (same icon as moonkin form)

### ISSUE THREAD

**Issue by moootv** [shagu/pfUI#566]
Happened twice: When i autodismount (both times in combat), the Buff "Strike of the Scorpok" gets removed.
https://www.youtube.com/watch?v=GNp3NKxRJvs
It is at the beginning of the video.

I looked into the code of autoshift.lua

  pfUI.autoshift.buffs = { "spell_nature_swiftness", "_mount_", "_qirajicrystal_",
    "ability_racial_bearform", "ability_druid_catform", "ability_druid_travelform",
    "spell_nature_forceofnature", "ability_druid_aquaticform", "spell_shadow_shadowform",
    "spell_nature_spiritwolf" }

[Strike of the scorpok](https://vanilla-twinhead.twinstar.cz/?spell=10672) has the same texture as [spell_nature_forceofnature](https://vanilla-twinhead.twinstar.cz/?search=force+of+nature#spells) and it gets removed when dismounting.

**Comment by shagu** [comment]
Thanks for the detailled report, I'm going to find a solution for that.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/cbcd1177c65e9adba54a61c4d416217e9435d174
