### ISSUE TITLE
Error when disabling GUI

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#57]
When disabling the GUI in the settings you wont be able to open the settings again and you'll get this error when trying to open it http://imgur.com/a/ncDj4 so theres no way of enabling it again unless you delete your pfUI files in WTF/Account/AccountName/SavedVariables and WTF/Account/AccountName/ServerName/CharacterName/SavedVariables

**Comment by shagu** [comment]
Wow, disabling the GUI has disabled the GUI? That was unexpected... :-D

I'll close this one. See: https://github.com/shagu/pfUI/issues/59

**Comment by Cruzix** [comment]
Yeah I know its a bit silly, but i bet this will "trap" a lot of people when you can't enable it again in anyway other than deleting your savedvariables for pfUI so you gotta start from scratch customizing it again
