### ISSUE TITLE
Debuff/Buff hightlighting/filtering on unit frames

### ISSUE THREAD

**Issue by psykeat** [shagu/pfUI#575]
Hello Shagu,
big thanks aheads for all the effort you are putting into this project. The addons are so much more memory/cpu efficient than everything from way back then.

Is there any way to filter certain buffs/debuffs for the unit frames? For example as a combat rogue you pretty much only care about weapon buffs, slice and dice, rupture etc. When raidbuffed however you are sitting there with as much as 29 buffs. Slice and dice is pretty much all over the place in the unit frames.  Would it be possible to only show filtered/own buffs/debuffs?
Thanks in advance,
Jörg

**Comment by moootv** [comment]
I use(d) modifiedpowerauras, but since it is so buggy, i would love to have a native solution in pfUI.

**Comment by Razorwynd** [comment]
Somehow it would be nice to have a priority buff/debuff system similar to that of [enemyframes](https://github.com/zetone/enemyFrames), that only shows you one of a few select buffs/debuffs on both the  player and target frames.

**Comment by nesherman** [comment]
This feature would also be desirable to a number of other raiders I play with who also use pFUI.

**Comment by Razorwynd** [comment]
It seems like a quick and functional solution might be to only display buffs (and debuffs) whose remaining duration is shorter than a user-specified duration. 

All the buffs I want to see above my player unit frame are generally shorter than 60 seconds and all the buffs I never want to see above my player unit frame are vastly longer than this. 

Additionally it would serve to greatly minimize the clutter around player frames that can occur when fully raid buffed.
