### ISSUE TITLE
Interrupts don't show up as successful on enemy castbars

### ISSUE THREAD

**Issue by moootv** [shagu/pfUI#576]
Like written here https://github.com/shagu/pfUI/issues/327, this doesn't seem to be fixed for me (also for the target uniframe). I use 3.0
Also if i LoS a mob, and he moves before finishing the cast, the castbar.

I use the addon "SimpleCombatLog" - could this interfere somehow? https://github.com/Road-block/SimpleCombatLog

**Comment by Road-block** [comment]
@moootv It's not SimpleCombatLog. It doesn't modify the combat log messages it just formats them.  
pfUI at the moment only tracks specific interrupt actions.  
You're probably playing a class that has interrupts missing from pfUI's internal database.  
The vanilla client in general doesn't offer information (events) about interrupted casts for NPCs (which makes situations like enemy interrupting casts to move in LoS as you describe virtually impossible to track)  
You should mention your class and what abilities you are using to interrupt, that will help shagu look at adding them.

**Comment by moootv** [comment]
@Road-block Thanks for your answer. I use warrior (pummel) and rogue (kick).

**Comment by Road-block** [comment]
That's peculiar, those appear to be in [interrupts](https://github.com/shagu/pfUI/blob/master/env/locales_enUS.lua#L37)  
Are you using something that actually does modify the combatlog like SW_Stats?

**Comment by moootv** [comment]
Not to my knowledge, here a list of my addons:
```
_LazyPig: enabled
AtlasLoot: enabled
AttackBar: enabled
AutoBar: enabled
aux-addon: enabled
Banana: enabled
BetterCharacterStats: enabled
BigWigs: enabled
BuyPoisons: enabled
CThunWarner: enabled
Cartographer: enabled
Cartographer_Herbalism: enabled
CastModifier: enabled
ChatSuey: enabled
ChatSuey-ItemLinkHover: enabled
ChatSuey-Mentions: enabled
ClassicSnowFall: enabled
Clean_Up: enabled
DebuffTimers: enabled
DPSMate: enabled
EQL3: enabled
HealComm: enabled
KLHThreatMeter: enabled
KTMAutoHider: enabled
MikScrollingBattleText: enabled
MikScrollingBattleTextOptions: enabled
MinimapButtonFrame: enabled
MobInfo2: enabled
ModifiedPowerAuras: enabled
CECB_Options: enabled
npcscan: enabled
Outfitter: enabled
Postal: enabled
RingMenu: enabled
SimpleCombatLog: enabled
TrinketMenu: enabled
WeaponQuickSwap: enabled
WeaponRebuff: enabled
WIM: enabled
pfUI: enabled
ShaguInventory: enabled
VCB: enabled
SUCC-ecb: enabled
```

**Comment by byaka** [comment]
same problem for me. What is best way to list enabled addons?
also, please, add rogue's Gouge to list of breckers.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/b39337c61ec6b16f1405916d4afbeffeac8b94c6
