### ISSUE TITLE
New Nameplates Branch Errors

### ISSUE THREAD

**Issue by moootv** [shagu/pfUI#577]
I tested the new Nameplates Branch in a raid, you can see it here:
https://www.twitch.tv/videos/155860628

But it threw a bunch of lua errors during the whole raid in my chat, which is unfortunatelly hidden in the bottom left.
If i remember right, it was about thirdparty lua and tooltip lua etc.

I will give more info to you here, if i test it again.

**Comment by shagu** [comment]
Thanks for trying the branch, but without any further information, I cannot do anything here.

**Comment by moootv** [comment]
I did another raid, this raid i used the normal 3.0 release Version, but got the errors again:
https://gyazo.com/175db12ae1b509cfddf48732502b70d6
https://gyazo.com/16b4c4a50189fe601e22d0f30a2a2b28

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/f00660fc21b09043ce87ed6f586dade51774e6e6
