### ISSUE TITLE
focus frame: implement /clearfocus

### ISSUE THREAD

**Issue by Grookshank** [shagu/pfUI#581]
As far as I know, the only command the focus frame has is /focus. There is no command to explicitly clear a focus; instead you have to target nothing and then use the focus command. Sometimes this does get stuck and the focus can't be cleared. I cannot reproduce this always, but it seems to have something to do with a mob transitioning into another phase (e.g. on Onyxia).

Additionally, it would be comfortable to have a function to explicitly clear a focus, w/o having to clear your target. Other frames have a command /clearfocus for this.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/17ccda5db60c861ebf34f16999705e672ae29bcf
