### ISSUE TITLE
Error loading macro tooltip

### ISSUE THREAD

**Issue by Grookshank** [shagu/pfUI#582]
When I mouseover one of my macros on my action bar, I get the following error:
ERROR: Interface\AddOns\pfUI\modules\tooltip.lua:94: attempt to concatenate local `name' (a nil value).

The macro is named "pet" and has the following macro text in it:
/script PetAttack(target)
/script CastPetAction(9)

I cannot reproduce this with any other macro I have.

The problem seems to start after while, but then continuosly happens till I log off. I could not track down what makes it start. The macro itself works fine.

I use the laster snapshot (but happened with 3.0 too).

**Comment by Grookshank** [comment]
Ok, I found the reason. It happens when I have no pet and no buff from a pet killed by Demonic Sacrifice. Once I summon a pet again, the error goes away; when I dismiss it, it comes back.

**Comment by shagu** [comment]
I'm not able to reproduce this on my warlock. Do you have any other addons active that might interfere?

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/e90f9e3ad7505badb9f8d778bb54d8d40bb5ef65
