### ISSUE TITLE
Some problems in raid

### ISSUE THREAD

**Issue by Vltnrch** [shagu/pfUI#588]
Since the 3.0, when I am in raid, heals does not display on the good player, I do not see either heals made by other players
I cannot either inspect, I have the message "Out of range" while I am against the character whom I wish to inspect...
Some members of my guild tell me that when they click on me, they see in target of the target (thus my target) I target extremely quickly on all the members in looped.
I cannot either attack in mellee, I go out of fight, well before to put the blow, as if I targeted somebody else

**Comment by shagu** [comment]
40y check enabled?

**Comment by Vltnrch** [comment]
Yeah, the "Agressive check"

**Comment by Vltnrch** [comment]
Ok thanks, it works better but the unit frame is "grey" if > 30 yard without.
