### ISSUE TITLE
Gathering nodes not showing on minimap sometimes

### ISSUE THREAD

**Issue by woopydalan** [shagu/pfUI#589]
Hello,

When I hover my cursor over the minimap to identify an herb that I want to pick up, I find that often the name of the herb will not show up. This has been happening in AV as well as outside.

**Comment by byaka** [comment]
also cant reproduce. what addons, that works with minimap, u use?

**Comment by woopydalan** [comment]
I think just gatherer

**Comment by shagu** [comment]
Related? https://github.com/shagu/pfUI/issues/518

**Comment by woopydalan** [comment]
my skill is max

**Comment by woopydalan** [comment]
Turned off gatherer, still have the issue. Maybe a coincidence, but in AV when there were only a few players I had no problem, but when many players joined the raid then the problem came back
