### ISSUE TITLE
Modules depend on each other and often can't be disabled seperatly

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#59]
When disabling chat in the settings it'll disable everything but action bars and give this error: http://imgur.com/a/8Pt0z

**Comment by Reiner88** [comment]
Try to deactivate all Addons instead of pfUI and try again

**Comment by Cruzix** [comment]
Same error without any other addons on and yes its the latest version

**Comment by shagu** [comment]
Disabling single modules is still very - and I mean VERY - experimental. 
I haven't found any time to add a big-red-warning yet. Sorry for the confusion.

Nevertheless, as another task I want to minimize and clear the dependencies between the modules.
So the content of your screenshot is still very helpful.

Thanks for contributing and trying out things :)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/1712b3a0989bc5678fc70d06f0096a4883a04fb0

**Comment by shagu** [comment]
pfUI-UnitFrames can now be disabled within the config GUI.
https://github.com/shagu/pfUI/commit/0dac5bc1e0b632163631e503f35b58aab2cbaf6f

**Comment by Cruzix** [comment]
Do you have any intentions of looking into this issue anytime soon? :) 

This issue is a bigger problem now than it will be in the future for me at least, because currently theres a few modules that dosnt quite offer the customization that I need it to have and I know it will take a while before those modules will be polished so until then it would be nice to be able to disable them and use other addons for its place temporarily especially since Nost release is right around the corner now

**Comment by shagu** [comment]
I totaly understand. I've planned to do this during the christmas time.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/b592949133136ec64b21657ac54c15d514e2e320
https://github.com/shagu/pfUI/commit/8d6407e8bd508f7432dd3f13e44e5fc14fad8633
https://github.com/shagu/pfUI/commit/5cdd890f233d31963b092a031e17abde89e31621
https://github.com/shagu/pfUI/commit/9d568e830f152e2f9ca4f1d2187ca49cfd0581f5
https://github.com/shagu/pfUI/commit/9163caf18c6dbe528d8a6fcdbc40ea56fea6c9c7
https://github.com/shagu/pfUI/commit/e43b1906bd5baf4a1843557a57059e61a3fea05e
https://github.com/shagu/pfUI/commit/4442f3f738b0baaeb1d6ac827ac18453fe227c17
https://github.com/shagu/pfUI/commit/8700478453fdafb32038d8f51db4abc5d6737592
