### ISSUE TITLE
[Suggestion] Option to show status text for rage/energy/mana 

### ISSUE THREAD

**Issue by woopydalan** [shagu/pfUI#590]
Hello,

I think it would be a good idea to allow the unit frame for the player to show how much rage/energy/mana (allow to disable mana but show rage/energy for druids) as a number, such as 6/100 or something like that. 

Thanks

**Comment by shagu** [comment]
You're already able to change your textfields to show rage or focus in a format like "6/100"

**Comment by woopydalan** [comment]
Is there a way to show it on the energy bar? Rather than the health bar. And to show for rage/energy but disable for mana?

**Comment by shagu** [comment]
Yes, you'll have to download the latest
