### ISSUE TITLE
[suggestion] target-of-target health percent

### ISSUE THREAD

**Issue by woopydalan** [shagu/pfUI#591]
Hello,

I think it would be nice to be able to show the target-of-target health %, for example as a healer I am mostly targeting a tank, and it would be nice to know what health the boss is at without having to click on the boss.

Thanks

**Comment by shagu** [comment]
You're already able to show target-of-target health percent.

**Comment by woopydalan** [comment]
found it, but I think it would be better if the percent wrote on top of the target name, often I cant see the percent because the name is covering it up
