### ISSUE TITLE
actionbar: show reagent count on buttons

### ISSUE THREAD

**Issue by RBO85** [shagu/pfUI#592]
Would be great if you add a function that would add the number of reagents left for spell on the toolbar. Like the addon BlindFlashCount does for Flash Powder on the Vanish spell. 

Using the BlindFlashCount addon does however not look good together with the cooldown timer.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/1405832085ced46c74b99de6df0e6c2cd946c3fb

**Comment by RBO85** [comment]
Thanks for adding this option. I have one more request on it though. Is it possible to hide (or make it more transparent) the reagent count when it is on cooldown? Right now, especially on low counts, the numbers overlap on the action bar as seen on the screenshot. Thanks

![schermafbeelding 2017-08-04 om 13 21 35](https://user-images.githubusercontent.com/29069381/29088423-491c5548-7c79-11e7-9641-d6d85aa70458.png)
