### ISSUE TITLE
V3.1 - dpsmate visual bug

### ISSUE THREAD

**Issue by moootv** [shagu/pfUI#593]
When switching to the bag by clicking the arrow at the bottom right and clicking it again to get back to the dpsmate view, the dps mate bars are too large.
https://gyazo.com/37cbe6baa43023e952836f6749263084

After /rl it's fine again.

**Comment by shagu** [comment]
Did this happen only on the first launch after the update?

**Comment by moootv** [comment]
After update.

**Comment by shagu** [comment]
So it doesn't happen anymore now?

**Comment by moootv** [comment]
I misread your question. I thought you meant if i just updated pfui or if i did a clean install.
I updated it without a clean install and it does happen every time i am switching to the bag, even after restarting the client.

**Comment by shagu** [comment]
weird. I'll have a look later.

**Comment by caspervk** [comment]
This happens to me too. It seems like the width of the dpsmate window fits perfectly with the width of the chatpanel.

https://gfycat.com/gifs/detail/ShowyFluffyHairstreak

**Comment by shagu** [comment]
Which Version of DPSMate is that?

**Comment by caspervk** [comment]
3.1.0

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/4d8ef373feddfa0d351372f1d93a1110127c3292

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/releases/tag/3.1.1
