### ISSUE TITLE
castbar: not working in groups anymore

### ISSUE THREAD

**Issue by lordkhonsu** [shagu/pfUI#600]
Since we updated to 3.1.2, castbars in parties are not working anymore. Without a party, a castbar on the target is displayed, however the times are incorrect (f.ex. Healing Wave rank 2 showing 3 seconds instead of 2 seconds it actually takes). When we form a party, the target castbar (target is in the party) doesn't show up anymore when casting.

edit: We also tried the usual classics (clearing the WDB folder, deleting saved variables) but nothing worked. Also, we have the same issue now after downgrading to 3.0 again (we are pretty sure it worked before)

edit2: Castbars on npcs and mobs are working fine with correct times.

**Comment by shagu** [comment]
That's a classic limitation, I cannot do anything there. In classic you can't read the castbars or cast-times of other players. The addon scans the combatlog and queries the pfUI internal spell database for the default-duration of the spell (which is usually the maximum time a spell can have) this is then shown as a target-castbar. If there aren't any combat logs regarding the spell, it cannot find anything. And if your opponent casts a lower-rank of the spell, the addon can't know that and still shows the max. duration of the spell.
