### ISSUE TITLE
Open bags overlap map

### ISSUE THREAD

**Issue by TilmanK** [shagu/pfUI#601]
This happens to me also with the current version from the repository. When I open the map it will be overlapped by the bag slots (but not the bag itself).
![overlap_map](https://user-images.githubusercontent.com/8856390/28383864-db9e2f5c-6cc2-11e7-8c20-e2cfdeee360e.png)

**Comment by shagu** [comment]
Hmm.. can't remember why I've added the custom frame strata there... removing it:
https://github.com/shagu/pfUI/commit/595b92419770f1fefeb0dfd9e2a36b424070a669

**Comment by caspervk** [comment]
After this change, the bag is behind some of my other addons. This didn't use to be the case.
