### ISSUE TITLE
hunterbar: addon conflict or ruRU incompatibility

### ISSUE THREAD

**Issue by Aviolas** [shagu/pfUI#604]
The panels do not automatically switch, what could be the problem?

addon and this setting restart several times, did not solve the problem =(

**Comment by shagu** [comment]
What client language do you run? 
Do you have the same issue while having all addons beside of pfUI deactivated?

**Comment by Aviolas** [comment]
RU client
if all addons beside pfui is off, problem is solved.
seems like Theory Craft (addon) provide it, But I can be wrong

**Comment by Aviolas** [comment]
Here screenshot of my addons, maybe it will help
[screenshot](http://imageshack.com/a/img922/3228/KBBU2q.jpg)

**Comment by Cruzix** [comment]
Why are u using ShaguPlates + pfUI O.o

**Comment by shagu** [comment]
Is it really TheoryCraft or do you really expect me to search and download all of your addons, just to try which of those causes the issue? Don't you think it would be faster to uncheck one-by-one on your own?

**Comment by Aviolas** [comment]
I just thought, maybe it was fault of pfUI setting. I'll try to fix it myself. Anyway thx for help!=)

**Comment by shagu** [comment]
Any updates?
