### ISSUE TITLE
The warrior skill alarm does not showing

### ISSUE THREAD

**Issue by muter941** [shagu/pfUI#607]
When the enemy was dodge, "[Overpower]" appeared on nearby center.
But it does not show up at the moment.
I want to see that skill alarm. please help.

**Comment by Road-block** [comment]
That is not part of pfUI.  
You probably had another addon like OverpowerAlert or SP_Overpower or WarriorHUD providing it, that you removed.

**Comment by muter941** [comment]
Thanks you. i will check another addon.
