### ISSUE TITLE
A standalone energy tick timer addon

### ISSUE THREAD

**Issue by subtletricks** [shagu/pfUI#608]
Hi Shagu! I do like pfUI and there are a ton of awesome features. Unfortunately, I couldn’t adapt to the visual style, so I’m stuck with the default UI.

What I really find useful as a rogue is the energy tick timer that is built right into the unit frame, unlike EnergyWatch that has a separate bar. I wanted to ask if it’s too much work to basically take this feature and make a standalone addon for the default UI?

If you do decide to do it, I hope other players will find it useful too.

Thanks!

**Comment by shagu** [comment]
No sorry, I'm not going to do that.
