### ISSUE TITLE
Possibility to add custom fonts through third party addons

### ISSUE THREAD

**Issue by jfastnacht** [shagu/pfUI#609]
Make it possible for third party addons to add custom fonts into the pfUI font list.

i.e.:
pfUI-verdana-font - Adds Verdana font to the font list in pfUI

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/a68cff7150a82a8fa924ccfac7fd582e87200bcc

Here's an example on how a font package could look like:
https://github.com/shagu/pfUI-font-roboto
