### ISSUE TITLE
How do I center position all windows?

### ISSUE THREAD

**Issue by grand-lotus-iroh** [shagu/pfUI#611]
Quest Dialogues, Hero Pane, or anything else that could be centered, but are often positioned on the left side of the monitor... how do I make them center middle aligned on the screen?

TYTY

**Comment by shagu** [comment]
pfUI allows you to move them, but the position is not saved because the wow-client resets these window positions.

**Comment by grand-lotus-iroh** [comment]
do you know of an addon that remembers, or saves positions of windows? will pfUI ever be able to do this? Does the API allow for it?


________________________________

**Comment by shagu** [comment]
The reset of the positions is hardcoded into the gameclient. You would need to hook every function that moves a window. I might do that some day but the priority on this is very low.

**Comment by grand-lotus-iroh** [comment]
I ended up using Move Anything addon - it works just awesome.
