### ISSUE TITLE
Docked DPSmate

### ISSUE THREAD

**Issue by elenmerbau** [shagu/pfUI#613]
Docked DPSmate always resets settings, have to configure it everytime. Dunno how undocked behaves tho

**Comment by shagu** [comment]
It's not `dock` it's the `skin` which does that. And that's how it is supposed to work. 

Here's a quote of the release page:
> Thirdparty threat and damage meters can now be "skinned" and "docked" seperatly. If "dock" is used, the meters can be toggled by clicking on the ">" button on the bottomright panel.
If "skin" is active, the settings of the corresponding meter will be changed to match the pfUI appearance.
