### ISSUE TITLE
pfui + Clique + SpellStopCasting

### ISSUE THREAD

**Issue by WoWerold** [shagu/pfUI#615]
Ich hab mir nen SpellStopCasting Makro erstellt, wenn ich nun mit Clique und dem pfui Raidinterface heile kann ich dieses nicht verwenden, wenn die Maus über dem Raidframe ist. Geh ich mit der Maus raus aus dem Raidframe funktioniert mein SpellStopCasting Makro. Liegt das Problem am pfui Raidframe oder an Clique, bzw dessen Implementation? Wäre super wenn man dies lösen könnte :-)

**Comment by shagu** [comment]
Am besten versuchst du das Makro mit anderen UnitFrames und Clique um herauszufinden ob es an Clique liegt.
