### ISSUE TITLE
BUG - undocked chat windows reset on UI reload

### ISSUE THREAD

**Issue by Priddles** [shagu/pfUI#617]
### Issue Severity - LOW
This issue:
- does not impact many users
- has a simple workaround
- is mainly an inconvenience; no other features appear to be affected

### Expected Behaviour
Undocked chat windows will retain their new positions and dimensions.

### Actual Behaviour
Undocked chat windows will retain their new positions and dimensions only until the next UI reload.

Whenever the UI is reloaded:
- the positions and dimensions of all undocked chat windows are set to the "General" chat window defaults
- all chat windows correctly retain their "lock" state

Probably unrelated but noticeable behaviour is that:
- all chat windows are rendered in the order of their creation, such that the last created chat window is "on top" of the rest
- all chat window interaction is layered in reverse order of their creation, such that the last created chat window is "underneath" the rest

This can be confusing when the user tries to move their custom chat window (which looks like it's on the top) but ends up moving the "General" chat window instead (assuming its unlocked).

### Workaround
Whenever the UI is reloaded, reposition and resize the chat windows. This workaround is time consuming and can be made more difficult due to the "layering" of the chat windows and the fact that they retain their lock state.

### Tested Configurations
**Config 1:**
- Client - US v1.12.1
- AddOns - whatever I had the first time I tried to have an undocked chat window
- WDB - same as AddOns
- WTF - same as AddOns

**Config 2:**
- Client - US v1.12.1
- AddOns - pfUI (commit e749b9543039f6bf96028b5716fb39199d117fed)
- WDB - empty
- WTF - empty

### Comments
Yes, this was completely unnecessary ^.^

**Comment by Road-block** [comment]
Holy Smokes!  
Overkill, but A++ for effort.  
This would make an excellent template for the *perfect* bug report 🥇 🙇

**Comment by Priddles** [comment]
### The Problem
After reading through the code, I think I know what's happening.

The cause of the bug is in `modules/chat.lua::RefreshChat`, more specifically `lines 315 ~ 328`:
``` Lua
if i == 3 and C.chat.right.enable == "1" then
  tab:SetParent(pfUI.chat.right.panelTop)
  frame:SetParent(pfUI.chat.right)
  frame:ClearAllPoints()
  frame:SetPoint("TOPLEFT", pfUI.chat.right ,"TOPLEFT", default_border, -panelheight)
  frame:SetPoint("BOTTOMRIGHT", pfUI.chat.right ,"BOTTOMRIGHT", -default_border, panelheight)
  frame:Show()
else
  tab:SetParent(pfUI.chat.left.panelTop)
  frame:SetParent(pfUI.chat.left)
  frame:ClearAllPoints()
  frame:SetPoint("TOPLEFT", pfUI.chat.left ,"TOPLEFT", default_border, -panelheight)
  frame:SetPoint("BOTTOMRIGHT", pfUI.chat.left ,"BOTTOMRIGHT", -default_border, panelheight)
end
```
This section of `RefreshChat()` is, interestingly, resetting the position and dimensions of every single chat window. However, the rest of the function does not modify the "lock" or dock states of any chat windows, explaining why the position and dimension changes were not observable for docked windows.

I also looked through `api/config.lua` which, unsurprisingly, did not contain information about chat window positions and dimensions. I confirmed in `modules/chat.lua` that they are all dynamically calculated using `C.chat.(left|right).(width|height)`.

### Proposed Solutions
#### 1. Restrict reset to a subset
Instead of resetting all chat frames, this can be restricted to a subset. For example change `line 322` to `elseif i <= 1 then`.

**Advantages:** Requires trivial changes to code.
**Disadvantages:** Not robust; the solution is essentially to hand over management of the windows to the WoW Client, which may introduce conflicts with other AddOns or even the client itself.

#### 2. pfUI config
Whenever any chat frame is moved or resized, store its new position and dimensions in pfUI's config. Modify `RefreshChat()` to use this information to rebuild the UI.

**Advantages:** Future proof.
**Disadvantages:** Requires non-trivial changes to code. UI-wise, if the "General" or "Loot and Spam" windows are not reset every reload, a method for the user to manually reset them may need to be implemented.

### Final Remarks
Wrote this just to mess with people xD.

I'll implement solution 1 and create a pull request if it doesn't break anything.

**Comment by Priddles** [comment]
@shagu this issue is ready to be closed after my pull request is approved

**Comment by byaka** [comment]
Is this also solve my small problem? I want to completely disable combat log window. But after every reload it returns back.

**Comment by Priddles** [comment]
Unfortunately, it doesn't. I would love to hide the Combat Log permanently as well, but it's actually the game itself that recreates it every time you login.

However, this fix will stop the stupid thing from coming back every UI reload.

**Comment by Priddles** [comment]
@byaka I ended up implementing a "Hide Combat Log" feature into pfUI. Unfortunately, you'll have to temporarily replace shagu's version of pfUI with [mine](https://github.com/Priddles/pfUI) (at least, until the pull request is approved).

You'll find the option in the pfUI menu, under the Chat tab.

Have fun!

**Comment by byaka** [comment]
@Priddles , thx

**Comment by shagu** [comment]
Sorry for my late response. I want to thank you for your detailled report. It really made my day :)
I never had such a detailled report before on this project, THANK YOU !

As you already pushed other commits to your PR, I wasn't able to merge yours so I just did it here:
https://github.com/shagu/pfUI/commit/c4996bc35bee1633c547ac342d69e3cb5d04cae4

Note to myself: I should create a Hall of Fame for reports somewhere... :D
