### ISSUE TITLE
Feature Request: more Thirdparty!

### ISSUE THREAD

**Issue by cnzjs** [shagu/pfUI#619]
**like "trhinketmenu","monkeyquest","EquipCompare","StatCompare","AtlasLoot","AdvancedTradeSkillWindow","EQL3",of course what I'm talking about is skin.
and about the "bags" module,can you add an option to not change all bags in one big bag?many players (like me) would put thing in my own will,healing thing in one bag,cant drop thing forever in one bag(like heartstone,horse),quest item in one bag,trinket in one bag,equip in one bag,so I really dont want all bags in one bag,but if disable this module,the wow default skin is so ugly to the pfUI.**

**Comment by shagu** [comment]
EQL is already included in pfUI, press shift or enable `Tooltip` -> `Always Show Item Comparison`.
Regaring the others: no.
