### ISSUE TITLE
Scalable Raidframes

### ISSUE THREAD

**Issue by TrueRmia** [shagu/pfUI#62]
Perhaps you could make the raidframes scalable in the options.

**Comment by shagu** [comment]
All movable frames can be scaled now: https://github.com/shagu/pfUI/commit/4fcb3076aa2ca6d20747428222daf514a07f63c6

for raidframes I'll add an option soon, to scale them all together.

**Comment by shagu** [comment]
hold down shift-key while scrolling will scale all frames in same cluster (e.g group or raid)
https://github.com/shagu/pfUI/commit/9b2a42972ae15eb8fd980f7dc66dc172803d033a

**Comment by TrueRmia** [comment]
Nice =)
Cluster support would be also nice to move the raid frames

Shagu <3
