### ISSUE TITLE
thirdparty: clique friendly spell does not work with player and pet frame

### ISSUE THREAD

**Issue by Grookshank** [shagu/pfUI#620]
I am using clique with pfUI and bind "Devour Magic" to a mousekey.

It works on the following frames: party, raid, target (friendly).

It does not work on the following frames: player, pet. Instead it gives the error "no target". It does work on those two frames if the player/pet is also targeted; e.g.: I target myself and then I can cast it on the player frame.

I assume is has something to do with clique/pfUI friendly target selection.

**Comment by shagu** [comment]
It works for me with the latest version of pfUI. 

Every pfUI unitframe has its own "Enable Clickcast"-Setting to use the pfUI-internal Clickcasting. Please make sure that those are disabled everywhere. And also make sure to disable "Auto Selfcast" as Clique recommends you.

**Comment by Grookshank** [comment]
I deleted pfUI and re-downloaded the lastest master from github.
I rechecked every clickcast setting in pfUI: they are all off.
I have bound my Felhunter's "Devour Magic" to a mouse button in clique.

It does not work on player and pet frame, when I have no target.
It does only work on player frame, when I have myself targeted.
It does only work on pet frame, when I have my pet targeted.

**Comment by shagu** [comment]
I have bound "Devour Magic" to "Shift-Click" and it works without any issues on Player, Pet and Target.

**Comment by Grookshank** [comment]
It it probably not gamebreaking, but I can't get it to work. See: https://www.twitch.tv/videos/167781788

**Comment by shagu** [comment]
[![video](https://img.youtube.com/vi/AZ3bVdgS28s/0.jpg)](https://www.youtube.com/watch?v=AZ3bVdgS28s)

Another try was to add `message("clicked on " .. unit)` to `Clique\Plugins\Clique_pfUI.lua` on line 35.
This does always show "clicked on player" and "clicked on pet". So there is no pfUI issue there.
It could either be a bug in Clique that happens under some unknown circumstances or another addon is interfering here.
