### ISSUE TITLE
localization: missing strings

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#622]
This can not be localized. Please add the possibility of their localization.

![bandicam 2017-08-10 11-44-11-022](https://user-images.githubusercontent.com/24303693/29177122-7cd2da00-7df6-11e7-9966-cada290827b0.jpg)
![bandicam 2017-08-10 12-27-01-720](https://user-images.githubusercontent.com/24303693/29177125-7cdd21f4-7df6-11e7-9b23-17b54e0386ed.jpg)
![bandicam 2017-08-10 12-31-52-081](https://user-images.githubusercontent.com/24303693/29177123-7cd91dca-7df6-11e7-831f-1c5dac827022.jpg)
![bandicam 2017-08-10 12-32-50-849](https://user-images.githubusercontent.com/24303693/29177126-7cde06b4-7df6-11e7-83ea-b642e572bb40.jpg)
![bandicam 2017-08-10 12-35-55-360](https://user-images.githubusercontent.com/24303693/29177124-7cdbfcac-7df6-11e7-90aa-150ccb4d2963.jpg)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/d7c3361eaec8087bfb666ad0e171228643b18d5f
https://github.com/shagu/pfUI/commit/fc36e34d8dd36e0adf098e0ebcc6459ccc959c67
