### ISSUE TITLE
pfUI + ShaguCopy

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#623]
Overlay scroll bars on the panel experience. Also, the scroll bar is outside the screen in the right chat window (Loot & Spam)
![bandicam 2017-08-10 12-30-47-135](https://user-images.githubusercontent.com/24303693/29177228-d124a728-7df6-11e7-9376-35a3623e3d4f.jpg)
If i am openning bags then button ShaguCopy is on the top layer:
![bandicam 2017-08-10 12-33-40-713](https://user-images.githubusercontent.com/24303693/29177227-d123e07c-7df6-11e7-9d36-24274bb263a6.jpg)

**Comment by shagu** [comment]
Thanks for your report.
This is more like an issue of ShaguCopy and I'm not going to track this here. I'd rather do this one: https://github.com/shagu/pfUI/issues/519 instead ;)
