### ISSUE TITLE
Fonts with support cyrillic

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#626]
[BigNoodleTitling.zip](https://github.com/shagu/pfUI/files/1216193/BigNoodleTitling.zip)
This font works well, I checked.

**Comment by Lichery** [comment]
Dear Shagu, if you If you can work with fonts, look at this font:
[DieDieDie.zip](https://github.com/shagu/pfUI/files/1216213/DieDieDie.zip)
This font supports Cyrillic when you open it, it displays symbols, but if you try to write Cyrillic symbols in the game or elsewhere, then the symbols are not displayed. I took this font from the [TukUI addon](https://git.tukui.org/Tukz/Tukui/tree/master).
Unfortunately, the Internet no has this font with Cyrillic support...

**Comment by shagu** [comment]
Hi,
The DieDieDie font you suggested will break the special characters for german and french.
You might want to create a cyrillic font package for pfUI. An example on how to achieve that can be found here: https://github.com/shagu/pfUI-font-roboto

**Comment by Lichery** [comment]
Why you did not update the font BigNoodleTitling? It supports the cyrillic symbols. I tested it in the game, it works.

**Comment by shagu** [comment]
I didn't had the chance to compare both fonts yet. And I don't know a tool which would easily allow me to compare fonts. I don't want to break any other languages by replacing a font with an `unknown` version.

Where did you got yours from?

**Comment by Lichery** [comment]
Downloaded this font here https://www.fonts-online.ru/font/BigNoodleTitlingCyr
