### ISSUE TITLE
unknown: fps drop in fullscreen mode

### ISSUE THREAD

**Issue by fuzzytrick** [shagu/pfUI#630]
The UI is beautiful, and apart from this issue, it has been flawless so far. Ever since I installed it, I started having some weird frame drops, not by a lot, usually 1-2 frames, but it is highly noticeable. The game stutters horribly during that time, and this happens most of the time when I'm moving the camera around. This happens only when I'm in fullscreen. I've figured a work-around for this, whenever I put my game into windowed, or windowed maximized, the issue is gone. I don't really have a problem with playing in windowed, but I thought it would be great to share this. Also, a friend who installed it, did not have any problem at all.

**Comment by cnzjs** [comment]
I think it's your hardware problem,maybe video card.

**Comment by shagu** [comment]
Looks like I cannot do anything here.
