### ISSUE TITLE
unitframes: rangefade doesn't apply correctly

### ISSUE THREAD

**Issue by nesherman** [shagu/pfUI#631]
I currently have range fading OFF, but a random number of my raid frames are faded out as if they're too far away. I might be standing right next to the person, but they still appear range faded. Typically this is fixed with a /rl but this happens 100% of the time whether it's in an instance, in world, or in bg's when I either first log in or first join a raid with players whom are far away.

I wish I had more info, but I've not yet been able to isolate a means to reproduce this.

**Comment by shagu** [comment]
Thanks for your report, let's see if we get more data in here ;)

**Comment by shagu** [comment]
Please check again with the latest version. The unitframes aborted too early (before an actual range check has been made). https://github.com/shagu/pfUI/commit/531f79b5765aa554029602fa74d926e49f69615e

**Comment by nesherman** [comment]
Latest version has been downloaded and installed--still having the same issue.

**Comment by shagu** [comment]
Please let me try to sum up the issue and correct me if I'm wrong:

## The Issue:
While Rangefading is disabled [Enable Range Fading: unchecked]
- people nearby are *sometimes* are shown as offline but the health is still shown
(offline: 25% alpha, out-of-range: 50% alpha)
- people who are `offline` and then `log on` are **always** shown with the same transparency as if they are still `offline`

While Rangefading is enabled
- everything is working as expeted

Aggressive 40y Rangecheck has no influence on that, as it was disabled during the tests.

**Comment by nesherman** [comment]
To my knowledge and experience this is correct.

I'm able to record in action if necessary.

**Comment by nesherman** [comment]
Of course /reload fixes this issue.

**Comment by nesherman** [comment]
I'd also like to add that if any player logs off then the problem reappears. Even if they log back on they will still have the same transparency as if they were offline.

**Comment by shagu** [comment]
Please check this one:
https://github.com/shagu/pfUI/commit/c6003f08f49fb2b997b857d76df25c7c995d77fa
