### ISSUE TITLE
unknown: player buff duration doesn't update on rebuff

### ISSUE THREAD

**Issue by aixiu** [shagu/pfUI#632]
![1](https://cdn.discordapp.com/attachments/329940978498666506/337067129629310977/unknown.png)

**Comment by aixiu** [comment]
Added: before the BUFF time did not arrive, and refresh the BUFF, it shows the wrong time

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/a2518da6cdad15a6eda6d664a97073c7172228ee
