### ISSUE TITLE
Add ability to link raid/group frames so they move together

### ISSUE THREAD

**Issue by t3hWheez** [shagu/pfUI#633]
As title says

**Comment by Haiwuu** [comment]
Shift + drag

**Comment by t3hWheez** [comment]
Not exactly the best way of doing it, especially if you want to change the width/height of the bars, you still have to touch each raid member frame individually

**Comment by Haiwuu** [comment]
shift + mousewheel?

**Comment by t3hWheez** [comment]
What exactly is that doing?  Scaling of them?  The width/height dont appear to change in the settings.

**Comment by shagu** [comment]
> Not exactly the best way of doing it, especially if you want to change the width/height of the bars, you still have to touch each raid member frame individually

If you change the width and the height before moving the frames, they will still stick together. 
They are unlocked and independent to each other, at the moment you ungroup them by dragging it to other positions. From that point on, a resize wont change the positions to others.

If you have a rocksolid workflow in mind to decide when other frames should move and when not after changing the size, please create a ticket for that.

**Comment by t3hWheez** [comment]
Shagu, am I able to get the raid frame positions reset without breaking everything else so I can resize/move this correct way?

Thanks

**Comment by shagu** [comment]
You can reset all positions by running `/run pfUI_config.position = nil` and then `/rl`
