### ISSUE TITLE
Add ability for user defined debuffs to appear as icons on Raid Frames

### ISSUE THREAD

**Issue by t3hWheez** [shagu/pfUI#634]
IE, corrosive acid on Chromaggus

**Comment by shagu** [comment]
same as: https://github.com/shagu/pfUI/issues/575 ?

**Comment by t3hWheez** [comment]
I think this is the best way to describe what I am looking for:

![fwkmi9v](https://user-images.githubusercontent.com/23520811/29843203-17511ede-8cc0-11e7-83eb-f0f407880561.png)

We can see the ressurection icon on each player frame in the middle in this picture.  I am looking for a way to enter spell IDs or spell names which are debuffs, to appear as icons just like the resurrection icon.  This would be different than dispellable debuffs.  Things like Corrosive Acid on Chromaggus or Mortal Strike on Broodlord. 

Does that make sense?

**Comment by shagu** [comment]
Yes makes sense :)
It's pretty much the same as https://github.com/shagu/pfUI/issues/575. While it's not exactly the same, it's still the same work that has to be done for it.

Closing this one.
Thanks for your input though
