### ISSUE TITLE
DPSMate dock resets config every time I launch the game

### ISSUE THREAD

**Issue by niklasbe** [shagu/pfUI#636]
I have a custom config for DPSMate and ever since I started using the dock the config keeps resetting every time I launch the game. I do not use the skin, only dock

EDIT: I only edit the colors, bar height and fonts of DPSMate and that is what is reset every time

**Comment by shagu** [comment]
Are you using the latest version of pfUI?

**Comment by niklasbe** [comment]
It happens when switching between two characters with different pfUI settings (DPSMate skin on/off). I was guessing settings were character specific and didn't realize they shared settings.

I would switch from a character with DPSMate skin turned off to a character with the setting turned on, and when I got back to my first character the skin would be reset. So am I right to assume this is DPSMate's fault?

**Comment by Road-block** [comment]
If you are not using pfUI profiles, then this is actually expected behavior.  
You've been changing the option of the default profile back and forth.  
The solution to your issue is to create a separate profile for each character and then the setting will "stick".

**Comment by niklasbe** [comment]
As of now I've been copying from my main pfUI profile for every character I make. I will go with your suggestion of creating a new profile for every character
