### ISSUE TITLE
pvp: add battleground timers

### ISSUE THREAD

**Issue by ghost** [shagu/pfUI#638]
I dont know why I can not see any timer by "DBM",it should be there,and I googled like 2 hours for a timer,like BGassitant,and something else,dont really work,maybe pfUI can ,you know,work on it,some day pfUI is the only addon we need.

**Comment by byaka** [comment]
BGAssist doing it for me

**Comment by Cruzix** [comment]
Quit,writing like,you know,like this,it hurts my brain,thank you,yaes,sorry for,offtopic too,but man...

**Comment by byaka** [comment]
looks like different versions of BGAssist have different problems.. i use version from [here](https://github.com/ericraio/vanilla-wow-addons/tree/master/b/BGAssist), maybe it helps u

**Comment by cnzjs** [comment]
thanks guys,I made DBM work finally,just because a redundant blank makes all timers dont work,now it's working right.
