### ISSUE TITLE
actionbar: reagent counter vanished after reloading UI

### ISSUE THREAD

**Issue by Grookshank** [shagu/pfUI#639]
If I change a setting in pfUI and let it reload the UI, the reagent counter vanishes. Once I restart the client, it is back.

**Comment by shagu** [comment]
Any other addons in use? Which ones? What client are you using?

**Comment by Grookshank** [comment]
Wow 1.12 (Elysium); latest pfUI version.

Addons: Atlas ,Atlasloot Enhanced, Atlast Quest, Aux, BigWigs Elysium, ccwatch, CT_Raid Assist, DPS mate Shino (all sub addons), Gatherer, KLH Mesmerize Edition, KLH performance meter, MobHealth3, zbar.

Can reproduce 100%

**Comment by shagu** [comment]
Could you please disable all addons beside pfUI and try again? I assume your using the enUS client, correct? Which class and on which specific spell is this happening?

**Comment by Grookshank** [comment]
It is the addon "zbar", that causes the problem.

I am a Warlock and it happens on all spells (soulshards and infernal stones as reagents).

**Comment by shagu** [comment]
Sorry mate, I won't have the time to dig into `zbar`. I'd rather spend the time to rewrite the whole actionbar module instead.
