### ISSUE TITLE
Bag items aren't properly grayed out when locked

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#64]

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/b3e74f1a1dc937f1b74701cb2ee8af10cea43bd7

**Comment by shirsig** [comment]
Did you avoid http://wowprogramming.com/docs/widgets/Texture/SetDesaturated on purpose?

**Comment by shagu** [comment]
Yes, kind of. 
As I use backdrops for bag textrures, I'd need to iterate through all ":GetRegions" until the textures is found to desaturate it. This has to be done on every Itemlock-event for all available itemslots. 
Therefore I  decided to skip desaturation and use alpha instead to not kill the performance, until another idea is ready to replace it :)

**Comment by shirsig** [comment]
The texture has a name: https://github.com/AtheneGenesis/Vanilla_enUS_FrameXML/blob/master/ItemButtonTemplate.xml

So you could do getglobal(pfUI.bags[bag].slots[slot].frame:GetName() .. 'IconTexture'):SetDesaturated()

Possibly get the global table with local _G = getfenf(0) (indexing is about 100x faster than function calls i think)

**Comment by shagu** [comment]
Yes, the Icon has a name, but as I said, it is replaced by a backdrop texture:
https://github.com/shagu/pfUI/blob/master/modules/bags.lua#L254-L266

**Comment by shirsig** [comment]
Hm, why are you doing this? Anyway, couldn't you still just find it once after creation and then reference it through a field on the button frame?

**Comment by shagu** [comment]
done. https://github.com/shagu/pfUI/commit/23c5456b364236b683f05dc11ab49564f41996ce

**Comment by shirsig** [comment]
Great, thanks.
