### ISSUE TITLE
Can you add non combat avatar frames to hide functionality?

### ISSUE THREAD

**Issue by volctent** [shagu/pfUI#640]
Very need this function, thank you

**Comment by byaka** [comment]
can u pls explain, what u mean?

**Comment by t3hWheez** [comment]
I think he wants Player/Target frames to be hidden when not in combat.  I thought there was an issue open for this already but I couldn't find it.

**Comment by Haiwuu** [comment]
https://github.com/shagu/pfUI/issues/612

**Comment by shagu** [comment]
Most probably what @Haiwuu and @t3hWheez said.
