### ISSUE TITLE
Player missing in "show group in raid frames"

### ISSUE THREAD

**Issue by vashin1** [shagu/pfUI#643]
Just tested this new feature tonight, worked fine up until we invited the 5th person to a party for Scholomance, I could see myself, the rogue, the tank and the healer but the 5th person that was a mage did not show up at all.  Had to revert to normal group frames which worked perfectly fine.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/f446689681c3db879b41ec43d8e05b686e26fd8f
