### ISSUE TITLE
question: simulating marks near players?

### ISSUE THREAD

**Issue by byaka** [shagu/pfUI#644]
Is it possible to simulate configurable markers (for players only) that will be vissible only for player (not raid markers) and also in solo?
Why i need it - when traveling world sometimes i meet enemy players, that do something... bad. And i want to mark them for myself, so next time i meet them - i will know what doing with them ;) Any ideas? Or maybe some existed addon can do it for me?

**Comment by Road-block** [comment]
You're talking about Kill On Sight addons.  
Popular ones in classic were [VanasKoS](https://legacy-wow.com/vanilla-addons/VanasKoS/) / [SKMap](https://legacy-wow.com/vanilla-addons/SKMap/) / [Opium](https://legacy-wow.com/vanilla-addons/Opium/) / [PvPLog](https://legacy-wow.com/vanilla-addons/PvPLog/)..  
I'm sure there's more, it was a popular kind of addon 😛 but those I remember as the most commonly used.

**Comment by byaka** [comment]
@Road-block thx for answer, but i speak about smthng different. I use Pvplog, it very usefull, but:
1. it not allow me to add notes, only stats of kills\death.
2. for read info about player i need to TARGET him.

what i want - i want analogue of raid marks (u can see it without targeting playe), but persistent and working in solo. Is it possible with addons? Is it hrd to implementing? Maybe something like this existed?

**Comment by Road-block** [comment]
@byaka Some of those I linked I'm pretty sure let you add notes.  
Regardless, without target / mouseover it's not really possible (or rather realistic).  
The only way to show marks over units in the 3D world is by using nameplates and the range at which nameplates appear is very close for pvp reasons.  
If you don't mind that then a plugin for ShaguPlates or CustomNameplates that uses the database of names from a KoS-type addon to add a custom graphic to player nameplates is indeed possible but I'm not aware of an existing one.  
Afaic a better kind of addon would be one that posts a link in your chatframe (and a sound alert maybe?) when it detects an action from a player on your KoS list that you can click to target them. I'm not sure if one exists already but it's not very hard to make, maybe you'll find an interested author or get started learning yourself 😄

**Comment by byaka** [comment]
> Regardless, without target / mouseover it's not really possible
Thx, this what i wanted to hear..

> Afaic a better kind of addon would be one that posts a link in your chatframe (and a sound alert maybe?) when it detects an action from a player on your KoS list that you can click to target them
good idea. ill check 3 other addons that you gave me and try to find another, but u right - implementing this atop of existed KoS addon not difficult.
