### ISSUE TITLE
Buff Timers permanent

### ISSUE THREAD

**Issue by Panda671** [shagu/pfUI#645]
Hi. I use Luna Unit Frames with mostly everything else pfUI. With your latest release when I updated my pfUI (Deleted old pfUI folder and pfUI saved variables for my character) I have a very frustrating bug. I have your buff timer text OVER the Luna Unit Frames buff timer text. I even went as far as going into the pfUI lua files and disabling every buff thing I could find, but to no avail. I did the same in the pfUI saved variable lua for my character. Very frustrating as your timers are inaccurate (it will say 10 minutes for my 5 minute weapon imbue and many other glitches).

https://imgur.com/a/AhKTf

**Comment by shagu** [comment]
disable the "cooldown" module.
