### ISSUE TITLE
Target Focusframe?

### ISSUE THREAD

**Issue by Suzaru** [shagu/pfUI#646]
Hi!

is there a command to target the focusframe via macro, without having to actually target it?
So i remember something like this for example:

/cast [target=focus] Polymorph 

I cant get it to work :( Thanks in advance!

**Comment by cnzjs** [comment]
good issue,that's why focus exists,should make it happen

**Comment by Road-block** [comment]
`focus` doesn't exist as a unitid in Vanilla, every addon that tries to "simulate" it has to work with target albeit briefly enough that you don't see it.  
Your best bet is [CastModifier](https://github.com/DennisWG/CastModifier) with one of its [supported addons](https://github.com/DennisWG/CastModifier/wiki/Supported-AddOns)
