### ISSUE TITLE
some suggestion

### ISSUE THREAD

**Issue by cnzjs** [shagu/pfUI#648]
![wowscrnshot_091417_145605](https://user-images.githubusercontent.com/2385648/30454550-4b509608-99cf-11e7-929c-0f88370cee81.png)

**Comment by cnzjs** [comment]
sorry for my poor english

**Comment by byaka** [comment]
think, adding MMB-like function, that moves all (or filtered) buttons to special bar or dropdown - good idea, BUT mmb is really hucky, not working properly with some addons and sometimes have problems. So implementing it here... not best way.

**Comment by cnzjs** [comment]
I'm glad if he take my trinketmenu's suggestion.

**Comment by shagu** [comment]
![invalid](https://user-images.githubusercontent.com/11586807/30588186-0da25b24-9d36-11e7-9dca-0f44ce3202c3.png)
