### ISSUE TITLE
actionbar: conflict with addon "Jim's Cooldown Pulse"

### ISSUE THREAD

**Issue by mario8000** [shagu/pfUI#649]
hi i setup your UI the other day, cleared my WTF folder after installing and everything works great but i noticed today when attempting to cast a spell such as Succubus that requires a soul shard it does nothing when clicking, marcoing nothing. Same with other spells such as my other pets that require a soulshard (imp works fine) Also my shadowburn spell does not work (requires ss)

**Comment by mario8000** [comment]
its working properly now. what setting would cause this though??

**Comment by mario8000** [comment]
Seems to be when im in grp/raid it does this, are you able to confirm? it shows a number by the spell signifying the amount of shards i have, seems to be when this number is there i cant cast that spell.

**Comment by mario8000** [comment]
OK now im in a ZG 20 man raid and its not doing it?! whats causing this?

**Comment by shagu** [comment]
Could you please add a list of other addons you're using?

**Comment by mario8000** [comment]
Currently using Atlas, Atlas Loot, Auctioneer, Big Wigs, Dhask's Flight Map, EnhToolTop, EquipCompare, Extended QuestLog, EZDismount, Improved Error Frame, Jim's Cooldown Pulse, KLH Threat Meter, MetaMap, Stubby, SW Stats, vQueue, Wim, Wowhead DB, BGAssist

**Comment by shagu** [comment]
I'm unable to reproduce this.

PS: pfUI already includes features like EZDismount and EquipCompare.

**Comment by shagu** [comment]
I made a fix today (https://github.com/shagu/pfUI/commit/2d624f921c8b79f29846281068ba56de2d0ce768) which could be related to your issue, please perform an update.

**Comment by mario8000** [comment]
Hmm so i downloaded the update AND disabled EZdismount/equipcompare to test this, and it still isnt working. Here is a picture of your UI setup on my toon. Notice how the pets have a number over them signifying the amount of shards, and the imp doesnt? when there isnt a indicator here representing the amount of shards, i can cast fine. 
![pfui bar](https://user-images.githubusercontent.com/24818108/30891080-e7f3f12a-a2fe-11e7-85f6-2ad8ed9778c9.PNG)

**Comment by mario8000** [comment]
i also cant use my Inferno or Ritual of Doom spells, and these spells also require mats. Notice the indication of how many of each mat i have to use the spell. **bottom right.**

**Comment by shagu** [comment]
Do you see any error messages and could you please verify that this issue also occurs while only pfUI is loaded?

**Comment by mario8000** [comment]
OK so after loading JUST pfUI addon and disabling everything else, i can now cast these spells. Obviously some kind of conflict going on here i guess.

**Comment by mario8000** [comment]
the conflict seems to be with Jim's Cooldown Pulse, which is actually a pretty cool addon. idk if you could look into this?
