### ISSUE TITLE
Left side chat position does not move

### ISSUE THREAD

**Issue by Lazzerz** [shagu/pfUI#651]
I get this error that is related to my chat window not being moved vertically: ERROR:Interface\addons\pfUI\api\unitframs.lua:: attempt to index field `?' (a nil value). 

It spams my chat box sometimes and Idk what to do

**Comment by shagu** [comment]
Please provide the complete error message. There should be a line number visible.

**Comment by Lazzerz** [comment]
![error](https://user-images.githubusercontent.com/32075487/30769113-38d8786a-9fd8-11e7-8f88-0643efa78f82.png)

**Comment by Lazzerz** [comment]
ERROR:Interface\addons\pfUI\api\unitframs.lua:1382: attempt to index field `?' (a nil value)

**Comment by shagu** [comment]
It's a serverbug and a workaround has been introduced in the latest pfUI version. For further details, please have a look here: https://github.com/shagu/pfUI/issues/660
