### ISSUE TITLE
chat: additional chat windows are not inherited by the chatdock

### ISSUE THREAD

**Issue by nesherman** [shagu/pfUI#654]
Recently, after updating I have noticed that some of my additional chat tabs on the left chat window cannot be hidden. Of course I am able to switch tabs normally, but the title of these windows does not disappear when the cursor is moved away. Thanks for your time and dedication.

**Comment by nesherman** [comment]
"Only Show Chat Dock On Mouseover" enabled, of course.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/ae6c8f0025a583b056c02cf72f764b5a7baae405
https://github.com/shagu/pfUI/commit/1c680c7f3c25619c39ca2db1db1ac827e4f1503b
