### ISSUE TITLE
Creating new tabs in the chat (such as a "Whisper" tab on left side, doesn

### ISSUE THREAD

**Issue by Aguilaa** [shagu/pfUI#658]
As the title refers to, creating new tabs next to the "General" tab doesn't remove the tab flashing of it. I would be thrilled if this one could be fixed.

**Comment by Aguilaa** [comment]
As the title refers to, creating new tabs next to the "General" tab doesn't remove the tab flashing of it. I would be thrilled if this one could be fixed.

**Comment by shagu** [comment]
related: https://github.com/shagu/pfUI/issues/654

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/ae6c8f0025a583b056c02cf72f764b5a7baae405
https://github.com/shagu/pfUI/commit/1c680c7f3c25619c39ca2db1db1ac827e4f1503b
