### ISSUE TITLE
Requesting the option to make the chat bigger without adjusting the height nor width of the panel and dock frame.

### ISSUE THREAD

**Issue by Aguilaa** [shagu/pfUI#659]
As the title refers too, I'd love the option to change the actual chat width and height, without adjusting the panel and the dock frame ontop and below of it.

**Comment by shagu** [comment]
How is the height involved into this? There is already an option to resize each chat window, which does not affect the height of the panel or dock in any way. The chat tabdock will always have the width of the chatwindow, but you also have the option to hide that. So i rather have misunderstood the issue or this is a wontfix.

Cheers

**Comment by Aguilaa** [comment]
I've manually made the dock and top panel smaller in the lua, but the actual chat doesn't resize with it. This results in gaps between dock frame and the chat, and a gap between the top panel and the chat. 

I basically just want the gaps to dissapear by increasing the height of the actual chat.

**Comment by shagu** [comment]
Well, the UI already provides an option to change Width and Height of the Chat individually. I have no idea which changes you made to the dock and the panel. I can't provide a mainline fix to your custom changes.

Feel free to contact me in Discord if you need any coding guidiance regarding your UI.
