### ISSUE TITLE
Bag frame breaks when resizing the game window

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#66]
![](http://i.imgur.com/sVLHnWe.png)
Reload fixes it.

**Comment by shirsig** [comment]
https://www.youtube.com/watch?v=dhLdvtDGelo&feature=youtu.be

**Comment by shagu** [comment]
https://www.youtube.com/watch?v=m5DnW52mVck

**Comment by shirsig** [comment]
You need to make a bigger size change.

**Comment by shagu** [comment]
It doesn't matter. It is always scaling for me.

**Comment by shirsig** [comment]
Strange. It happens even when all other addons are disabled. Maybe an issue with my client.

**Comment by Voidmenull** [comment]
i could reproduce it a single time - but closing/repoening the bag frame (pressing B) fixed it - no reloading needed.

**Comment by shagu** [comment]
Please try to reproduce with this commit: https://github.com/shagu/pfUI/commit/8891a1df446f4fb5088ecdfb0fd196a7c334bd69

**Comment by shirsig** [comment]
It still happens.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/fd0161f277e69f1a9ccc559ea1c9334793d27ef6

**Comment by shirsig** [comment]
It's fixed now. Thanks :)

**Comment by shagu** [comment]
Puhhhhhh :D Finally
