### ISSUE TITLE
chat: add option to disable chat tab flashing

### ISSUE THREAD

**Issue by Aguilaa** [shagu/pfUI#661]
Hello Shagu, 

The recent hotfix to the tab flashing did not fix it. I'm still receiving the flash tabs on both tabs (whisper and General), whenever I receive a whisper.

Furthermore, I am unsure if you saw my reply to the closed issue in regards to chat height. If not, please let me know. I'd really like some assistance with it, even though it' might be just me who'll be needing it. 

Thank you for your awesome work. Loving it.

Aguila

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/9accc8bfcf3eb167de809301f3bd0ab07b88dd68
