### ISSUE TITLE
Disabling Pet Unitframe Error

### ISSUE THREAD

**Issue by Ceivent** [shagu/pfUI#663]
With the only add-on running being pfUI, if i disable the pet unitframe, it breaks some of the UI, spitting out  ERROR: Interface\AddOns\pfUI\modules\player.lua:25 attempt to index field 'hp' (a nil value)
http://puu.sh/xEEqo/4020b34700.jpg

when i hit ESC to open the menu its the default Blizzard UI skin for the Menu, having to use the /pfUI command. if i re-enable the Pet Unitframe it fixes the issue. Also to note that when the pet unitframe is disabled and you're going to "unlock" and change your UI bar locations, all the Raid/Party/Loot/Target-of-Target, etc frames are missing.

Normal - http://puu.sh/xEEDZ/7c6581d039.jpg
Disabled - http://puu.sh/xEEFM/cf9ff47640.jpg

**Comment by shagu** [comment]
Thank you very much for the report, I'll fix that ASAP

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/700a9f78a4d4f3f014f1160c8dee91562c0d13a2

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/924b58a92d276bafcee888499734899103b48e54
