### ISSUE TITLE
Have double spell names [RU]

### ISSUE THREAD

**Issue by KasVital** [shagu/pfUI#664]
`1474 ["Устрашающий рев"] = 30` => `["Demoralizing Roar"] = 30,`
`1917 ["Устрашающий рев"] = 8` => `["Intimidating Roar"] = 8,`

and i have debuff `Устрашающий рев` in the game for 8 sec. :(

we need growl (druid bear) = 3, but we have in russian 1620 ["Рык"] = 30
i think you can easly delete 1917 ["Устрашающий рев"] = 8 and change  1620 ["Рык"] = 30 to 3sec
and add:
["Growl"] = 3, to english version

**Comment by shagu** [comment]
**Intimidating Roar** (http://db.vanillagaming.org/?spell=16508)
ruRU `["Устрашающий рев"] = 8`
enUS `["Intimidating Roar"] = 8`

**Demoralizing Roar** (http://db.vanillagaming.org/?spell=9898)
ruRU `["Устрашающий рев"] = 30`
enUS `["Demoralizing Roar"] = 30`

Now which one is wrong and what's the accurate translation?

Regarding the `Growl` please link the debuff of the spell. I can't find any 3sec Debuff caused by Growl.

**Comment by Road-block** [comment]
This is the Growl (Druid Taunt) spell http://db.vanillagaming.org/?spell=6795
3sec is the duration of the fixate it causes, shows up on the target as a growl debuff.

**Comment by KasVital** [comment]
i used "Demoralizing Roar" in russian client (Устрашающий рев) and got debuff on target for 8 sec - coz ["Устрашающий рев"] = 8 is below in the file than ["Устрашающий рев"] = 30.....

**Comment by shagu** [comment]
As long as you can't provide me correct translations for both spells, I'm not going to remove any spell, just because you're using the "demoralizing roar" more often.

**Comment by shagu** [comment]
I have updated the locales to match the latest translations of the ruRU client and it looks like both spells still have the same translation. You'll have to remove the spell on your own if you're using that kind of debuff more often.

**Comment by Lichery** [comment]
Very soon we will release a new version of the ruRU client, in which these spells will have different names. As soon as the new version of the client is publicly available, I will correct it in this addon.

**Comment by shagu** [comment]
Please tell me when there is a new client available. I have set up some scripts that automatically generate those translations from the gameclient (https://github.com/shagu/pfUI-toolbox) :grinning:
