### ISSUE TITLE
skin: add support for underwater breath bars

### ISSUE THREAD

**Issue by nesherman** [shagu/pfUI#666]
Best to see the attached image: https://imgur.com/a/N1a14

Thanks, and have a great day!

**Comment by lbjdaking23** [comment]
Official name for these bars seem to be MirrorTimers. 
A [link](https://www.townlong-yak.com/framexml/1.12.1/MirrorTimer.xml) to the XML design for them. 
I am going to see if I am going to try my hand on skinning them unless @shagu wants to.

**Comment by shagu** [comment]
Thank you for your comment, @lbjdaking23. Feel free to have fun with those frames. Pull Requests are always welcome.

**Comment by shagu** [comment]
Thank you very much for your contribution @lbjdaking23 !
