### ISSUE TITLE
please fix localization string

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#668]
["Healthbar Height"] it is used for nameplates, so it must be "Nameplate Height"

**Comment by shagu** [comment]
No, because it's only the height of the nameplate, not the height of the nameplate itself

**Comment by Lichery** [comment]
no, that's exactly the nameplates height

**Comment by Lichery** [comment]
![bandicam 2017-09-24 19-27-37-217](https://user-images.githubusercontent.com/24303693/30784502-cbd126e4-a15e-11e7-9e4e-e4b197ccbd6a.jpg)
![bandicam 2017-09-24 19-28-31-670](https://user-images.githubusercontent.com/24303693/30784503-ccbb7c62-a15e-11e7-9f9f-ad69d902955b.jpg)

**Comment by Lichery** [comment]
This line is only used in one place:
![bandicam 2017-09-24 19-33-34-772](https://user-images.githubusercontent.com/24303693/30784532-68ad4678-a15f-11e7-977e-695e47a2bf42.jpg)

**Comment by shagu** [comment]
![nameplate](https://user-images.githubusercontent.com/11586807/30784544-80a95738-a157-11e7-825a-162c2bf9ca2c.png)
