### ISSUE TITLE
actionbar: bad hook for IsConsumableAction

### ISSUE THREAD

**Issue by WaldFeeDE** [shagu/pfUI#673]
pfUI running well since 2 weeks. now wanted to use TNE_FiveSec for Raidhealing as Mana Tick addon and when enabled i cant use Spells anymore with Bindings, just via clicking.

ERROR: Interface\AddOns\pfUI\modules\actionbar.lua:79: attempt to index global 'this' (a nil value)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/2d624f921c8b79f29846281068ba56de2d0ce768
