### ISSUE TITLE
Unitframes - Performance issues in 40 man raids

### ISSUE THREAD

**Issue by stva23** [shagu/pfUI#676]
I had a lot of performance issues (1 frame / 5 sec and less) in 40 man raids, especially with certain bosses and mobs ( Vaelastrasz, C'thun, trash before twins) where i got disconnected. Disabling pfUI Unitframes resolved all these Problems. I also disabled all other addons, so there should'nt had been any conflict.

I have seen some people had similar problems (#100). Im on d5ef7c1a07e05dfde35a7cacdacc20dd5c5eab70

pls help, i really like your addon :)

**Comment by shagu** [comment]
Hi, I made alot updates on the unitframes since your version. This also includes many that should increase the performance. (like this one: https://github.com/shagu/pfUI/commit/480860139807d93a2833d8fc8934435c2604b610)

Please update to the latest version and try again.

Thanks in advance

**Comment by shagu** [comment]
PS: Also make sure to not have the `Aggressive 40y-Range Check (Will break stuff)` option active.

**Comment by stva23** [comment]
Aggressive Check is disabled, same problems with updated version (master).

**Comment by stva23** [comment]
An other player in my raid encountered the same problems with activated unitframes.

**Comment by stva23** [comment]
Are there any further investigations planned? I am asking because this was set to "invalid". I am willing to assist with debugging as much as i can.

**Comment by shagu** [comment]
Sure, but as I'm not even able to reproduce the performance issues on integrated intel graphics, there isn't much I could do about. It could just be everything. If you have any specific hints, hardware details, config options you've tried, additional addons, ... please add them here.

It's just `invalid` as there aren't enough information provided to have a clue about the root cause.
Maybe I should rather have tagged this as `cannot reproduce`.

**Comment by stva23** [comment]
Mhmm we are both Shadowpriests. Beside these nothing in common. At least i tried without any other addons. Other player in my raid uses pfui too and they don't have issues.. it gets confusing. 

I'm using default pfUI Settings, Nvidia graphics, AMD CPU.

**Comment by chrheg** [comment]
Do you use notgrid by any chance ?

**Comment by shagu** [comment]
OS, resolution, gxApi, fps in idle, fps in cities, window/fullscreen mode, double/triple buffer, multisample, ..?
Every information could help.

**Comment by moootv** [comment]
in idle, fps in cities, window/fullscreen mode, double/triple buffer, multisample, ..?
OS: Win 10
gxAPI - How to find out?
FPS in cities 150-220
Windows Mode
Graphic Options : https://gyazo.com/4845be99bfb4385d93ff705eb702a833

**Comment by Road-block** [comment]
> gxAPI - How to find out?

If you need to ask it's Direct3D (the default)  
But for future reference: `/run message(GetCVar("gxApi")`

**Comment by shagu** [comment]
Today on discord:
> Nurhaci - Today at 9:27 PM
I get screenfreezes for 2/3 sec with the raidframes enabled when ppl go offline/come online, join the raid/leave the raid and on bosses when the boss uses an ability on someone like living bomb i get screenfreeze for maybe 10 seconds. Disabling the raidframes solved all this and made my performance alot better. any solution for this?

**Comment by stva23** [comment]
OS: Win10 64Bit
Resolution: 1680x1050 Fullscreen
gxApi: Direct3D
FPS Cities: ~80

Tried lowest graficoptions for testing, normaly best. Lately i had ~2-3sec freezes with about 30 people in the raid, but i was in a city, the raid was fighting a worldboss.

**Comment by Meridaw** [comment]
OS: Win7 64bit
Resolution: 1920x1080 Fullscreen window mode
gxApi: Direct 3D
FPS Cities  90-110
Aggressive Check is disabled

I get freezes on Vael, most if some one get Burning Adrenaline. I play druid, but my guildy who play warrior and priest only get the lag when he play on the priest. If i swap to Luna i get no freezes at all.

**Comment by shagu** [comment]
Thanks everyone for participating. The idea of having a class specific issue was a good hint.
Please try again with the latest version (https://github.com/shagu/pfUI/commit/8218f3f28c31429c71ba12da4e77f698fb2e8cde)

**Comment by moootv** [comment]
I play rogue btw.

**Comment by shagu** [comment]
Another one: https://github.com/shagu/pfUI/commit/4fa7c416aa61cbcd95627246a4eef5615c300ac1

**Comment by stva23** [comment]
Tried latest version today: No freezes with Vael / Geddon, much less lags. But stil 0.5-1sec freezes sometimes (but less often than before). Thanks for investigating this issue!

**Comment by Meridaw** [comment]
No lag at all on Vael now, it worked great, tnx alot! =)
