### ISSUE TITLE
gui: add auto-resize of top tabs

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#677]
![bandicam 2017-09-26 23-20-45-340](https://user-images.githubusercontent.com/24303693/30882431-976b0a64-a311-11e7-8587-7ae90f223843.jpg)

**Comment by Lichery** [comment]
I had an idea to implement this with string.len (title) + indent, but this can not be done because the length of the Latin symbol= 1, but the length of the Cyrillic symbol = 2.  Therefore the width of the buttons with the Cyrillic name will be very broad. I don't know how to solve this problem.  :((((

**Comment by lbjdaking23** [comment]
The WoW API has http://wowprogramming.com/docs/widgets/FontString/GetStringWidth
I did a quick test and seems like this should work fine at least with English did not test with other languages. The only problem is the settings UI can get very funky with too short of buttons or too long.

**Comment by Lichery** [comment]
This API is not supported in 1.12.1. I get error "attempt to call method `GetStringWidth' (a nil value)"

**Comment by Lichery** [comment]
I seem to understand how to count the number of letters, but I do not know how to correctly calculate the count for each title. I have one iteration for all the titles, and I need to count first for one, and then move on to the next.

That's how I did it:

	i = 1
	local count_width = 0
	repeat
		symbol = string.sub(title, i, i+1)
		count_width = count_width+1
		i=i+1
	until symbol
	DEFAULT_CHAT_FRAME:AddMessage(count_width)

**Comment by shagu** [comment]
`GetStringWidth()` **is** available in classic:
https://github.com/shagu/pfUI/blob/a2e0615659c4d4db5b291a0a4377e7de1652673e/modules/loot.lua#L437
