### ISSUE TITLE
Prat item/web links bugging out when using it together with pfUI

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#68]
If you use prat together with pfUI and someone links an item or URL to you, the link will show the persons name in the chat instead of the actual item/URL name

https://youtu.be/r2t3hU3m7lg

**Comment by shagu** [comment]
Prat and pfUI using the same mechanism to provide class colored names on the Chatframe. 
If this function is ran twice, it will come to this effects. You can either disable "playernames" module in Prat or wait for a fix.

`/prat playernames toggle`

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/bbdeeb5217a0b39593dddaa9d94d9ce7f6cdfe00

You'll have either to disable Prat's class colors by `/prat playernames toggle` or pfUI's class color within the settings dialog `Use class colors for known players:`.

**Comment by furyen** [comment]
Any fix being looked into?

**Comment by shagu** [comment]
> You'll have either to disable Prat's class colors by /prat playernames toggle or pfUI's class color within the settings dialog.

Both addons do the same, you'll have to choose which one should make the class colors.

**Comment by furyen** [comment]
Ah, thank you. Couldn't find the option under pfui's settings. it is called "Enable Class Colors" now.
