### ISSUE TITLE
DPSMate and KTM dock do not actually hide chat window

### ISSUE THREAD

**Issue by l1amm** [shagu/pfUI#683]
When using KTM and DPSMate skins and dock, the loot/spam chat window is not hidden when the arrow button is clicked. I want DPSMate to have a transparent background but i just see chat behind it and it looks bad. Any way to hide the chat window when the arrow in the bottom right is clicked?

**Comment by shagu** [comment]
Sorry, but If I remember correctly, I already had this a while ago, but the Blizzard's Chatframe code will automatically disable ChatFrames whenever they are hidden for some time, which led to many complains about lost chat windows. It would require some hacks to prevent this. And I don't feel like doing so. If anyone else want to, I would of course accept a well tested Pull Request.

**Comment by l1amm** [comment]
Can't we just resize the chat window to make it super small to avoid it being disabled?

**Comment by shagu** [comment]
It already hides itself when the meters are shown. Hasn't been disabled yet for me while hidden.
