### ISSUE TITLE
The tooltip and the "stack" frame in bag is overlapping

### ISSUE THREAD

**Issue by Aguilaa** [shagu/pfUI#687]
Currently when shift-clicking an item in your bag to open the "stack frame" to split items into X number (usually consumables) is blocked by the tooltip window. It would be ideal if the stack-frame could be moved to the right side of it, or somewhere else, so that tooltip and stack frame doesn't overlap.

**Comment by shagu** [comment]
but... it's blizzlike.. 
![image](https://user-images.githubusercontent.com/11586807/32797224-446a5636-c971-11e7-902a-369e822d086f.png) :'D
