### ISSUE TITLE
Enhancement: Chat scroll speed

### ISSUE THREAD

**Issue by Aguilaa** [shagu/pfUI#688]
The speed of which your mouse scrolls through the chat window is fairly slow. If this could be changeable, it would be nice.

**Comment by tmpreport** [comment]
shift + scroll can go to top and bottom  :)

**Comment by Aguilaa** [comment]
Correct. But you don't always want to scroll all the way to the top.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/2210e6c904b53fef1b029bac985ea7d3eb7f2f84
