### ISSUE TITLE
castbar: highlight lag and other delays

### ISSUE THREAD

**Issue by tmpreport** [shagu/pfUI#697]
Hi,
We'd like to see an exciting update on casting bar on the next version, which can show the latency and fill  a red bar to show the percentage at right side.
Thanks a lot.
A simple example  :)
--------------------------------------------------
|                                                      |  200ms   |
|____________________________________|__________|

**Comment by Sour** [comment]
I ended up making this before reading all of the cast bar code... the current cast bar already accounts for latency by delaying the entire event. I can get it to you but it is mostly pointless.
![Image of Cast Bar](https://imgur.com/VHT4yx9.png)
