### ISSUE TITLE
When titanpanel is enabled my right action bar moves to this position

### ISSUE THREAD

**Issue by Larsy93** [shagu/pfUI#70]
https://i.gyazo.com/bc25268a7d8fe2e0775316c0e3f3c2b2.png

if i disable titan panel it moves back again

**Comment by shagu** [comment]
Titan does some weird stuff in TitanMovable.lua on line 14
`MultiBarRight = {frameName = "MultiBarRight", frameArchor = "BOTTOMRIGHT", xArchor = "RIGHT", y = 98, position = TITAN_PANEL_PLACE_BOTTOM},`

I won't workaround their code inside of pfUI. Sorry

**Comment by shagu** [comment]
nvm. found an easy fix.

**Comment by Larsy93** [comment]
How can I fix this? Or will it be fixed since u reopened it? :)

**Comment by shagu** [comment]
It will be fixed soon :)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/127d0e52da1f4d86862174918f6fc3dc353501fe
