### ISSUE TITLE
Masterloot: LUA error on clicking an item

### ISSUE THREAD

**Issue by Grookshank** [shagu/pfUI#701]
I got the error below, when clicking on a loot item. I think it has to do with someone leaving the party, since I could click it before just fine.

https://imgur.com/a/be5im

**Comment by Road-block** [comment]
They left after you opened the lootframe? (while it was open?)

**Comment by Grookshank** [comment]
Not 100% sure, but I think so.

**Comment by Road-block** [comment]
This or similar edit should fix it https://github.com/shagu/pfUI/pull/702

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/fb1642b6b9bb2c909363ce8999aa0480418adcd4
