### ISSUE TITLE
Copy-paste error in castbar code

### ISSUE THREAD

**Issue by Road-block** [shagu/pfUI#705]
https://github.com/shagu/pfUI/blob/8f983f9e7ca9c48fe69ab834a6ef60445032545f/modules/castbar.lua#L416

Should be `SPELLLOGCRITOTHEROTHER`

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/75b3ad35f5e8758c48a2a40a1ab612130f728d16

Thanks :)
