### ISSUE TITLE
eqcompare bug

### ISSUE THREAD

**Issue by risuxd** [shagu/pfUI#708]
hi,
found a bug with eqcompare not hiding the compare tooltip. I also use the setting "tooltip position: cursor" for tooltips.

![2017-10-07_23-16-59](https://user-images.githubusercontent.com/23323160/31311887-3eef5996-abb6-11e7-988f-6f5e024fbc64.png)

great addon btw!

**Comment by Road-block** [comment]
pfUI has its own compare tooltip.  
Are you talking about the EQCompare addon? It would be best to use one or the other not both.

**Comment by risuxd** [comment]
No, I am talking about the module "eqcompare.lua" in pfUI

**Comment by shagu** [comment]
Do you have an outdated version of questie installed?

**Comment by risuxd** [comment]
yep, you know your stuff. sorry for no proper testing. +_+ thanks
