### ISSUE TITLE
nameplates: add mobhealth3 support

### ISSUE THREAD

**Issue by byaka** [shagu/pfUI#709]
![image](https://user-images.githubusercontent.com/1580811/31352098-237d0a4c-ad36-11e7-8413-5166243d97d7.png)
as u can see, in nameplate only percents.. why?

**Comment by moootv** [comment]
just a short question about addons like mobhealth 3 (mobinfo2) - 
I would like to prefer mobinfo2, since it also shows resistances of mobs. 
Should it work as well?
If not would it be possible to implement such feature: Track and show resistances.
