### ISSUE TITLE
Add an option to Hide and limit the UIErrors Frame

### ISSUE THREAD

**Issue by AquamariaWoW** [shagu/pfUI#71]
Let me first say that I greatly appreciate your work, Shagu. This UI that you're working on is far and beyond anything available for the 1.12 client today.

I was thinking perhaps it'd be a small improvement to include an option to disable the usually annoying error messages that pops up when you're rage starved or out of range etc. Just a thought.

**Comment by shagu** [comment]
I just thought about that. I don't think it's a good idea to completely remove the UIErrors. 
It might be a better idea to make them movable and/or maybe limit them to a maximum one line. 

What do you think?

**Comment by AquamariaWoW** [comment]
You're the artist. I thinkog you should follow your vision. Limiting it to a single line world certainly help clean out some of the junk on the screen. Per sy N måmåmå øøøø

**Comment by AquamariaWoW** [comment]
Personally I think that adding an option to disable it entirely would make people require downloading one less additional addon

**Comment by Cruzix** [comment]
@AquamariaWoW 
I always made my own addon for this as the error message serves no purpose at all other than cluttering your screen but would definitely not mind this being implemented into pfUI either. You can also just type /script UIErrorsFrame:Hide() ingame to hide the messages or copy paste that code into your own addon (not including /script)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/da5fcbf48529da6341ffaec704c101d334527c2c
