### ISSUE TITLE
EnemyFrames not working anymore with pfUI nameplates

### ISSUE THREAD

**Issue by moootv** [shagu/pfUI#710]
This used to work with an older version of shaguplates:
https://github.com/zetone/enemyFrames

Now it won't show debuffs anymore above the nameplates.
 Any idea?

**Comment by byaka** [comment]
pfUI also shows debuffs near nameplates. I just disabled this feature in EnemyFrames.

**Comment by moootv** [comment]
But the debuffs from pfUI do not have a timer, and that's why i want to use enemyFrames as well.

**Comment by byaka** [comment]
Try to disable pfUI's nameplates module, athink it will help.

**Comment by moootv** [comment]
But i would like to just use the integrated nameplates of pfUI with this addon.

**Comment by shagu** [comment]
As a side note: The pfUI nameplate debuffs do only show a timer if "DebuffTimers" is not loaded.

**Comment by shagu** [comment]
I had a look into this, and the reason seems to be that ShaguPlates and pfUI-plates modify the nameplates in terms of their layout and textures which lead to the fact that enemyFrames can no longer detect those as nameplates.

You'll either have change those 3 lines in enemyFrames:
https://github.com/shagu/enemyFrames/commit/3d32e8ea0f669558b49eef27c4a09dd2172b7fc5

Or simply use this version:
https://github.com/shagu/enemyFrames

Cheers

**Comment by shagu** [comment]
Pull Request has been opened to hopefully git this patch upstream:
https://github.com/zetone/enemyFrames/pull/12

**Comment by moootv** [comment]
THank you. I tried this version https://github.com/shagu/enemyFrames (deleted LUA etc.) but get this error:
https://gyazo.com/12673f0e7e98c4f8d23b9bc03d06a52b

**Comment by shagu** [comment]
Are you using the latest version?

**Comment by moootv** [comment]
Yes, just downloaded it yesterday.

**Comment by shagu** [comment]
Please don't use the release and use the latest instead. (https://github.com/shagu/pfUI#installation-latest)

**Comment by moootv** [comment]
Alright, will test it after Naxx Progress on Kronos. When will there be a new release btw?

**Comment by shagu** [comment]
I've updated the fork: https://github.com/shagu/enemyFrames/

New pull request: https://github.com/zetone/enemyFrames/pull/13

> When will there be a new release btw?
Nothing planned. I guess I'm going to remove the release section soon.
