### ISSUE TITLE
Localization: missing strings for locale

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#712]
![bandicam 2017-10-16 22-55-46-129](https://user-images.githubusercontent.com/24303693/31632783-dc9ff288-b2c6-11e7-930a-590859b859a0.jpg)
![bandicam 2017-10-16 22-56-47-855](https://user-images.githubusercontent.com/24303693/31632787-debd5920-b2c6-11e7-9e50-c48224122e6e.jpg)

**Comment by shagu** [comment]
good catch
