### ISSUE TITLE
panel: display account-wide gold value on tooltip

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#714]
![bandicam 2017-10-16 23-38-29-576](https://user-images.githubusercontent.com/24303693/31634182-40a36702-b2cb-11e7-9354-d1a299afad46.jpg)
Now in the line "Login" writes the amount of money at the time of entering the game.I think that this is unnecessary information. After all, there is the same line "This session", where it is written how much you earned for the current game. Probably, everyone will be able to calculate in mind how much money he originally had...

I propose instead to make a calculation of the money from all the characters on the account.

P.S. Sorry for my bad english...

**Comment by shagu** [comment]
You could also calculate the MobsHealth on your own, your free bagslots, the percentage of your gear's durability. But the question is why.

Regarding the account-wide money display: makes sense ;)

**Comment by Lichery** [comment]
#716 why write T[key]? These are the nicknames of game characters and they do not need to be localized)

**Comment by Sour** [comment]
@Lichery Copy paste of previous lines honestly had no idea what the T[] was
