### ISSUE TITLE
Enemy castbar not showing

### ISSUE THREAD

**Issue by jaystabins** [shagu/pfUI#718]
I can not see the enemy cast bars or enemy buffs.

Debuffs show no problem but buffs don't show and cast bar does not show. I have the option to move the enemy cast bar but can't see it when an enemy casts a spell.

**Comment by shagu** [comment]
In vanilla you can't see enemy buffs. You would need a seperate addon to track them. The castbar is shown for every target which produced an combatlog entry for the beginning of the cast.

I would need to know which enemy you're talking about, which cast, which client language and which pfUI version you're using.

**Comment by shayne56** [comment]
Hi there, I am having a similar issue. I suppose the object in question is the target unit frame cast bar in this case.
 I attempted a screen capture targeting myself casting a heal. The player cast bar shows the spell being cast, while the target cast bar does not.<img width="907" alt="2017-11-01 16_33_07-world of warcraft" src="https://user-images.githubusercontent.com/33299637/32303245-985d6bf4-bf24-11e7-9428-2ee5d495c0f2.png"> The second screen shot is showing the position with object positions unlocked.
<img width="819" alt="2017-11-01 16_33_48-world of warcraft" src="https://user-images.githubusercontent.com/33299637/32303246-9882fc5c-bf24-11e7-8bcc-38f278b1ff77.png">
The third image is to show that name plate cast bars are enabled. However, those do not show spells being cast either.
<img width="663" alt="2017-11-01 16_40_19-world of warcraft" src="https://user-images.githubusercontent.com/33299637/32303247-989c6174-bf24-11e7-9eb1-0dc4f453cc1c.png">

I've reset the settings, reinstalled and tried to use this addon exclusively to rule out interference from other addons.

I'm using the English client. Let me know if I can be of any more assistance.

**Comment by shayne56** [comment]
Just a few more observations:
No cast bars for the Rot Hide Mystic and the Scarlet Friar in Tirisfal Glades, however the Dalaran Apprentices in Silverpine Forest show cast bars on both their unit frame and name plate. Leads me to believe its not a pfUI issue. 
<img width="835" alt="2017-11-01 20_02_10-world of warcraft" src="https://user-images.githubusercontent.com/33299637/32307867-f62412ae-bf3f-11e7-93c7-932caf18082a.png">

**Comment by shagu** [comment]
Thanks for your investigations, but there are no native enemy castbars in vanilla. Therefore pfUI provides a database of all spells including their casttimes. Whenever the combatlog indicates that someone is starting to cast, it will check its database and display the according bar. 

If you target yourself, there is usually no combatlog for or at least I haven't added one, as you already see your castbar on the playercastbar. 

For every other mob, a castbar should be shown when a combatlog event exists. If you experience a missing castbar AND have a corresponding combat log event, please screenshot. But for me, it looks like, everything is working just fine.
