### ISSUE TITLE
WorldMap Tooltip Skin + Cartographer

### ISSUE THREAD

**Issue by Road-block** [shagu/pfUI#719]
The new WorldMap tooltip skinning shows properly for poi added to the world map from pfQuest but "breaks" the player arrow tooltip as well the profession node tooltips of Cartographer.  

* ![pfQuest poi tooltip](https://i.imgur.com/K9UKqHe.png)
* ![Cartographer node tooltip](https://i.imgur.com/VX68aEA.png)

**Comment by shagu** [comment]
Thanks

https://github.com/shagu/pfUI/commit/11186371eaaf959a2c99c34f3766ffd7774f3add
