### ISSUE TITLE
target frame mob tag

### ISSUE THREAD

**Issue by risuxd** [shagu/pfUI#72]
hi, 
is this feature currently implemented and bugged or is it missing? 
(if a mob is tagged by another person the target frame gets f.e. grey)
it would be very kind of you if you could add it! :)
I really like this ui and want to use it further!
thanks for your work! really appreciating it

**Comment by risuxd** [comment]
:D thanks for noticing! 
I just updated the addon with your recent changes and the sort bag button is not drawn until you move an object in your inventory or is added from loot. 
after "/rl" the button is invisible again.

echt coole sache, gibt kein besseres addon für classic! danke dir und sorry für den spam :)
gn8

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/851d2292f270002f6ec570d3f32a41a3a764c2be

**Comment by shagu** [comment]
I cannot reproduce your issue with the lost bagsort buttons. 
Please open a new ticket if it is still occurring. Including the steps to reproduce and the servername might be relevant.

Cheers
