### ISSUE TITLE
group/raid frames: missing indicator for buffs

### ISSUE THREAD

**Issue by Grookshank** [shagu/pfUI#720]
pfUI displays some buffs your class can cast on group frames, but not all it seems. I am missing:
* soulstone
* fire shield
* blood pact

This is the icon indicator I mean.
https://imgur.com/tcSXBsF

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/9708ac50d1582c8a09eedba9b95ffd235c892ed9
