### ISSUE TITLE
Stutter

### ISSUE THREAD

**Issue by moootv** [shagu/pfUI#722]
I can't reproduce it - but often times when entering a raid instance, i get stutter when approaching hostile mobs, like a short screenfreeze for 50 ms for every creature.
I do not know if it is even related to enemy creatures, but it seems like it.
When i delete the Cache via pfUI it gets solved for some time. Any idea?

**Comment by shagu** [comment]
Yes, it might be related to your setup.

**Comment by Road-block** [comment]
I don't think this can be fixed without removing features.  
In all likelihood this very short stutter is pfUI nameplate module doing a table scan on the cached player names to see if it should class color the nameplate on screen.  
As those tables get bigger and bigger over time the scan for the name will also take longer (comparatively)   
One possibility (haven't checked if this is already implemented) would be to set a limit on how many player names can be stored overall and implement an _aging_ mechanism that drops entries _older than x_.  
That would mean storing a timestamp along with the player name and purging names older than xx days when you reach your cache limit.

**Comment by shagu** [comment]
Does this also happen without any other addon active?

**Comment by shagu** [comment]
No further information were given. In case anyone stumbles over this issue, please have a look at https://github.com/shagu/pfUI/issues/676 and share your experience there.
