### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#723]
I think missing the check for the presence of a font
![bandicam 2017-10-27 00-47-58-674](https://user-images.githubusercontent.com/24303693/32078967-97575f66-bab1-11e7-9d58-8d3a2cd21e07.jpg)

**Comment by shagu** [comment]
What font did you select?

**Comment by Lichery** [comment]
I do not know how or why, but this character did not have fonts selected in the settings... it caused such errors. Only pfUI and pfQuest were loaded. After clicking on the reset config, the fonts were restored and no errors appeared.

**Comment by shagu** [comment]
I'm not going to add more checks to every setting, it would bloat the whole GUI code way to much. Sorry
