### ISSUE TITLE
Heal Prediction meter passes behind portrait

### ISSUE THREAD

**Issue by Cephel** [shagu/pfUI#725]
I mean the heal prediction green bar you get with HealComm. The target portrait for example is layered higher than the bar, so the bar just goes behind it in case of an overheal.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/d337ee7a91ebf9c6163c774b36a65847181a83bd

**Comment by Cephel** [comment]
This became a problem again sometime lately.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/377d15f22c570f9204b2983f60adf799d015661c
