### ISSUE TITLE
Target's Health bar Not showing Total Health in Min/Max format

### ISSUE THREAD

**Issue by Kalusion** [shagu/pfUI#726]
Hello,

Not sure if this is a bug or not, but I've been unable to get the target's health bar to show health in terms of Min/Max, even when the text option for Right text is selected as so. It only shows the total percentage out of 100. Makes it tough to evaluate how much damage is needed to kill a target.

**Comment by shagu** [comment]
You'll have to install MobHealth3 for that:
https://github.com/shagu/pfUI#recommended-addons
