### ISSUE TITLE
MilaTimer addon cannot be shown 

### ISSUE THREAD

**Issue by tmpreport** [shagu/pfUI#735]
MilaTimer is a simple addon to shown the  5 seconds mana recover rule. 
it shows a short purple bar to indicate 5sec after a healing action.
but it's not shown when pfui enable.
Hope it can be compatible, or pfui  can add it as a new feature.

Thanks a lot.

**Comment by Road-block** [comment]
What doesn't work? I can't see anything in addon code that would make it not work with pfUI.  
Have you tried using the `/milatimer` command instead of the `/ml` shorthand?
