### ISSUE TITLE
debufftimer: adding a new debuff does not respect the cast time

### ISSUE THREAD

**Issue by cupanoodle** [shagu/pfUI#737]
I disabled all addons except the most recent versions (as of 11/4/2017) of pfUI and pfQuest.
[here is a video of the issue](https://giant.gfycat.com/FeminineSociableIberianlynx.mp4)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/12ddd9ad8afb8206364864fa884e6e626c94afb6
