### ISSUE TITLE
Debufftime Silence

### ISSUE THREAD

**Issue by stva23** [shagu/pfUI#738]
The "Silence" debuff (priest talent) is displayed with a duration of 10 seconds. It should be 5 sec.

**Comment by shagu** [comment]
http://db.vanillagaming.org/?spell=26069

**Comment by stva23** [comment]
Its that one: http://db.vanillagaming.org/?spell=15487

**Comment by shagu** [comment]
Are you sure and can you verify the other one isn't used by anything else in the game?

**Comment by stva23** [comment]
No i cant - But i think in most cases you want to track your own casts. And the priest talent is the only silence a player can cast.
