### ISSUE TITLE
Tooltip: Show quest information

### ISSUE THREAD

**Issue by Minotic** [shagu/pfUI#739]
Show quest information in the tooltip when hovering over a quest mob that is needed for a quest that is currently in the quest log. For instance:

Foul Magic
Bloodstone Amulet: 3/10

Maybe this enhancement can only be used if pfQuest is installed but you can probably assess that better =).

Many thanks for the awesome addons you create, keep it up!

**Comment by byaka** [comment]
this implemented in EQL (that recomended to use with pfQuest) but not work correctly for me https://github.com/shagu/pfQuest/issues/4

**Comment by Minotic** [comment]
Hi byaka.

Thanks for the suggestion, indeed it adds some info on quest mobs.
Will try out if this also is the case for mobs that drop items when it is not a specific kill x mobs quest.

**Comment by shagu** [comment]
Thanks for the suggestion, but this won't ever be part of pfUI.
