### ISSUE TITLE
thirdparty.lua typo in DPSMate integration code

### ISSUE THREAD

**Issue by Road-block** [shagu/pfUI#740]
https://github.com/shagu/pfUI/blob/48b9b24d001beef622710013d926c3d8e0561b72/modules/thirdparty.lua#L312 should probably be 
```lua
pfHookDPSMate:UnregisterEvent("VARIABLES_LOADED")
``` 
to avoid the startup error.

**Comment by shagu** [comment]
`the` startup error? I didn't knew about one..

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/2a2a61dac55b374e9bdcb0ff02de9bc490d6b650

**Comment by Road-block** [comment]
Bad wording on my part and poor ticket in general.  
I think this happened when KTM was **not** docked but DPSMate **was**. When you tried to click the show/hide arrow at the bottom of the chat to show / hide DPSMate you got a lua error.  
I patched my local copy pretty fast and didn't think about it no more :P
