### ISSUE TITLE
How does team frame therapy open with 40 yards range?

### ISSUE THREAD

**Issue by aixiu** [shagu/pfUI#741]
How does team frame therapy open with 40 yards range?

**Comment by shagu** [comment]
Sorry, I don't understand this question.

**Comment by aixiu** [comment]
@shagu Sorry, I'd like to say that the treatment profession for the RAID list, 40 distance settings, the default is 30 distance, right?

**Comment by Road-block** [comment]
Sounds like he's talking about Healers and Raid Frames.  
How to enable 40yard range check for healers?

**Comment by aixiu** [comment]
@Road-block yes,That's what it means.

**Comment by shagu** [comment]
![image](https://user-images.githubusercontent.com/11586807/32797000-a540bb54-c970-11e7-97d0-7d5d56aa29bd.png)

**Comment by aixiu** [comment]
@shagu thx
