### ISSUE TITLE
chat: whispermod produces errors on invalid itemlinks

### ISSUE THREAD

**Issue by gundrust** [shagu/pfUI#742]
I just started playing with the Single Player Project - Vanilla and whenever i want to link an item in chat to command a bot i get the following LUA error:

ERROR: Iterface\FrameXML\ChatFrame.lua:1954: Invalid escape code in chat message

this is the only addon i have on a "clean" 1.12.1 install.

**Comment by Road-block** [comment]
"command a bot" sounds like a custom change to the client?

**Comment by gundrust** [comment]
No, its a repack with playerbots (fork from mangos-bots) in which you can control server made bots or any of your other made characters with good old plain chat commands (follow, stay, etc.). My client is still as vanilla as we can get (for now, now that blizz finally decided to make vanilla servers a thing)

**Comment by shagu** [comment]
And it works without having pfUI active?

**Comment by gundrust** [comment]
I just tested it and yes, the links work without issue with the addon turned off.

![ss1](https://user-images.githubusercontent.com/28711558/32630113-3e88e624-c57a-11e7-8cae-d3143cad6922.png)
![ss2](https://user-images.githubusercontent.com/28711558/32630114-40bc4ada-c57a-11e7-821e-28c71c1c9f6c.png)
![ss3](https://user-images.githubusercontent.com/28711558/32630467-6dfb496e-c57b-11e7-9c37-c78dc3aaa722.png)

**Comment by shagu** [comment]
Reproduced: Same issue on stock mangos-zero with playerbots. It looks like the bots do not produce a valid itemLink.

**Comment by shagu** [comment]
Issue:
pfUI -> Chat -> "Enable Custom Incoming Whispers Layout"
https://github.com/shagu/pfUI/blob/master/modules/chat.lua#L777

**Comment by shagu** [comment]
Thanks for your report, welcome to vanilla :)

Fixed: https://github.com/shagu/pfUI/commit/ecb6640d4f5898781856f6a9826ae483965b4ee4
