### ISSUE TITLE
third party: Heal prediction stopped working

### ISSUE THREAD

**Issue by Cephel** [shagu/pfUI#745]

**Comment by shagu** [comment]
Did you update to the latest version of HealComm?

**Comment by shagu** [comment]
Old and new versions of HealComm still work for me.

**Comment by Cephel** [comment]
![](https://i.imgur.com/YPjK13S.png)

**Comment by Cephel** [comment]
Turns out the issue lies in HealComm -> 
![](https://i.imgur.com/20ISlOB.png)
