### ISSUE TITLE
Thirdparty: MobHealth3 not showing the values

### ISSUE THREAD

**Issue by Radeghost** [shagu/pfUI#748]
I have downloaded MobHealth3 from your source and added MobHealth.lua (exported all values from elysium database, found [here](https://github.com/Jakobud/lights-hope-mobhealth3-extract)) but it does not show mob's health points in Auto mode.  Only in Min/Max and yet sometimes it's bugged and shows same values for the next target.
It works without pfUI though (.mh3 save is enabled)

**Comment by shagu** [comment]
Also doesn't work for me without pfUI
![1](https://i.imgur.com/JotgBCY.png)

**Comment by shagu** [comment]
Nevermind, I forgot to enable `/mh3 save`. It works for both now, pfUI and Blizzard Frames. Only "Health - Dyn" hasn't taking care of, using "Health - MinMax" worked as expected.

Fix for "Health - Dyn": https://github.com/shagu/pfUI/commit/a9fe29016272733aea64857ccf150f682572d373
