### ISSUE TITLE
Bug with action bar on Warrior

### ISSUE THREAD

**Issue by saysmaker** [shagu/pfUI#75]
When using the class Warrior, the first action bar bugs out and you cannot move/switch skills onto that bar. It is stuck and you can't place new skills on the bar. Not sure if it has to do with stances. I tried with other classes and it works fine

**Comment by RHawtin** [comment]
Yeah this bug happened to me also, first time using this UI. But i noticed that you can actually place your spells on all action bars normaly and only on main action bar you won't see spell icons, although they are there, when i hover my mouse over em i can ready description. Hope this helps

**Comment by shagu** [comment]
Well, I'm not happy with this one, but at least it fixes it..
https://github.com/shagu/pfUI/commit/981af6528601560e0adfd4bef92b234710520b53

**Comment by JamesCutter** [comment]
When I hover my mouse over my main action bar as warrior I cant even see the description. I have to play via clicks on my left and right action bar :E

**Comment by shagu** [comment]
I cannot reproduce this on my warrior. 
Does this still occurs with the latest version of pfUI and with all other addons disabled?

**Comment by JamesCutter** [comment]
I will download the latest version again and let u know

**Comment by JamesCutter** [comment]
It works now ! :) thanks man ( weiter so! )

**Comment by RHawtin** [comment]
Well it works for me too, so it's fixed i guess. Thanks. I also wanted to
report that i can't see items value when i hover my mouse over items. Is
that a bug too or it's just how it works?
