### ISSUE TITLE
[Chat] URL capture pattern false positives

### ISSUE THREAD

**Issue by Road-block** [shagu/pfUI#750]
Actual message: `[7. World] [PlayerName]: only prob with 1.1... no raids`  
Linkification:
![pfui-urlcapture](https://user-images.githubusercontent.com/109839/32793407-830e0020-c96e-11e7-8a36-1ff35f0366ee.png)

**Comment by shagu** [comment]
As long as I don't put a dump of the [IANA](https://www.iana.org/) database into the addon, there will always be false positives. In my opinion, it's not gamebreaking and does not harm the messages itself.
A Pull Requests is welcome, but from my side, I'm not going to dig into this.

**Comment by Road-block** [comment]
Alright, I'll try to improve the capture and submit a pull request (no timeline, might be a while)

**Comment by Road-block** [comment]
https://github.com/shagu/pfUI/pull/758
