### ISSUE TITLE
HealComm Integration Not Working

### ISSUE THREAD

**Issue by towneh** [shagu/pfUI#751]
pfUI version is the clone of the latest commit you made (2a2a61d)
HealComm is release 1.11 from Aviana's github repo
Third party Integration option is enabled
No indicators appear when heals are incoming from either myself or other people in a group or raid.

**Comment by towneh** [comment]
Update: If I disable the raid module in pfUI then HealComm starts working against my own unitframes and partyframes again!

**Comment by towneh** [comment]
Update: Re-enabling raid module, I continue now to see HealComm function across all raid frames. Very strange. This is definitely an issue but seems to straighten itself out under specific conditions.

**Comment by towneh** [comment]
Update: I believe I worked it out... HealComm bars do not appear when you use click casting configuration in pfUI on any of the raid/group frames. The HealComm bar only appears works when you select the player and press a heal spell.

**Comment by shagu** [comment]
latest version `master` of healComm:
[![healcomm](https://img.youtube.com/vi/u0cFliy-TrY/0.jpg)](https://www.youtube.com/watch?v=u0cFliy-TrY)

**Comment by towneh** [comment]
OK it turned out to be an issue with HealComm, this was fixed since I raised this issue:
https://github.com/Aviana/HealComm/commit/08a726dc901e6a9918a4f79085915952eff3b114
Thanks for taking a look though! :x
