### ISSUE TITLE
Hunter Paging BUG.

### ISSUE THREAD

**Issue by Killval** [shagu/pfUI#755]
The bug comes in at the section of action bar where you can select "enable ranged based auto paging (Hunter)" When this is enabled only about half of the time, when in melee range your bar pages to the correct page, the other half it doesn't change anything, this is extremely irritating because you can free up action bar slots by having this sort of paging, but when it doesn't work you're shit out of luck for using the abilities allotted for the bar that gets paged to in melee range. PLZ FIX. This is an excellently handy addition when it works properly!!!

**Comment by Killval** [comment]
no response??

**Comment by shagu** [comment]
I never had that problem and I was never able to reproduce it. Given that, I can't fix things that aren't broken.

**Comment by shagu** [comment]
I assume you have Wing Clip and Arcane Shot on your actionbar, don't you?

**Comment by Jabark** [comment]
I had the same problem, very rarely, but doesn't seem to happen on the latest version(s) now.

**Comment by Killval** [comment]
oh okay good deal, so I am not alone, glad someone else has seen this, and yeah Shagu thanks for clarifying I didn't understand the cannot reproduce mark. And yeah like I said I had all the proper abilities the bar needs for it to page properly and it works about 80% of the time, but there are times, it just won't page at all. You will see it if you just play around with the Hunter enough, it doesn't happen every time like I said just here and there. And it sucks because you take off the abilities to make room for other abilities on your bar, and if it doesn't page you're stuck.
