### ISSUE TITLE
Rearrange the loot frame after looting an item

### ISSUE THREAD

**Issue by shirsig** [shagu/pfUI#76]
to remove the empty slots. Xloot does this. That way you can just keep clicking to loot everything.

**Comment by gangsterakato** [comment]
Is this possible to implement it as an option only? It is convenient as it is, especially when you want to loot only 3 items on 4 for example, and leave one in the middle of the list.

**Comment by shagu** [comment]
> Is this possible to implement it as an option only?

Yup. :)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/635d403186496bc0f71892df6038f1b3f278d6eb
