### ISSUE TITLE
The user interface using more than 48MB of memory

### ISSUE THREAD

**Issue by Maltm** [shagu/pfUI#763]
I keep getting an error about this and it wants me to restart the game

**Comment by greenya** [comment]
How much memory do you have set for addons? Try to increase it. You can see it in Addons dialog at top right corner.

**Comment by stokbaek** [comment]
You should set it to 0 really, alot of these "newer" vanilla addons uses alot more memory than addon used to in vanilla

![0 memory](https://stokbaek.org/pictures/stokbaek/WoW_2017-11-20_20-01-08.png)

**Comment by Maltm** [comment]
where do i change it?

**Comment by stokbaek** [comment]
At the character screens bottom left corner click on "Addons" top right corner of this window that opens is the option to set it

**Comment by Maltm** [comment]
okay thanks will try that.

But is it normal for the addon to use that much? and it only happend while i was in BG

**Comment by Road-block** [comment]
It's pretty normal, even on the low side as addon requirements go.  
Consider the minimum amount of RAM these days is measured in Gibabytes ... that's thousands of Megabytes.

**Comment by Maltm** [comment]
True, just wondering if it's normal for it to work fine at the start, but suddenly needing more RAM, was just thinking if there was a memory leak. If there is it would at some point use alot more memory then it should.
