### ISSUE TITLE
Action bar: Action Bars Disabled for all Classes Besides Rogue and Hunter

### ISSUE THREAD

**Issue by LazyViolet** [shagu/pfUI#764]
After Playing my Rogue for quite a bit i decided to make an alt and noticed that 3 bars are missing (Namely the 6x6 one on the left, the 6x6 one on the right, and the 12x1 one in the middle) i tried reinstalling, fiddling with settings, and many other things, including making new characters with a few different race/class combos among other things, but unfortunately nothing has seemed to work, is pfUI designed to only work with Rogue/Hunter(possibly druids, only class i didnt check) or if not is there a setting or switch i am missing somewhere?
Thank you for your time

**Comment by Road-block** [comment]
The bars are enabled from Default Blizzard Options.  
Esc > Interface > Advanced Options (tab) > Action Bars section.  
Are you sure you have the other bars checked there for those characters?  
This is a per character setting and new characters don't start with all extra bars by default visible.

**Comment by LazyViolet** [comment]
That worked, i subconsciously assumed turning on Blizzard bars would lead to the weird action bar clutter im sure we have all seen once before. I feel like a moron now, thank you for the help. 

Please close this issue if you can.
