### ISSUE TITLE
Enable 40yard range，Looking at other people and equipment, lost frames

### ISSUE THREAD

**Issue by aixiu** [shagu/pfUI#767]
> ### Enable 40yard range，Looking at other people and equipment, lost frames

![default](https://user-images.githubusercontent.com/8064012/33173624-cc05a95e-d08f-11e7-8228-defbf6767281.png)
![default](https://user-images.githubusercontent.com/8064012/33173674-02952486-d090-11e7-8dd2-0b145a817c7b.png)

**Comment by shagu** [comment]
Has been fixed by this commit: https://github.com/shagu/pfUI/commit/c4380df146381542f755abb0bac8c46953e7dad3

**Comment by aixiu** [comment]
@shagu thx
