### ISSUE TITLE
Right chat issue

### ISSUE THREAD

**Issue by Draizl** [shagu/pfUI#769]
Last night when I downloaded the addon, I went into settings and began customizing it. After killing some mobs, I noticed I wasn't getting information in my right chat log regarding profession skill-ups, gathered loot, reputation gains, etc. Things that were found in the default Vanilla chat log. I've tried searching through the settings for the solution but couldn't find out where the issue was.

**Comment by SaintEcho** [comment]
Certain things are restricted to the general chat box, this is why I made it my spam one and made the right one my party/guild/whisper etc.. one. Still not perfect because then your bags block the important chat but for now thats what I'm doing.

**Comment by Draizl** [comment]
To be honest, I went into settings and reset everything to default (I
pressed customize over default when I had the option) and everything works
fine now
