### ISSUE TITLE
[BUG?] Tooltip with position [Cursor] not showing all info

### ISSUE THREAD

**Issue by dein0s** [shagu/pfUI#775]
Hey  there.
First of all I'd like to thank you for your amazing job on this addon :)

And now back to the subj - I've faced some weird issue, when quest info is not displayed in the tooltip if position of it set to [Cursor] (works fine with [Bottom] and [Dodge]). Not sure is it related to your addon or any other, but I was able to reproduce it only by changing settings in pfUI.
Position [Dodge]
![dodge](https://i.imgur.com/mRbJ6PC.png)
Position [Cursor]
![cursor](https://i.imgur.com/zZxKhFa.png)

Minimal addon list to reproduce:
1. pfUI at https://github.com/shagu/pfUI/commit/566928c9cbdbf542f7ef31c6a7aeeceea5082272
2. Questie at https://github.com/AeroScripts/QuestieDev/commit/724a864c1e32d23dd10f60d1533a255a86cd66d7
3. EQL3 at https://github.com/laytya/EQL3/commit/0c65e4a58d76b1e7271e861c5267c36df200cf37

**Comment by Svahnen** [comment]
I face the same issue, it seems to work like normal when using questie 3.69 https://github.com/AeroScripts/QuestieDev/commit/2474498bde5502e2fc31b82183ffce1ad9d941dc
