### ISSUE TITLE
request: view bank from anywhere

### ISSUE THREAD

**Issue by Valmere** [shagu/pfUI#777]
I used bagnon/banknon for the sole purpose of being able to view my bank from anywhere but it opens 2 bank windows when used along side pfUI. Could you implement this feature into pfUI?

**Comment by nonameform** [comment]
Is there any chance that you might add bank browsing from anywhere feature?

**Comment by nonameform** [comment]
What is the current state of private servers?

I am playing casually, so I might have not noticed how things have changed recently. Of course population went down after Classic was released, but I switched to TBC in the meantime and the community there is pretty lively.

It's a pity that you have lost interest in game. As someone who was really hardcore during WotLK, I know that you might get exhausted at some point, but after a long hiatus I found myself enjoying WoW once again.

**Comment by shagu** [comment]
> What is the current state of private servers?

I will not answer that question. If you have fun, just enjoy it while it lasts :wink:
