### ISSUE TITLE
Add option to disable castbars

### ISSUE THREAD

**Issue by Larsy93** [shagu/pfUI#78]
Hi, I want to disable the castbar part of the addon or well, only the one under my player portrait, but when I do I get this message spammed in my chat

https://i.gyazo.com/b32fbe3f35011176ad6459a7d6a5e665.png

would it be possible to just "hide" the player castbar instead of disabling the whole castbar module?

(I still want the nameplate castbars enabled)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/37fdaa53672b2c0cfe6b1b27ef8c85744c53bc82
