### ISSUE TITLE
bags: show cooldowns within the bankslots

### ISSUE THREAD

**Issue by Valmere** [shagu/pfUI#780]
screenshot with pfUI and banknon enabled:

![image](https://user-images.githubusercontent.com/2462756/33596197-efa6cb90-d968-11e7-8121-893a147cc8e7.png)

The cooldown time displays in the mouseover text but not on the icon while in the bank. Works fine if the item is in the bag, just not the bank.

unrelated thing with banks - moving an item from one spot to another causes the item's border color to linger on the old spot every time it's moved.

![image](https://user-images.githubusercontent.com/2462756/33596373-7a7a93dc-d969-11e7-8b3d-6a9f20634693.png)

**Comment by shagu** [comment]
Regarding the first point:
It's the same behaviour as you have with the default interface. For some reason, blizzard doesn't show cooldowns within the bankframe. I'll have a look how to workaround this.

For the second issue, I cannot reproduce this, please make sure to have the latest version installed.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/5f435d4eda07717aeae47e47d041df7850b3312e

**Comment by Valmere** [comment]
Thanks for implementing the cooldown thing. I updated to the recent commit and tried the second issue again, had all addons disabled except for pfUI. it's a small issue and there's a good chance I'm just retarded. made a small webm https://webmshare.com/Pea7L
