### ISSUE TITLE
Request: pet loyality

### ISSUE THREAD

**Issue by Qilanvan** [shagu/pfUI#782]
Pet loyality on pet bar please)

**Comment by shagu** [comment]
any suggestion how it should look like?

**Comment by Qilanvan** [comment]
mb like buff or debuff?

**Comment by mayphilc** [comment]
id suggest lookaing at the PetFeeder addon and implimenting that into PFui

**Comment by shagu** [comment]
PetFeeder doesn't have a loyality icon.

**Comment by mayphilc** [comment]
Oh it certainly does tell you the loyalty when you hover over the bar

**Comment by mayphilc** [comment]
I can provide screenshots of you'd like or you can try it out see what you think

**Comment by shagu** [comment]
I think having the color like it is now is sufficient.
