### ISSUE TITLE
Elite Dragon

### ISSUE THREAD

**Issue by eNtreDefias** [shagu/pfUI#783]
Hey, i cant seem to find the topic for the elite/rare dragon i was making for you, sorry if im just blind as fuck. If u removed it couse ur not intrested let me know, as i have spent many hours on it and im still working. Its taking a long time couse im not exsperienced at painting and i rarly have time to paint. Here is the current version if ur still intrested: https://imgur.com/a/ZR5hq (Almost only worked on the head neck part to get it to look like the original version from wow.)

**Comment by shagu** [comment]
I closed the issue (https://github.com/shagu/pfUI/issues/157) because I finished making this:
https://github.com/shagu/pfUI-eliteoverlay

Feel free to post a new issue there, as soon as you have a new graphic for me to add ;)

*You should have received a mail by github regarding that issue*

**Comment by eNtreDefias** [comment]
Ah lol, diddent think u would use the unfinished version:P I will add the finished version when its done:)
