### ISSUE TITLE
[BUG] Tracking icon changes to question mark on mount/dismount

### ISSUE THREAD

**Issue by dein0s** [shagu/pfUI#792]
As stated in subj, tracking icon acts fine until I mount or dismount. Then it changes to question mark and starts flashing, totally ignoring that tracking spell is still active.
![screen](https://i.imgur.com/9TqhDK1.png)

**Comment by Road-block** [comment]
It does that in raids as well.  
No matter if you set tracking (and the ore stays tracked on minimap) the icon changes to a pulsing question mark after a few seconds and stays that way)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/423ad332ae43859224136262a50f08617ff8f670
