### ISSUE TITLE
sellvalue: disable basic sellvalue display

### ISSUE THREAD

**Issue by tsheeley** [shagu/pfUI#799]
I love the extended SellValue option, it's helpful on so many levels. It would be really nice though if it was either a toggle between the basic and the extended version... or if there was a second option that would turn off the basic.

I've got a pretty good tooltip setup going, from top to bottom... MasterTradeSkills, pfUI Extended SellValue, ShaguInv, Aux Disenchant & Today's Value, pfUI Basic SellValue... but the basic value just throws the whole thing off.

![image](https://user-images.githubusercontent.com/31299310/34238128-04e9ac54-e5b5-11e7-939f-c5c044edd5c4.png)
 ![image](https://user-images.githubusercontent.com/31299310/34238112-e07bb7ae-e5b4-11e7-9aef-6608824816f6.png)

**Comment by Road-block** [comment]
Just disable the sellvalue module from modules.

**Comment by tsheeley** [comment]
Sorry... I should have mentioned that I also tried to disable the module in Components, but then I lose the extended info as well. So it seems to be an all or nothing setting at this point.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/issues/274
