### ISSUE TITLE
Request: Ability to re-order tooltips

### ISSUE THREAD

**Issue by tsheeley** [shagu/pfUI#800]
Is it possible to have a way to re-order how addons are displayed in tooltips?

For example, in my screens below it would be nice to have the Aux Disenchant and Today's Auction Price be above the pfUI Extended SellValue info.

As an awesome bonus, this would make it a lot easier to debug when multiple addons are doubling/tripling up on the same info.

![image](https://user-images.githubusercontent.com/31299310/34238128-04e9ac54-e5b5-11e7-939f-c5c044edd5c4.png)
 ![image](https://user-images.githubusercontent.com/31299310/34238112-e07bb7ae-e5b4-11e7-9aef-6608824816f6.png)

**Comment by shagu** [comment]
No, every addon does it's own stuff
