### ISSUE TITLE
prediction: (target)target frame isn't properly updated

### ISSUE THREAD

**Issue by shagu** [shagu/pfUI#801]
![image](https://user-images.githubusercontent.com/11586807/34272371-55192bd8-e690-11e7-80cb-929671679b57.png)

**Comment by stokbaek** [comment]
seems like it happens with target too https://imgur.com/1oRW7CZ

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/4fb75aa7d4267931f2b03ca8bf43d9dcdb88cdf7
