### ISSUE TITLE
[Enhancement] Show Hots in Unit/Raidframes

### ISSUE THREAD

**Issue by stva23** [shagu/pfUI#803]
For healers it would be i great improvement to have an option (or autodetection based on talents) for showing the hots of the own class in the raid and unitframes like the class-buffs. Remaining hot-time would be awsome but at least showing if there is already any hot would be very helpful.

**Comment by shagu** [comment]
![image](https://user-images.githubusercontent.com/11586807/34294131-633e6ddc-e707-11e7-901f-886ca93c7d5b.png)
What is missing?

**Comment by stva23** [comment]
.. nothing. Sorry everything is perfect :)  Must have overlooked this option.
