### ISSUE TITLE
env\fonts.lua: 67

### ISSUE THREAD

**Issue by Road-block** [shagu/pfUI#805]
This conditional can execute before VARIABLES_LOADED (or ADDON_LOADED for pfUI) has fired when pfUI_config is not yet populated.  
Needs a check for existence like the force_region option further up.

```lua
if pfUI_config and pfUI_config.chat and pfUI_config.chat.text.outline == "1" then
``` 
or similar will fix it.

**Comment by shagu** [comment]
thanks
https://github.com/shagu/pfUI/commit/0ab7507cc878a0102f8fea65ab58a2c127dbabcf
