### ISSUE TITLE
Submit Chinese Client Missing translate

### ISSUE THREAD

**Issue by Qcat0214** [shagu/pfUI#806]
hey shagu.i come to submit Chinese Translation：

["AtlasLoot"] = "Atlas 副本拾取",
["Average Per Hour"] = "平均每小时",
["Buff Indicator Size"] = "Buff标记大小",
["Buy"] = "购买",
["Center"] = "中间",
["Components"] = "组件",
["Cursor Tooltip Align"] = "鼠标提示对齐",
["Cursor Tooltip Offset"] = "鼠标提示偏移",
["Decode"] = "转换",
["Disable Skin"] = "禁用皮肤",
["Enable Action On Key Down"] = "启用按下动作键",
["Enable Autohide For Left Chat Panel"] =  "启用自动隐藏左聊天面板",
["Enable Autohide For Microbar Panel"] = "启用自动隐藏微面板",
["Enable Autohide For Minimap Panel"] = "启用自动隐藏小地图面板",
["Enable Autohide For Right Chat Panel"] = "启用自动隐藏右聊天面板",
["Enable Combo Point Display"] = "启用连击点显示",
["Enable Maximum Graphic Details"] = "启用最大画面细节",
["Enable Native UI-Scale"] = "启用本地UI缩放",
["Enable Vertical Health Bar"] = "启用垂直血条",
["Encode"] = "编码",
["Export"] = "导出",
["Hide Totems"] = "隐藏图腾",
["Ignore Layout"] = "忽略布局",
["Import"] = "导入",
["Minimap Tracking"] = "小地图追踪",
["Mousewheel Scroll Speed"] = "鼠标滚轮滚动速度",
["N/A"] = "N/A",
["Native"] = "本地",
["No tracking spell active"] = "没有激活的跟踪法术",
["Power Bar Anchor"] = "能量条锚点",
["Power Bar Width"] = "能量条宽度",
["Search"] = "搜索",
["Sell Grey Items"] = "出售灰色物品",
["Sell"] = "出售",
["Show Equipped Items"] = "显示已装备的物品",
["Show Inactive Tracking"] = "显示闲置的跟踪",
["Show Tooltip On Mouseover"] = "在鼠标悬停处显示提示",
["Skins"] = "皮肤",
["SortBags"] = "背包整理SortBags",
["Tracking Icon Size"] = "跟踪技能图标大小",
["Your items have been repaired for"] = "你的物品已经修好了",
["Your vendor trash has been sold and you earned"] = "你的垃圾已经售出，你赚了",

**Comment by g34651684** [comment]
Add：
["Enable Text Shadow"] ="启用文本阴影",

**Comment by shagu** [comment]
Hi, is this zhCN or zhTW?

**Comment by g34651684** [comment]
is zhCN

**Comment by g34651684** [comment]
by the way.don't you plan to update your pfQuest?That's a very powerful addons.looking forward to more functions :D

**Comment by shagu** [comment]
> by the way.don't you plan to update your pfQuest?That's a very powerful addons.looking forward to more functions :D

Yes, I plan to do that. :)
I've just checked your 60addons page, could you please add links to my original work on the pfUI and pfQuest site, thanks?

**Comment by Qcat0214** [comment]
> could you please add links to my original work on the pfUI and pfQuest site

ok.This is of course.It will be added immediately

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/8e7af2ceedcf7e65b9c02963c6acb21578f029fb
