### ISSUE TITLE
Gezielter Schuss

### ISSUE THREAD

**Issue by Genoveria** [shagu/pfUI#807]
Sorry for my bad English. But would it be possible to patch the pfUI so that the targeted shot does not appear in the Blizzard Original Bar?

<a href="http://abload.de/image.php?img=unbenannt-1f0uie.png"><img src="https://abload.de/thumb/unbenannt-1f0uie.png" /></a>

**Comment by Road-block** [comment]
You have a third-party addon that is forcing the default castbar to show.  
pfUI normally hides default castbars.

**Comment by g34651684** [comment]
@Road-block hello Road-block. i am Qcat. i see you update the EPGP addon and the at addon.And update zhCN localisation text.i want to ask, who sent you the zhCN translation text of the 2 addons?

**Comment by Road-block** [comment]
We'd better move the discussion to one of my addons @Qcat0214 😸   
I tried to contact you in-game with a couple questions, trying to make your localization efforts easier.  
To answer your question I used the terms found on the localized versions from 60addons.  
I even credit you in latest shootyepgp alpha I think [shootyepgp.toc](https://github.com/Road-block/shootyepgp/blob/98560d192c6129395616e92a76a671217ba9c16d/shootyepgp.toc#L9)

**Comment by Genoveria** [comment]
@Road-block 
Even if I hide or delete my third-party addon's I see the default castbar. But this only with the targeted shot, otherwise no other.

<a href="http://abload.de/image.php?img=bild1mpobq.png"><img src="https://abload.de/thumb/bild1mpobq.png" /></a>

**Comment by Road-block** [comment]
@Genoveria Look through SHunterTimers options, can't think of something else.  
Assuming typical pfUI settings.

**Comment by Genoveria** [comment]
@Road-block 
Big thanks, that's it, an option in SHunterTimers.
