### ISSUE TITLE
Error in prediction module

### ISSUE THREAD

**Issue by Road-block** [shagu/pfUI#808]
`[2017/12/24 09:17:24-4053-x1]: modules\prediction.lua:130: table index is nil
modules\prediction.lua:130: in function `Ress'
modules\prediction.lua:70: in function `ParseChatMessage'
modules\prediction.lua:12: in function <Interface\AddOns\pfUI\modules\prediction.lua:10>`

Shortly after entering a ZG raid.  
I'm afraid I can't say the exact circumstances, might have been that someone died across the instance portal? It was soon after entering the instance, didn't notice errors after this.

On  869e4c9

**Comment by Road-block** [comment]
Yeah I see what's the problem.  
[prediction.lua:70](https://github.com/shagu/pfUI/blob/869e4c91f771a73aedfc78d844fbfd4c12e1d98b/modules/prediction.lua#L70) needs to be
```lua
pfUI.prediction:Ress(sender, target)
```
and [prediction.lua:128](https://github.com/shagu/pfUI/blob/869e4c91f771a73aedfc78d844fbfd4c12e1d98b/modules/prediction.lua#L128)
```lua
function pfUI.prediction:Ress(sender, target)
```
That should fix it.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/eb7bae44e2643aef956738e9283cb5e457a36f2d
