### ISSUE TITLE
Frame rate always down

### ISSUE THREAD

**Issue by Kryos1** [shagu/pfUI#809]
Hi,

I don't know why but my fps won't go above 30 fps, when I do bg i am at 20 fps :/

without pfui it goes 60 fps all the time,I just have 9 addon without pfui, I can't find solution :/

**Comment by shagu** [comment]
I'd need more information on that, do you have the `Maximum Graphic Detail` enabled?
What other addons are loaded? What class do you play? Any steps to reproduce?

![image](https://user-images.githubusercontent.com/11586807/34328304-84a876d0-e8dc-11e7-86fd-9f0fe6e1147d.png)

**Comment by Kryos1** [comment]
I am on 3.2.0 (maybe the issue come from that), I play Mage and I disabled Maximum graphic detail 
![2017-12-25](https://user-images.githubusercontent.com/34816244/34338823-a89f321e-e96c-11e7-970b-13a98d846b81.png)
The weird thing is that the game is slow even on the title screen

**Comment by shagu** [comment]
Well, it can't be addon related if this already happens in the title screen.

**Comment by Kryos1** [comment]
I found the issue !

It was because I renamed the WoW.exe, then the game started to stutter, I definitely cannot understand ^^

anyway, thank you for answering this topic !

**Comment by shagu** [comment]
That's really weird o_O
