### ISSUE TITLE
Putting a weapon with a "buff enchant" into the bag triggers a lua error

### ISSUE THREAD

**Issue by Larsy93** [shagu/pfUI#81]
This happens when I put my 2H axe into the bag while rockbiter weapon is on it. If the weapon is unbuffed nothing happens.

https://i.gyazo.com/04da52267347177c31d7de0fa4868422.png

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/9a7980fa6b4bc79be946be1d4c00777de019f1a2
