### ISSUE TITLE
pfUI and QuestieRU

### ISSUE THREAD

**Issue by DafiQwart** [shagu/pfUI#810]
Please correct.
No progress is shown after the murder or collection.
That is, above the head does not appear the message MOBNAME 1/10 or MOBNAME 3/10

Addon: 
Eng Client: https://wowskill.ru/wp-content/uploads/2017/03/Questie.zip
Ru Client: https://wowskill.ru/wp-content/uploads/2017/03/QuestieRU.zip

**Comment by stokbaek** [comment]
Enable `Single Line UIErrors` in the genereal settings section and quest updates should be notified on screen.

![Option](https://stokbaek.org/pictures/stokbaek/WoW_2017-12-26_13-24-57.png)

**Comment by shagu** [comment]
Quest Progression is displayed in the so called "UIErrorFrame", if you've disabled it in pfUI, you won't be able to see it.
