### ISSUE TITLE
actionbar: change page while shift/ctrl/alt is pressed

### ISSUE THREAD

**Issue by xatian** [shagu/pfUI#811]
Hello,

First of all thank you for creating this amazing mod. Because of it I removed about 15 other old addons that are extremely clunky and hard to configure.
But one feature imho is missing from your addon regarding action-bars.

I would like to put multiple commands on the same spot of the main action bar and access them by holding a modifier (like shift / ctrl / alt)
So for example I bind "A" to a spot on the main action bar and put some skill into it.
When I press A it casts that skill.
If I press and hold shift, the main action bar goes to lets say page 2, so I see all commands I put there and then I can execute the skill on the same spot also by pressing "A" (while I still hold shift).
This greatly enhances the number of skill you can efficiently reach with the keyboard and not having them visible all the time clogging up the interface :-)

bartender2 has this functionality implemented in an separated module (called pagemaster) which you can download here:
https://classicaddons.com/index.php?/file/6-bartender2/

Thank you!

**Comment by shagu** [comment]
http://addons.us.to/addon/bartender2

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/ac250e226580c6d480f875f2ae073feae793542d
