### ISSUE TITLE
loot: enable right mouse click for loot buttons

### ISSUE THREAD

**Issue by EarthlingZero** [shagu/pfUI#817]
Hey there!

Following issue:

pfUI disabled =>
 you need to right-click a dead mob to open loot frame, then right-click (again) individual items to pick them up.

pfUI enabled =>
 you need to right-click a dead mob to open loot frame, then LEFT-click individual items to pick them up.

I know you can always shift-right-click the mob to loot everything, but I prefer to loot select items. But having to do that with a left-click feels odd.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/3440fc7c7a4d8d4541233ddeda94984552346c8d
