### ISSUE TITLE
First time playing on Light's Hope; pfUI installed 10 min ago for first time: LUA error.

### ISSUE THREAD

**Issue by MajorKryme** [shagu/pfUI#830]
Hello, I did a completely fresh install today, the only addon I currently have in my addons folder if pfUI.  I loaded the game and clicked defaults for the installation wizard.  Everything appeared fine until I attempted to look at the pfUI menu system. Upon entering the pfUI settings, I was repeated given the following error in the left side chat box: ERROR: Interface\AddOns\pfUI\modules\gui.lua:42: attempt to index field 'gui' (a nil value)

This is all of the data I can provide.  Thank you.

**Comment by shagu** [comment]
Sorry, I forgot to push something yesterday: https://github.com/shagu/pfUI/commit/cb34dd715f9174a9140eef0aa6aee342b092c80a

It's now fixed on the latest version
