### ISSUE TITLE
raidframe layout Suggest

### ISSUE THREAD

**Issue by rionli** [shagu/pfUI#831]
Hi!!  First of all, thank you for the good use of UI.   But I have a suggestion about the RAID module

I think his layout can be changed into 5 horizontally arranged in a small team, not a vertical arrangement. In this way, I can use the team module's display team directly to replace the team module. Can you add a number of team arrangement patterns? Or how do I change your code to do this?

Chinese people use translation software for translation of articles may not be well expressed, please forgive me

**Comment by shagu** [comment]
I don't think I'll going to add that. People can just move their frames by themselves using the unlock-mode
