### ISSUE TITLE
Amount of energy shown.

### ISSUE THREAD

**Issue by 0v3rd0s3d** [shagu/pfUI#833]
Hey there. Could not find any information about displaying of amount of energy shown in frame. Is there any way to show current amount of avaliable energy?

**Comment by Haiwuu** [comment]
The menu options under Unit Frames -> Player tagged with mana should apply to energy aswell.  You'll have to scroll down for the options.

**Comment by 0v3rd0s3d** [comment]
Thanks you Haiwuu, that works!
