### ISSUE TITLE
Bug: borders overpapping in latest version

### ISSUE THREAD

**Issue by Grookshank** [shagu/pfUI#835]
In the lastest version I have some issues with borders I did not have before.

* Item Compare does overlapp
* KTM/DPS mate windows don't fit chat frame.

See screenshots.
https://imgur.com/a/qIpfr

**Comment by shagu** [comment]
I'll just write the same as I already wrote you on discord:

It is only the backdrop overlapping by the amount of your `borderpx`-size to avoid having two vertical lines. 

![image](https://user-images.githubusercontent.com/11586807/34915843-501bf57a-f92d-11e7-9ed7-20dc11b2b76b.png)

As a reference: https://github.com/shagu/pfUI/blob/master/modules/thirdparty.lua#L86

Regarding the item comparison, are you sure to use the pfUI-builtin equip compare?

**Comment by Grookshank** [comment]
Regarding DPS mate and KTM:
![grafik](https://user-images.githubusercontent.com/9802675/34915995-b51e4c7c-f930-11e7-8722-d2246d1e7302.png)
looks bad imho. The black background of dps mate is higher than from KTM. Also the top line from DPS mate does not finish right. I don't want to get on your nerves, but I don't get what I am supposed to change to avoid those effects.

EQcompare: I actually had the external one activated on the character. My bad.

**Comment by shagu** [comment]
The game renders all UI-elements to a layer with the height of 786px. This one is then stretched to your current resolution. Each graphic card does that in other ways. Some look good, some look bad. You can play with UIScale to find a setting that can be scaled nicely.
