### ISSUE TITLE
Weird targeting

### ISSUE THREAD

**Issue by elenmerbau** [shagu/pfUI#836]
Since last updates I noticed some really weird targeting. It targets on mouseover or somehow like this. Our lock with PfUI installed noticed it aswell, summoning random people instead of chosen one. If I target myself, I can see how my target changes on mouseover. (pic related: https://imgur.com/a/nGgNx)

Did I miss some new feature or checkbox?

**Comment by shagu** [comment]
Are you sure it is pfUI related? Please add a list of your addons.

**Comment by elenmerbau** [comment]
Hm, I turned off all addons and this glitch disappeared. Thanks for advice :<

**Comment by elenmerbau** [comment]
Figured out that it was Honorspy, very confused now.
