### ISSUE TITLE
Suggestion: Integrate LunaUnitFrames

### ISSUE THREAD

**Issue by mrrosh** [shagu/pfUI#84]
The addon LunaUnitFrames is the most well made unit frame addon so far for vanilla, why bother working on your own and putting tons of hours into it when you can find a way to integrate it with pfUI.

If that's not possible, it's cool, we'll wait until you sort things out with modules not reacting good when disabled.

**Comment by shagu** [comment]
Please read the description of the project.
> An educational project for World of Warcraft (1.12) mostly known as "Vanilla" which aimes to be a full replacement for the original Wow interface. [...]  It is completely written from scratch without any inclusion of 3rd party addons or libraries.

Nevertheless, there will be an option to disable pfUI's UnitFrames sometime.

**Comment by shagu** [comment]
pfUI-UnitFrames can now be disabled. https://github.com/shagu/pfUI/commit/0dac5bc1e0b632163631e503f35b58aab2cbaf6f
