### ISSUE TITLE
Aimed shot castbar still shows even if it was casted out of range

### ISSUE THREAD

**Issue by cleiru** [shagu/pfUI#841]
Castbar shows even when casted out of range and remains there,
Outcome:
1.) Aimed shot is not casted (because it's out of range)
2.) Castbar stays there.

Recommended outcome:
When Aimed shot is out of range and the button is pressed,
1.) Castbar does not appear.

Same issue appears whenever target is too close.

**Comment by Road-block** [comment]
That in all likelihood is another addon.  
pfUI does not have an aimed-shot castbar.  
Check the options of SHunterTimers (/sht menu) or rais_Autoshot or similar addon.

**Comment by shagu** [comment]
`pfUI does not have an aimed-shot castbar.`
that's not the truth, pfUI does have an aimed shot castbar.

A screenshot would be nice anyways. Just to be sure that we talk about the pfUI one.

**Comment by Road-block** [comment]
Yeah I've seen the screenshot he's talking about this  
![image](https://user-images.githubusercontent.com/109839/35188682-e581069a-fe42-11e7-91d9-18b2e574e0b5.png)

**Comment by shagu** [comment]
Ehm, where did you saw that screenshot? I can't see any in the ticket

**Comment by Road-block** [comment]
Another discord 😸

**Comment by shagu** [comment]
Well then, as @Road-block said: `Check the options of SHunterTimers (/sht menu) or rais_Autoshot or similar addon.` 😁
