### ISSUE TITLE
Aimed shot castbar still shows even if it was casted out of range [Reissue]

### ISSUE THREAD

**Issue by cleiru** [shagu/pfUI#844]
Original post: https://github.com/shagu/pfUI/issues/841

Providing screenshot: 
![image](https://user-images.githubusercontent.com/35625012/35216647-45111f62-ffa3-11e7-9141-e8b1aced71dd.png)

As you can see, target is too close yet the aimedshot castbar shows and stays under player portrait

**Comment by cleiru** [comment]
2.) Out of range scenario
![image](https://user-images.githubusercontent.com/35625012/35216741-9bf48fee-ffa3-11e7-84e5-74d25dccce48.png)

**Comment by cleiru** [comment]
Also, I do not know who road-block is

**Comment by cleiru** [comment]
It's okay.. I was just surprised the issue was made invalid.

**Comment by shagu** [comment]
Only happens when using a macro, ay?

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/040abcb270868eb4c819c78b2470e304f2f04970
