### ISSUE TITLE
BUG: Profile pfUI breaks UI

### ISSUE THREAD

**Issue by stokbaek** [shagu/pfUI#845]
If you load the default pfUI profile from the profile list will pfUI break and give the following error
```
env\fonts.lua:67: attempt to index field `text' (a nil value)
env\fonts.lua:67: in function `UpdateFonts'
pfUI\pfUI.lua:75: in function <Interface\AddOns\pfUI\pfUI.lua:72>
```

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/2ab74b1f3d474d0cc9ef1ab64aa9f39ecac57ce7
