### ISSUE TITLE
Visual Bug on Shadow Word: Pain duration

### ISSUE THREAD

**Issue by Leithmorien** [shagu/pfUI#846]
Not sure if may happen with other time-based spells (but I'm pretty sure it does), anyway:

When spending the 2 talent points to raise to above mentioned from 18 to 24 seconds, the debuff time on any target KEEPS showing 18 seconds instead of the correct 24.

Please solve.

**Comment by Haiwuu** [comment]
https://github.com/shagu/pfUI/issues/624

**Comment by Leithmorien** [comment]
Thanks, noted (and increased value in locale\enUS)

**Comment by Road-block** [comment]
This will never be solved in a generic way for everyone, for two reasons.

- There is no way to know what other players have specced into.
- Even if you used addon communication among pfUI users to transmit that information  
   There is no way to separate **your** SW:P on an enemy from another player's SW:P

As a result the compromise of using base values for spell durations.  
It is just a limitation we have to live with in vanilla.

**Comment by Leithmorien** [comment]
Is a limit in the vanilla core indeed

**Comment by v1p4** [comment]
You can adjust it by yourself. Just edit the value like you want

env/locales_enUS.lua

126 | ["Whipweed Entangle"] = 18,
-- | --
127 | ["Moonfire"] = 12,
128 | ["Fireball"] = 8,
129 | ["Frostbolt"] = 9,
130 | ["Serpent Sting"] = 15,
131 | ["Shadow Word: Pain"] = 18,
