### ISSUE TITLE
Pet happyness

### ISSUE THREAD

**Issue by bhaap** [shagu/pfUI#849]
Pet happyness showing as very happy no matter what level its on.

**Comment by shagu** [comment]
where?

**Comment by bhaap** [comment]
Character pane, pet tab. The icon there shows a happy icon nomatter what happyness level the pet is at.

**Comment by shagu** [comment]
That's not a pfUI issue, you will have the same without any addons. PfUI displays the happyness with the colors of your pet bar. Green/Yellow/Red.
