### ISSUE TITLE
Elite icon for nameplates

### ISSUE THREAD

**Issue by eNtreDefias** [shagu/pfUI#853]
Something simple like in bfa: https://imgur.com/a/dEErs sorry for small picture. Its pretty nice to notice elites around you easyer from the nameplates when you have not targeted anything.

**Comment by dein0s** [comment]
Have you tried https://github.com/shagu/pfUI-eliteoverlay ?

**Comment by Polopollo85** [comment]
Luna unit frame does it very well. I don;t know if we can have that with pfUI:

https://imgur.com/p6DLnsj

**Comment by shagu** [comment]
This issue is about nameplates, not unitframes.

For unitframes, use: https://github.com/shagu/pfUI-eliteoverlay
