### ISSUE TITLE
Moveable/removable repair icon statue

### ISSUE THREAD

**Issue by eNtreDefias** [shagu/pfUI#854]
https://imgur.com/a/aF4AS If you increase the minimap size it will get stuck in a akward spot. Maybe evn a reskinned kinda blocky, squarey version that fits with the ui could be nice. I know there is a %repair on the panels, but it does not show what specific item that is geting destroyed.

**Comment by eNtreDefias** [comment]
Made some simple ones just to show(they are obviously not done cleanly), kinda something like this: https://imgur.com/a/D1D80 can make it more advanced or simpler if ur intrested, was gonna try to experiment with making the same kinda borders like in pfui with them, but did not have time:P

**Comment by MOUZU** [comment]
I will look into this request.

The according Frame in Blizzard's UI is called "DurabilityFrame". I will look into possibly making it moveable and also adding a parameter to hide the frame entirely.
