### ISSUE TITLE
Unitframes - Swapping from Vertical to Horizontal will not update properly

### ISSUE THREAD

**Issue by MOUZU** [shagu/pfUI#857]
If you switch from horizontal(default) to vertical orientation for your unitframes and back to horizontal again it will not update the unitframes until you relog.

This can be corrected in unitframes.lua by enhancing the if-statement at line 131 and add an else-statement and set it to horizontal

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/39fc5a0d37ebe5b46dc30db9d2344c1dbc880292
