### ISSUE TITLE
non-translatable strings

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#862]
please add the translation capability for:
![bandicam 2018-03-08 00-44-23-549](https://user-images.githubusercontent.com/24303693/37120030-434fca4a-226a-11e8-81c1-006fbb26fc32.jpg)
![bandicam 2018-03-08 00-44-36-674](https://user-images.githubusercontent.com/24303693/37120032-44fcefd0-226a-11e8-8d0c-9217e87fbc3b.jpg)
![bandicam 2018-03-08 00-44-55-274](https://user-images.githubusercontent.com/24303693/37120037-479ca7d0-226a-11e8-9d94-72ba94afb520.jpg)
![bandicam 2018-03-08 00-44-47-290](https://user-images.githubusercontent.com/24303693/37120038-47c1652a-226a-11e8-8d9a-deb712147e11.jpg)

Also please delete old strings (maybe there are others):
  ["Enable Combat Glow Effects On Group Frames"] 
  ["Enable Combat Glow Effects On Screen Edges"] 
  ["Enable Combat Glow Effects On Unit Frames"]

**Comment by shagu** [comment]
https://github.com/shagu/pfUI-toolbox/commit/3d6c7be919a577792b9d948d2244254b0d471156
&
https://github.com/shagu/pfUI/commit/bb131f6021acc12378bb2e660800fb2c54f0bbf4
