### ISSUE TITLE
Suggestion: Ability to completely disable custom fonts

### ISSUE THREAD

**Issue by throwaway7** [shagu/pfUI#864]
It seems that the chat font and the "Standard text font" are locked together, whereas in a default setting the chat font would be "ARIALN" while the other stuff would be "FRIZQT".

Also, I can't seem to find an option to change the font for the scrolling combat text for damage dealt, changing the "Scrolling combat text font" setting only affects incoming damage and similar.

Would it be possible to add an option to completely disable custom fonts and force default for everything?

**Comment by shagu** [comment]
> Also, I can't seem to find an option to change the font for the scrolling combat text for damage dealt, changing the "Scrolling combat text font" setting only affects incoming damage and similar.

You need to restart the game to have the selected font take effect.

Regarding the other suggestions, I will have a look into

**Comment by throwaway7** [comment]
Oh I will try that, given that the other fonts changed on reloadui, I assumed that one would too.
Thanks for looking into it, this really is the only gripe I have, really excellent work by the way.
