### ISSUE TITLE
fonts: error while loading addon for the first time

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#869]
When I load the addon for the first time (the WTF folder is empty), this error occurs.
![bandicam 2018-03-27 22-30-56-928](https://user-images.githubusercontent.com/24303693/37994249-a2bef1e0-3219-11e8-813a-1e393f106d22.jpg)
launched only pfUI. Screenshot full screen:
![wow 2018-03-27 23-59-26-279](https://user-images.githubusercontent.com/24303693/37994770-3441b25a-321b-11e8-90a8-5f272cc0ad91.jpg)

P.S. Also note that the name of the button in Russian. This is not very good, it is better to make such names non-localizable. :)

**Comment by shagu** [comment]
Thanks, I will look into this tomorrow.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/50ea0749dd1c20fcfcf86da9c5b700790d0c7a9c
