### ISSUE TITLE
Add resting indicator

### ISSUE THREAD

**Issue by jfastnacht** [shagu/pfUI#87]
Add a resting indicator into the UI.

Example:
![image](https://cloud.githubusercontent.com/assets/6183607/20235371/4926f1e6-a890-11e6-818c-4bf151a393b4.png)

WoW API:
http://wowprogramming.com/docs/api/IsResting

**Comment by jfastnacht** [comment]
I'm not completely happy with the result. Maybe you can fix the layering issue and adjust placing to your taste:

![image](https://cloud.githubusercontent.com/assets/6183607/20243003/f6a25450-a944-11e6-96d3-fd870a89746f.png)

**Comment by shagu** [comment]
I'm not sure where to place this icon. The position on your screenshot conflicts with the leader Icon.
To let every icon know about each other to perfectly arrange them will be alot of extra work.
Any suggestions?

**Comment by shagu** [comment]
For now, you can see the resting status in the XPbar tooltip since this commit:
https://github.com/shagu/pfUI/commit/00b7941de7851185be7db2d8c15525d3d61482c2

**Comment by shagu** [comment]
> Add a resting indicator into the UI.

Implemented via mouseover on the experience bar. 
As no further suggestions where made regarding the icon placement, I'll close this one.
