### ISSUE TITLE
Buff: debuff tooltip not showing on mouseover

### ISSUE THREAD

**Issue by dein0s** [shagu/pfUI#870]
There seems to be an issue when you have more then 1 debuff on you. Tooltip shows for only first debuff, but not for the rest. Also, as shown on second screen - tooltip value is wrong. It shows info about left debuff for the right one.
![Iscreenshot1](https://i.imgur.com/P6hEkPa.png)
![Iscreenshot2](https://i.imgur.com/unPGkkq.png)

**Comment by Grookshank** [comment]
Testing this seems to show, that the tooltips for debuffs are shifted by 1 to the right; i.e.:
1st debuff (from right) shows the tooltip from zero debuff (i.e. none)
2nd debuff (from right) shows the tooltip from 1st debuff
3nd debuff (from right) shows the tooltip from 2nd debuff

Reason seems to be that there is a weapon buff, but no weapon debuff, but the buff module starts counting both the same (from 1).

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/fc0106e741967123834004fecadd3bb1b9a6bb0a
