### ISSUE TITLE
Overpower/Berserker rage stance swap macro error message

### ISSUE THREAD

**Issue by Frainb** [shagu/pfUI#875]
/run local texture,name,isActive,isCastable = GetShapeshiftFormInfo(1); if isActive then CastSpellByName("Overpower"); else CastSpellByName("Battle Stance()"); end;

and

/run local texture,name,isActive,isCastable = GetShapeshiftFormInfo(3); if isActive then CastSpellByName("Berserker Rage"); else CastSpellByName("Berserker Stance()"); end;

gives the error messege
Interface\AddOns\pfUI\api\spell.lua:126: table index is nil

I've tried and disabled addons checked if there was something wrong but i don't understand how all of a sudden it became a problem

**Comment by shagu** [comment]
This was fixed 20 hours ago with this commit: https://github.com/shagu/pfUI/commit/1c4299ad015847c1e96a4146664a3c4030101427

please update to the latest version and try again
