### ISSUE TITLE
Target Castbar not showing up

### ISSUE THREAD

**Issue by PuffedxO** [shagu/pfUI#878]
Since I updatet to the latest Version some days ago my Enemy Castbar disappeared.
Reinstalled wow and with only pfUI installed it also doesnt work. The only option i found is to disable it, but that box istn checked (I think by default it's activated!). In the unlock mode, the Castbar shows up.

Anything i am missing here?

**Comment by shagu** [comment]
Which enemy doesn't show its castbar?

**Comment by PuffedxO** [comment]
The castbar isnt working at all. Neather when I'm selfcasting nor someone else or e.g. a Boss casts something.

![unbenannt](https://user-images.githubusercontent.com/34540617/38493410-6622a866-3bf2-11e8-961a-04d211797bfa.jpg)
![unbenannt2](https://user-images.githubusercontent.com/34540617/38493411-663cd43e-3bf2-11e8-90c1-af2015bd3a85.jpg)

**Comment by shagu** [comment]
Regarding your own castbar, this was never shown, as it just scans the combat log for others activity. Regarding the rest, I fucked up your german locales lately. I will fix that as soon as i come home.

**Comment by shagu** [comment]
fixed:
https://github.com/shagu/pfUI/commit/f39d84a9b84f457b24f2cdb1e6463f1848961e71

**Comment by PuffedxO** [comment]
Perfect, now the debuff timer is also working again! Big thx! Love it :)
