### ISSUE TITLE
A small request

### ISSUE THREAD

**Issue by on-dit** [shagu/pfUI#879]
Dear shagu: First of all thank you very much for your pfui. When I first saw pfui, I fell in love with her. I am obsessed with pfui, and even I recommend pfui to every friend around me. However, I have a small question. Do you not know how my dear can help? You should know xpel ui. When you place the cursor on the buff, it will show your team who does not have this buff. Do not know my favorite pfui can achieve this function? I am the team's DKP administrator. This is very important to us. I hope shagu can help. Finally, may the Lord be with you.

**Comment by shagu** [comment]
Thanks for the kind words. I will look into this. Could be easy to achieve, let's see :)

**Comment by on-dit** [comment]
Wow, I'm really lucky. I received a reply from shagu in the first place. Thank you very much for your help, I love you!

**Comment by shagu** [comment]
![image](https://user-images.githubusercontent.com/11586807/38515467-a533a28e-3c34-11e8-9aca-84f22a225f36.png)

here we go: https://github.com/shagu/pfUI/commit/8cf70d5d6a843922019a345e12a71bdfc45863e3

:)
