### ISSUE TITLE
Left chat text doesn't scale to the chat frame at launch

### ISSUE THREAD

**Issue by gangsterakato** [shagu/pfUI#88]
![leftchatframe](https://cloud.githubusercontent.com/assets/15717943/20235980/133b0ac2-a8a4-11e6-878e-eae3714a2331.png)

When launching the game, the left chat text doesn't fully scale to its frame in comparison to the right frame one. Only two lines are displayed at once. _Reset Player Cache, Chat or Positions_ fixes the problem and displays 8 lines, like the right chat frame.

The bug seems to appears when on the fly, or when I'm hearthstone, too. Maybe when the character go in another area.

I play in windowed mode.

**Comment by gangsterakato** [comment]
Alright, I cleaned my WTF folder and it seems that the bug is now gone. I close this issue, and re-open it later if I find what was the problem.

**Comment by mep2664** [comment]
this is happening to me :(
