### ISSUE TITLE
core: show firstrun dialog after configuration reset

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#880]
After use Delete/Reset **Configuration** or **Cache**:
if hide right chat panel then the name will not be hidden
![bandicam 2018-04-10 23-49-39-085](https://user-images.githubusercontent.com/24303693/38583650-5ce10bbe-3d1c-11e8-9974-5298922e6c0e.jpg)

**Comment by shagu** [comment]
This is working as intended. Because as long as you haven't told pfUI to manage this chatframe, using the first-run dialog, pfUI won't touch it.

**Comment by Lichery** [comment]
But when you reset the configuration or cache, the first-run dialog does not appear. How can I configure the management of this chatframe?

**Comment by shagu** [comment]
When I reset the cache, it doesn't affect the cache. And when I press reset-everything, the firstrun will show

**Comment by Lichery** [comment]
Please add the launch of the first-run dialog after reset configuration so that everything can be properly configured.

**Comment by Lichery** [comment]
In this case, it seems to me that the "Firstrun" button is no longer needed because:
1) this dialog is launched automatically at the first start, when the addon cache is absent
2) you can manually start it by resetting the configurations

**Comment by shagu** [comment]
What I need to do is merge the "Reset Configuration" and "Reset Firstrun" together. Because from a user perspective, those are affecting the same.

Actually those are two seperate configurations, but as it might be confusing for the enduser who doesn't know, I will merge that.

**Comment by Lichery** [comment]
I also meant that it is necessary to unite :)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/4c3e8564a955e0ca270518476116310ead5f87b6
