### ISSUE TITLE
unbuffed players dont show when hold shift

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#881]
If you hover the mouse over the buff and hold down the Shift key, then players without a buff will not be displayed. They start to be displayed ONLY if you update the tooltip without releasing the Shift key.
![bandicam 2018-04-10 23-51-55-283](https://user-images.githubusercontent.com/24303693/38583676-75ad4e5a-3d1c-11e8-9412-0a6ffa07397b.jpg)

**Comment by shagu** [comment]
The check is done "OnEnter" as there isn't any OnUpdate that I could invoke for this. Not without creating another frame or let pfUI eat some resources. You will have to press shift right before you start hovering the buff.

**Comment by Lichery** [comment]
I have an idea. Make a check via MouseIsOver http://vanilla-wow.wikia.com/wiki/API_MouseIsOver
something like this:
We check if the Shift key is pressed and whether the cursor is on the buff, and if this is done, then update the tooltip
```
if IsShiftKeyDown() and MouseIsOver(pfUIPlayerBuff1) then
	GameTooltip:Show() -- for update tooltip
end
```
