### ISSUE TITLE
Ability to set someone else as lootmaster

### ISSUE THREAD

**Issue by Eltafez** [shagu/pfUI#883]
As leader of a raid you can set someone as disenchanter and/or banker, but there is no option to set them as lootmaster unless you pass them leadership first. I propose integrating this option from the default Blizzard UI.

**Comment by shagu** [comment]
`I propose integrating this option from the default Blizzard UI.` - Done.
![image](https://user-images.githubusercontent.com/11586807/38633027-aa6e9458-3dbe-11e8-8a8d-58b7d03d5832.png)

**Comment by Grookshank** [comment]
He is talking about the loot master option, which with pfUI only works on the target frame, but not on the raid frames. I personally have no issue with that, but pfUI changes the standard behaviour here.

**Comment by shagu** [comment]
I know what he's talking about adding the Lootmaster to the raidframes. But I don't see where pfUI is different from the standard here, because all I'm saying here is, that I can't find the Lootmaster option on the wow standard raid frames.

**Comment by shagu** [comment]
Well, Here's the fix: https://github.com/shagu/pfUI/commit/865ae6384ab2f81425c08b1d7f6e6b2ce5e341dd
pfUI now uses group-frame dropdowns on raid-frames.
Would still love to see a screenshot of the so-called "standard behaviour" that pfUI was breaking.

**Comment by Eltafez** [comment]
Apologies for not being clearer. After re-checking, it appears it's already there but I'm wondering if it can be expanded on instead.

If you're leader and set loot to master looter, then target someone from your group within the raid, you can promote them to master looter.

![screenshot_1](https://user-images.githubusercontent.com/38287865/38644776-075b0598-3de2-11e8-97d3-127babad7cd5.png)
![ayxnvzcetv2hiu46dva9gw](https://user-images.githubusercontent.com/38287865/38644786-0f334834-3de2-11e8-99ab-e85723d01637.png)

If I recall correctly, disenchanter and banker had the same limitation (same group only) months ago in an  old version and, if possible, I would like masterlooter enabled for people in other groups.

I hope this makes sense?
