### ISSUE TITLE
Coloring profession

### ISSUE THREAD

**Issue by on-dit** [shagu/pfUI#884]
Wow, today I know a beautiful woman. I thought it was the luckiest thing. But I did not expect that the biggest surprise comes from shagu. Thank you very much for your help. Today's team activity, I can clearly see whether the team members buff is missing. However, if the missing name can be used professional colors, is not it more perfect? I think pfui is the perfect UI. I love her!

**Comment by on-dit** [comment]
I was a fool and apologized to shagu for my confusion. For example, mage's professional color is blue and priest's professional color is white. Why use different colors to mark careers? Melee occupation requires Elixir of the Mongoose, but the legal profession does not need to, the legal profession needs Greater Arcane Elixir. When we check the Greater Arcane Elixir, there is definitely no such buff in melee. If all people use one color, there is no way to distinguish who is not Greater Arcane Elixir and who does not need Greater Arcane Elixir, so I hope shagu can be more perfect. Let fools like me distinguish careers with different colors. Finally, thanks to shagu's help, without your pfui, my WOW will be a lot less fun.

**Comment by on-dit** [comment]
I was a fool and apologized to shagu for my confusion. For example, mage's professional color is blue and priest's professional color is white. Why use different colors to mark careers? Melee occupation requires Elixir of the Mongoose, but the legal profession does not need to, the legal profession needs Greater Arcane Elixir. When we check the Greater Arcane Elixir, there is definitely no such buff in melee. If all people use one color, there is no way to distinguish who is not Greater Arcane Elixir and who does not need Greater Arcane Elixir, so I hope shagu can be more perfect. Let fools like me distinguish careers with different colors. Finally, thanks to shagu's help, without your pfui, my WOW will be a lot less fun.

**Comment by shagu** [comment]
Included in the latest version by this commit: https://github.com/shagu/pfUI/commit/be00feaf85f157706b2cddc8e08bb19452155b6a
