### ISSUE TITLE
actionbars: vertical bar cannot hide empty buttons

### ISSUE THREAD

**Issue by Zeenar** [shagu/pfUI#887]
The empty action bar buttons sometimes show even though being disabled, but only for right bar 2 for some reason. They disappear again if forced to show, e.g opening and closing the spellbook. Some things that always seem to cause the issue to appear are: everytime logging in to a character and anytime a pet is manually commanded to take any sort of action.

**Comment by shagu** [comment]
This works as designed. They always show up while the spellbook is open. This also matches the behaviour of the default UI and I think thats what people expect.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/891c1ba13784be068fc72a55bda44f57de57d974
