### ISSUE TITLE
World Chat

### ISSUE THREAD

**Issue by Biggdad** [shagu/pfUI#889]
I cannot seem to get world chat to populate in the Loot / Spam window. Any ideas?

**Comment by shagu** [comment]
No idea. But on Kronos I've experienced, that the world-chat went into the first window once. I was able to remove it from there and  never experienced that again.

**Comment by Biggdad** [comment]
Yea, I'm on Lightshope and just cant get it to the Loot Spam window. Doesn't matter what I do, it always stays in the main chat window. 
Also I love your work man! You make some great stuff.

**Comment by shagu** [comment]
Just to be sure, you did ran the firstrun-dialog and you have selected to let pfUI handle the chat windows there, right?
