### ISSUE TITLE
Native letters not entering in chat window.

### ISSUE THREAD

**Issue by Smoothie321** [shagu/pfUI#890]
I have encountered NUMEROUS times where my native letters is not being entered into the chat...

i can write it in the chatbox. But when i press enter. Nothing for example.

Rød -> Rd
Æble -> ble
Står -> Str.

If i write æøå, nothing comes up, no chatbubble, no nothing, i have disabled every single other addons but pfUI, still to no awail.. Some times it works, sometimes it doesn't, nothing seem to trigger it.
Its not the end of the world and all, but sure would like to be able to atleast make it work.

Ask me everything possible, i will try and answer as best as i can, and thanks for a fantastic addon 

Cheers Smoothie
- Kronos III

**Comment by stokbaek** [comment]
Works fine for me with Expressway font. What font are you using?
![Chat letters](https://stokbaek.org/pictures/stokbaek/WoW_2018-04-21_07-56-33.png)

**Comment by Lichery** [comment]
this is the problem in the font. The font you selected does not support these characters.

**Comment by Lichery** [comment]
please, write fonts that do not support these characters, I'll try to fix it.

**Comment by Smoothie321** [comment]
I changed to the font you are using, and the problem was still there, but
it comes and goes occasionally, still have no clue what causes it.
But it was on all my chars, with and without pfUI. So not sure.

But atleast i have partially native letters now, thats huge! :D

**Comment by Smoothie321** [comment]
OH! And it was the default font

2018-04-25 12:42 GMT+02:00 Mikkel Hjort <codhjort@gmail.com>:

> I changed to the font you are using, and the problem was still there, but
> it comes and goes occasionally, still have no clue what causes it.
> But it was on all my chars, with and without pfUI. So not sure.
>
> But atleast i have partially native letters now, thats huge! :D
>
