### ISSUE TITLE
change "Bagslots Per Row"

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#898]
along with "Bagslots Per Row" changing scale. :(
![wow 2018-04-27 01-38-47-925](https://user-images.githubusercontent.com/24303693/39335462-d968a222-49bb-11e8-8047-8531c7d1d343.jpg)
![wow 2018-04-27 01-39-05-093](https://user-images.githubusercontent.com/24303693/39335463-d99316f6-49bb-11e8-914c-746f882cdbe2.jpg)
![wow 2018-04-27 01-39-26-344](https://user-images.githubusercontent.com/24303693/39335465-da2e7e3e-49bb-11e8-9342-3ff7cae20f25.jpg)

**Comment by Lichery** [comment]
apparently this is due to the fact that bagframe set a static size and if you change slots per row, the cell size is made as the frame size

**Comment by Lichery** [comment]
https://github.com/shagu/pfUI/pull/896
> Old function was based at right panel (chat) size and had fixed params. New function based on icon size variable from bags gui configs and it has dynamically params

apparently the snap to the size of the chat remained

**Comment by shagu** [comment]
This is working as expected. As long as you don't define a custom `Item Slot Size`, each slot is sized dynamically based on the chat-frame width.
