### ISSUE TITLE
Limit the length text in the settings

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#899]
Please add limit the length text in the settings
![bandicam 2018-04-27 01-49-08-584](https://user-images.githubusercontent.com/24303693/39335928-c0cde5e0-49bd-11e8-8fd3-3d5919fc9703.jpg)
as done here:
![bandicam 2018-04-27 01-49-14-071](https://user-images.githubusercontent.com/24303693/39335929-c0ed7bda-49bd-11e8-9232-3bc9dfe5a2db.jpg)

**Comment by shagu** [comment]
I don't see why someone should ship a string that doesn't fit inside a fixed window. If your translation exceeds the window size, then there is something wrong with the translation.
