### ISSUE TITLE
Minimap information on mouseOver

### ISSUE THREAD

**Issue by jfastnacht** [shagu/pfUI#9]
Add map name and coordinates when mouse over minimap.

**Comment by jfastnacht** [comment]
Example:
![image](https://cloud.githubusercontent.com/assets/6183607/15431281/66c48680-1ea9-11e6-8441-c80a88157d52.png)

**Comment by shagu** [comment]
Or like this:
http://shaguaddons.ericmauser.de/shaguui/img/mmbuff.png

Should be adjustable in config.
