### ISSUE TITLE
[Lua Error] Nameplate module error if other modules are disabled

### ISSUE THREAD

**Issue by Voidmenull** [shagu/pfUI#90]
If you disable modules like "Target" or the Unitframes in general (to use Luna for example)
you get errors from the nameplate module:
http://i.imgur.com/0JpxijO.jpg
http://i.imgur.com/IZcrQEA.jpg

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/issues/59

**Comment by shagu** [comment]
pfUI-UnitFrames can now be disabled.
https://github.com/shagu/pfUI/commit/0dac5bc1e0b632163631e503f35b58aab2cbaf6f
