### ISSUE TITLE
Change a command to announce in raid

### ISSUE THREAD

**Issue by CorruptBadger** [shagu/pfUI#901]
Wondering if anyone can help me, I'm very much a novice at Lua editing.

Within the loot.lua I am trying to edit the Roll announce to be a raid warning.

The current code on line 41 looks like this

      SendChatMessageWide(T["Random Rolling "]..GetLootSlotLink(slot))

How would I go about making this a raid warning instead?

**Comment by Road-block** [comment]
You'd have to change the method in [pfUI\api:212](https://github.com/shagu/pfUI/blob/dbcc7de8821f01c03c0236ba4bbb6d6f281c8886/api/api.lua#L212) to something like
```lua
function pfUI.api.SendChatMessageWide(msg)
  local channel = "SAY"
  if UnitInRaid("player") then
    if ( IsRaidLeader() or IsRaidOfficer() ) then
      channel = "RAID_WARNING"
    else
      channel = "RAID"
    end
  elseif UnitExists("party1") then
    channel = "PARTY"
  end
  SendChatMessage(msg,channel)
end
```

**Comment by CorruptBadger** [comment]
God send man, any way I can donate a couple dollars your way for an excellent addon and excellent support.

**Comment by Road-block** [comment]
I'm not pfUI author (I've just written that particular method) and shagu doesn't accept donations far as I know 😄

**Comment by CorruptBadger** [comment]
Oh right, at any rate thanks for helping me, works a treat.
