### ISSUE TITLE
Right chat won't show when "Show Meters By Default" is activated

### ISSUE THREAD

**Issue by no-trick-pony** [shagu/pfUI#906]
With installed KTM and DPSMate, when unselecting "DPSMate (Dock)" and "KLH Threat Meter (Dock)" but selecting "Show Meters By Default" in the "Thirdparty" settings, the right chat won't show up at all. Clicking on the Arrow button also won't toggle the chat again, it appears to be simply gone. Quick fix for this is to untick the "Show Meters By Default" option but it does not appear to me as the intended behaivour.

Occurs with PfUI v3.9.0 and said addons for 1.12.1

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/002106b6324caf1e6238667c7e64daa6d8b8bc32

**Comment by no-trick-pony** [comment]
Thanks for fixing it that quickly! 👍
