### ISSUE TITLE
PfUi and AUX

### ISSUE THREAD

**Issue by Aggr1** [shagu/pfUI#908]
Hello, I write through the translator so it is necessary only to hope that you will understand me. Not so long ago the mistake when using an add-on of AUX and PfUi began to jump out. I attach a screenshot with a mistake in a chat. http://uploads.ru/SLUjG.png

**Comment by Road-block** [comment]
Are you using [latest Aux](https://github.com/shirsig/aux-addon)?  
Did you post this on Aux tickets as well?  
I don't see pfUI mentioned anywhere in the error.  
You need to be specific about which versions of addons you have 😃

**Comment by Aggr1** [comment]
Yes, I'm using the latest versions of the Addons. The error appears only when PfUi has been tried.

**Comment by Aggr1** [comment]
I'll do. Forgot to thank you for the beautiful work on this addon , thank you so much

**Comment by shagu** [comment]
I cannot see any pfUI related error here.
