### ISSUE TITLE
minimap: add support other shapes

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#913]
such as "CORNER-TOPLEFT", "CORNER-TOPRIGHT", "CORNER-BOTTOMLEFT", "CORNER-BOTTOMRIGHT", "SIDE-LEFT", "SIDE-RIGHT","SIDE-TOP", "SIDE-BOTTOM", "TRICORNER-TOPLEFT", "TRICORNER-TOPRIGHT", "TRICORNER-BOTTOMLEFT", "TRICORNER-BOTTOMRIGHT"

the whole problem is the lack of textures ... can someone know how to work with textures and create them ...?

**Comment by Lichery** [comment]
I think I found someone I know who can draw textures.

**Comment by Lichery** [comment]
from here https://www.wowace.com/projects/chinchilla/files you can take the texture, there are a lot of masks there and the texture of the border. Tomorrow I'll check how it looks.

**Comment by shagu** [comment]
Every pfUI-frame uses the same mechanism to draw the backdrop without the need of any texture and I'm not interested in changing such a core design pattern. I also won't ever add that many textures. Today it's the minimap, tomorrow the unitframes and in a year the repo would contain megabytes of textures.

Feel free to create a seperate pfUI-module, but that's something that shouldn't go into pfUI directly.
