### ISSUE TITLE
unlock mode: frame cling to the mouse

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#914]
if during the movement of the frame to press the button 'esc', then this frame cling to the mouse and starts to move constantly. At the same time, clicking the mouse button stops working. Helps only restart the game. I think we need somehow to implement protection from this.
https://youtu.be/WLhCpCNjsyo

**Comment by Lichery** [comment]
> What happens if you go to this pfUI\modules\unlock.lua:276 and add this line right above?
frame:StopMovingOrSizing()

The frame no longer sticks to the mouse, but there is one very small problem left. The new position of the frame is not saved and after the restart UI the frame returns to its original position (this only after the incorrect exit from the unlock mode on onShow. If you exit from the unlock mode correctly, the position is saved.)

**Comment by Road-block** [comment]
Yeah that was expected.  
I'm thinking that might actually be desirable so you don't accidentally save a frame to some random position.  
If you look at the hoverbind overlay it has similar logic, I intentionally made it so if you get in combat for example it auto-exits so you get back control of your character to fight.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/a211c9028fd7df9690987de2659d803171f90ef6

**Comment by shagu** [comment]
> but you can make it so that if the exit from the unlock mode is incorrect, the frame would return immediately to its original position, and not remain on the new position until the reload UI?

No, because most frames don't have saved positions till they are moved for the first time. Those frames are placed initially by the module-code itself, not by the UpdateMovable function. That's why you can't reset those positions without reloading the whole module. (which is not possible atm)
