### ISSUE TITLE
[BUG] bags: the frame is not updated after unequip the bag

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#915]
If you unequip the bag and put NOT in the first free slot, the frame will not be updated.
https://youtu.be/SR94xEPkazY

**Comment by Lichery** [comment]
Update:
is updated only if you put a bag in a backpack, if in any cell of other bags, even the very first free, it is not updated

**Comment by shagu** [comment]
When putting the Bag into another Bag, the game events are fired as following:
1. `BAG_UPDATE`
2. `BAG_CLOSED`

When putting a Bag into the bagpack, the events are:
1. `BAG_CLOSED`
2. `BAG_UPDATE`

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/a003e05960b5b096d63095534448e836d2816704
