### ISSUE TITLE
BarPet: add triangles for automatically cast spells

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#916]
these ones:
![bandicam 2018-05-11 21-44-24-104](https://user-images.githubusercontent.com/24303693/39941269-b230985e-5564-11e8-9975-bf0c681a8328.jpg)
because now these triangles are not there and a little uncomfortable / unusual:
![bandicam 2018-05-11 21-45-22-401](https://user-images.githubusercontent.com/24303693/39941304-cd20dbba-5564-11e8-94d8-97e8069e71f5.jpg)

**Comment by Lichery** [comment]
please see this blazzard code:
[PetActionBarFrame.zip](https://github.com/shagu/pfUI/files/1996643/PetActionBarFrame.zip)
line 95 global variable petAutoCastableTexture. Also see 112-116 lines.
This can be used and do not need to add any textures to the addon. Please do it.

**Comment by Lichery** [comment]
or you can use textures at once UI-AutoCastableOverlay
[UI-AutoCastableOverlay.zip](https://github.com/shagu/pfUI/files/1998871/UI-AutoCastableOverlay.zip)

**Comment by Lichery** [comment]
I was able to do it like this:
```
574 line in actionbar.lua:
local castable = _G["PetActionButton"..i..'AutoCastable']
castable:SetWidth(C.bars.icon_size*1.5)
castable:SetHeight(C.bars.icon_size*1.5)
castable:SetParent(button)
castable:SetTexCoord(.08, .92, .08, .92)
```
I would have done PR, but I already have a lot of things in there, so I'll leave it that way...
![bandicam 2018-05-14 03-15-57-102](https://user-images.githubusercontent.com/24303693/39973168-28a3058c-5725-11e8-8c55-9a288f5b0292.jpg)
![bandicam 2018-05-14 03-12-03-999](https://user-images.githubusercontent.com/24303693/39973170-2fd25fce-5725-11e8-963c-1b0749749e0a.jpg)

**Comment by Lichery** [comment]
here in an bring closer, see how everything is accurately :)
![bandicam 2018-05-14 03-24-11-772](https://user-images.githubusercontent.com/24303693/39973271-89f7f56c-5726-11e8-9360-c4edcd770383.jpg)

P.S. it seems to me much better if remove (or make it smaller) the transparency from autocast (see the code below in the file)

**Comment by Lichery** [comment]
I need to make a PR?

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/bd7d2b61fa36ee311a7c8aeffb1d725a9779caca
