### ISSUE TITLE
[Suggestion] Menu Bar

### ISSUE THREAD

**Issue by Voidmenull** [shagu/pfUI#92]
i would love to see an integrated manu bar instead the standard one on the top

also the mouseover effect is missing on the menu bar

**Comment by shagu** [comment]
It's not the default one, it already has the pfUI theming. You're free to move it whereever you want it.
If you want to have a better integrated one, please make a suggestion where and how you like to see it.

**Comment by shagu** [comment]
Closing this, as no further suggestions where made. 
Feel free to reopen it as soon as you got an awesome idea where to place menubar :)

**Comment by Voidmenull** [comment]
i will edit something and post it, no time atm :/
