### ISSUE TITLE
Mail Icon not found in latest version

### ISSUE THREAD

**Issue by SomeVanillaplayer** [shagu/pfUI#923]
I have no idea where the mail icon is in this latest version, I can't seem to be able to enable it?

**Comment by shagu** [comment]
There wasn't any change.
![image](https://user-images.githubusercontent.com/11586807/40267658-baf5aa54-5b60-11e8-8133-15cd8c76076b.png)

**Comment by SomeVanillaplayer** [comment]
Oddly enough It doesn't show up for me with the version on the website, a possible bug?

**Comment by shagu** [comment]
What addons do you use and could you provide a screenshot of your minimap?

**Comment by SomeVanillaplayer** [comment]
I hope this will suffice

2018-05-19 15:16 GMT+02:00 Shagu <notifications@github.com>:

**Comment by SomeVanillaplayer** [comment]
Incase you didnt get the images, I'll post this imgur link https://imgur.com/a/kW8rxzB

**Comment by shagu** [comment]
You are using simpleMinimap...

**Comment by shagu** [comment]
apart from the main issue, the addons: cyCircled, Classic Snowfall, linkmend, OmniCC, OneBag/OneBank, Prat, simpleMinimap, SmallerRollframes, TinyTip*, XLoot and ShaguPlates are addons that you probably won't need or don't want in combination with pfUI.

**Comment by SomeVanillaplayer** [comment]
Probably, I only just recently stumped upon your UIpack, so I've been
cleaning up so to speak.

2018-05-19 17:52 GMT+02:00 Shagu <notifications@github.com>:

**Comment by SomeVanillaplayer** [comment]
Actually, when I deleted some of these addons, the mail icon returned, is
it possible it was smipleMinimap causing the issue?

2018-05-19 19:29 GMT+02:00 Eataman Out <eatmentonight@gmail.com>:

**Comment by Lichery** [comment]
Yes, it was he who caused the problem. In order to avoid other problems, I advise you to disable/remove the above addons, since the same features is implemented in pfUI.
