### ISSUE TITLE
Suggestion: hide the autosell button when autosell is enabled

### ISSUE THREAD

**Issue by Wayleran** [shagu/pfUI#926]
if you simply add the following line to autovendor.lua then the disabled icon will not appear when you have "auto sell greys items" selected...

autovendor.lua

line 87:      if C["global"]["autosell"] == "1" then
line 88:       autovendor:Show()
line 89:       autovendor.button:Hide()    --ADDED
line 90:      end

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/aecef68ab6f0683d2dc8f1fb80315b9598d7a592
