### ISSUE TITLE
Raid loot distribution - random roll

### ISSUE THREAD

**Issue by Jabark** [shagu/pfUI#930]
When I am raid leading with master loot on in ZG, I use the "Random" option for things like Bijous. In the most recent update that has meant that a raid warning happens for EVERY random roll. This can get quite annoying as you can imagine, wonder if this could be an option we can turn off? I can see this being useful in some circumstances of course.

Also it would be good if it wrote the character name that the item was going to in raid chat after the roll, as sometimes if their inventory is full it doesn't go to them and it would be nice to quickly know who to manually assign the loot to once they have made room.

![image](https://user-images.githubusercontent.com/9607853/40554560-f77abef6-603d-11e8-90a4-a5750a307beb.png)
Before and after being made raid assist

**Comment by Road-block** [comment]
![image](https://user-images.githubusercontent.com/109839/40551638-3668d596-6046-11e8-9dfa-4b188bbb8cd9.png)
Uncheck "Detailed Random Roll Announcement"  
If you are talking about the one-liner with Random Rolling [x] there is no option for that currently.

**Comment by Road-block** [comment]
To add a bit to that, there is currently no intuitive way to have more fine-grained options for some things as the current options structure doesn't support "nested options".  
So you can't have something like  
- [ ] Announce Random Rolls
  - [ ] Only for x quality and up
  - [ ] Detailed Random Roll Announcement

So at the moment this is the best compromise I could come up with.  
You can comment out (put `--` in front) [pfUI\modules\loot.lua:41](https://github.com/shagu/pfUI/blob/e5448632917ff4e5de2a3bb8e3578e62fccbfc66/modules/loot.lua#L41) if you want completely *silent* random rolling.

**Comment by Jabark** [comment]
@Road-block "Detailed Random Roll Announcement"  _is_ unchecked. I'm very happy with the announcements, I just want to be able to control _where_ they get announced. If I am lead or assist it sends them to `/rw`, otherwise it sends them to `/r`. I want to be able to force them to _always_ go to `/r` whether I am raid lead or not. It would appear to be controlled by the `SendChatMessageWide` function?

**Comment by Road-block** [comment]
That is correct and your edit in this case would have to be commenting out lines 227 to 229 in [pfUI\api\api.lua](https://github.com/shagu/pfUI/blob/e5448632917ff4e5de2a3bb8e3578e62fccbfc66/api/api.lua#L227)  

SendChatMessageWide is a generic function that could potentially be used in other places where you want chat output automatically routed to the highest available channel so to change this behavior you'd have to have specific options for the loot announce and not use it.  
Same considerations apply as before. A dropdown with "none" (for silent) and specific chat options would be an idea but it still wouldn't allow for more fine grained control over what's posted.
