### ISSUE TITLE
Pfui & Clique

### ISSUE THREAD

**Issue by sanguma** [shagu/pfUI#932]
Hallo Shagu, Ich habe mir die aktuellen Versionen von Clique & Pfui geladen.
Improved Error Frames nutze ich um etwaige  Fehlermeldungen zu filtern.
Folgender Fehler wird allerdings im Chat angezeigt:

ERROR:Interface\AddOns\pfUI\api\spell.lua:112 attempt to perform arithmetic on a nil value

Bei einem Instant-Cast wird der Fehler nicht beobachtet.

**Comment by shagu** [comment]
Hi, 
Ich dachte dass hätte ich heute Nacht schon gefixt (https://github.com/shagu/pfUI/commit/17a210825368a3f52196f277fba545b07b01b692).

Kannst du es bitte nochmal ausprobieren?

**Comment by shagu** [comment]
Wann tritt das auf? Welcher Spell, Welche Klasse?

**Comment by sanguma** [comment]
Paladin (60) Die Meldung bekomme ich sobald ich Lichtblitz / Heiliges Licht caste (egal welcher Rang) 
Bei Segen des Schutzes z.B. ist keine Fehlermeldung zu sehen.

**Comment by sanguma** [comment]
Bei erstellen eines neuen Charakters funktioniert Clique ohne Probleme, logge ich mich dann jedoch aus und wieder ein bringt das Programm die Meldung das Clique nicht mit den automatischen Selbstzaubern von der Blizzardeinstellung funktioniert. 
Nach Deaktivierung der Blizzard Einstellung ist Clique wiederum nutzbar, aber der o.g. Fehler ist dann wieder da.

**Comment by shagu** [comment]
Fixed:
https://github.com/shagu/pfUI/commit/c697218b55d40137065a809128cdcb2506e67b8a
