### ISSUE TITLE
a pfUI function that returns the pfUI.uf.focus unitname safely (meaning no nil) for use by external addons

### ISSUE THREAD

**Issue by Altoholic** [shagu/pfUI#934]
Don't blame me for the title, i don't fully understand what i'm asking, but the problem is here: https://github.com/shirsig/cdframes/issues/28 and the related discussion here: "from: altoholic#7481 in: talk cdframes in pfUI"

**Comment by shirsig** [comment]
pfUI and pfUI.uf and pfUI.uf.focus and pfUI.uf.focus.unitname

**Comment by Road-block** [comment]
I posted the same on pfUI discord a couple hours ago and someone tried it (not me) and said it didn't work.  
I also tried making an anonymous function that returns the same.  
Now I haven't tried it myself (I would expect the first version - what you also posted here - to work) so it might be user error but there you have it .. @shirsig

**Comment by shirsig** [comment]
The problem is that pfUI doesn't preserve case in the name and cdframes is case sensitive. Use this to uppercase the first letter:
**pfUI and pfUI.uf and pfUI.uf.focus and pfUI.uf.focus.unitname and gsub(pfUI.uf.focus.unitname, '^%l', strupper)**

**Comment by Altoholic** [comment]
(working with that last command)

**Comment by shagu** [comment]
`pfFocus and pfFocus.unitname and UnitName(pfFocus.label .. pfFocus.id)`
This should work too, no?

**Comment by Altoholic** [comment]
Yes, it is.
