### ISSUE TITLE
[cosmetic bug] crafty addon always appear disabled in "addons tab" in game

### ISSUE THREAD

**Issue by Altoholic** [shagu/pfUI#935]
But it is actually working fine.
I tried enabling it in game, that trigger an UI reload, it still appear disabled, and still actually work.

**Comment by Road-block** [comment]
crafty is most likely a load on demand addon with a dependency on Blizzard CraftUI.  
That means it will not be loaded until you open a crafting frame.  
I'm not sure if pfUI would catch addons loading later as a response to a ##LoadWith: toc entry.

**Comment by Altoholic** [comment]
Right, @Road-block : pfUI addon tab update itself when i open the craft window. So no bug here.
