### ISSUE TITLE
castbar: add support for channeling enemy spells

### ISSUE THREAD

**Issue by Altoholic** [shagu/pfUI#939]
It's hard to test on my desertic server, but right now i had a druid in target, i saw him cast healing touch, but nothing for tranquility. Maybe that explain why i also don't see myself cast blizzard (on target castbar - i see my blizzard on player castbar).
Testing on my priest: i don't see any spell on my target castbar (tested with all healing spells).
Hunter: same, i only see chaneled spells on player castbar, not on target castbar (tested with volley and hearthstone).
Warlock: same.
Shaman: same.
Druid: same.

**Comment by Road-block** [comment]
This is not going to be easy or comprehensive (source: I have done a bit of exploratory work on it for oCB months ago)  
Reason being there is no universal way to detect channel spells, no specific event, rather it changes case by case and in some cases there is no event at all.

**Comment by Altoholic** [comment]
I don't get it... as a former user of LunaUF, i never had a problem seing any non instant spell cast by my target. I'm talking about the target castbar here, not the focus castbar, maybe there's some confusion ?

**Comment by shagu** [comment]
`I don't get it... as a former user of LunaUF, i never had a problem seing any non instant spell cast by my target. I'm talking about the target castbar here, not the focus castbar, maybe there's some confusion ?`

Oh really? That's interesting, because that's simply wrong.

1. Install LunaUF
2. Search a Mage, let him cast Blizzard
3. Search a Hunter, let him cast Volley
4. ... proceed like that

**Comment by Altoholic** [comment]
That's what i remembered (having no problem). But i believe you, i must be wrong.

**Comment by Altoholic** [comment]
Also, with my priest, not seing my own healing spell (i tested them all) when i target myself (on the target castbar), that seem weird. I saw the one that druid casted, tho, so maybe i must have NOT me in target to see the target castbar ?

**Comment by shagu** [comment]
The enemy catbar is made for enemyspells, it is unreleated to self casts. I'm don't clone your own castbar to the enemybars just for the sake of having you seeing your cast twice.

But this issue is about channeling spells, not about duplicating frames.

**Comment by Altoholic** [comment]
> enemy castbar

Ok... that make sense now. As it's named TargetCastBar (if i remember correctly), that's why i expected to see anything casted by my target. But thinking of it as an enemy castbar, (or as a "not me" castbar, because i saw that friendly druid), i'm fine with how it work now.

And on an unrelated note, i suppose that Luna did the cloning, and that's what i remembered working, not the channeled one, i suppose.
