### ISSUE TITLE
[request] sticky frames or/and absolute values

### ISSUE THREAD

**Issue by Altoholic** [shagu/pfUI#940]
It's almost impossible to set frames in a pixel perfect way. Some addons solve this problem with absolute values (e.g: LunaUF, where you enter coordinates for each frame), other (i remember using one in TBC, for bars... maybe Bongos) solve it with sticky frames: when a frame is close enough to another one, or to the screen limit, it "stick" to it, trying to go where it make more sense (usually trying to align everything that can be aligned).

Can we have these kind of options, for perfectionism sake ? ^^

(nb: that issue is strongly related to https://github.com/shagu/pfUI/issues/207)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/issues/253
