### ISSUE TITLE
error pfUI wow classic 1.13.2 RU

### ISSUE THREAD

**Issue by SDinM** [shagu/pfUI#948]
![1](https://user-images.githubusercontent.com/58772607/70615838-3448bc00-1c1e-11ea-8b1e-63caee50d44e.jpg)
![2](https://user-images.githubusercontent.com/58772607/70615859-3c086080-1c1e-11ea-911b-256bf16b0590.jpg)

**Comment by shagu** [comment]
This addon was made for the original Vanilla World of Warcraft (1.12.1) Gameclient. It does not work on the Classic remake (1.13.x) which is based on the latest BfA Addon API.
