### ISSUE TITLE
Actionbars: Unable to use both Auto Paging options

### ISSUE THREAD

**Issue by parsec01** [shagu/pfUI#950]
When selecting both "Switch Pages On Meta Key Press" and "Range Based Hunter Paging", the former only works until you engage an enemy with the latter, after which you can no longer switch pages on meta key press.

**Comment by shagu** [comment]
Thanks for your report. Fixed by this commit: https://github.com/shagu/pfUI/commit/7c2988d41356888137724592b84df69602016757
