### ISSUE TITLE
TBC | Shaman Elemental Mastery Issue

### ISSUE THREAD

**Issue by t3hWheez** [shagu/pfUI#957]
When under the default UI it has expected behavior.

1. action is clicked
2. ability goes "dark" until buff is used on character
3. ability is used and stays "dark" but cooldown ticks down

When under pfUI:

1. action is clicked
2. buff is gained but nothing happens on the action bar, looks normal like nothing happened
3. ability is used, buff goes away and ability still looks the same
4. if i do a /rl, it does not change
5. if i log out and back in, cooldown shows as normal on the actionbar

Thanks!

**Comment by shagu** [comment]
I am unable to reproduce this issue. When I click (or keypress) elemental mastery, the icon goes "dark" and as soon as the buff is consumed, the cooldown starts. Everything looks like it should.

https://youtu.be/VkyT5vMkGlo

Are you sure to have the latest version installed? Do you have any other addons that may conflict?

**Comment by t3hWheez** [comment]
It has to be an addon, testing one by one now.

**Comment by t3hWheez** [comment]
https://youtu.be/qyX9TbSGe34

**Comment by shagu** [comment]
Which pfUI version is it? Did you tried to delete the WDB folder?

**Comment by t3hWheez** [comment]
v4.5, let me try

**Comment by t3hWheez** [comment]
deleted WDB and still have the issue

**Comment by shagu** [comment]
Please update to the latest (4.5.1)
