### ISSUE TITLE
clickcasting: add support for macros

### ISSUE THREAD

**Issue by albea** [shagu/pfUI#958]
Hi. I would like to use [SmartHeal Enhanced](https://www.curseforge.com/wow/addons/project-2267) with pfUI, but I cannot get it to run click casting using something like `/script SmartHeal:Cast('Flash Heal')`.

![image](https://user-images.githubusercontent.com/22937072/77971444-f8ca1e80-72ee-11ea-91a6-a474f01ac343.png)

Is it possible to use `/script` or `/run` at all or am I out of luck?

**Comment by shagu** [comment]
Hi, it should work now. Whenever your input begins with a `/` it will always assume a macro instead of spell. Implemented by this commits: https://github.com/shagu/pfUI/compare/25b6926d86d7...d4818d69fa39

*verified on vanilla and tbc.*

**Comment by albea** [comment]
Thank you for the quick response and fix.  
I can confirm that it works like a charm.
