### ISSUE TITLE
nameplates: enhance by several features

### ISSUE THREAD

**Issue by gamer4eg** [shagu/pfUI#959]
Please add support for PlateBuffer or similar functionality.
Specifically:
Debuff Whitelist
Configure the size of debuffs on the nameplate.
Tracking the time of debuffs not only on target, but on all mobs.
(as well as data collection when hovering over NPCs with debuffs, without the need for a target)
https://github.com/nullfoxh/PlateBuffer
![image](https://user-images.githubusercontent.com/23147230/78210932-5491d480-74b4-11ea-8e0d-3dfe2549f72b.png)

**Comment by gamer4eg** [comment]
Does not work correctly with current templates.
Sometimes it starts on no more than 1 mob, and after 3-5 seconds it disappears.

**Comment by shagu** [comment]
> Configure the size of debuffs on the nameplate.

Done by: https://github.com/shagu/pfUI/commit/65374aea5a60aac1be724502957b5c5193c6c33b

**Comment by shagu** [comment]
> Tracking the time of debuffs not only on target, but on all mobs.
(as well as data collection when hovering over NPCs with debuffs, without the need for a target)

Done by: https://github.com/shagu/pfUI/commit/c2649eef46a43a2ccea0dd4134b27e31447445bf
https://github.com/shagu/pfUI/commit/bbf527513a26be1517ba473bfb330b36256aeecd
https://github.com/shagu/pfUI/commit/19a7c57f514557aa97abcf5a5be2ac61a2ed368f
https://github.com/shagu/pfUI/commit/86fbc00940d37ab0281e8b723d09867227e3ba9b
https://github.com/shagu/pfUI/commit/c260c77d68cd7faa28046741ddd1fb9b7740641f
https://github.com/shagu/pfUI/commit/d01efafcb6637b94424ae00823a26d7277cca802
https://github.com/shagu/pfUI/commit/bb6248fe29422dd797669ec6985ecffb166c387a

**Comment by shagu** [comment]
> Please add support for PlateBuffer or similar functionality.

PlateBuff conflict resolved by: https://github.com/shagu/pfUI/commit/f85de73816d5d575a5e9d86a1f716c835e70d52a https://github.com/shagu/pfUI/commit/58462c59cbc7de3d81cc5bf76a7a4019d35d8002 https://github.com/shagu/pfUI/commit/5f3ff376d9eca14f89a0fff2fa2210b173695aed https://github.com/shagu/pfUI/commit/3e694dcc43bb2b9b079f3dd9a3464506457265b8

**Comment by shagu** [comment]
> Debuff Whitelist

Done by: https://github.com/shagu/pfUI/commit/3f7399a1f39938a2577cc2507bdb6a19bee7e91b
