### ISSUE TITLE
xp bar lua error

### ISSUE THREAD

**Issue by risuxd** [shagu/pfUI#96]
hi,
getting a lua error, if I mouseover the XP bar:
http://i.imgur.com/z9KyVZH.png

also if u enable the option "always show xp/rep bar"; the rep bar only becomes visible if u mouseover the spot, where it should be.

thx for your past fixes. your UI really makes classic wow even greater!

**Comment by Cruzix** [comment]
I dont get any lua errors when I hover the xp bar, I tried with "always show exp/rep bar" enabled and disabled. 

Im also not experiencing the 2nd issue you mentioned

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/485f3f073d7d5fdd5a5d50f90c82938fa751cdd7

**Comment by shagu** [comment]
regarding your 2nd issue: https://github.com/shagu/pfUI/commit/bf6678844140fc24f8782b16f1ad3e1dda31e123
