### ISSUE TITLE
Move raidframes

### ISSUE THREAD

**Issue by gamer4eg** [shagu/pfUI#960]
Moving raidframes by groups, and not separately for each.
This is torture for a perfectionist! ..

**Comment by shagu** [comment]
Hold Shift while moving one. More details in the Popup that is shown when entering the unlock mode.

**Comment by shagu** [comment]
I've added new options to make it easier to rearrange the raidframes:
![raidcluster](https://user-images.githubusercontent.com/11586807/78271691-c269ea80-750c-11ea-847a-e0216092b87a.gif)
![raidframe](https://user-images.githubusercontent.com/11586807/78271703-c564db00-750c-11ea-9730-a16580206bcb.gif)

Commits: https://github.com/shagu/pfUI/compare/d4818d69fa39...2a36162d9531e3b5e77ba91ae9014706126697f0
