### ISSUE TITLE
[tbc] Raid info doesnt't work in combat

### ISSUE THREAD

**Issue by Nghedi** [shagu/pfUI#961]
The raid info window (place to create raid and switch groups) doesn't work in combat.
"Interface action failed because of an AddOn"

**Comment by shagu** [comment]
Thanks for your report. I'm already aware of that and spent several hours trying to understand.
But in fact, there are still many things tainting the environment so it's a long term effort to clean up those. I already begun moving from the Blizzard UIDropDown Menus to an own implementation, as those dropdowns often tend to taint things.

https://github.com/shagu/pfUI/commit/c7d777ec702cb54d662789211647963c94fea17d
https://github.com/shagu/pfUI/commit/6b57e851e5bc3801e50a26c770cc0381decffb5c
https://github.com/shagu/pfUI/commit/aa446efe18c3d7d746f4d2f02529dca3439a482a

I can't tell when this will finally get fixed. I'm just working the list one by one and hope that one day, the taint will be gone :)

**Comment by confessore** [comment]
if you go to pfUI config -> components -> skins -> disable skin friends,
it will set this skin to the default and allow you to switch player groups while in combat

**Comment by shagu** [comment]
Fixed by https://github.com/shagu/pfUI/commit/8ae0aeb706032016ffc8b821cf8ff391ef34ebab
