### ISSUE TITLE
addon menu [enhancement]

### ISSUE THREAD

**Issue by shikulja** [shagu/pfUI#962]
add (tips) description of addons from toc ## Notes:

**Comment by shagu** [comment]
Thanks for your suggestion. Addon informations are now shown as tooltips:
![image](https://user-images.githubusercontent.com/11586807/81458698-161ac400-919c-11ea-8d3b-f48bfd3effde.png)

https://github.com/shagu/pfUI/commit/f052eef1c816cd96afeff48f40d5c80903429a69
