### ISSUE TITLE
new option - debug mode

### ISSUE THREAD

**Issue by shikulja** [shagu/pfUI#963]
add option to output itemid spellid bossid
very useful for setting up various add-ons such as bigwigs, buff-addons
(it becomes hard to look up the correct id on wowhead)

**Comment by shagu** [comment]
ItemID - Can be enabled in the tooltip settings
SpellID - Might be able to get this in TBC but I don't think it is possible in Vanilla
BossID/UnitID - I don't think there's an api for it in Vanilla/TBC

**Comment by shikulja** [comment]
@shagu 
it is clear whether it is possible to add the removal of buffs/debuffs by clicking on the icons, for gm mode

**Comment by shagu** [comment]
I don't really understand.
