### ISSUE TITLE
Reputation Bar

### ISSUE THREAD

**Issue by nonameform** [shagu/pfUI#966]
When you are not tracking any reputation, the bar is still there and it displays text.

![Rep](https://user-images.githubusercontent.com/34381716/82756012-075d1f80-9de0-11ea-815d-c55b35db1cab.jpg)

**Comment by shagu** [comment]
Thanks for your report. I think it's time to rewrite most parts of the code. It will take another few days.

**Comment by shagu** [comment]
Fixed by this commits: https://github.com/shagu/pfUI/commit/8e3d3678a18e215dc33112036ed1fa2dc66f20a1 https://github.com/shagu/pfUI/commit/a11d0a27a7f14b94793f150e0d1ad13d5547cdbe

**Comment by nonameform** [comment]
While running the latest pfUI version I have noticed that sometimes it will display a lower case letter _c_ before the faction name like it did back in May.

[WoWScrnShot_102420_201252](https://user-images.githubusercontent.com/34381716/97213731-1010b200-17d3-11eb-91c5-08e535734cae.jpg)

**Comment by shagu** [comment]
Fixed by https://github.com/shagu/pfUI/commit/89c27f788aa092ad403dd4bf740a8ba017810ce1
