### ISSUE TITLE
Proper Tooltips for /pfcast macros

### ISSUE THREAD

**Issue by salt-die** [shagu/pfUI#969]
I was using MacroTT-V for this -- you could specify which spell's tooltip you wanted and it would add it.  It has mysteriously stopped working, but I thought this would be a nice feature for pfUI given how many /pfcast macros a healer in particular ends up using.

**Comment by shagu** [comment]
Fixed by https://github.com/shagu/pfUI/commit/f5b63a4faef26c176eca906ba66e1dc7d2a721c2 and https://github.com/shagu/pfUI/commit/e4d6b555d3d74af6cdcca7ab3fc47d9814b22425

**Comment by shagu** [comment]
Related: `/pfcast` macros do now also show the spell texture and cooldown on the actionbar by this commits: https://github.com/shagu/pfUI/commit/b1634a3d7aef8ecc26bd7a19900eef1115c275ce https://github.com/shagu/pfUI/commit/a2aa9e9f1a63897a211912c26cdddf3d3c03ce05 https://github.com/shagu/pfUI/commit/3efb00c4caa43c231b567a83b83edc1722ed1739

**Comment by salt-die** [comment]
Thank you so much!
