### ISSUE TITLE
add button skin for few addons

### ISSUE THREAD

**Issue by shikulja** [shagu/pfUI#973]
MCP (MaterControlProgram)
MoveAnything!
and can check SuperMacro
![Аннотация 2020-06-28 205549](https://user-images.githubusercontent.com/3386359/85954660-cbd6e780-b981-11ea-8eb3-1904682e4d9c.png)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/66aa9a587e9fcd335b5c8a451a54f8192921a206
