### ISSUE TITLE
add colored fps\ping bar

### ISSUE THREAD

**Issue by shikulja** [shagu/pfUI#974]
Natur Ecb It has an excellent visual FPS indicator, I would like something similar in pfui so that I no longer use a separate fps indicator

**Comment by shagu** [comment]
The goal of this project is not to rebuild every single addon that exists in the wow addon universe. I'm actually not interested in such a bar and can't think of a place where it would fit inside the default layout. If ECB already provides such a bar, it's fine to use it. However, I like the idea of the colors and put that into pfUI.

This commit provides an option to have a color gradient on the FPS and Latency on the panel, that is now enabled by default: https://github.com/shagu/pfUI/commit/7ea4fa8521354e7b25b652558be8c9058f5c06f0

![image](https://user-images.githubusercontent.com/11586807/86162002-695f2200-bb0e-11ea-961a-1ed7a09fd9d7.png)
