### ISSUE TITLE
questitem show the required number of items [enhancement]

### ISSUE THREAD

**Issue by shikulja** [shagu/pfUI#977]
![Аннотация 2020-07-05 210312](https://user-images.githubusercontent.com/3386359/86539135-fe915a80-bf02-11ea-885a-d35599635df8.png)

comparison with BSK Wowhead DB

**Comment by shagu** [comment]
No, pfQuest already does this

**Comment by shikulja** [comment]
@shagu 
also not for all quests is displayed
![Аннотация 2020-07-05 210554](https://user-images.githubusercontent.com/3386359/86539201-647de200-bf03-11ea-8e24-117446ad010f.png)
yes pfquest does it like a quest journal, but not like item hints, there is no quantity there.

**Comment by shagu** [comment]
I don't speak russian and have a hard time guessing what your screenshots are supposed to show.
pfQuest shows the required amount on the tooltip, while you have the quest active.
pfUI does not have any quest database and does only scan the questlogs for the corresponding item name. So there's no way to determine the amount without adding a database.

**Comment by shikulja** [comment]
@shagu 
it does not display some quests for items.
for example this one:
https://classic.wowhead.com/item=22528/dark-iron-scraps

it's not about cost, but about questitem

**Comment by shagu** [comment]
As I said, it only shows for which you have a quest for, and the item name appears in the quest.
I will not merge pfQuest into pfUI to have a database. There's a reason why this is split into two addons.

**Comment by shikulja** [comment]
@shagu 
clearly, I really don't have these quests in the journal, I was wrong

**Comment by shikulja** [comment]
It’s a pity that the number of items cannot be displayed for quests. it's comfortable

**Comment by shagu** [comment]
That's something I can look into for pfQuest. But that's going to be some effort, not sure if I will ever do that.

**Comment by shikulja** [comment]
@shagu 
Is it possible to take the number of items needed for a task from a standard journal?

**Comment by shagu** [comment]
It is now possible to show the required item count on quests that are shown as objectives (1st screenshot).
The setting is disabled by default as it duplicates pfQuest features (2nd screenshot).
It can be found in: Tooltips -> Show Required Questitem Count [x]

Related Commits: https://github.com/shagu/pfUI/commit/5cab5e1d4c2e63e6357ce6033f1a810f825b4269 https://github.com/shagu/pfUI/commit/11bc84524fde6f35cf430dfdc48b35cc21a78a5c

1st:
![image](https://user-images.githubusercontent.com/11586807/86541887-fb04d000-bf10-11ea-9f46-e980b595e735.png)

2nd:
![image](https://user-images.githubusercontent.com/11586807/86541905-32737c80-bf11-11ea-8e9a-e814f7d91f21.png)

**Comment by shikulja** [comment]
I mixed up the [questitem] and [wowheadDB] addons, so there was a mess (
