### ISSUE TITLE
Wrong class colour outline on some of the menu buttons (shaman only)

### ISSUE THREAD

**Issue by shoraine** [shagu/pfUI#978]
The class-coloured outline for some of the menu buttons and drop-downs uses the paladin pink for the shaman.

Affected buttons:
- all in the main menu
- all in AddOns, Video Options, Sound Options, Interface Options menus
- pfUI config menu: Unlock, Hoverbind, Share

Buttons in the Key Bindings and Macros menus are displaying the shaman blue outline (as is probably intended).

Class-coloured outlining on buttons is displaying correctly for all other classes.
![WoWScrnShot_070920_185844](https://user-images.githubusercontent.com/68074784/87070244-cba7d900-c218-11ea-9aab-115b3c919b0a.jpg)
![WoWScrnShot_070920_185859](https://user-images.githubusercontent.com/68074784/87070246-cc406f80-c218-11ea-8e70-705aa0425486.jpg)
![WoWScrnShot_070920_190015](https://user-images.githubusercontent.com/68074784/87070247-ccd90600-c218-11ea-9ce9-af49df34aead.jpg)
![WoWScrnShot_070920_190025](https://user-images.githubusercontent.com/68074784/87070249-ccd90600-c218-11ea-84ab-3fbc25ff4a96.jpg)
![WoWScrnShot_070920_190116](https://user-images.githubusercontent.com/68074784/87070250-cd719c80-c218-11ea-9291-4643c9017234.jpg)
![WoWScrnShot_070920_190123](https://user-images.githubusercontent.com/68074784/87070252-cd719c80-c218-11ea-94b2-82bff6ec819b.jpg)

**Comment by shagu** [comment]
Thanks for your report. Fixed by this commit: https://github.com/shagu/pfUI/commit/fe8833a5d89322924fc068b6968d4ba06fde22d5
