### ISSUE TITLE
Pet frame still shows after disabling pfUI unitframes

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#98]
Pet frame still shows after disabling pfUI unitframes http://imgur.com/a/QXevI

**Comment by shagu** [comment]
whoops...

**Comment by Cruzix** [comment]
Haha dont worry its a level 6 wolf I just tamed for testing purpose on a instant lvl 60 server :D

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/3ff26bd682f31ab1ab84c270f6691224bd6590b8
