### ISSUE TITLE
Problem with roll.lua

### ISSUE THREAD

**Issue by Aviolas** [shagu/pfUI#988]
Hi!
problem with BC 2.4.3 version 
when click on any button "need" or "greed" or "pass" resive error (attach screenshot). also, buttons dosnt displayed the of count of vote players
[https://prnt.sc/tsh08w <- screenshot ](https://prnt.sc/tsh08w)

**Comment by shagu** [comment]
Hi,

I can't reproduce it on my 2.4.3 client. Do you have any client modifications?

**Comment by shagu** [comment]
I now got it reproduced on the ruRU client.

**Comment by shagu** [comment]
Should now be fixed by this commit: https://github.com/shagu/pfUI/commit/c059bba4abf9795cb8c5c6fe72c7703685c1d285

**Comment by Aviolas** [comment]
now it works, but now always, sometimes buttons still dosnt displayed the of count of vote players. Error dosnt displayed now

**Comment by shagu** [comment]
I've tried to reproduce on two ruRU 2.4.3 clients, but wasn't able to. Might be related to the server not sending loot events due to player distances. I will keep an eye on it, but can't do anything right now against.
