### ISSUE TITLE
addon buttons are layered on top of each other

### ISSUE THREAD

**Issue by shikulja** [shagu/pfUI#989]
outfitter and on par with pfui enabled, they will lay on top of each other

standart:
![Аннотация 2020-08-03 190631](https://user-images.githubusercontent.com/3386359/89203217-de65c180-d5bc-11ea-91a8-b4a53ea92a97.png)

with pfui:
![Аннотация 2020-07-31 000857](https://user-images.githubusercontent.com/3386359/89203233-e58ccf80-d5bc-11ea-95cd-a0265dd2baab.png)

**Comment by shagu** [comment]
tbc?

**Comment by shikulja** [comment]
> tbc?

vanilla

**Comment by shagu** [comment]
I can't find an "on par" addon

**Comment by shikulja** [comment]
@shagu 

[InventoryOnPar.zip](https://github.com/shagu/pfUI/files/5017080/InventoryOnPar.zip)

**Comment by shagu** [comment]
They're both overlapping with and without pfUI.
![image](https://user-images.githubusercontent.com/11586807/89205417-00a91080-d5b8-11ea-9a16-b5a051c328e2.png)

**Comment by shikulja** [comment]
if someone is looking for how to fix it
then you can change the value to -45 in
InventoryOnPar.xml

```
				<Offset>
					<AbsDimension x="0" y="0"/>
				</Offset>
```

![Аннотация 2020-08-03 194649](https://user-images.githubusercontent.com/3386359/89206535-1a4f5580-d5c2-11ea-86fe-30b28a2105aa.png)
