### ISSUE TITLE
Embedded DPSMate resets some configs after client close

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#99]
When DPSMate is embedded into the right chat frame it resets some configs after client close, so far I have only noticed it resetting "Background Opacity" under "Content" but it could be resetting other configs as well.

https://youtu.be/Gcy97abvuwc

This bug ONLY occurs when DPSMate is embedded.

**Comment by shagu** [comment]
The thirdparty integration of DPSMate the skinning the window and therefor it must overwrite the DPSMate settings. If you don't want pfUI Backdrop or other colors and opacities, you should disable the integration or comment out corresponding lines of code.(https://github.com/shagu/pfUI/blob/master/modules/thirdparty.lua#L8-L27)
