### ISSUE TITLE
relogin in battle

### ISSUE THREAD

**Issue by shikulja** [shagu/pfUI#990]
if login\relogin is before the battle, and the battle has already begun, then the raidframe and targetframe are not displayed
(especially problematic for a healer)

**Comment by shagu** [comment]
![infight-raid-relog](https://user-images.githubusercontent.com/11586807/90242726-d3692780-de2d-11ea-8a0f-4b7d8e5ddc7d.gif)

**Comment by shikulja** [comment]
https://youtu.be/nNZn8Ej0jpw

**Comment by shagu** [comment]
You have bunch of Addons enabled, Lua extenders, Libraries and some sort of Compatibility stuff. With so many addons messing around with the Addon API and a chat full of error messages, there is nothing I can do for you.
