### ISSUE TITLE
TBC Shaman Water Totem

### ISSUE THREAD

**Issue by nonameform** [shagu/pfUI#994]
Whenever I hover over Water Totem, game starts spitting out errors:

`ERROR: Interface\AddOns\pfUI-tbc\modules\questitem.lua:63: attempt to concatenate local 'quest' (a nil value)`

I have tried reloading UI, but that does not help.

**Comment by shagu** [comment]
Please try again with the latest version. Should be fixed by: https://github.com/shagu/pfUI/commit/dabd86794429a7d32029705666c74f8cec2dc17f

**Comment by nonameform** [comment]
Fixed, thank you.
