### ISSUE TITLE
TBC Totem Timer/Buff Duration

### ISSUE THREAD

**Issue by nonameform** [shagu/pfUI#995]
There is an issue associated with Shaman. While the totem bar shows that the totem has 2 minute life time, the buff bar shows that the buff has a 10 minute timer. That does not happen every time, so I cannot say for sure what are the exact steps to reproduce that. I have a screenshot that shows totem with 15 seconds to go and the buff with 8 minutes left.

**Comment by shagu** [comment]
The buff of the totem does not always match the time of the buffs. This works as intended. For example, a windfury totem lasts quite a while, but the buff is refreshed every few seconds.

**Comment by nonameform** [comment]
OK, working as intended then.
