### ISSUE TITLE
Activating target/focus window with click casting.

### ISSUE THREAD

**Issue by makkerd** [shagu/pfUI#998]
Hi Shagu,
1st of all I want to tell you I like the pfUI a lot.
Nice work!
But I got one problem as a resto druid.
When I use click casting on my group members frames, the group member won't be placed in focus window.
I can't do spells like Natures Swiftness and Swiftmend. If the group member isn't in target.
Is there a fix so when u click cast a group member, this member is automaticly put in target/focus window?
thx!

**Comment by shagu** [comment]
Is this for TBC or Vanilla? Isn't the whole point of click-casting that you don't need to switch the target in order to cast something on him? I don't understand what you're trying to say with the focus window however.

**Comment by shagu** [comment]
If you're dependant on targetting a unit, set the string "target" to some button. Like this:
![image](https://user-images.githubusercontent.com/11586807/95011338-52a9f900-0630-11eb-99d3-69a525871631.png)

Or if it's just to use switftmend, assign it to a click action aswell.

**Comment by makkerd** [comment]
Its TBC.
Yeah, assigning swiftmend to a click action can help.
But for example, I want on my Left Mouse Button, Click Action cast Lifebloom + target the player i click on.
I tried many different things. But I only can cast Lifebloom or target the player. Not the 2 combined in 1 mouseclick.
Don't know this can't be done either.
